feat: 상점 카테고리 순서 변경 api 추가
BCSDLab/KOIN_API_V2 pull request #1007
Opened 2024-11-11 11:41 UTC by BaeJinho4028

# 🔥 연관 이슈

- close #989 

# 🚀 작업 내용

1. 상점 카테고리 순서 변경하는 api를 작성하였습니다.
2. 드래그&드롭으로 원활한 순서변경을 위해 기존 전체 상점카테고리 조회 로직의 페이지네이션을 제거하였습니다.

# 💬 리뷰 중점사항

한번에 카테고리들을 조회하여 map으로 매핑하는 방식을 사용하였습니다. 중복된 id검증을 위해 매핑되는 것마다 remove를 진행하여 예외를 처리했습니다.

2024-11-12 05:10 UTC, krSeonghyeon requested changes
고생하셨습니다!
리뷰 몇가지만 확인해주시면 될 것 같아요

2024-11-12 05:10 UTC, krSeonghyeon commented on src/main/java/in/koreatech/koin/domain/shop/model/shop/ShopCategory.java
> +    @Column(name = "order_index", nullable = false)
# A
Valid 제약조건에 관한 내용도 추가해주면 좋을 것 같습니다

2024-11-13 07:55 UTC, 20HyeonsuLee requested changes

2024-11-13 07:55 UTC, 20HyeonsuLee commented on src/main/java/in/koreatech/koin/admin/shop/service/AdminShopService.java
> +    public void modifyShopCategoriesOrder(AdminModifyShopCategoriesOrderRequest adminModifyShopCategoriesOrderRequest) {
# C
Set의 차집합 연산을 이용하면 코드가 더 깔끔해지지 않을까 싶어요

2024-11-14 08:10 UTC, BaeJinho4028 commented on src/main/java/in/koreatech/koin/admin/shop/service/AdminShopService.java
> +    public void modifyShopCategoriesOrder(AdminModifyShopCategoriesOrderRequest adminModifyShopCategoriesOrderRequest) {
적용 중 차집합말고 set 요소들로 equal하는 방식이 더 깔끔하게 나와서 그렇게 수정했습니다. 아이디어 감사합니다 👍

2024-11-14 08:12 UTC, krSeonghyeon approved these changes

2024-11-14 08:14 UTC, 20HyeonsuLee approved these changes

2024-11-14 08:27 UTC, merged