refactor : User, Student 패키지 리팩토링
BCSDLab/KOIN_API_V2 pull request #1058
Opened 2024-11-19 10:03 UTC by duehee

# 🔥 연관 이슈

- close #1006 

# 🚀 작업 내용

1. User, Student 리팩토링을 진행했습니다.
- DTO JsonNaming 통일
- 너무 긴 메소드 분리
- 필요없는 메소드 정리
- 검증서비스단인 ValidationService 분리

유저가 많이 묶여있어서, 최대한 User와 Student에 대한 리팩토링만 진행했습니다.
추후 영양사나 어드민 머지가 완료되면 추가적 2차로 리팩토링을 진행 할 예정입니다.

# 💬 리뷰 중점사항
서비스 검증단을 추가했는데, 검증 서비스에 어떻게 넣어야하지? 라는 모호함이 조금 있어서 의견 내주시면 감사하겠습니다.
기존 Service에 그대로 남아있는 검증 로직이 몇 개 있습니다.
추가적으로 "util 클래스를 유지하여 작성하는 것은 어떤가?"(학번 분리 로직 등)에 대한 의견도 부탁드립니다. 
몇 개 안 되는 메소드를 분리하기 위해 패키지 만드는 것에 대한 생각이 궁금합니다! 감사합니다 :D

2024-11-21 02:05 UTC, Soundbar91 requested changes
고생하셨습니다!!
> 서비스 검증단을 추가했는데, 검증 서비스에 어떻게 넣어야하지? 라는 모호함이 조금 있어서 의견 내주시면 감사하겠습니다.

개인적으로는 유효성 검증 로직은 모두 검증 서비스로 넘겨야 한다고 생각합니다. 

> 추가적으로 "util 클래스를 유지하여 작성하는 것은 어떤가?"(학번 분리 로직 등)에 대한 의견도 부탁드립니다. 

저는 서비스에 구현된 `private`메소드에서 공통된 기능이 있으면 util 클래스로 넘겼습니다. 예시로 들어주신 학번 관련해서 묶어서, util 클래스로 넘기면 서비스 코드가 확 줄어들고 수정이 필요할 때도 해당 부분만 변경하면 되기 때문에 저는 util로 넘기는 것을 선호하는 편입니다. 다만 비즈니스 로직은 서비스에 남기고, 그 외의 부가적인 기능은 분리할 수 있다면 분리하는 것이 좋다고 생각합니다. 

> 몇 개 안 되는 메소드를 분리하기 위해 패키지 만드는 것에 대한 생각이 궁금합니다

저도 처음에는 정빈님이랑 동일한 생각을 가지고 있었는데, 메소드가 다른 곳에 위치하는 것이 적절하다고 생각되면 그거에 맞게 패키지를 만들고 클래스를 만드는 것이 좋다고 생각이 들었습니다 !

2024-11-23 09:54 UTC, duehee commented on src/main/java/in/koreatech/koin/admin/user/service/AdminUserService.java
> +        student.updateStudentInfo(adminRequest.studentNumber(), adminRequest.major());
중복되는 내용이라서 그렇게 처리하는게 좋으려나요? 의견 감사합니다

2024-11-23 09:55 UTC, duehee commented on src/main/java/in/koreatech/koin/domain/student/model/StudentDepartment.java
> +        .collect(Collectors.toMap(StudentDepartment::getValue, Function.identity()));
리팩토링 차원보다는 성능 개선에 가깝긴하더라구요. 사실 학과 찾는 거 몇 개 안 되서.. 다시 쓰던 메소드 쓸까 생각하고 있씁니다

2024-11-23 09:56 UTC, duehee commented on src/main/java/in/koreatech/koin/domain/student/service/StudentService.java
> +        user.update(request.nickname(), request.name(), request.phoneNumber(), request.gender());
초반에 업데이트 관련해서 메소드 만들었을 때, 인자가 너무 조금 많은 것 같다고 생각해서 분리했었어요

2024-11-23 09:57 UTC, duehee commented on src/main/java/in/koreatech/koin/domain/user/model/User.java
> +        this.resetExpiredAt = LocalDateTime.now(clock).plusHours(1);
이 친구도 상수화시키면 좋겠네요

2024-11-23 09:58 UTC, duehee commented on src/main/java/in/koreatech/koin/domain/user/model/User.java
> +        }
Token 관련해서 클래스를 하나 만들면 좋지 않을까.. 생각이 들긴 했어요. 한 번 해보면 좋을 거 같네요

2024-11-23 09:58 UTC, duehee commented on src/main/java/in/koreatech/koin/domain/user/service/UserService.java
> +        return String.format("%s-%d", UUID.randomUUID(), user.getId());
엇. 일치가 안 되어있나보네요. 처리하겠습니당

2024-11-23 09:58 UTC, duehee commented on src/main/java/in/koreatech/koin/domain/student/service/StudentService.java
>          String refreshToken = String.format("%s-%d", UUID.randomUUID(), user.getId());
ㅋㅋㅋㅋ 아래 있었네요 .. ... 수정하겠씁니다

2024-11-23 10:01 UTC, duehee commented on src/main/java/in/koreatech/koin/domain/user/controller/UserController.java
> +        AuthResponse authResponse = userService.getAuth(userId);
그게 더 깔끔할까요? 변수를 보고 딱 알 수 있으면 좋겠다 생각하긴 하는데, Controller에서는 단일로 호출하는 경우가 더 많다고 생각이 드네요. 변수명 통일 좋은 거 같아요 :D. 이 부분은 아마 코드 컨벤션으로 올리는 것 권유해보는 건 어떨까요? (백엔드 회의 때)

2024-11-25 11:52 UTC, kwoo28 approved these changes
수고 많으셨습니다! 깔끔하게 잘 작성하신것같아요

2024-11-25 11:52 UTC, kwoo28 commented on src/main/java/in/koreatech/koin/domain/student/service/StudentValidationService.java
> +@Transactional(readOnly = true)
## C
StudentService 상위 메서드에서 트랜잭션을 적용하고 있어서 이 어노테이션은 적용안해도 되지 않을까요??

2024-11-25 11:52 UTC, kwoo28 commented on src/main/java/in/koreatech/koin/domain/user/service/UserService.java
> +        userRepository.save(user);
## C
userRepository.save(user); 코드는 없어도될것같아요!

2024-11-25 11:52 UTC, kwoo28 commented on src/main/java/in/koreatech/koin/domain/student/service/StudentService.java
>          userRepository.save(authedUser);
## C
이 부분도 빼도될것같습니다!

2024-11-25 11:52 UTC, kwoo28 commented on src/main/java/in/koreatech/koin/domain/student/service/StudentService.java
>          studentRepository.save(student);
## C
이 부분도 빼도 될것같습니다!

2024-11-25 12:02 UTC, Soundbar91 approved these changes

2024-11-25 12:03 UTC, duehee commented on src/main/java/in/koreatech/koin/domain/student/service/StudentValidationService.java
> +@Transactional(readOnly = true)
여기서 적용하면 2번 적용될 수 있겠네요. 지우겠습니당

2024-11-25 12:09 UTC, Soundbar91 reviewed
마지막 하나만 확인해주시면 될 것 같습니다. 고생하셨습니다 !

2024-11-25 12:09 UTC, Soundbar91 commented on src/main/java/in/koreatech/koin/domain/user/service/UserTokenService.java
> +    }
## C
이 친구 역할이 어떤건가용 ?? 
void로 반환하고 있어서 아무것도 안 하는 것 같아요.

2024-11-25 12:19 UTC, duehee commented on src/main/java/in/koreatech/koin/domain/user/service/UserTokenService.java
> +    }
로그인 상태 체크 메소드인데, 기존에도 반환값이 없어서 TokenService에서도 반환 안하고 메소드 호출만 했어요

2024-11-25 12:38 UTC, merged