fix: lecutre 테이블 컬럼 수정
BCSDLab/KOIN_API_V2 pull request #1065
Opened 2024-11-20 07:54 UTC by Soundbar91

# 🔥 연관 이슈

- close #1063 

# 🚀 작업 내용

- lecture 테이블의 class_time 컬럼의 크기를 키웠습니다. 
  - 계절학기 시간을 넣었을 경우 터지는 상황이 발생해서 변경했습니다.
- lecture 테이블에 semester fk를 추가했습니다.
- lecture 테이블에 semester_date 컬럼을 삭제했습니다.
- 관련 테스트 코드 수정했습니다. 

# 💬 리뷰 중점사항

2024-11-20 08:08 UTC, kwoo28 requested changes
정말 빠르게 작업해주셨네요!! 수고많으셨습니다.
FK관련 부분 코멘트 남겼습니다.

2024-11-20 08:08 UTC, kwoo28 commented on src/main/resources/db/migration/V104__alter_lecture_class_semester_fk.sql
> +            ON DELETE CASCADE;
## R
lecture가 semester에 완전히 종속된 데이터가 아닌데, 학기가 삭제된다해서 lecture의 모든 데이터가 삭제되는건 조금 위험하지 않을까요..? 전 이 부분은 fk로 안거는게 어떨까 생각해봅니다

2024-11-20 08:10 UTC, kwoo28 commented on src/main/resources/db/migration/V104__alter_lecture_class_semester_fk.sql
> +            ON DELETE CASCADE;
아니면 on delete cascade 부분만 빼는건 어떨까요?

2024-11-20 08:22 UTC, Soundbar91 commented on src/main/resources/db/migration/V104__alter_lecture_class_semester_fk.sql
> +            ON DELETE CASCADE;
동의합니다!
그럼 `ON UPDATE CASCADE`로 변경하는 것은 어떻게 생각하시나요 ??

2024-11-20 08:31 UTC, kwoo28 commented on src/main/resources/db/migration/V104__alter_lecture_class_semester_fk.sql
> +            ON DELETE CASCADE;
좋은것같습니다!

2024-11-25 03:41 UTC, duehee requested changes
고생하셨어요~ 이 PR을 체크 못했네요..
코멘트 확인해주세요!

2024-11-25 03:41 UTC, duehee commented on src/main/resources/db/migration/V105__alter_lecture_drop_semester_date_column.sql
> +DROP COLUMN `semester_date`;
### C
컬럼 삭제..하는 과정에서 flyway 오류가 안 날지 모르겠네용

2024-11-25 03:41 UTC, duehee commented on src/main/resources/db/migration/V104__alter_lecture_class_semester_fk.sql
> +                     WHERE l.`semester_date` = s.`semester`);
### C
DML이랑 DDL이 같이 있네요👀(분리..!!)
추가적으로 최근에 진호님이 PR 올리신 내용이 있어서 한 번 확인해보시는 것도 좋을 거 같아요

2024-11-25 11:39 UTC, Soundbar91 commented on src/main/resources/db/migration/V105__alter_lecture_drop_semester_date_column.sql
> +DROP COLUMN `semester_date`;
흠,, 일단은 컬럼을 삭제하지 않는 방향이 적절할까요..?
지금 그렇게 큰 문제가 되지는 않는 것 같아서, 있어도 그만, 없어도 그만이라고 생각은 듭니다.

2024-11-25 11:39 UTC, Soundbar91 commented on src/main/resources/db/migration/V104__alter_lecture_class_semester_fk.sql
> +                     WHERE l.`semester_date` = s.`semester`);
헉,, 감사합니다 !

2024-12-01 07:35 UTC, duehee approved these changes
굿. 말씀하셨던 내용 처리해주셨네요
추후 처리해야 할 컬럼들 있다면 정리해서 한 번에 없애면 좋겠네용 :D 
고생하셨습니다~

2024-12-01 11:02 UTC, merged