feat: 위험한 sql문 체크 로직 추가
BCSDLab/KOIN_API_V2 pull request #1077
Opened 2024-11-25 02:05 UTC by BaeJinho4028

# 🔥 연관 이슈

- close #1076 

# 🚀  AS-IS

1. 리팩터링을 하며, 칼럼이나 테이블이 수정, 삭제됨
2. 기존 WAS에서 이를 반영하지 못하여 새로운 was는 정상적으로 배포는 되지만, 오류 로그가 쏟아져내림.

WAS 배포와 Flyway 배포를 분리하는 것이 맞지만, 일단 수정, 삭제와 같이 문제가되는경우 경우를 다른 변경사항과 격리시킴으로써 이를 해결하고자함. (DROP|TRUNCATE|RENAME|CONSTRAINT|MODIFY|CHANGE) 을 체크

# 💬 TO-BE
1. flyway를 제외한 코드가 변경되었는지? -> 이는 수정, 삭제와 같은 flyway만 따로 올릴 수 있음을 목적으로함.
2. 코드가 변경이 되었다면, 수정,삭제와 같은 위험한 sql을 막음

2024-11-25 06:00 UTC, Choi-JJunho approved these changes
좋습니다~
해당 내용은 채널에 공유하고, 주간공유같은 때 한번 더 이야기하면 좋을것 같아요

2024-11-27 00:59 UTC, 20HyeonsuLee submitted a review, later dismissed
수고하셨습니다~👍
ALTER에 관한 조건이 안보이는것 같습니다. 추가가 필요해보여요

2024-11-27 01:02 UTC, 20HyeonsuLee requested changes
수고하셨습니다~👍
ALTER에 관한 조건이 안보이는것 같습니다. 추가가 필요해보여요

2024-11-27 04:48 UTC, BaeJinho4028 reviewed
@20HyeonsuLee ALTER를 막으면 테이블을 새로 생성하는것이 아니라면 칼럼 추가를 할수가 없어서, ALTER 대신 DROP, MODIFY와 같은 옵션을 제한했습니다. 👍

2024-11-27 06:37 UTC, 20HyeonsuLee approved these changes

2024-11-27 12:18 UTC, merged