feat: 버스 교통편 조회 API
BCSDLab/KOIN_API_V2 pull request #1099
Opened 2024-11-28 06:52 UTC by DHkimgit

# 🔥 연관 이슈
![image](https://github.com/user-attachments/assets/2f2b276c-262b-47a8-bc36-e765321717ca)

- [API 요구명세](https://www.notion.so/API-ad5e6bc7f8bb4705b06a7c5ffe1e13c8?pvs=4), [피그마](https://www.figma.com/design/tDCzPQyt4AeWSW7937T10a/KOIN-Mobile?node-id=19647-23553&t=c0Z11FcqRyYHmyXf-4)
- 캠퍼스팀 11월 버스 스프린트 - 버스 교통편 조회하기 기능을 구현한 API 입니다. 

# 🚀 작업 내용
- 출발지, 도착지, 날짜, 시간, 차량 종류에 대응하는 버스 스케줄을 반환하는 API를 작성했습니다.

## 설계
![image](https://github.com/user-attachments/assets/f5e95b3b-46ba-4104-8cc6-181c48213cb1)

- 스케줄을 조회하는 메서드에 대한 추상화가 가능하다고 생각해서 이를 적용했습니다.
- 고속버스의 경우 스케줄 데이터를 가져오는 외부 API가 현재 KEY 만료로 동작하지 않는 상태입니다. redis에 정적으로 저장된 데이터를 가져오는 방법이 있었으나, 추후 리팩토링이 예정되어 있으므로 일단 데이터를 final class에 정적으로 정의하고 이를 이용했습니다.

**DataSource**
- **셔틀버스(shuttle, commuting)** : MongoDB (collection = "bus_timetable")
- **시내버스** : MongoDB (collection = "citybus_timetable")
- **고속버스(대성)** :  ExpressBusSchedule 클래스

## 셔틀버스 스케줄 조회 상세 구현 로직
![image](https://github.com/user-attachments/assets/3df77660-2218-4ba6-930d-90e5c32a5855)

- Stream을 이용해서 데이터를 정제합니다.
```java
public boolean filterDepartAndArriveNode(BusStation departNode, BusStation arriveNode) {
        boolean foundDepart = false;
        for (ArrivalNode node : arrivalInfos) {
            if (!foundDepart && node.getNodeName().contains(departNode.getQueryName())) {
                foundDepart = true;
            }
            else if (foundDepart && node.getNodeName().contains(arriveNode.getQueryName())) {
                return true;
            }
        }
        return false;
    }
```
- ArrivalNode 를 순회하면서 depart와 arrive가 순서대로 나온다면 결과에 추가하는데, 혹시 더 좋은 방법 떠오르신다면 알려주세요... 

## RequestBody
```js
{
	"date": "2024-11-05",
	"time": "00:00",
	"bus_type": "ALL",
	"depart": "KOREATECH",
	"arrival": "TERMINAL"	
}
```

- **date**: 요청하는 날짜 (예: `"2024-11-05"`).
- **time**: 요청하는 시간 (예: `"00:00"`).
- **bus_type**: 요청할 버스 유형 (`ALL, CITY, EXPRESS, SHUTTLE`)
- **depart**: 출발지 (`KOREATECH, TERMINAL, STATION`).
- **arrival**: 도착지 ( `KOREATECH, TERMINAL, STATION`).

## ResponseBody
```js
{
  "depart": "KOREATECH",
  "arrival": "TERMINAL",
  "depart_date": "2024-11-05",
  "depart_time": "16:00",
  "schedule": [
    {
      "bus_type": "express",
      "route_name": "대성티앤이",
      "depart_time": "16:50"
    },
    {
      "bus_type": "city",
      "route_name": "400",
      "depart_time": "16:56"
    },
    {
      "bus_type": "city",
      "route_name": "402",
      "depart_time": "17:30"
    },
    {
      "bus_type": "shuttle",
      "route_name": "주중(20시 00분)",
      "depart_time": "20:00"
    }
  ]
}
```

# 💬 리뷰 중점사항
- 설계, 구현 다 부족합니다ㅜ 한번씩 읽어보시고 조언 부탁드려요!

2024-11-28 09:04 UTC, kih1015 approved these changes
PR 상세히 작성해주셔서 리뷰하기 편했습니다!

고생많이하셨어요~

2024-11-28 17:07 UTC, DHkimgit commented on src/main/java/in/koreatech/koin/domain/bus/service/BusService.java
> +        }
천안역 -> 천안역 처럼 출발지와 도착지가 같거나, 터미널 -> 천안역 & 천안역 -> 터미널 같은 데이터를 제공하기 애매한 요청에 대해 빈 리스트를 반환하기 위해 저렇게 작성했습니다.
저 상황의 경우 서버에서 예외로 처리하는 것 보다는 빈 목록을 반환하는 것이 맞는 것 같은데 어떻게 생각하시나요?

2024-11-28 17:17 UTC, DHkimgit commented on src/main/java/in/koreatech/koin/domain/bus/model/mongo/CityBusTimetable.java
> +    private static final Integer ADDITIONAL_TIME_DEPART_TO_STATION = 7;
맞습니다! 시내버스 API 에서 받아오는 출발 시간 데이터는 기점 출발 기준입니다. 예를 들어 400번의 경우 한기대 정류장이 아니라 출발지인 병천3리 정류장을 기준으로 스케줄 정보를 제공합니다. 따라서 사용자가 한기대 -> 터미널의 스케줄을 요청한 경우 시간 데이터에 병천3리 -> 한기대 사이의 이동 시간을 추가하여 시간을 보정합니다. 해당 작업을 위해 정의한 상수입니다.

2024-11-28 17:18 UTC, DHkimgit commented on src/main/java/in/koreatech/koin/domain/bus/service/route/ShuttleBusRouteStrategy.java
> +    private final BusRepository busRepository;
들여쓰기 신경 안쓴 부분이 너무 많네요... 찾아주셔서 감사합니다!

2024-12-10 13:52 UTC, songsunkook requested changes
리뷰 늦게남겨서 죄송합니다 😭
고생하셨습니다! 코멘트 확인 부탁드려요~

2024-12-10 13:52 UTC, songsunkook commented on src/main/java/in/koreatech/koin/domain/bus/controller/BusApi.java
> +            - **출발지 & 도착지** : 출발지와 도착지가 일치하는 경우 빈 리스트를 반환합니다. (천안역 -> 터미널) & (터미널 -> 천안역) 역시 빈 리스트를 반환합니다.
### R
터미널, 천안역 간 교통편 조회는 빈 결과를 반환한다는 요구사항이 있었나요??

2024-12-10 13:52 UTC, songsunkook commented on src/main/java/in/koreatech/koin/domain/bus/controller/BusApi.java
> +        @Parameter(description = "HH:mm") @RequestParam String time,
### C
request와 response에서 모두 date와 time을 분리하여 전달하고 있는데, 분리해야 했던 이유가 있을까요?? 다른 곳에서는 대부분은 합쳐서 사용하고 있지 않나요??

2024-12-10 13:52 UTC, songsunkook commented on src/main/java/in/koreatech/koin/domain/bus/controller/BusApi.java
> +        ) @RequestParam BusRouteType busRouteType,
### A
파라미터 타입으로 enum을 주면 swagger에서 조회 시 드롭다운으로 나타날텐데 description에 예시를 제공해야 할까요??

2024-12-10 13:52 UTC, songsunkook commented on src/main/java/in/koreatech/koin/domain/bus/dto/BusRouteCommand.java
]### C
request dto 용도의 클래스를 만들어야 한다면 차라리 GET요청이지만 request body를 사용하는 건 어떻게 생각하시나요?? 기능에 비해 복잡도가 커지는 것 같아서 우려되네요

2024-12-10 13:52 UTC, songsunkook commented on src/main/java/in/koreatech/koin/domain/bus/dto/BusScheduleResponse.java
> +    ) {
### A
여기도 `@Schema`로 부연설명을 붙일 수 있을 것 같아요. 그렇게 한다면 schedule 변수의 Schema 예시 설명을 제거할 수 있을 것 같습니다.

2024-12-10 13:52 UTC, songsunkook commented on src/main/java/in/koreatech/koin/domain/bus/model/express/ExpressBusSchedule.java
### A
주석으로 부연설명을 조금 달아두는 것도 좋을 것 같아요!

2024-12-10 13:52 UTC, songsunkook commented on src/main/java/in/koreatech/koin/domain/bus/model/mongo/CityBusTimetable.java
> +    private static final Integer ADDITIONAL_TIME_DEPART_TO_STATION = 7;
### A
해당 정보의 출처는 어디인지, 이 상수들의 용도가 무엇인지 주석으로 명시하면 좋을 것 같아요!

2024-12-10 13:52 UTC, songsunkook commented on src/main/java/in/koreatech/koin/domain/bus/model/mongo/Route.java
> +        String busType = "한기대".equals(depart.getQueryName()) ? "하교셔틀" : "등교셔틀";
### A
출발지가 한기대가 아닌데 하교셔틀이면 어떡하나요??
ex) 터미널 -> 천안역

+) 크게 치명적인 내용은 아닌 것 같습니다

2024-12-10 15:33 UTC, DHkimgit commented on src/main/java/in/koreatech/koin/domain/bus/model/mongo/Route.java
> +        String busType = "한기대".equals(depart.getQueryName()) ? "하교셔틀" : "등교셔틀";
위 터미널 <-> 천안역 사이 빈 결과를 반환 부분과 연결되는 내용 같아요.. 셔틀버스를 터미널에서 타서 천안역에서 내리는 경우는 없다고 생각하고 배제해서 로직을 작성했습니다...

2024-12-10 15:33 UTC, DHkimgit commented on src/main/java/in/koreatech/koin/domain/bus/model/express/ExpressBusSchedule.java
적용했습니다.

2024-12-10 15:33 UTC, DHkimgit commented on src/main/java/in/koreatech/koin/domain/bus/dto/BusScheduleResponse.java
> +    ) {
수정했습니다.

2024-12-10 15:34 UTC, DHkimgit commented on src/main/java/in/koreatech/koin/domain/bus/dto/BusRouteCommand.java
`BusRouteCommand`를 request dto처럼 만드는게 어떻냐는 말씀이신가요? command 객체가 `BusRouteStrategy` 추상화 메소드의 매개변수 타입으로 사용되고 있는데 이 객체를 request dto처럼 만들면 더 복잡해 질 것 같습니다.

2024-12-10 15:34 UTC, DHkimgit commented on src/main/java/in/koreatech/koin/domain/bus/controller/BusApi.java
> +        ) @RequestParam BusRouteType busRouteType,
불필요하네요! 제거하겠습니다.

2024-12-11 12:04 UTC, songsunkook commented on src/main/java/in/koreatech/koin/domain/bus/controller/BusApi.java
> +            - **출발지 & 도착지** : 출발지와 도착지가 일치하는 경우 빈 리스트를 반환합니다. (천안역 -> 터미널) & (터미널 -> 천안역) 역시 빈 리스트를 반환합니다.
넵 회색지대인 요구사항이 있다면 임의로 구현하기보다는 PM님과 팀에서 논의하는게 좋을 것 같아요~
논의 올려주신내용 확인했습니다

2024-12-11 12:07 UTC, songsunkook commented on src/main/java/in/koreatech/koin/domain/bus/dto/BusRouteCommand.java
파라미터로 받은 내용들을 다시 전부 단일 record로 묶어서 service를 호출하길래 get 요청에 body를 담지 않으려고 이렇게 한건가? 했습니다. 그런 구조였다면 괜찮을 수도 있을 것 같네요 👍

2024-12-11 12:11 UTC, songsunkook approved these changes

2024-12-12 05:30 UTC, merged