feat: 키워드 알림 소프트 딜리트 구현
BCSDLab/KOIN_API_V2 pull request #1107
Opened 2024-12-02 13:28 UTC by seongjae6751

# 🔥 연관 이슈

- close #1105

# 🚀 작업 내용
![image](https://github.com/user-attachments/assets/04a3db5f-6177-4630-8272-9347dc9d2756)

da님의 요청으로 로깅을 위해 소프트 딜리트로 전체 로직을 바꿨습니다.

# 💬 리뷰 중점사항
생각보다 수정 요소가 많았네요.. 😢 
로컬에서 다 돌려봤지만 혹시 모르니까 놓친 부분 있었는지 꼼꼼하게 봐주시면 감사하겠습니다!

2024-12-04 10:09 UTC, Soundbar91 requested changes
혹시나 불상사가 발생할 수 있기 때문에, Request changes 걸겠습니다.

2025-01-18 12:05 UTC, Choon0414 approved these changes
고생하셨습니다!

2025-02-09 12:24 UTC, Soundbar91 approved these changes
다른 분들 리뷰도 있으면 좋을 것 같네요.
flyway 삭제 된 거 확인해서 어프로브 할께요.

2025-03-12 15:06 UTC, seongjae6751 commented on src/main/java/in/koreatech/koin/domain/community/keyword/model/ArticleKeyword.java
> +    public void delete() {
너무나도 늦게 답을 드리게 되었네요ㅠ 로깅을 위해 모든 기록을 남기기 위해 완전 삭제가 아닌 restore 하는 방식으로 하게 되었습니다!

2025-03-12 15:06 UTC, merged