feat: 시간표 프레임 한번에 조회 구현
BCSDLab/KOIN_API_V2 pull request #1108
Opened 2024-12-02 14:35 UTC by seongjae6751

# 🔥 연관 이슈

- close #1106 

# 🚀 작업 내용

1. 시간표 프레임을 한번에 조회 할 수 있게 구조를 변경했습니다.

# 💬 리뷰 중점사항

2024-12-02 15:00 UTC, Soundbar91 requested changes
고생하셨습니다. 
하나의 API에서 값에 따라서 반환값이 달라져서, 스웨거에 추가 설명이 필요할 것 같아요..!

코멘트 확인 부탁드립니다.

2024-12-02 15:00 UTC, Soundbar91 commented on src/main/java/in/koreatech/koin/domain/timetableV2/controller/TimetableApiV2.java
>      @GetMapping("/v2/timetables/frame")
## R
이거 왜 인지 모르겠는데, 컨트롤러랑 API Path가 다르네요..? 뭐지뭐지

2024-12-02 15:00 UTC, Soundbar91 commented on src/main/java/in/koreatech/koin/domain/timetableV2/controller/TimetableApiV2.java
>          @RequestParam(name = "semester") String semester,
## C
여기에도 required 옵션 줘야 하나용 ??

2024-12-02 15:00 UTC, Soundbar91 commented on src/main/java/in/koreatech/koin/domain/timetableV2/service/TimetableFrameService.java
> +    @Transactional(readOnly = true)
## C
클래스에 readOnly 트랜잭션이 걸려있는데, 여기에 추가하신 이유가 궁금합니다 !

2024-12-02 15:00 UTC, Soundbar91 commented on src/main/java/in/koreatech/koin/domain/timetableV2/service/TimetableFrameService.java
> +        return Map.of("semesters", groupedBySemester);
## C
dto 클래스로 반환할 수 있을 것 같아요. 
리펙토링 할 때 반영하면 좋을 것 같아요 !

2024-12-02 15:02 UTC, Soundbar91 commented on src/main/java/in/koreatech/koin/domain/timetableV2/controller/TimetableApiV2.java
>      @GetMapping("/v2/timetables/frame")
이미 클라에서 적용이 됐을 것 같은데 `/v2/timetables/frame`은 기존 방식, `/v2/timetables/frames`는 새로운 방식으로 나눠도 좋을 것 같아요. 대응이 필요한,,

2024-12-02 15:41 UTC, seongjae6751 commented on src/main/java/in/koreatech/koin/domain/timetableV2/controller/TimetableApiV2.java
>      @GetMapping("/v2/timetables/frame")
스웨거에는 기존꺼도 /v2/timetables/frames로 올라가있네요!
저는 그래서 그냥 지금처럼 해도 되지 않을까 하는데 어떻게 생각하시나요

2024-12-02 15:55 UTC, Soundbar91 commented on src/main/java/in/koreatech/koin/domain/timetableV2/controller/TimetableApiV2.java
>      @GetMapping("/v2/timetables/frame")
좋습니당

2024-12-02 15:55 UTC, Soundbar91 approved these changes

2024-12-04 05:39 UTC, kwoo28 approved these changes
꼼꼼하게 잘 작성하신것같습니다. 수고 많으셨습니다!?

2024-12-04 05:41 UTC, merged