feat: 상점 메뉴 조회 API 구현
BCSDLab/KOIN_API_V2 pull request #112
Opened 2023-12-21 08:44 UTC by Invidam

# 🔥 연관 이슈

- close #41

# 🚀 작업 내용

1. 상점 메뉴 관련 도메인 생성
2. 상점 메뉴 조회 API([스테이지](https://api.stage.koreatech.in/swagger-ui.html#!/(Normal)_Shop/getMenuUsingGET_2)) 인수테스트 작성
3. 컨트롤러-서비스-레포지토리를 거쳐 처리하는 로직 완성

# 💬 리뷰 중점사항
1. 도메인 설계
2. 인수 테스트
  - Null 검사 부분
  - 데이터 저장 방식

# 참고
## 상점 - 메뉴 ERD

[드라이브 원본](https://lh3.googleusercontent.com/keep-bbsk/ALhRneFoTsgsZWFaMocx4hiTosqbretAGGDUggCpuVftlz4CdnHQiUL5R-WgiE995EP8J_A0DiyfdLc5xZ74a6kp4Mwme40iSuDwZ3Qj8MaOBUxWSn-Y=s512)

요약 이미지:
![상점 다이어그램 drawio](https://github.com/BCSDLab/KOIN_API_V2/assets/71889359/cd30692a-ba13-41a9-bf0a-f37407a1a3ab)

[ERD 설명 링크](https://inpa.tistory.com/entry/DB-%F0%9F%93%9A-%EB%8D%B0%EC%9D%B4%ED%84%B0-%EB%AA%A8%EB%8D%B8%EB%A7%81-1N-%EA%B4%80%EA%B3%84-%F0%9F%93%88-ERD-%EB%8B%A4%EC%9D%B4%EC%96%B4%EA%B7%B8%EB%9E%A8#:~:text=ERD%20(Entity%20Relationship%20Diagram)%EB%8A%94,%EC%9C%84%ED%95%B4%20%EA%B7%B8%EB%A0%A4%EB%86%93%EB%8A%94%20%EB%8B%A4%EC%9D%B4%EC%96%B4%EA%B7%B8%EB%9E%A8%EC%9D%B4%EB%8B%A4.)

2023-12-21 09:23 UTC, Choi-JJunho requested changes
고생하셨습니다~
몇가지 코멘트 남겼으니 확인 부탁드려요

2023-12-21 09:23 UTC, Choi-JJunho commented on src/main/java/in/koreatech/koin/controller/shop/ShopController.java
> +    }
### A

`@RequiredArgsConstructor`를 사용하는건 어떨까요?

```suggestion
@RestController
@RequiredArgsConstructor
public class ShopController {

    private final ShopService shopService;

```

2023-12-21 09:23 UTC, Choi-JJunho commented on src/main/java/in/koreatech/koin/domain/shop/Menu.java
> +    public static final int SINGLE_OPTION_COUNT = 1;
### C
해당 변수가 public인 이유가 있을까요?

2023-12-21 09:23 UTC, Choi-JJunho commented on src/main/java/in/koreatech/koin/domain/shop/Menu.java
> +    @Id
### R

한줄 공백을 주는건 어떨까요?
```suggestion
    public static final int SINGLE_OPTION_COUNT = 1;
    
    @Id
```

2023-12-21 09:23 UTC, Choi-JJunho commented on src/main/java/in/koreatech/koin/dto/shop/ShopMenuResponse.java
> +public class ShopMenuResponse {
### A
옵션의 개수에 따라 반환값이 달라지는걸 잘 표현해주셨네요 👍

2023-12-21 09:23 UTC, Choi-JJunho commented on src/main/java/in/koreatech/koin/dto/shop/ShopMenuResponse.java
> +        if (menu.getMenuOptions().size() <= 1) {
### C
> 위에서 만들어둔 hasMultipleOption 메소드를 사용하는건 어떤가요?
```suggestion
        if (menu.hasMultipleOption()) {
```
위와 동일한 의견입니다.

2023-12-21 09:23 UTC, Choi-JJunho commented on src/main/java/in/koreatech/koin/dto/shop/ShopMenuResponse.java
> +        if (menu.getMenuOptions().size() != 1) {
### C
위에서 만들어둔 hasMultipleOption 메소드를 사용하는건 어떤가요?
```suggestion
        if (menu.hasMultipleOption()) {
```

2023-12-21 09:23 UTC, Choi-JJunho commented on src/main/java/in/koreatech/koin/dto/shop/ShopMenuResponse.java
> +            throw new IllegalStateException("옵션이 하나를 초과한 메뉴입니다. 다른 팩터리 메서드를 활용해주세요.");
### C

`다른 팩터리 메서드를 활용해주세요` 라는 문구는 디버깅하는 입장에서 다소 어색할 수 있을 것 같다는 생각이 드는데 어떻게 생각하나요?
 해당 예외 메시지는 클라이언트에게 전달될 수 있다는 생각이 들어 위와 같은 메시지는 log로 남기는 방향도 생각해보면 좋을 것 같아요.

클래스 상단에 `@Slf4j`를 사용하여 다음과 같이 표현할 수도 있겠네요
```suggestion
            log.warn("옵션이 하나를 초과한 메뉴입니다. 다른 팩터리 메서드를 활용해주세요.");
            throw new IllegalStateException("서버에서 문제가 발생했습니다.");
```

2023-12-21 09:23 UTC, Choi-JJunho commented on src/main/java/in/koreatech/koin/service/shop/ShopService.java
> +
### A
`@RequiredArgsConstructor`를 사용하는건 어떨까요?

2023-12-21 09:23 UTC, Choi-JJunho commented on src/test/java/in/koreatech/koin/acceptance/ShopApiTest.java
> +    @DisplayName("옵션이 여러 개 있는 상점의 메뉴를 조회한다.")
꼼꼼한 테스트 👍

2023-12-21 09:23 UTC, Choi-JJunho commented on src/main/java/in/koreatech/koin/domain/shop/MenuCategoryMap.java
> +public class MenuCategoryMap {
### C
중간테이블이군요...
ManyToMany 관계라 어쩔수 없으려나요

2023-12-21 11:12 UTC, Invidam commented on src/main/java/in/koreatech/koin/domain/shop/Menu.java
> +    public static final int SINGLE_OPTION_COUNT = 1;
IntelliJ 리팩터링 단축키로 빼낸 뒤 접근 제어자를 안바꿨네요

https://www.jetbrains.com/help/idea/extract-constant.html 참고해서 기본적으로 private 되도록 바꿨습니당

2023-12-21 11:20 UTC, Invidam commented on src/main/java/in/koreatech/koin/dto/shop/ShopMenuResponse.java
> +            throw new IllegalStateException("옵션이 하나를 초과한 메뉴입니다. 다른 팩터리 메서드를 활용해주세요.");
TODO 걸어놓지말구 쓰레드에서 논의할걸 그랬네요

2023-12-23 13:05 UTC, daheeParkk approved these changes
수고하셨습니다!

2023-12-23 13:46 UTC, Invidam commented on src/main/java/in/koreatech/koin/domain/shop/MenuOption.java
> +    @Column(name = "`option`")
JPA Buddy 활용한 것 뿐인데, 버그가 있었떤 것 같네요..

앞으로 JPA Buddy 이용해 코드 생성하더라도, 한 번씩 살펴보겠습니다~

2023-12-23 13:46 UTC, Invidam commented on src/main/java/in/koreatech/koin/domain/shop/MenuImage.java
> +        if (this.menu != null) {
예외처리 위해서는 개행하는 게 좋을 것 같네요 👍

2023-12-23 13:59 UTC, songsunkook approved these changes
크게 고쳐야 할 부분은 없었던 것 같아요.
고생하셨습니다!

2023-12-23 13:59 UTC, songsunkook commented on src/main/java/in/koreatech/koin/dto/shop/ShopMenuResponse.java
> +            log.error("{}는 옵션이 하나인 메뉴입니다. createForSingleOption 메서드를 이용해야합니다.", menu);
```suggestion
            log.error("{}는 옵션이 하나인 메뉴입니다. createForSingleOption 메서드를 이용해야 합니다.", menu);
```
띄어쓰기.. 해주세요! ㅎㅎ

2023-12-24 01:50 UTC, Choi-JJunho approved these changes
고생하셨습니다 👍

2023-12-24 01:50 UTC, merged