refactor: 이미지 업로드 알림 로직 분리
BCSDLab/KOIN_API_V2 pull request #1124
Opened 2024-12-07 13:16 UTC by dradnats1012

# 🔥 연관 이슈

변경 이유 : 
```
기존에는 식단 이미지 업로드와 동시에 알림이 발송 됐는데 
그렇게 되면 모든 식단이 올라오지 않는 경우에도 알림이 발송되어 사용자들에게 좋지 않은 경험이 될것이라고 판단되어 
6분마다 검사후 특정 날짜와 타입에 대하여 모든 이미지가 업로드 되면 알림을 발송하기 위해서
```

# 🚀 작업 내용

1. 식단 품절 알림 로직 스케줄러로 분리

변경된 로직
- 시간을 기준으로 식단 타입을 가져옴 
- 날짜와 타입을 기준으로 해당하는 식단을 가져옴
- 해당하는 식단의 모든 이미지가 존재하는지 판단
- 오픈시간(1시간 전부터)인지 판단
- case : `모든 이미지 존재` && `오픈시간` 
    - case : `Redis에 해당하는 키가 있음`
        - 메서드 종료
    - case : `Redis에 해당하는 키가 없음` 
        - 알림 발송, `Redis`에 키값 넣기
- case : `오픈 시간 10분 전 이후` && `Redis에 해당하는 키가 없음` && `이미지가 하나라도 있음`
    - 알림 발송,  `Redis`에 키값 넣기 

# 💬 리뷰 중점사항
오래 걸렸네요.. 
혹시라도 이상한 부분 있는지 확인 부탁드립니다!

2024-12-07 15:05 UTC, Soundbar91 requested changes
브랜치에 [과거의 잔재](https://bcsdlab.slack.com/archives/CGQK77GCB/p1733297799558829?thread_ts=1733226731.093789&cid=CGQK77GCB)가 남아있어요..!
확인 부탁드립니다 (__)

2024-12-08 00:20 UTC, Soundbar91 approved these changes

2024-12-14 14:51 UTC, ImTotem approved these changes
conflict 해결해주세용~

2024-12-14 15:52 UTC, Choon0414 approved these changes
고생하셨습니다~!

2024-12-14 15:52 UTC, Choon0414 commented on src/main/java/in/koreatech/koin/domain/coop/util/CoopScheduler.java
> +    @Scheduled(cron = "0 30/6 16-17 * * *")
**A**
한번에 여러 개 되는 지는 몰랐네요

2024-12-14 15:52 UTC, Choon0414 commented on src/main/java/in/koreatech/koin/domain/coop/service/CoopService.java
> +    List<String> placeFilters = Arrays.asList("A코너", "B코너", "C코너");
**C**
여기 접근 제어 안해줘도 되나요?

2024-12-15 03:33 UTC, dradnats1012 commented on src/main/java/in/koreatech/koin/domain/coop/service/CoopService.java
> +    List<String> placeFilters = Arrays.asList("A코너", "B코너", "C코너");
오 나이스입니다

2024-12-15 03:43 UTC, merged