fix: 시간표 프레임 롤백 로직 수정
BCSDLab/KOIN_API_V2 pull request #1126
Opened 2024-12-10 14:07 UTC by Soundbar91

# 🔥 연관 이슈

- close #1125 

# 🚀 작업 내용

- 시간표 롤백 과정에서 발생하는 버그를 수정했습니다.
  - main 시간표 프레임과 main 시간표 프레임이 아닌 시간표 2개가 있음
  - main 시간표를 지우면 그 다음 시간표 프레임이 main이 됨
  - 그 시간표도 지우면 둘 다 main = false / is_deleted = 1 인 상태로 DB에 유지
  - 롤백 API 호출하면 is_delete = 0 으로만 복구되고, main은 여전히 false
  - 이때, 시간표 생성하면 다 main = false 으로 생성됨 (시간표 개수로 메인을 판단해서 생기는 문제)
  - 롤백 과정에서 현재 시간표의 개수를 바탕으로 main여부를 설정하는 로직을 넣었습니다. 

# 💬 리뷰 중점사항

2024-12-10 14:25 UTC, duehee approved these changes
앗. 빠른 대응 감사합니다
고생하셨습니다~

2024-12-10 15:23 UTC, seongjae6751 requested changes
아직 안드로이드 프로덕션에서 어떤 api 쓰는지 확신이 없기 때문에 우선 request change로 드리겠습니다!

2024-12-10 15:23 UTC, seongjae6751 commented on src/main/java/in/koreatech/koin/domain/timetableV2/service/TimetableLectureService.java
> +        }
C
존재 하는 지만 확인 하는 것이 목표라면 지금 방식보다
jpa의 exist를 사용해서 확인하는 것이 좋지 않을까 하는데 어떻게 생각하실까요?

2024-12-11 10:39 UTC, Soundbar91 commented on src/main/java/in/koreatech/koin/domain/timetableV2/service/TimetableLectureService.java
> +        }
오오 좋은 의견주셔서 감사합니다 !
관련해서 찾아보니, exist는 데이터를 발견함과 동시에 true를 반환해서 성능 향상에도 도움을 준다고 하네요 ! 
반영하겠습니다 !

2024-12-11 16:29 UTC, seongjae6751 approved these changes

2024-12-16 03:47 UTC, merged