fix: 중복된 여러개의 lecture_id 삭제 해결
BCSDLab/KOIN_API_V2 pull request #1128
Opened 2024-12-11 01:31 UTC by kwoo28

# 🔥 연관 이슈

- close #1127
기존 DB에 똑같은 lecture_id가 여러개 있을때 DELETE/v2/timetables/frame/{frameId}/lecture/{lectureId} API를 쓰게되면 오류가 발생했습니다.

# 🚀 작업 내용
1. JPA Repository에서 해당 쿼리반환타입을 List로 변경했습니다.

# 💬 리뷰 중점사항

2024-12-11 15:19 UTC, seongjae6751 requested changes
R
문제점이 **강의가 중복으로 들어가는 것**이 문제인거지 **잘못 들어간 중복된 강의들을 한번에 못 삭제 하는 것**이 문제는 아닌 것 같다는 생각이 드는데 어떻게 생각하실까요
(Unique 제약 조건 걸어주시면 좋을 것 같아용)

2024-12-11 15:36 UTC, kwoo28 commented
> R 문제점이 **강의가 중복으로 들어가는 것**이 문제인거지 **잘못 들어간 중복된 강의들을 한번에 못 삭제 하는 것**이 문제는 아닌 것 같다는 생각이 드는데 어떻게 생각하실까요 (Unique 제약 조건 걸어주시면 좋을 것 같아용)

소프트딜리트라서 유니크 제약조건을 어덯게 걸어야할지 모르겠더라고요..

2024-12-12 04:49 UTC, Soundbar91 reviewed
> 소프트딜리트라서 유니크 제약조건을 어덯게 걸어야할지 모르겠더라고요..

소프트 딜리트가 걸리네용,,
클라에서 시간표 복구 시간이 끝나면 하드 딜리트하는 api 호출하는 건 어떻게 생각하시나요?? 불필요할까요..?

2024-12-30 07:26 UTC, 20HyeonsuLee reviewed
>소프트 딜리트가 걸리네용,,
클라에서 시간표 복구 시간이 끝나면 하드 딜리트하는 api 호출하는 건 어떻게 생각하시나요?? 불필요할까요..?

redis를 이용해보는건 어떨까요👀

2025-02-05 08:53 UTC, Soundbar91 reviewed
이거 다시 테스트 하고 있는데, 이 문제가 아닌 거 같아요.

1. timetable_lecture에 쿼리 날릴 때, `is_deleted = 0`이 들어감
2. 안드에서 해봤는데 안 터짐 (ios는 제가 없어서,,)
3. 로컬에서 테스트 해봤는데 동일한 정규 강의 두 개가 `is_deleted=0`인 경우에 터지는데, 시간표 생성 할 때, 따닥 아닌 이상 클라에서 강의 시간 겹치는 거 막아줘서 이 경우가 안 나옴..|

의견 주시면 감사하겠습니다

2025-02-07 04:21 UTC, closed without merging