refactor: 패키지 구조 변경
BCSDLab/KOIN_API_V2 pull request #114
Opened 2023-12-26 08:14 UTC by Invidam

# 🔥 연관 이슈

- close #113

# 🚀 작업 내용

1. 유저, 트랙, 상점, 인증 도메인에 대한 패키지들 (현재까지의 모든 도메인들)을 분리하였다.
2. class로 존재하던 DTO들을 record로 변경하였다. 

## 패키지 구조 확인하기

<details>
<summary>이미지로 확인하기</summary>
<div markdown="1">

![image](https://github.com/BCSDLab/KOIN_API_V2/assets/71889359/667a7b73-0a8a-45ed-ab71-7159ad847a43)

</div>
</details>

<details>
<summary> 트리 구조로 확인하기 </summary>
<div markdown="1">

```
└── koin
    ├── KoinApplication.java
    ├── domain
    │   ├── auth
    │   │   └── JwtProvider.java
    │   ├── shop
    │   │   ├── controller
    │   │   │   └── ShopController.java
    │   │   ├── domain
    │   │   │   ├── Menu.java
    │   │   │   ├── MenuCategory.java
    │   │   │   ├── MenuCategoryMap.java
    │   │   │   ├── MenuImage.java
    │   │   │   └── MenuOption.java
    │   │   ├── dto
    │   │   │   └── ShopMenuResponse.java
    │   │   ├── repository
    │   │   │   └── MenuRepository.java
    │   │   └── service
    │   │       └── ShopService.java
    │   ├── track
    │   │   ├── controller
    │   │   │   └── TrackController.java
    │   │   ├── domain
    │   │   │   ├── Member.java
    │   │   │   ├── TechStack.java
    │   │   │   └── Track.java
    │   │   ├── dto
    │   │   │   ├── TrackResponse.java
    │   │   │   └── TrackSingleResponse.java
    │   │   ├── repository
    │   │   │   ├── MemberRepository.java
    │   │   │   ├── TechStackRepository.java
    │   │   │   └── TrackRepository.java
    │   │   └── service
    │   │       └── TrackService.java
    │   └── user
    │       ├── controller
    │       │   └── UserController.java
    │       ├── domain
    │       │   ├── Student.java
    │       │   ├── User.java
    │       │   ├── UserGender.java
    │       │   ├── UserIdentity.java
    │       │   ├── UserToken.java
    │       │   └── UserType.java
    │       ├── dto
    │       │   ├── UserLoginRequest.java
    │       │   └── UserLoginResponse.java
    │       ├── repository
    │       │   ├── UserRepository.java
    │       │   └── UserTokenRepository.java
    │       └── service
    │           └── UserService.java
    └── global
        ├── common
        │   └── BaseEntity.java
        ├── config
        │   └── JpaConfiguration.java
        └── exception
            └── GlobalExceptionHandler.java

```

</div>
</details>

# 💬 리뷰 중점사항
### 논의 해볼 내용과
> 이에 대한 생각

### Problem1. `domain.auth`에 인증 관련 유틸리티 객체(`JwtProvider`)가 있는데 적합할까요?
> `global.util`을 만드는 건 어떨까요?

### Problem2. `global.common`이라는 패키지는 너무 포괄적이어서 다양한 역할의 클래스들이 모이게 될 것 같아요.
> 추후 다양한 클래스들이 생기면 리팩터링하면 어떨까요?

# 기타

RCA 룰을 이용해서 리뷰 남겨주세요~

2023-12-26 08:34 UTC, Choi-JJunho requested changes
고생하셨습니다!
남겨주신 의견에 대한 제 의견을 남겨봤습니다 확인 부탁드려요~

2023-12-26 08:34 UTC, Choi-JJunho commented on src/main/java/in/koreatech/koin/domain/auth/JwtProvider.java
> +package in.koreatech.koin.domain.auth;
### C
최상위 domain 패키지는 생략하는게 어떤가요?

`domain...domain` 과 같은 구조가 나오는데 최상단의 domain이라는 패키지는 생략해도 좋을 것 같다는 의견입니다.

> 변경 전
<img width="307" alt="image" src="https://github.com/BCSDLab/KOIN_API_V2/assets/49794401/c83361ed-23fa-4654-a1bd-319ee146b215">

> 변경 후
<img width="312" alt="image" src="https://github.com/BCSDLab/KOIN_API_V2/assets/49794401/e85847b4-f095-42cf-81ce-6d9ed2033f43">

2023-12-26 08:34 UTC, Choi-JJunho commented on src/main/java/in/koreatech/koin/domain/auth/JwtProvider.java
> +package in.koreatech.koin.domain.auth;
### A
> Q: domain.auth에 인증 관련 유틸리티 객체(JwtProvider)가 있는데 적합할까요?

위와같이 최상단의 domain을 제거하면 굳이 util로 묶지 않아도 좋아보인다는 의견입니다.

2023-12-26 08:34 UTC, Choi-JJunho commented on src/main/java/in/koreatech/koin/global/common/BaseEntity.java
> +package in.koreatech.koin.global.common;
### A

> Q: global.common이라는 패키지는 너무 포괄적이어서 다양한 역할의 클래스들이 모이게 될 것 같아요.
추후 다양한 클래스들이 생기면 리팩터링하면 어떨까요?

동의합니다~
저는 현재로서 common 이상으로 구체화시킬 네이밍이 생각나지않네요 😅

2023-12-26 09:18 UTC, songsunkook commented on src/main/java/in/koreatech/koin/domain/auth/JwtProvider.java
> +package in.koreatech.koin.domain.auth;
저도 상위 domain 패키지 생략이 좋아보입니다.

2023-12-26 09:22 UTC, songsunkook commented
### C
> 논의해볼 내용

결국에는 Menu나 User, Track과 같이 세부 클래스들을 하위 패키지로 묶어야 할 것 같은데, 지금 패키지 구조를 변경하면서 함께 진행하는 것은 어떻게 생각하세요?? 저는 이후 개발을 진행할 때도 알아서 패키지를 분리하고 작업할 수 있어 좋다고 생각합니다.

### A
> Problem1. domain.auth에 인증 관련 유틸리티 객체(JwtProvider)가 있는데 적합할까요? 
global.util을 만드는 건 어떨까요?

저도 `auth`가 `domain` 패키지와 형제 관계로 유지된다면 괜찮다고 생각합니다!

### C
Problem2. global.common이라는 패키지는 너무 포괄적이어서 다양한 역할의 클래스들이 모이게 될 것 같아요.
추후 다양한 클래스들이 생기면 리팩터링하면 어떨까요?

`base`와 같이 패키지를 분리하는 방향에 대해 생각해보았는데, `base`가 되는 패키지가 많을 것 같지도 않아서 그 때 가서 패키지를 분리해도 충분하다는 생각이 들었습니다. 저도 `common`이라는 네이밍으로 진행하는 것이 적절하다고 생각합니다.

2023-12-26 12:55 UTC, daheeParkk approved these changes
수고하셨습니다!

### A
> Problem1. domain.auth에 인증 관련 유틸리티 객체(JwtProvider)가 있는데 적합할까요?

여러 곳에서 사용되니까 global 하위에 auth 패키지를 만드는 건 어떨까요?

### A
> Problem2. global.common이라는 패키지는 너무 포괄적이어서 다양한 역할의 클래스들이 모이게 될 것 같아요.

추후 클래스들이  생기면 common 패키지 하위에 패키지로 구별하는 방식으로 리팩토링하면 좋을 것 같습니다..!

2023-12-26 15:02 UTC, songsunkook approved these changes

2023-12-26 15:12 UTC, Invidam commented on src/main/java/in/koreatech/koin/domain/auth/JwtProvider.java
> +package in.koreatech.koin.domain.auth;
가시성은 떨어지긴 하지만,

global은 user, track과 추상화 레벨이 다르다고 생각하여 user와 track을 묶어주는 별도 계층은 필요할 것 같아요

`domain.~~.domain`이라는 이름이 가시성이 떨어지는 것이 문제라면

`domain.~~.model` 이런 네이밍은 어떨까요?


### 참고
- [추상화](http://www.ktword.co.kr/test/view/view.php?m_temp1=3026)
- [domain vs model](https://velog.io/@wnajsldkf/%EB%8F%84%EB%A9%94%EC%9D%B8%EA%B3%BC-%EB%AA%A8%EB%8D%B8%EC%9D%98-%EA%B0%80%EC%9E%A5-%ED%81%B0-%EC%B0%A8%EC%9D%B4%EA%B0%80-%EB%AC%B4%EC%97%87%EC%9D%B4%EB%9D%BC%EA%B3%A0-%EC%83%9D%EA%B0%81%ED%95%98%EC%8B%9C%EB%82%98%EC%9A%94)
- [도메인 관련 여러 용어 표로 정리](https://devfunny.tistory.com/874)

2023-12-26 15:39 UTC, Invidam commented
> 결국에는 Menu나 User, Track과 같이 세부 클래스들을 하위 패키지로 묶어야 할 것 같은데, 지금 패키지 구조를 변경하면서 함께 진행하는 것은 어떻게 생각하세요?? 저는 이후 개발을 진행할 때도 알아서 패키지를 분리하고 작업할 수 있어 좋다고 생각합니다.

`shop.menu`.Menu.class
`shop.menu`.MenuOption.class
`shop`.Shop.class
가 되어야 한다는 이야기 일까요? 그렇다면 아예 


`menu`.Menu.class
`menu`.MenuOption.class
`shop`.Shop.class

로 나누는 건 어떨까요?

(개인적으로 [링크](https://hwannny.tistory.com/74)보며 어그리게이트라는 개념을 조금 알게되었는데 이러한 개념을 적용해봤어요)

2023-12-26 15:55 UTC, Invidam commented
auth를 "도메인의 일부"로 볼건지, "유틸리티의 일부"로 볼 건지에 따라 패키지 위치가 달라질 것 같아요.
생각해본 결과 저는 도메인이면서 유틸리티라고 생각이 드네요. 

둘 다 속한다면 도메인에 넣는 게 모듈화에 좋을 것 같아요.

(기존 코인같은 경우는 라이브러리를 활용하는 JwtUtil(유틸리티)과 Jwt 처리 로직이 있는 JwtManager(도메인?)로 분리했었는데 오버엔지니어링 같긴 합니다..)

2023-12-27 00:37 UTC, songsunkook commented
@Invidam 

### C

> @songsunkook
> 
> > 결국에는 Menu나 User, Track과 같이 세부 클래스들을 하위 패키지로 묶어야 할 것 같은데, 지금 패키지 구조를 변경하면서 함께 진행하는 것은 어떻게 생각하세요?? 저는 이후 개발을 진행할 때도 알아서 패키지를 분리하고 작업할 수 있어 좋다고 생각합니다.
> 
> `shop.menu`.Menu.class `shop.menu`.MenuOption.class `shop`.Shop.class 가 되어야 한다는 이야기 일까요? 그렇다면 아예
> 
> `menu`.Menu.class `menu`.MenuOption.class `shop`.Shop.class
> 
> 로 나누는 건 어떨까요?
> 
> (개인적으로 [링크](https://hwannny.tistory.com/74)보며 어그리게이트라는 개념을 조금 알게되었는데 이러한 개념을 적용해봤어요)

첨부해주신 글 잘 읽었습니다! 확실히 애그리거트 설계 방법을 도입하는 것도 좋아 보입니다. 각 애그리거트 간 의존 관계를 낮추면서 애그리거트의 루트 객체만 서브 객체의 상태를 변경할 수 있다는 성질이 강건성에 도움을 줄 수 있을 것 같아요!

다만 제안해주신 패키지 경로는 애그리거트별로 패키지를 분리한다는 관점에서 직관적일 수 있지만 도메인이 쌓이다 보면 `menu` 패키지가 어느 api에 쓰이는 도메인인지 헷갈릴 수 있을 것 같습니다. 

저는 
- `shop.menu`.Menu.class 
- `shop.menu`.MenuOption.class 
- `shop`.Shop.class 

와 같이 작성하여 애그리거트와 상위 애그리거트 사이의 관계를 표현하는 것이 적절하다고 생각합니다.

2023-12-27 00:56 UTC, songsunkook commented
### A

> @songsunkook @daheeParkk @Choi-JJunho 좋은 의견들 감사합니다.
> 
> auth를 "도메인의 일부"로 볼건지, "유틸리티의 일부"로 볼 건지에 따라 패키지 위치가 달라질 것 같아요. 생각해본 결과 저는 도메인이면서 유틸리티라고 생각이 드네요.
> 
> 둘 다 속한다면 도메인에 넣는 게 모듈화에 좋을 것 같아요. 어떻게 생각하시나용?? (기존 코인같은 경우는 라이브러리를 활용하는 JwtUtil(유틸리티)과 Jwt 처리 로직이 있는 JwtManager(도메인?)로 분리했었는데 오버엔지니어링 같긴 합니다..)

global 패키지는 아래와 같은 특성을 지니고 있습니다.
- 특정 domain에 종속되지 않는다.
- 프로젝트 전방위적으로 활용 가능하다.

`JwtProvider`는 위 특성에 만족하기 때문에 global 패키지 내에 있는 것이 적절하다고 생각합니다.

+) domain 패키지를 DB 연관 작업의 응집처라고 생각한다면 더욱 global 패키지에 두는 것이 적절하다고 생각합니다.

참고 자료) https://velog.io/@jsb100800/Spring-boot-directory-package

2023-12-27 04:22 UTC, Invidam commented
> 
> global 패키지는 아래와 같은 특성을 지니고 있습니다.
> 
> * 특정 domain에 종속되지 않는다.
> * 프로젝트 전방위적으로 활용 가능하다.
> 
> `JwtProvider`는 위 특성에 만족하기 때문에 global 패키지 내에 있는 것이 적절하다고 생각합니다.
> 
> +) domain 패키지를 DB 연관 작업의 응집처라고 생각한다면 더욱 global 패키지에 두는 것이 적절하다고 생각합니다.
> 
> 참고 자료) https://velog.io/@jsb100800/Spring-boot-directory-package

도메인을 DB 작업의 응집이라고 볼순 없을 것 같아요. 저는 비지니스 로직 처리를 위해 모델링된 객체라고 생각합니다. (참고: [링크](https://hudi.blog/domain-domain-model-domain-object/#:~:text=%EB%A7%88%ED%8B%B4%20%ED%8C%8C%EC%9A%B8%EB%9F%AC%EC%97%90%20%EB%94%B0%EB%A5%B4%EB%A9%B4%20%EB%8F%84%EB%A9%94%EC%9D%B8,%EA%B0%9D%EC%B2%B4%EB%9D%BC%EA%B3%A0%20%ED%95%A0%20%EC%88%98%20%EC%9E%88%EB%8B%A4.))

생각해봤는데 (1) 추후 auth 관련 API들이 생겨날 수도 있고 (2) 인증 서버가 분리될 수도 있어서 별도 도메인으로 있긴 해야할 것 같아요

2023-12-27 04:27 UTC, Invidam commented
> @Invidam
> 
> ### A
> > @songsunkook
> > > 결국에는 Menu나 User, Track과 같이 세부 클래스들을 하위 패키지로 묶어야 할 것 같은데, 지금 패키지 구조를 변경하면서 함께 진행하는 것은 어떻게 생각하세요?? 저는 이후 개발을 진행할 때도 알아서 패키지를 분리하고 작업할 수 있어 좋다고 생각합니다.
> > 
> > 
> > `shop.menu`.Menu.class `shop.menu`.MenuOption.class `shop`.Shop.class 가 되어야 한다는 이야기 일까요? 그렇다면 아예
> > `menu`.Menu.class `menu`.MenuOption.class `shop`.Shop.class
> > 로 나누는 건 어떨까요?
> > (개인적으로 [링크](https://hwannny.tistory.com/74)보며 어그리게이트라는 개념을 조금 알게되었는데 이러한 개념을 적용해봤어요)
> 
> 첨부해주신 글 잘 읽었습니다! 확실히 애그리거트 설계 방법을 도입하는 것도 좋아 보입니다. 각 애그리거트 간 의존 관계를 낮추면서 애그리거트의 루트 객체만 서브 객체의 상태를 변경할 수 있다는 성질이 강건성에 도움을 줄 수 있을 것 같아요!
> 
> 패키지 구조도 레이어 단위 분리가 아니라 도메인 단위 분리로 이루어지니 헷갈리거나 할 일이 없어서 패키지 구조를 단순화하는 것도 좋아 보입니다.
> 
> +) 제가 지금까지 새로운 구조에 대한 이해가 부족했었는데, 지금 보니 하위 패키지를 묶을 필요성도 크게 없을 것 같아요..!

요건 문제가 복잡하니까 나중에 프로젝트에 많은 도메인들이 생기면 그 때 다시 생각하는 건 어떨까 싶습니다 ㅋㅋㅋ

2023-12-28 12:09 UTC, Choi-JJunho commented on src/main/java/in/koreatech/koin/domain/auth/JwtProvider.java
> +package in.koreatech.koin.domain.auth;
domain과 model이라는 용어를 분리하는게 좋아보이네요 👍

2023-12-29 23:38 UTC, Choi-JJunho approved these changes
반영한 내용 확인했습니다~
고생하셨습니다!

2023-12-29 23:38 UTC, merged