feat : 엑셀 파일로 과거 시간표 추가하기
BCSDLab/KOIN_API_V2 pull request #1153
Opened 2024-12-27 13:17 UTC by duehee

# 🔥 연관 이슈

- close #1140

# 🚀 작업 내용

1. 엑셀 파일을 이용해 과거 시간표를 추가할 수 있는 API를 작성했습니다.
- 엑셀 파일이라 함은, 학사에서 제공하는 성적 확인 엑셀입니다.(아래 사진 참조)
<img width="601" alt="image" src="https://github.com/user-attachments/assets/c439df40-a1b3-465c-b348-c89c5b6b0a51" />

- 이를 이용하여 2019학년도 2학기부터 시작하여 정보를 집어넣을 수 있습니다.
- 현재 재수강과 S/U 중 U를 받게 되면 입력되지 않도록 했습니다. (F의 경우는 인정이 되는지 모르겠어서, 데이터가 있다면 의견 주시면 감사하겠습니다.)
- 학사에서 제공하는 엑셀 파일의 형식은 "xls"이어서, "xlsx"에 대한 처리는 추가적으로 진행하지 않았습니다.
- 아래의 사진은 성적표를 집어넣을 시, 데이터가 어떻게 추가되는지에 대한 사항입니다. 
- course_type은 임의로 "전필" 하나를 집어넣고 테스트했는데, 문제 없었습니다. 추후 course_type 크롤링 사항에 따라 상황을 보고 코드 수정 예정입니다. 
<img width="539" alt="image" src="https://github.com/user-attachments/assets/26f29e13-64a0-4d26-8a5f-9ae438e98d3e" />
<img width="823" alt="image" src="https://github.com/user-attachments/assets/a4e5146a-ad5a-4b0a-a291-73d65e2c8848" />

# 💬 리뷰 중점사항
엄청 오래 걸릴 사항은 아니었는데, 생각보다 따질 사항이 많아서 코드 작성이 오래 걸린 것 같습니다.
예전 코드를 최신화하며 graduation 패키지에서 model 밖에 없길래 따로 추가해서 작성했습니다.
일단 먼저 리뷰해주시고, 아마 충돌 문제 생길 거 같아서 추가 할 사항 있으면 그것도 말씀해주시면 감사하겠습니다.

브랜치에서 테스트를 하고 싶으신 분이 있다면 아래의 사항을 따라서 진행해주세요.
1. Swagger에서는 파일이 안 올라가므로, Postman으로 진행합니다.
2. 로그인을 진행해서 토큰 받고,`localhost:8080/graduation/excel/upload` 을 **POST**로 처리합니다.
3. body의 file을 선택하고, **Key**에 "file"이라고 적습니다. 그 후 Value에 엑셀 파일을 넣습니다.
<img width="764" alt="image" src="https://github.com/user-attachments/assets/5dad3506-1665-4121-8615-bf6513dd1156" />

4. 아래 사진이 뜬다면 성공! DB에서 확인해보세요.
<img width="788" alt="image" src="https://github.com/user-attachments/assets/3f38d6ab-7b85-410f-a9d8-4c9d16eaa896" />

코드 좀 지저분할수도 있습니다. 수정사항 있다면 말씀해주세요. 긴 글 읽어주셔서 감사합니다.😄

2024-12-27 14:54 UTC, Soundbar91 requested changes
고생하셨습니다 💯 
졸학계 컨텍스트 부족 + 처음보는 라이브러리 공부할 게 많아 보이네요..!
코멘트 확인 부탁드립니다 👍

2024-12-27 14:54 UTC, Soundbar91 commented on src/main/java/in/koreatech/koin/domain/graduation/dto/ExcelStudentData.java
> +public record ExcelStudentData(
## C
학생의 수강 정보가 저장된 엑셀 파일을 읽은 데이터 `GradeExcelData`도 괜찮아 보여요 ! 변수도 excel로 빼면 좋을 거 같아요.

2024-12-27 14:54 UTC, Soundbar91 commented on src/main/java/in/koreatech/koin/domain/graduation/service/GraduationService.java
> +             Workbook workbook = new HSSFWorkbook(inputStream)) {
## C
개행 해주면 보기 좋을 거 같아요 !

2024-12-27 14:54 UTC, Soundbar91 commented on src/main/java/in/koreatech/koin/domain/graduation/service/GraduationService.java
> +                    .build();
## R
초기값(null)을 사용할 수 있는 필드는 빌드로 선언 안 해도 될 것 같아요 ! 코드가 더 길어보이는 느낌이..

2024-12-27 14:54 UTC, Soundbar91 commented on src/main/java/in/koreatech/koin/domain/graduation/service/GraduationService.java
> +                }
## A
제가 이 라이브러리는 처음이라,, 😢 
코드를 줄일 수 있는 방법을 같이 찾아보면 좋을 것 같아요 !

2024-12-27 14:54 UTC, Soundbar91 commented on src/main/java/in/koreatech/koin/domain/graduation/service/GraduationService.java
> +                timetableFrame.cancelMain();
## C
시간표 메인을 취소하는 이유가 궁금합니다.
졸학계 컨텍스트가 부족하니 어렵네요 😿

2024-12-27 14:54 UTC, Soundbar91 commented on src/main/java/in/koreatech/koin/domain/graduation/service/GraduationService.java
> +            .isMain(true)
## R
이 부분도 컨텍스트가 부족해서 여쭙니다..!

이렇게 되면 `졸업학점 계산용 테이블`의 이름으로 사용자 시간표가 생기게 되는데, 사용자가 이 이름을 꺼려할 수 있을 것 같다는 생각이 듭니다..

메인 시간표만 학점 계산에 들어간다고 기억이 나는데, 관련해서 회의 때 이야기 나누면 좋을 것 같아요 !

2024-12-27 14:54 UTC, Soundbar91 commented on src/main/java/in/koreatech/koin/domain/graduation/service/GraduationService.java
> +    private ExcelStudentData extractStudentData(Row row) {
## R
record에 정적 팩토리 메소드를 선언해서 사용하면, 서비스에서 코드를 줄일 수 있을 것 같아요

2024-12-27 14:54 UTC, Soundbar91 commented on src/main/java/in/koreatech/koin/domain/graduation/service/GraduationService.java
> +            throw new ExcelFileCheckException("엑셀 파일인지 확인 해주세요.");
## R
어..! 이렇게 되면 `.xls`도 막히는 거 아닌가용..?

2024-12-27 14:54 UTC, Soundbar91 commented on src/main/java/in/koreatech/koin/domain/graduation/dto/ExcelStudentData.java
> +public record ExcelStudentData(
## C
이 친구는 dto보다는 model로 들어가는게 적절해보이는데, 어떻게 생각하시나요 ??

2024-12-28 02:00 UTC, Soundbar91 commented on src/main/java/in/koreatech/koin/domain/graduation/service/GraduationService.java
> +            throw new ExcelFileCheckException("엑셀 파일인지 확인 해주세요.");
아아 착각했네욥,,

2024-12-28 04:24 UTC, duehee commented on src/main/java/in/koreatech/koin/domain/graduation/dto/ExcelStudentData.java
> +public record ExcelStudentData(
간단하게 정말 정보만 캡슐화하는 용도로만 사용해서 DTO로 뒀는데.. 이런 경우에는 모델이 더 나은 판단일까요?
`UserDeleteEvent`를 Model에 관리하는 것처럼 하는게 더 좋을까요? 반영해볼게요!

2024-12-28 04:26 UTC, duehee commented on src/main/java/in/koreatech/koin/domain/graduation/service/GraduationService.java
> +                timetableFrame.cancelMain();
성적표를 사용해서 시간표를 추가하는 건 결국, 과거의 시간표에 값을 대입하는 경우에요!
시간표를 띄우는 건 결국 가장 최근 학기를 보여주는 게 주인데, 메인 시간표의 학점을 더하는 로직을 사용하는 시점에서는 과거의 시간표를 메인으로 설정하는 것이 필요하기 때문에 기존에 있던 Main 시간표를 취소하고 졸업학점 계산용 프레임을 Main으로 두기 위해서 Cancel을 진행했어요.

2024-12-28 04:29 UTC, duehee commented on src/main/java/in/koreatech/koin/domain/graduation/service/GraduationService.java
> +            .isMain(true)
이름을 어떻게 지으면 좋을까요? 그냥 고민고민하다가 일단 저 이름으로 넣어놓긴 했는데, 의견 있다면 부탁드려요 :D

2024-12-28 04:29 UTC, duehee commented on src/main/java/in/koreatech/koin/domain/graduation/service/GraduationService.java
> +                }
ㅎㅋㅋㅋ 많이 줄였는데.. 더 필요하군요..

2024-12-28 04:30 UTC, duehee commented on src/main/java/in/koreatech/koin/domain/graduation/service/GraduationService.java
> +                    .build();
확인해볼게요!

2024-12-28 04:37 UTC, duehee commented on src/main/java/in/koreatech/koin/domain/graduation/service/GraduationService.java
> +             Workbook workbook = new HSSFWorkbook(inputStream)) {
<img width="466" alt="image" src="https://github.com/user-attachments/assets/ede1a77f-5ba0-4486-ba06-edafd140d0b1" />

👀

2024-12-28 04:37 UTC, duehee commented on src/main/java/in/koreatech/koin/domain/graduation/dto/ExcelStudentData.java
> +public record ExcelStudentData(
이름 수정해볼게요~!

2024-12-28 05:38 UTC, Soundbar91 commented on src/main/java/in/koreatech/koin/domain/graduation/service/GraduationService.java
> +             Workbook workbook = new HSSFWorkbook(inputStream)) {
![image](https://github.com/user-attachments/assets/c4641687-43d6-4cca-8a3e-c7c588ba42a3)
👀

2024-12-28 05:44 UTC, Soundbar91 commented on src/main/java/in/koreatech/koin/domain/graduation/service/GraduationService.java
> +            .isMain(true)
메인 시간표..? 어렵네요 네이밍은 역시 😢

2024-12-28 05:46 UTC, Soundbar91 commented on src/main/java/in/koreatech/koin/domain/graduation/dto/ExcelStudentData.java
> +public record ExcelStudentData(
계층 간 데이터를 전송하는 역할을 수행하지 않고 있다고 생각이 들어서, dto보다는 모델이 나아보였어요 !

2024-12-28 05:54 UTC, Soundbar91 approved these changes

2024-12-28 06:16 UTC, duehee commented on src/main/java/in/koreatech/koin/domain/graduation/service/GraduationService.java
> +             Workbook workbook = new HSSFWorkbook(inputStream)) {
아하

2024-12-28 06:34 UTC, Soundbar91 commented on src/main/java/in/koreatech/koin/domain/graduation/service/GraduationService.java
> +             Workbook workbook = new HSSFWorkbook(inputStream)) {
이쁜 거 같아요.. 개인 취향입니다 😸

2024-12-30 07:17 UTC, 20HyeonsuLee commented on src/main/java/in/koreatech/koin/domain/graduation/service/GraduationService.java
> +                }
if문에 중괄호가 없어요👀

2024-12-30 07:20 UTC, 20HyeonsuLee commented on src/main/java/in/koreatech/koin/domain/graduation/service/GraduationService.java
> +            throw new ExcelFileCheckException("엑셀 파일인지 확인 해주세요.");
뭔가 가독성 더 좋아보이는 코드 투척
```suggestion
        if (!(extension.equals("xls") || extension.equals("xlsx"))) {
            throw new ExcelFileCheckException("엑셀 파일인지 확인 해주세요.");
```

2024-12-30 07:22 UTC, 20HyeonsuLee commented on src/main/java/in/koreatech/koin/domain/graduation/dto/ExcelStudentData.java
> +public record ExcelStudentData(
비즈니스에서 사용되는 Model 객체를 만들어서 사용하기도 하네요😃
https://www.youtube.com/watch?v=ZE_R0PN_yGA

2024-12-30 13:14 UTC, duehee commented on src/main/java/in/koreatech/koin/domain/graduation/service/GraduationService.java
> +                }
앗!!! 머지 전 발견해서 다행이에요👀 감사함니다

2024-12-30 13:30 UTC, merged