feat: 졸업학점 계산 동의 API 및 학과, 시간표 수정 대응
BCSDLab/KOIN_API_V2 pull request #1154
Opened 2024-12-27 23:53 UTC by kwoo28

# 🔥 연관 이슈

- close #이슈번호

# 🚀 작업 내용

1. 졸업학점 계산 동의 API 구현했습니다.
해당 학생에 대한 졸업학점 계산 동의 요청 api를 날리게되면 계산테이블과 변경감지테이블에 학생에 대한 데이터값이 초기화됩니다.

2. 시간표 수정
aop를 이용하여 시간표 생성, 수정, 삭제되는 요청에 대해 공통적으로 변경감지테이블의 변경 여부를 true로 변경시킵니다.

3. 학과 수정
학생이 학과를 수정했을때 기존 계산테이블을 삭제하고, 새롭게 변경된 학과의 졸업요건에 맞게 계산테이블의 데이터값이 초기화됩니다.

# 💬 리뷰 중점사항

2024-12-28 06:15 UTC, duehee approved these changes
고생하셨습니다~
작은 코멘트 하나씩만 확인해주세요 :D

2024-12-28 06:32 UTC, Soundbar91 requested changes
고생하셨습니다 💯 
코멘트 확인해주세욥

2024-12-28 06:32 UTC, Soundbar91 commented on src/main/java/in/koreatech/koin/domain/graduation/aop/GraduationAspect.java
> +    @AfterReturning(pointcut = "execution(* in.koreatech.koin.domain.timetable.controller.TimetableController.createTimetables(..)) || " +
## C
GET 요청만 요청한다면, 포인트 컷으로 `GetMapping`을 제외시키고 나머 요청만 포함시키면 줄일 수 있을 것 같아요 !

히스토리 구현할 때 이렇게 작성했었습니다 !

```java
@Pointcut("execution(* in.koreatech.koin.admin..controller.*.*(..))")
private void allAdminControllers() {}

@Pointcut("!@annotation(org.springframework.web.bind.annotation.GetMapping)")
private void excludeGetMapping() {}
```

2024-12-28 06:32 UTC, Soundbar91 commented on src/main/java/in/koreatech/koin/domain/graduation/aop/GraduationAspect.java
> +        Integer userId = (Integer) args[1];
## A
저는 `AuthContext`에서 userId를 가져오는 방법을 사용했었는데, 이런 방법도 있었네요 !

2024-12-28 06:32 UTC, Soundbar91 commented on src/main/java/in/koreatech/koin/domain/graduation/repository/StudentCourseCalculationRepository.java
> +public interface StudentCourseCalculationRepository extends JpaRepository<StudentCourseCalculation, Integer> {
## A
여기에서는 `JpaRepository`를 사용하신 이유가 있으신가요 ?

2024-12-28 06:32 UTC, Soundbar91 commented on src/main/java/in/koreatech/koin/domain/graduation/service/GraduationService.java
> +        );
## R
`createStudentCourseCalculation`메소드에서도 동일한 로직이 있어서 메소드화 하면 좋을 것 같습니다.

2024-12-29 03:49 UTC, duehee commented on src/main/java/in/koreatech/koin/domain/graduation/repository/StudentCourseCalculationRepository.java
> +public interface StudentCourseCalculationRepository extends JpaRepository<StudentCourseCalculation, Integer> {
예리하셔라 👀

2024-12-29 12:21 UTC, kwoo28 commented on src/main/java/in/koreatech/koin/domain/graduation/aop/GraduationAspect.java
> +        Integer userId = (Integer) args[1];
근데 AuthContext에서 가져오는 방법이 더 좋겠네요. ㅋㅋ 감사합니다

2024-12-29 12:26 UTC, kwoo28 commented on src/main/java/in/koreatech/koin/domain/graduation/service/GraduationService.java
> +        }
!넵!

2024-12-29 12:29 UTC, kwoo28 commented on src/main/java/in/koreatech/koin/domain/graduation/service/GraduationService.java
> +                student.getDepartment(), student.getStudentNumber().substring(0, 4));
감사합니다

2024-12-29 12:35 UTC, kwoo28 commented on src/main/java/in/koreatech/koin/domain/graduation/aop/GraduationAspect.java
> +    @AfterReturning(pointcut = "execution(* in.koreatech.koin.domain.timetable.controller.TimetableController.createTimetables(..)) || " +
좋은방법이네요! 근데 Frame의 생성,수정 요청은 포함시키지 않기때문에 Get요청빼고 다 포함시키엔 걸리더라구요..

2024-12-29 12:41 UTC, kwoo28 commented on src/main/java/in/koreatech/koin/domain/graduation/repository/StudentCourseCalculationRepository.java
> +public interface StudentCourseCalculationRepository extends JpaRepository<StudentCourseCalculation, Integer> {
예전에 무슨 오류때문에 저렇게 썼었는데 기억이 안나네요.... 근데 지금 다시 Repository로 수정해보니 오류가 안생기네요. 수정하겠습니다

2024-12-29 12:50 UTC, kwoo28 commented on src/main/java/in/koreatech/koin/domain/graduation/service/GraduationService.java
> +        );
알겠습니다!

2024-12-29 13:48 UTC, Soundbar91 approved these changes

2025-01-04 02:16 UTC, merged