feat: 졸업학점 자신이 들은 학점 보여주는 기능 구현
BCSDLab/KOIN_API_V2 pull request #1155
Opened 2024-12-28 03:24 UTC by seongjae6751

# 🔥 연관 이슈

- close #860

# 🚀 작업 내용

사용자 id를 받아서 다음과 같이 동작합니다. 

동작 과정:

**1. 학생 검증**
Student 테이블에서 해당 학생의 정보(학과, 학번 등)를 확인합니다.
학과나 학번이 누락된 경우 예외를 발생시킵니다.

**2. 시간표 데이터 조회**
학생이 수강한 모든 강의를 조회하고, 각 강의가 소속된 대학 요람 데이터(Catalog)를 가져옵니다.
강의명(lectureName), 학생의 입학 연도, 학과 정보를 바탕으로 대학 요람 정보를 조회합니다.

**3. 이수구분별 학점 계산**
조회된 Catalog 데이터를 기반으로, 각 이수구분(courseType)별로 학점을 합산합니다.

**4. 졸업 요건 비교**
학생의 학과와 입학 연도를 기준으로 StandardGraduationRequirements에서 졸업 기준 정보를 가져옵니다.
각 이수구분별 졸업 기준 학점과 계산된 학점을 비교합니다.

**5. 결과 저장 및 반환**
각 이수구분별 계산 결과를 StudentCourseCalculation 테이블에 저장하거나 업데이트합니다.
응답 객체(GraduationCourseCalculationResponse)를 생성하여 클라이언트에 반환합니다.

# 💬 리뷰 중점사항

2024-12-28 07:59 UTC, Soundbar91 requested changes
고생하셨습니다 💯 
코멘트 확인 부탁드립니다 !

2024-12-28 07:59 UTC, Soundbar91 commented on src/main/java/in/koreatech/koin/domain/graduation/service/GraduationService.java
> +        String studentYear = student.getStudentNumber().substring(0, 4);
## R
Student 패키지 StudentUtil 클래스에 학점 추출 메소드 사용하면 좋을 것 같아요 !

2024-12-28 07:59 UTC, Soundbar91 commented on src/main/java/in/koreatech/koin/domain/graduation/service/GraduationService.java
> +        }
## R
`throw` 키워드가 없어요..! 이렇게 해도 예외가 던져지나요 ??

2024-12-28 07:59 UTC, Soundbar91 commented on src/main/java/in/koreatech/koin/domain/graduation/service/GraduationService.java
> +            .map(timetableLecture -> timetableLecture.getLecture().getName())
## C
커스텀 강의인 경우 NPE가 발생할 것 같아요 !

2024-12-28 07:59 UTC, Soundbar91 commented on src/main/java/in/koreatech/koin/domain/graduation/service/GraduationService.java
> +        List<GraduationCourseCalculationResponse.InnerCalculationResponse> courseTypes = new ArrayList<>();
## C
static import !

2024-12-28 07:59 UTC, Soundbar91 commented on src/main/java/in/koreatech/koin/domain/graduation/service/GraduationService.java
> +            throw new IllegalStateException("CourseType이 null입니다.");
## C
표준 예외를 사용한다면, IllegalArgumentException가 적절 해 보이는데 어떻게 생각하시나요 ??

2024-12-28 07:59 UTC, Soundbar91 commented on src/main/java/in/koreatech/koin/domain/graduation/service/GraduationService.java
> +        );
## C
response dto 내부에서 정적 패토리 메소드를 바로 호출하는 것이 아닌, 메소드로 한 번 더 감싸신 이유가 궁금합니다 !

2024-12-28 07:59 UTC, Soundbar91 commented on src/main/java/in/koreatech/koin/domain/graduation/service/GraduationService.java
> +        );
여기도 개행 !

2024-12-28 07:59 UTC, Soundbar91 commented on src/main/java/in/koreatech/koin/domain/graduation/service/GraduationService.java
> +            DepartmentNotFoundException.withDetail("학번을 추가하세요.");
## C
학번 예외라서 학과 예외 말고 다른 예외를 사용하는 것이 좋아 보여요 !

2024-12-28 07:59 UTC, Soundbar91 commented on src/main/java/in/koreatech/koin/domain/graduation/service/GraduationService.java
> +                catalogList.addAll(catalogs);
## C
과목 이름, 학년, 학과로 조회를 하면 이수구분이 하나로 특정될 것 같다는 생각이 드는데, 리스트로 받는 케이스가 있는지 궁금합니다 !

2024-12-28 07:59 UTC, Soundbar91 commented on src/main/java/in/koreatech/koin/domain/graduation/service/GraduationService.java
> +        return GraduationCourseCalculationResponse.InnerCalculationResponse.of(
## C
> static import !

2024-12-29 10:32 UTC, duehee approved these changes
앞 관규님이 엄청 잘.. 찾아주셨네요👍 킹 관 규
고생하셨습니다~

2024-12-29 10:32 UTC, duehee commented on src/main/java/in/koreatech/koin/domain/graduation/service/GraduationService.java
>  import lombok.RequiredArgsConstructor;
### C
한 줄 개행해주세요!!
```suggestion
import in.koreatech.koin.domain.timetableV2.repository.TimetableFrameRepositoryV2;

import lombok.RequiredArgsConstructor;
```

2024-12-29 14:35 UTC, seongjae6751 commented on src/main/java/in/koreatech/koin/domain/graduation/service/GraduationService.java
> +            .map(timetableLecture -> timetableLecture.getLecture().getName())
꼼꼼한 리뷰 감사합니다!

2024-12-29 16:19 UTC, Soundbar91 approved these changes

2025-01-03 14:00 UTC, merged