feat: GET /dept, GET /depts 구현
BCSDLab/KOIN_API_V2 pull request #147
Opened 2023-12-30 06:47 UTC by songsunkook

# 🔥 연관 이슈

- close #107 
- close #108 
- close #109 

하나씩 작업하려 했으나 #108 구현 후 #109 를 구현하기 위해 필요한 작업이 거의 없어서 한 번에 진행했습니다.

# 🚀 작업 내용

1. 특정 학과 조회
2. 모든 학과 정보 조회

참고: [스테이지](https://api.stage.koreatech.in/swagger-ui.html#!/(Normal)_Dept)

# 💬 리뷰 중점사항

존재하지 않는 학과 코드에 대한 정보 요청 시 응답을 수정했습니다. 문제가 있을지 확인이 필요할 것 같습니다.
- 기존 API 응답
![image](https://github.com/BCSDLab/KOIN_API_V2/assets/21010656/e623fa3b-be66-4aae-b179-2d2959bdd21a)

- 새로 작성한 API 응답
![image](https://github.com/BCSDLab/KOIN_API_V2/assets/21010656/2a434665-7899-4a86-98dd-e30f8a8ef647)

JPA Entity 작성이나 **연관관계 매핑**, Spring Data JPA 사용이 미숙해서 이 부분을 위주로 리뷰해주시면 감사하겠습니다.

+) Response가 올바른 형태로 작성되었는지 한 번씩만 확인해주시면 감사하겠습니다!

2023-12-30 14:28 UTC, Invidam commented on src/main/java/in/koreatech/koin/domain/dept/service/DeptService.java
> +    public DeptResponse findDeptBy(Long id) {
서비스의 메서드 명 관련해서 여러 도메인들을 확인해봤는데
- dept, shop은 `findXXX` 을 사용하고
- track은 `getXXX`을 사용하네요.

일관성을 유지하는 편이 좋을 것 같고,
서비스는 비지니스 로직을 나타내는 ` getXXX`이 더 나을 것 같아, 해당 방향으로 통일해보는 건 어떨까요?  @Choi-JJunho 

(그라운드 룰 혹은 컨벤션에 추가해도 좋을 것 같아요)

참고: https://www.inflearn.com/questions/520176/%EB%84%A4%EC%9D%B4%EB%B0%8D-%EC%A7%88%EB%AC%B8

2023-12-30 14:29 UTC, Invidam commented on src/main/java/in/koreatech/koin/domain/dept/model/DeptNum.java
> +}
` `

2023-12-30 14:34 UTC, Invidam commented on src/main/java/in/koreatech/koin/domain/dept/controller/DeptController.java
> +        DeptResponse response = deptService.findDeptBy(id);
```suggestion
    public ResponseEntity<DeptResponse> findDept(@RequestParam(value = "dept_num") Long deptNumber) {
        DeptResponse response = deptService.findDeptBy(deptNumber);
```

`id`라는 포괄적인 변수 명보다
`deptNumber` 라는 구체적인 변수 명을 활용하면 좋을 것 같습니다.

2023-12-31 10:58 UTC, Invidam requested changes
첫 V2 작업이라 힘들었을텐데 수고하셨습니다~
많이 고민한 게 느껴지네요. 👍

굉장히 쉬운 도메인 같았는데 생각보다 난이도가 있었을 것 같아요 🤣 

## R1
 > 존재하지 않는 학과 코드에 대한 정보 요청 시 응답을 수정했습니다. 문제가 있을지 확인이 필요할 것 같습니다. 

이 부분은 클라이언트 인원들과 본인이 소통하는 게 제일 좋은 방법 같아요. 추가로 요청한 컨텐츠가 없을 때, 200번대 응답을 주는 것 (지금은 200이지만 no content는 204긴 합니다.)이 무조건 잘못된 건 아니라고 알고 있는데 수정한 이유가 무엇일까요?

## R2
Dept 관련 도메인(특히 DeptNum)이 꼭 JPA-DB로 설계하는게 맞는건지에 대한 고민이 있었어야 할 것 같아요. 개인적으로 코드 단위에서 Enum으로 관리하는 게 시간효율, 복잡성 측면에서 더 좋았을 것 같아요.

참고
- https://jojoldu.tistory.com/137
- https://tech.socarcorp.kr/dev/2021/08/17/common-code-management.html

## C
> JPA Entity 작성이나 연관관계 매핑, Spring Data JPA 사용이 미숙해서 이 부분을 위주로 리뷰해주시면 감사하겠습니다.

에 대해 어떻게 고민했고 어떤 점이 모호한지 구체적으로 언급이 되었으면 좋았을 것 같아요. 특히 도메인 설계 부분이요! 어떠한 생각으로 작성했는지 알고 리뷰를 했다면 편했을 것 같아서요~ 추가로 리뷰하다가 못보고 놓칠 수도 있고요

## A
DTO나 Test에서 Long <-> String 변환이 기존 코드들과 조금 다른 부분이 있었는데, 기존 코드들이 어떻게 작성됐는지 살펴보는 것도 좋을 것 같아요

## 기타
리뷰 많이 남겼는데 천천히 고민해서 답변해도 괜찮습니다~

2023-12-31 10:58 UTC, Invidam commented on src/main/java/in/koreatech/koin/domain/dept/model/DeptInfo.java
> +    private List<DeptNum> deptNums = new ArrayList<>();
## R
연관관계로 설계한다면, 편의 메서드가 필요할 것 같습니다.

2023-12-31 10:58 UTC, Invidam commented on src/main/java/in/koreatech/koin/domain/dept/model/DeptNumId.java
> +    private DeptInfo deptInfo;
## R
복합키가 다른 테이블과 연관관계가 있도록 설계한 이유가 어떤 건가요?

저는 String, Long과 같은 기본타입들만 와야한다고 이해하고 있었습니다~

2023-12-31 10:58 UTC, Invidam commented on src/main/java/in/koreatech/koin/domain/dept/repository/DeptNumRepository.java
> +public interface DeptNumRepository extends Repository<DeptNum, Long> {
## R 
![image](https://github.com/BCSDLab/KOIN_API_V2/assets/71889359/6045f767-546f-4a89-b3f1-923527c86e46)

인 상황이기에

DeptNum이 DeptNumId를 ID로 갖고, DeptInfo는 name을 ID로 가지는 방식으로 Repository 제너구성이  되야하지 않을까요?


저는 기본키(식별자)가 `<Entity, ID>`중 ID에 와야한다고 이해하고 있어서

2023-12-31 10:58 UTC, Invidam commented on src/test/java/in/koreatech/koin/acceptance/DeptApiTest.java
> +                softly.assertThat(response.body().jsonPath().getList(".").size()).isEqualTo(2);
## C
```suggestion
                softly.assertThat(response.body().jsonPath().getList(".").size()).isEqualTo(DEPT_SIZE);
```

2023-12-31 10:58 UTC, Invidam commented on src/test/java/in/koreatech/koin/acceptance/DeptApiTest.java
> +                for (int i = 0; i < DEPT_SIZE; i++) {
## C
N개가 아니라 2개라면 반복문 대신 중복을 사용하는 게 작성하는 시간, 가시성 등을 고려했을 때 더 편했을 것 같아요 

실제로 
- `dept_nums[0]` 부분은 0, 1을 사용했구
- Track, Shop Test도 배열 대신 중복을 사용했구요

2023-12-31 10:58 UTC, Invidam commented on src/test/java/in/koreatech/koin/acceptance/DeptApiTest.java
> +                        softly.assertThat(parseLong(response.body().jsonPath().getString("[" + i + "].dept_nums"))).isEqualTo(deptNum2.getNumber());
## R
```suggestion
                        softly.assertThat(response.body().jsonPath().getLong("[" + i + "].dept_nums[0]"))
                            .isEqualTo(deptNum2.getNumber());
```

- `[0]`이 이쪽에도 있는 게 일관성 있고,
- parseLong 없이도 테스트할 수 있을 것 같아요

2023-12-31 10:58 UTC, Invidam commented on src/test/java/in/koreatech/koin/acceptance/DeptApiTest.java
> +                        softly.assertThat(parseLong(response.body().jsonPath().getString("["+ i + "].dept_nums[0]"))).isEqualTo(deptNum1_1.getNumber());
## R

```suggestion
                        softly.assertThat(response.body().jsonPath().getLong("[" + i + "].dept_nums[0]")).isEqualTo(deptNum1_1.getNumber());
```

parseLong 없이도 가능해보여요

2023-12-31 11:10 UTC, Invidam commented on src/main/java/in/koreatech/koin/domain/dept/service/DeptService.java
> +    public DeptResponse findDeptBy(Long id) {
## C
findById 가 복잡하긴 하지만 덜 모호하고 명확할 것 같은데 어떻게 생각하세요?

2023-12-31 12:46 UTC, Invidam commented
![image](https://github.com/BCSDLab/KOIN_API_V2/assets/71889359/712a6544-a95c-4be1-8e80-bcfcfa7fdc8b)

저도 작업할 때 위 이미지와 같이 다른PR의 커밋이 있었는데 체리픽 이용해서 제거했었어요~

2024-01-01 03:06 UTC, Choi-JJunho requested changes
한수가 많은 코멘트를 달아줘서 크게 남길 내용이 없네요~ ㅎㅎ
코멘트 확인 부탁드려요

2024-01-01 03:06 UTC, Choi-JJunho commented on src/main/java/in/koreatech/koin/domain/dept/repository/DeptNumRepository.java
> +public interface DeptNumRepository extends Repository<DeptNum, Long> {
### R

동의합니다. Long으로 ID를 정의할 수 없는 상황인 것 같습니다
다시 확인 부탁드립니다.

2024-01-01 03:06 UTC, Choi-JJunho commented on src/test/java/in/koreatech/koin/acceptance/DeptApiTest.java
> +    @DisplayName("학과 번호를 통해 학과 이름을 조회한다.")
꼼꼼한 테스트 좋습니다 👍

2024-01-01 03:06 UTC, Choi-JJunho commented on src/test/java/in/koreatech/koin/acceptance/DeptApiTest.java
> +    void findAllDepts() {
복잡한 결과물에 대한 테스트 고생하셨습니다 👍👍

2024-01-01 09:04 UTC, daheeParkk approved these changes
수고하셨습니다!

2024-01-01 14:28 UTC, songsunkook commented on src/test/java/in/koreatech/koin/acceptance/DeptApiTest.java
> +                for (int i = 0; i < DEPT_SIZE; i++) {
처음에는 반복문을 사용하지 않았는데, json 특성 상 배열의 몇 번째 요소로 특정 요소가 올지 정해져있지 않고 랜덤하다고 판단하여 이를 해결하기 위해 반복문을 사용했습니다. 반복문을 사용하지 않고 구현하기 위한 방법을 더 고민해보겠습니다.

2024-01-01 14:28 UTC, songsunkook commented on src/test/java/in/koreatech/koin/acceptance/DeptApiTest.java
> +                        softly.assertThat(parseLong(response.body().jsonPath().getString("["+ i + "].dept_nums[0]"))).isEqualTo(deptNum1_1.getNumber());
오 그러네요 감사합니다!

2024-01-02 01:38 UTC, Choi-JJunho commented on src/main/java/in/koreatech/koin/domain/dept/service/DeptService.java
동의합니다~ 
비즈니스(Service)에서는 getXXX를 사용하도록 컨벤션에 추가해두도록하죠!

2024-01-02 08:14 UTC, songsunkook commented on src/main/java/in/koreatech/koin/domain/dept/repository/DeptNumRepository.java
> +public interface DeptNumRepository extends Repository<DeptNum, Long> {
변경 과정에서 착오가 있었던 것 같습니다. 
```java
public interface DeptInfoRepository extends Repository<DeptInfo, String> {
public interface DeptNumRepository extends Repository<DeptNum, DeptNumId> {
```
위와 같이 수정하겠습니다. 알려주셔서 감사합니다!

2024-01-06 11:16 UTC, songsunkook commented
@Invidam 

> ## R1
> > 존재하지 않는 학과 코드에 대한 정보 요청 시 응답을 수정했습니다. 문제가 있을지 확인이 필요할 것 같습니다.
> 
> 이 부분은 클라이언트 인원들과 본인이 소통하는 게 제일 좋은 방법 같아요. 추가로 요청한 컨텐츠가 없을 때, 200번대 응답을 주는 것 (지금은 200이지만 no content는 204긴 합니다.)이 무조건 잘못된 건 아니라고 알고 있는데 수정한 이유가 무엇일까요?

요청한 컨텐츠가 없을 때 200대를 응답할 수 있는 줄 몰랐습니다. 해당 부분 롤백하겠습니다.

> ## R2
> Dept 관련 도메인(특히 DeptNum)이 꼭 JPA-DB로 설계하는게 맞는건지에 대한 고민이 있었어야 할 것 같아요. 개인적으로 코드 단위에서 Enum으로 관리하는 게 시간효율, 복잡성 측면에서 더 좋았을 것 같아요.
> 
> 참고
> 
> * https://jojoldu.tistory.com/137
> * https://tech.socarcorp.kr/dev/2021/08/17/common-code-management.html

해당 고민 관련하여 discussion 생성했습니다. cc. #152

> ## C
> > JPA Entity 작성이나 연관관계 매핑, Spring Data JPA 사용이 미숙해서 이 부분을 위주로 리뷰해주시면 감사하겠습니다.
> 
> 에 대해 어떻게 고민했고 어떤 점이 모호한지 구체적으로 언급이 되었으면 좋았을 것 같아요. 특히 도메인 설계 부분이요! 어떠한 생각으로 작성했는지 알고 리뷰를 했다면 편했을 것 같아서요~ 추가로 리뷰하다가 못보고 놓칠 수도 있고요

피드백 주신 내용 참고하여 다음 PR부터는 꼭 구체적으로 언급하겠습니다. 감사합니다!

> ## A
> DTO나 Test에서 Long <-> String 변환이 기존 코드들과 조금 다른 부분이 있었는데, 기존 코드들이 어떻게 작성됐는지 살펴보는 것도 좋을 것 같아요

요청과 응답에 대해서는 꼭 기존 코드를 확인하는 습관을 들이겠습니다. 감사합니다!

2024-01-06 16:42 UTC, Invidam approved these changes
확실히 간단해졌네요! (성능 향상은 덤이고요~)

기존 코드 잘짜놔서 수정도 원활하지 않았나 싶습니다

수고했어요~ 👍

2024-01-06 16:42 UTC, Invidam commented on src/main/java/in/koreatech/koin/domain/dept/model/Dept.java
> +    private final List<Long> numbers;
## C

Long을 사용한 이유가 있을까요? 
DB에 대응하기 위함인가요?

2024-01-06 17:31 UTC, songsunkook commented on src/main/java/in/koreatech/koin/domain/dept/model/Dept.java
> +    private final List<Long> numbers;
다른 도메인과의 일관성을 지키기 위해 Long을 사용했습니다!

2024-01-07 04:35 UTC, Invidam commented on src/main/java/in/koreatech/koin/domain/dept/model/Dept.java
> +    private final List<Long> numbers;
다른 도메인과 일관성을 지켜야하는 이유가 있을까요?..

저는 Integer, Long을 비교해보았을 때,
- Integer: 메모리 소모가 작다, 범위가 좁다.
- Long: 메모리 소모가 크다, 범위가 크다
만을 고려하면 된다고 생각합니다.

해당 도메인은 적은 범위의 수만 다루기에 Integer가 더 좋지 않나 싶습니다.

## C
추가로 학번 코드를 다루는 거면 가능한 범위가 `000` ~ `999`이기 때문에, `000`, `001`, `002`등 `00`을 포함한 숫자코드를 처리하기 위해 String을 사용하는 건 어떨까요?

2024-01-07 05:42 UTC, songsunkook commented on src/main/java/in/koreatech/koin/domain/dept/model/Dept.java
> +    private final List<Long> numbers;
조언 감사합니다!
지금 반환형태는 앞의 0을 생략하지만 내년부터는 변경된다고 하니 String으로 수정하겠습니다.

2024-01-07 11:22 UTC, Choi-JJunho approved these changes
Good 전체적으로 내용을 깔끔하게 잘 반영해주셨네요~!
테스트도 꼼꼼히 작성하신 모습 좋습니다 👍
고생하셨습니다~

2024-01-07 11:22 UTC, merged