feat: GET /lands API 구현
BCSDLab/KOIN_API_V2 pull request #148
Opened 2023-12-30 16:38 UTC by daheeParkk

# 🔥 연관 이슈

- close #126 

# 🚀 작업 내용

1. 복덕방 Domain, DTO 생성
2. 복덕방 관련 컨트롤러, 서비스, 레파지토리 구현
3. 인수테스트 작성

# 💬 리뷰 중점사항
복덕방 도메인에서 수정할 필드가 있는지도 봐주시면 감사하겠습니다!

2023-12-30 16:58 UTC, songsunkook reviewed
이번 프로젝트에 올리시는 첫 PR이었는데도 깔끔하게 잘 작성해주신 것 같아요.
고생하셨습니다!

2023-12-30 16:58 UTC, songsunkook commented on src/main/java/in/koreatech/koin/domain/land/dto/LandResponse.java
> +    @JsonProperty("room_type") String roomType) {
### R

```suggestion
@JsonNaming(value = PropertyNamingStrategies.SnakeCaseStrategy.class)
public record LandResponse(String internalName, String monthlyFee, String latitude, String charterFee,String name, String longitude, String roomType) {
```
`@JsonNaming` 어노테이션을 활용하면 코드를 간소화할 수 있을 것 같습니다!

2023-12-31 14:55 UTC, Invidam requested changes
첫 작업 수고하셨습니다~

2023-12-31 14:55 UTC, Invidam commented on src/main/java/in/koreatech/koin/domain/land/dto/LandResponse.java
> +    @JsonProperty("room_type") String roomType) {
## A
`@JsonNaming(value = SnakeCaseStrategy.class)`

가 되면 더 좋을 듯합니다

Remove Qualifier 하면 돼요~

2023-12-31 14:55 UTC, Invidam commented on src/main/java/in/koreatech/koin/domain/land/service/LandService.java
> +    @Transactional
## R

readOnly 옵션을 제거한 이유가 있을까요? 

제가 알기로는
- 조회용도로 readOnly 옵션을 사용하고,
- 일반적인 DB에서는 readOnly 옵션을 붙이면, 힌트를 통해 최적화가 일어나고,
- JPA에서는 더티체킹을 안해서 최적화가 된다
고 알고 있어서, 단순 조회 용도라면 readOnly가 붙는 게 좋을 것 같아요

2023-12-31 14:55 UTC, Invidam commented on src/main/java/in/koreatech/koin/domain/land/controller/LandController.java
> +    public ResponseEntity<List<LandResponse>> getLands() {
## C

`LandResponse`는 단일 조회 용도로 사용하고, 
리스트의 원소로 존재하는 DTO라면 LandListItemResponse와 같은 표현은 어떨까요?

-List보단 s를 권장하지만, 이번 경우는 무조건 리스트라서 List를 써도 될 것 같아요.

2024-01-01 03:18 UTC, Choi-JJunho requested changes
첫 작업 고생하셨습니다
Good First PR 👍

몇가지 간단한 내용만 확인 부탁드려요~

2024-01-01 03:18 UTC, Choi-JJunho commented on src/main/java/in/koreatech/koin/domain/land/service/LandService.java
> +    @Transactional
### R
위 의견에 동의합니다.
추가로 class level에 Tx(readOnly=true) 가 선언되어있으므로 트랜잭션 어노테이션을 생략해도 될 것 같아요~

> Tx (Transaction의 약어)

2024-01-01 03:18 UTC, Choi-JJunho commented on src/test/java/in/koreatech/koin/acceptance/LandApiTest.java
> +    @DisplayName("복덕방 리스트를 조회한다.")
꼼꼼한 테스트 👍

2024-01-01 03:18 UTC, Choi-JJunho commented on src/main/java/in/koreatech/koin/domain/land/domain/Land.java
> +package in.koreatech.koin.domain.land.domain;
### R
```suggestion
package in.koreatech.koin.domain.land.model;
```
최상단은 domain 하위 세부 레이어에서는 model로 이야기했던 것 같네요~

2024-01-01 11:15 UTC, daheeParkk commented on src/main/java/in/koreatech/koin/domain/land/domain/Land.java
> +    @Column(name = "id", columnDefinition = "int UNSIGNED not null")
JPA Buddy로 가져오고 더 꼼꼼히 확인하지 못했습니다,, 굳이 필요해 보이지 않으니 지우겠습니다!

2024-01-01 11:16 UTC, daheeParkk commented on src/main/java/in/koreatech/koin/domain/land/domain/Land.java
> +package in.koreatech.koin.domain.land.domain;
수정하겠습니다!

2024-01-01 11:38 UTC, daheeParkk commented on src/main/java/in/koreatech/koin/domain/land/controller/LandController.java
> +    public ResponseEntity<List<LandResponse>> getLands() {
단일 조회와 리스트 조회의 반환값이 다르다는 것을 생각하지 못했습니다..
LandListItemResponse라는 표현 괜찮은 것 같습니다! 이렇게 수정하겠습니다.

2024-01-02 01:33 UTC, Choi-JJunho approved these changes
반영해주신 내용 확인했습니다~
고생하셨습니다 👍

2024-01-02 15:08 UTC, Invidam approved these changes
👍 👍

2024-01-04 02:15 UTC, songsunkook approved these changes

2024-01-04 02:19 UTC, merged