feat: 메뉴 카테고리 목록 조회
BCSDLab/KOIN_API_V2 pull request #153
Opened 2024-01-07 08:38 UTC by Invidam

# 🔥 연관 이슈
- close #40

# 🚀 작업 내용

1. 메뉴 카테고리 조회 기능 추가했습니다.
  -  MenuCategoryRepository 생성했습니다.
2. 상점 유효성 검증 부분은 상점 조회 로직 만들 때 추가하는 게 맞는 것 같아 `TODO` 에 남겼습니다. (머지시 이슈 댓글에 남길 예정입니다.)

# 💬 리뷰 중점사항

- 도메인 설계가 없고, 단순한 로직이라 크게 리뷰 중점사항이 없어 보입니다..
- 상점/메뉴/메뉴카테고리 등 분리는 추후 상점 로직 다룰 때 하는 게 맞는 것 같아 진행하지 않았습니다.

2024-01-07 11:41 UTC, Choi-JJunho approved these changes
고생하셨습니다!
작업단위가 간단하여 크게 변경할만한 부분은 보이지 않아 Approve 드립니다!
간단한 코멘트 확인 한번만 부탁드려요~

2024-01-07 11:41 UTC, Choi-JJunho commented on src/test/java/in/koreatech/koin/acceptance/ShopApiTest.java
> +        final long SHOP_ID = 1L;
### A
실제로 Shop Entity를 하나 save() 하고 그 ID를 활용하는건 어떨까요?

2024-01-08 05:01 UTC, daheeParkk approved these changes
수고하셨습니다!

2024-01-08 07:50 UTC, songsunkook commented
고생하셨습니다! 위에 달린 코멘트에 답변이 올라오는 대로 Approve 및 merge 하겠습니다!

2024-01-10 10:40 UTC, songsunkook approved these changes

2024-01-11 00:21 UTC, Invidam commented
cascade 걸어주면 하나의 동일한 메뉴 카테고리 A를 두 개의 메뉴인 메뉴1과 메뉴2가 저장하려고 할 때 에러가 납니다.

## 바뀌기 전 에러가 나던 코드
```
        // given
        final long SHOP_ID = 1L;

        Menu menu1 = Menu.builder()
            .shopId(SHOP_ID)
            .name("짜장면")
            .description("맛있는 짜장면")
            .build();

        Menu menu2 = Menu.builder()
            .shopId(SHOP_ID)
            .name("짬뽕")
            .description("맛있는 짬뽕")
            .build();

        MenuCategory menuCategory1 = MenuCategory.builder()
            .shopId(SHOP_ID)
            .name("이벤트 메뉴")
            .build();

        MenuCategory menuCategory2 = MenuCategory.builder()
            .shopId(SHOP_ID)
            .name("메인 메뉴")
            .build();

        MenuCategoryMap menuCategoryMap1 = MenuCategoryMap.create();
        MenuCategoryMap menuCategoryMap2 = MenuCategoryMap.create();
        MenuCategoryMap menuCategoryMap3 = MenuCategoryMap.create();

        // when then
        menuCategoryMap1.map(menu1, menuCategory1);
        menuCategoryMap2.map(menu1, menuCategory2);
        menuCategoryMap3.map(menu2, menuCategory2);

        menuRepository.save(menu1);
        menuRepository.save(menu2); //error menu1에서 메뉴 카테고리 맵을 저장했는데, 또 저장하려고하니 에러가 남.
```


## 바뀐 후 잘 돌아가는 방법
```
        // given
        final long SHOP_ID = 1L;

        Menu menu1 = Menu.builder()
            .shopId(SHOP_ID)
            .name("짜장면")
            .description("맛있는 짜장면")
            .build();

        Menu menu2 = Menu.builder()
            .shopId(SHOP_ID)
            .name("짬뽕")
            .description("맛있는 짬뽕")
            .build();

        MenuCategory menuCategory1 = MenuCategory.builder()
            .shopId(SHOP_ID)
            .name("이벤트 메뉴")
            .build();

        MenuCategory menuCategory2 = MenuCategory.builder()
            .shopId(SHOP_ID)
            .name("메인 메뉴")
            .build();

        MenuCategoryMap menuCategoryMap1 = MenuCategoryMap.create();
        MenuCategoryMap menuCategoryMap2 = MenuCategoryMap.create();
        MenuCategoryMap menuCategoryMap3 = MenuCategoryMap.create();

        // when then
        menuCategoryMap1.map(menu1, menuCategory1);
        menuCategoryMap2.map(menu1, menuCategory2);
        menuCategoryMap3.map(menu2, menuCategory2);

        menuCategoryRepository.save(menuCategory1);
        menuCategoryRepository.save(menuCategory2);

        menuRepository.save(menu1);
        menuRepository.save(menu2); //메뉴 카테고리가 따로 저장돼서 에러가 안남
```

따라서 (1) 메뉴 카테고리를 먼저 저장하도록  (2) 메뉴 카테고리 저장시, 메뉴가 저장되지 않도록 수정했어요

2024-01-11 00:22 UTC, Invidam commented on src/test/java/in/koreatech/koin/acceptance/ShopApiTest.java
> +        final long SHOP_ID = 1L;
상점 객체는 아직 안만들기도 했고, 일부로 의존하지 않도록 의존관계가 아니라 id만 유지하도록 해서 필요하지 않을 것 같습니다!

2024-01-11 14:54 UTC, Invidam commented on src/main/java/in/koreatech/koin/domain/shop/model/MenuCategoryMap.java
> +    @ManyToOne(fetch = FetchType.LAZY)
저는 `~~map` 테이블은 N:M 관계를 매핑하기 위한 중간 테이블 목적으로 설계해서  필요하다고 생각합니다~

2024-01-12 05:01 UTC, songsunkook requested changes
> 상점 저장시 메뉴 카테고리가 저장되도록 cascade ALL 옵션 걸어줬는데 이것도 바꾸는 게 좋을까요??

처음에는 cascade.PERSIST만 사용하는 것이 적절하지 않을까 생각했는데 Menu와 MenuCategory는 다대다 관계이고 map 엔티티는 연결 테이블일 뿐이어서 cascade.ALL로 지정해도 괜찮다고 생각합니다.

> (수정된 방식에서도 메뉴 카테고리를 암시적으로 먼저 저장해줘야 에러가 안나는 상황인데, 이게 좋지 않을 것 같아서 메뉴와 메뉴카테고리를 저장하는 순서가 어떤 순서든지 저장가능하도록 하는 게 베스트 같아서요)

이렇게 수정되면 cascade를 통해 persist는 이루어지지 않아 cascade를 사용하는 의미가 퇴색되는 것 같아요. 말씀해주신 내용(저장 순서 상관없이 가능하게)이 제일 좋다고 생각하지만 어떻게 구현 가능할지 모르겠습니다.

+) 제 로컬에서는 제시해주신 *바뀐 후 잘 돌아가는 코드*에서도 에러가 발생합니다.

제시해주신 코드(에러 발생)
```java
        menuCategoryMap1.map(menu1, menuCategory1);
        menuCategoryMap2.map(menu1, menuCategory2);
        menuCategoryMap3.map(menu2, menuCategory2);

        menuCategoryRepository.save(menuCategory1);
        menuCategoryRepository.save(menuCategory2);

        menuRepository.save(menu1);
        menuRepository.save(menu2);
```

menu를 먼저 save하도록 수정하니 에러가 사라졌습니다.
```java
        menuRepository.save(menu1);
        menuRepository.save(menu2);
        
        menuCategoryMap1.map(menu1, menuCategory1);
        menuCategoryMap2.map(menu1, menuCategory2);
        menuCategoryMap3.map(menu2, menuCategory2);

        menuCategoryRepository.save(menuCategory1);
        menuCategoryRepository.save(menuCategory2);
```

2024-01-15 14:48 UTC, Invidam commented
늦었네요! 고민한 결론 말씀드립니다~
1. 메뉴 카테고리와 메뉴는 동시에 저장되지 않고, **항상 메뉴 카테고리가 먼저 저장된다.**
    - 게시글-카테고리의 관계를 생각해보면, 카테고리가 항상 먼저 존재하고 게시글은 뒤늦게 생성된다.
    - 실제 메뉴-메뉴카테고리의 흐름도 이렇다. 즉 순서가 결정되어있다.
2. 따라서 **메뉴 카테고리 생성 및 저장**은 `given`에 해당하고 메뉴 테스트시 이미 저장되어 있어 있는 **조건이라고 가정해야 한다.**
3. **메뉴** 저장 혹은 수정시 **메뉴 카테고리와의 관계(MeuCateogryMap)**는 같이 결정되기에 메뉴에 MenuCategoryMap에 대한 cascade 옵션은 필요하다.

(2)에 따라 테스트 문맥(코드 위치)를 수정하였고, cascade는 내버려뒀습니다.

N:M 관계 그리고 중간테이블이 있는 경우는 N 과 M 중 하나가 사전에 저장되어 있지 않은지 생각해봐야 할 것 같습니다.

@songsunkook @Choi-JJunho  
추가된 커밋에 16일까지 더이상 코멘트 없으면 머지하겠습니다!.. (그리고 별도 PR 파던지 디스커션을 팠어야 했을 것 같네용 ㅠ)

2024-01-15 15:20 UTC, Choi-JJunho approved these changes
확인했습니다~ 고생하셨어요

2024-01-16 06:54 UTC, merged