refactor: default method 활용한 getByXXX 메소드 추가
BCSDLab/KOIN_API_V2 pull request #164
Opened 2024-01-17 11:12 UTC by Choi-JJunho

# 🔥 연관 이슈

- close #162 

# 🚀 작업 내용

1. Service 로직에서 사용중인 findByXXX().orElseThrow() 부분을 getByXXX() 형태로 변경했습니다.
2. IAE를 사용중이던 도메인에 대해 XXXNotFoundException 추가

# 💬 리뷰 중점사항

인증 및 기타 상황에 맞는 예외 메시지를 던져주는 부분에서는 findByXXX를 사용하여 예외를 핸들링하도록 유지했습니다.
ex) ArgumentResolver에서 사용자 조회하는 상황

2024-01-17 11:35 UTC, songsunkook approved these changes
빠르게 수정해주셨네요!
전반적으로 코드가 간결해져 보기 좋아진 것 같습니다 😊
고생하셨습니다!

2024-01-17 11:35 UTC, songsunkook commented on src/main/java/in/koreatech/koin/domain/shop/dto/MenuCategoriesResponse.java
> +        return new MenuCategoriesResponse((long) categories.size(), categories);
### A
이런 컨벤션도 있었나요..?

2024-01-17 11:58 UTC, songsunkook commented on src/main/java/in/koreatech/koin/domain/shop/dto/MenuCategoriesResponse.java
> +        return new MenuCategoriesResponse((long) categories.size(), categories);
저는 라인포맷팅을 하면 `(long)`과 `categorise.size()` 사이에 띄어쓰기가 사라집니다.
컨벤션 적용이 다르게 되어있는 것 같아요..!!
어느 쪽이 적절한 것인지는 잘 모르겠습니다...

2024-01-18 06:33 UTC, daheeParkk requested changes
수고하셨습니다!!

2024-01-18 06:33 UTC, daheeParkk commented on src/main/java/in/koreatech/koin/domain/land/exception/LandNotFoundException.java
>  public class LandNotFoundException extends RuntimeException {
### C

복덕방은 아직 service 에서 예외 처리하고 있는데, 수정 안 하신 이유가 있나요??

2024-01-18 06:33 UTC, daheeParkk commented on src/main/java/in/koreatech/koin/domain/shop/exception/MenuNotFoundException.java
> +public class MenuNotFoundException extends RuntimeException {
### R

새로 만든 `NotFoundException`들은 `GlobalExceptionHandler`에도 추가해야 할 것 같습니다!

2024-01-18 06:33 UTC, daheeParkk commented on src/main/java/in/koreatech/koin/domain/shop/repository/MenuRepository.java
> +    default Menu getById(Long menuId) {
### A

`getByXXX()`로 repository에서 예외 처리를 하니 코드 중복이 줄어 좋은 것 같습니다!

2024-01-19 08:14 UTC, Choi-JJunho commented on src/main/java/in/koreatech/koin/domain/land/exception/LandNotFoundException.java
>  public class LandNotFoundException extends RuntimeException {
이걸 놓쳤네요 ㅠㅠ 감사합니다 👍

2024-01-19 08:18 UTC, Choi-JJunho commented on src/main/java/in/koreatech/koin/domain/shop/exception/MenuNotFoundException.java
> +public class MenuNotFoundException extends RuntimeException {
아래 Discussion 참조하여 묶어 관리하겠습니다~!
- https://github.com/BCSDLab/KOIN_API_V2/discussions/163

2024-01-19 08:24 UTC, daheeParkk approved these changes

2024-01-19 08:25 UTC, merged