feat: 버전 단일 조회
BCSDLab/KOIN_API_V2 pull request #168
Opened 2024-01-21 04:10 UTC by xhdtn8070

# 🔥 연관 이슈

- close #4 
- close #5 

# 🚀 작업 내용

1. 버전 단일 조회 API를 구현하였습니다.

2. `type`에 해당하는 버전이 존재하지 않을 경우 `VersionException`이 발생하도록 구성하였습니다.

3. 기존 KOIN의 경우 `Version.type`을 `String`으로 사용하고 있었지만, 의논(최준호) 후 `Enum`으로 변경하였습니다.
  * Enum의 경우 기존 버전과 동일하게 작업하기 위해, snake case로 작성하였습니다.
  ![image](https://github.com/BCSDLab/KOIN_API_V2/assets/19249550/0d740a8c-0331-4a8f-b9cc-5394dbc579f6)
  ![image](https://github.com/BCSDLab/KOIN_API_V2/assets/19249550/79bd630d-c89d-4ab5-9844-ae5704d7d10f)

# 💬 리뷰 중점사항

 - test
   - 성공 사례에 대한 1개의 테스트만 작성하였는데, 충분할까요? 실패에 대한 경우도 추가해야 할까요?

 - repository
   - repository에 default 함수를 사용하는 방법을 적용해보았습니다. 이러한 네이밍과 사용법 괜찮을까요?
   ![image](https://github.com/BCSDLab/KOIN_API_V2/assets/19249550/b256fcf2-0d0a-455b-a3a2-b37677ba6ca8)

 - swagger-ui
   - 추후에 swagger가 추가되면 컨트롤러 및 response 예시에 추가하겠습니다.

2024-01-22 06:59 UTC, Choi-JJunho requested changes
첫 PR인데도 너무 잘 작성해주셨네요!!
RCA 룰을 적용해서 리뷰를 남겼습니다.
각각의 알파벳이 의미하는 부분은 wiki를 참고해주세요~!
[Wiki - 그라운드룰 - RCA 룰](https://github.com/BCSDLab/KOIN_API_V2/wiki/%F0%9F%A7%91%E2%80%8D%E2%9A%96%EF%B8%8F-%EA%B7%B8%EB%9D%BC%EC%9A%B4%EB%93%9C%EB%A3%B0#rca-%EB%A3%B0)

2024-01-22 06:59 UTC, Choi-JJunho commented on src/main/java/in/koreatech/koin/domain/version/controller/VersionController.java
> +    public ResponseEntity<VersionResponse> getVersions(@PathVariable(value = "type") VersionType type)
### A

Enum이 이렇게 매핑될수도 있군요!

2024-01-22 06:59 UTC, Choi-JJunho commented on src/main/java/in/koreatech/koin/domain/version/dto/VersionResponse.java
> +    @JsonProperty("updated_at") LocalDateTime updatedAt) {
### C

`@JsonProperty`를 선언할거면 `@JsonNaming(value = SnakeCaseStrategy.class)`은 굳이 선언하지 않아도 될 것 같아요!

2024-01-22 06:59 UTC, Choi-JJunho commented on src/main/java/in/koreatech/koin/domain/version/model/VersionType.java
> +    express_bus_timetable,
### A
후행쉼표 센스 굿 👍

2024-01-22 06:59 UTC, Choi-JJunho commented on src/main/java/in/koreatech/koin/domain/version/model/VersionType.java
> +    express_bus_timetable,
### C

Google Java Style Guide를 보면 상수는 UPPER_SNAKE_CASE를 사용한다고 해요~

https://google.github.io/styleguide/javaguide.html#s5.2.4-constant-names

코드레벨에서 상수(Enum 값)가 snake_case로 작성되는 부분이 일관성에서 살짝 우려되는데 (Dept 클래스 확인 부탁드릴게요)
Enum value는 camelCase로 작성하고 별도의 value 값으로 클라이언트값을 핸들링하는건 어떻게 생각하시나요?

```java
// ex)
public enum VersionType {
  SHUTTLE_BUS_TIMETABLE("shuttle_bus_timetable")
  ...
}
```

2024-01-22 06:59 UTC, Choi-JJunho commented on src/main/java/in/koreatech/koin/domain/version/repository/VersionRepository.java
> +    }
### R

Good 👍 Default 메소드 잘 적용해주셨네요! 
.withDetail() 메소드의 경우 default 메시지가 존재하기 때문에 상세 정보만 넣어주는 용도로 계획했습니다!

```java
public static VersionException withDetail(String detail) {
    String message = String.format("%s %s", DEFAULT_MESSAGE, detail);
    return new VersionException(message);
}
```

이에 메시지가 아니라 detail 정보를 넘겨주는건 어떨까요?

```suggestion
    default Version getByType(VersionType type) {
        return this.findByType(type).orElseThrow(() -> VersionException.withDetail("versionType: " + type));
    }
```

2024-01-22 06:59 UTC, Choi-JJunho commented on src/main/java/in/koreatech/koin/domain/version/service/VersionService.java
> +    @Transactional(readOnly = true)
### R

class 레벨에서 `@Tx(readOnly = true)` 옵션을 설정해줬기 때문에 메소드 레벨에서는 생략해도 될 것 같아요~

2024-01-22 06:59 UTC, Choi-JJunho commented on src/test/java/in/koreatech/koin/acceptance/VersionApiTest.java
> +            .extract();
### A

사소한 내용입니다만! log().all() 에 대한 부분은 한줄로 작성해도 좋지 않을까 의견 드려봅니다
줄바꿈이 너무 많아서 되려 가독성을 해치는 것 같아서요~

```suggestion
        ExtractableResponse<Response> response = RestAssured
            .given()
            .log().all()
            .when()
            .log().all()
            .get("/versions/" + versionType.name())
            .then()
            .log().all()
            .statusCode(HttpStatus.OK.value())
            .extract();
```

2024-01-22 07:53 UTC, songsunkook approved these changes
앞에서 피드백을 너무 잘해주셔서 저는 따로 남길 피드백이 없어 보입니다. 
기존 컨벤션을 준수하면서 잘 작성해주신 것 같습니다. 
고생하셨습니다!

2024-01-22 09:15 UTC, daheeParkk approved these changes
수고하셨습니다!

2024-01-22 09:15 UTC, daheeParkk commented on src/main/java/in/koreatech/koin/domain/version/controller/VersionController.java
> +        {
### A

중괄호가 내려가 있어요! 위로 올려주는 게 좋을 것 같습니다

2024-01-25 07:51 UTC, xhdtn8070 commented on src/main/java/in/koreatech/koin/domain/version/dto/VersionResponse.java
> +    @JsonProperty("updated_at") LocalDateTime updatedAt) {
그렇네요. 복사하는 과정에서 가져왔는데,  `JsonProperty`를 쓰면 사용하지 않는게 맞네요!

2024-01-25 08:03 UTC, xhdtn8070 commented on src/main/java/in/koreatech/koin/domain/version/model/VersionType.java
> +    express_bus_timetable,
맞아요. 저도 기본적으로 UPPER_SNAKE_CASE로 사용하는데요.
저도 많이 고민했어요. 기존 KOIN의 경우, 말씀하신것처럼 작성되어 있는데,
이 경우, 컨트롤러에서 Enum 타입을 받지 못하고, string을 받아온 후에 value로 name을 조회하는 컨버터를 구성하는 과정이 필요해요. 그리고 Entity에 붙이는 Enumerate 이걸 도입하고 싶었거든요.


```
public enum VersionType {
  SHUTTLE_BUS_TIMETABLE("shuttle_bus_timetable")
  ...
}
```
만약 기존과 같은 형태로 작성한다면 Enumerate를 쓰지않고 AttributeConverter를 구현하여 작성할 수 있다고는 합니다.
https://devvkkid.tistory.com/270

오버엔지니어링이라는 생각이 들어서 간편한 코딩을 해봤는데, 어떻게 하면 좋을까요?
어렵네요...

2024-01-25 08:06 UTC, xhdtn8070 commented on src/main/java/in/koreatech/koin/domain/version/repository/VersionRepository.java
> +    }
디폴트 메시지가 `"올바르지 않은 버전입니다."` 이더라구요.
일치하는 타입이 존재하지 않는 타입 즉 versionType이 올바르지 않다는 뜻이였는데...
저렇게 리퀘스트가 바로 보이는게 좋을 것 같네요. 반영하겠습니다!

2024-01-25 08:10 UTC, xhdtn8070 commented on src/main/java/in/koreatech/koin/domain/version/service/VersionService.java
> +    @Transactional(readOnly = true)
아 클래스 레벨에서 달아줬군요!
아 복붙부터 하다가 놓쳤네요. 와우 꼼꼼해...
수정하겠습니다!

2024-01-25 08:12 UTC, xhdtn8070 commented on src/test/java/in/koreatech/koin/acceptance/VersionApiTest.java
> +            .extract();
엇! 넵넵 알겠습니다.
혹시 예시 주신거에서 when() 뒤에 다시 로그를 찍는데,
이게 어떤 의미가 있는 것일까요?

2024-01-25 08:14 UTC, xhdtn8070 commented on src/main/java/in/koreatech/koin/domain/version/controller/VersionController.java
> +        {
아고. 수정할게요!! 고맙습니다!

2024-01-25 09:59 UTC, Choi-JJunho commented on src/test/java/in/koreatech/koin/acceptance/VersionApiTest.java
> +            .extract();
요청 보내는걸 콘솔에 보여주는건데 특별하게 필요하진 않습니다~!
나중에 log().all() 이것도 다 지우긴 해야할거같네요 ㅋㅋㅋㅋ console IO 잡아먹는거라

2024-01-25 11:50 UTC, Choi-JJunho commented on src/main/java/in/koreatech/koin/domain/version/model/VersionType.java
> +    express_bus_timetable,
AttributeConverter까지 필요할까요?
Enumerate는 그대로 사용하고 Application Layer에서 String을 받아오고 `VersionType.from(requestValue)` 처럼 작성하는건 어떤가요?

Controller에서 String으로 받고
![image](https://github.com/BCSDLab/KOIN_API_V2/assets/49794401/66bfd7eb-f1fd-4155-8375-79136096667d)

Service에서 정적 메소드로 변환해서 매핑
![image](https://github.com/BCSDLab/KOIN_API_V2/assets/49794401/f8daf146-a9f5-44b3-8c38-85790bd90620)

Enum 변환 예시
![image](https://github.com/BCSDLab/KOIN_API_V2/assets/49794401/92f6212e-c781-4681-acda-5c1566f8bf33)

제 하나의 의견이니 이 방법에 대해 어떻게 생각하시는지 슬쩍 여쭤봅니당.

2024-01-26 06:47 UTC, songsunkook approved these changes

2024-01-26 06:47 UTC, songsunkook commented on src/test/java/in/koreatech/koin/acceptance/VersionApiTest.java
### A
> 성공 사례에 대한 1개의 테스트만 작성하였는데, 충분할까요? 실패에 대한 경우도 추가해야 할까요?

꼭 필요한 것은 아니지만 Exception이 발생하는 케이스도 간단하게 있으면 좋을 것 같습니다.

2024-01-26 06:47 UTC, songsunkook commented on src/main/java/in/koreatech/koin/domain/version/repository/VersionRepository.java
> +    }
### C
> repository에 default 함수를 사용하는 방법을 적용해보았습니다. 이러한 네이밍과 사용법 괜찮을까요?
   ![image](https://github.com/BCSDLab/KOIN_API_V2/assets/19249550/b256fcf2-0d0a-455b-a3a2-b37677ba6ca8)

혹시 `this.`를 명시한 이유가 있을까요?? 개인적으로 `this`는 꼭 필요한 것이 아니라면 없어도 된다고 생각합니다.
+) `withDetail`은 준호님께서 말씀해주신 것처럼 부가 정보를 반환하는 용도로 메시지를 전달하는 것이 설계 목적에 부합해 보입니다.

2024-01-29 05:32 UTC, xhdtn8070 commented on src/main/java/in/koreatech/koin/domain/version/repository/VersionRepository.java
> +    }
좋은 의견 감사합니다.
부가 정보를 반환하도록 반영하겠습니다!

2024-01-29 05:32 UTC, xhdtn8070 commented on src/test/java/in/koreatech/koin/acceptance/VersionApiTest.java
케이스 만들어보겠습니다! 감사합니다!

2024-01-29 05:40 UTC, xhdtn8070 commented on src/main/java/in/koreatech/koin/domain/version/model/VersionType.java
> +    express_bus_timetable,
방법이 2가지 나뉘는데 둘 중 하나로 정해주시면 좋을 것 같아요.
1. enum의 UPPER_SNAKE_CASE를 포기하고, Enumerate 어노테이션의 사용으로 entity의 타입을 관리하기 쉽도록 하는 방향. 이 경우 enum 컨벤션이 아쉽지만 작성, 관리해야하는 리소스가 적습니다.
2. UPPER_SNAKE_CASE를 만족하는 enum 작성. 의견 주신대로 기존의 방식인데, Enum의 type을 통해 해야하고, 추가적인 코드 등이 많아집니다.

저는 간결한 코드가 좋아서 1번을 선호하는데, 둘 다 문제가 있는 코드는 아니기에 준호 님이 선택을 해주시면 좋을 것 같아요. 둘 중 하나 골라주시면 거기에 맞춰 구성하여 다시 제출하겠습니다!

2024-01-29 13:01 UTC, Choi-JJunho commented on src/main/java/in/koreatech/koin/domain/version/model/VersionType.java
> +    express_bus_timetable,
선택의 기회를 주시다니...! 사양않고 선택하겠습니다.

일단 결론부터 말씀드리자면 2번을 선호합니다.
저의 주관적인 의견이지만 다음과 같은 생각이 함께 있다는 것을 말씀드리고자합니다.

해당 API는 다른 도메인과 연관성이 없을 뿐더러 Enum 또한 재사용의 여지가 없어보입니다.
컨벤션을 해칠만큼 간결한 코드가 얻는 이점이 적다고 생각해서 2번 내용에 조금 더 생각이 기우는 것 같습니다.

또한 intelliJ 플러그인 sonarLint에 계속 걸리는것도 신경쓰이는 부분이긴 합니다.
<img width="1343" alt="image" src="https://github.com/BCSDLab/KOIN_API_V2/assets/49794401/cf7eeb28-57ee-45d7-851d-3c2d2e473dc3">

> sonarLint는 코드 품질을 검사해주는 정적 툴로 깔끔한(?) 코드를 작성하기 위한 가이드를 제공해줍니다.
- 참고자료: https://yongdev91.tistory.com/7

2024-02-01 06:26 UTC, xhdtn8070 commented on src/main/java/in/koreatech/koin/domain/version/model/VersionType.java
> +    express_bus_timetable,
2번으로 수정하여 진행하였습니다.
추가적으로 Exception Test Case 추가하였습니다.

2024-02-05 07:48 UTC, Choi-JJunho requested changes
고생하셨습니다~!
컨벤션만 확인되는대로 Merge하겠습니다~

2024-02-05 07:48 UTC, Choi-JJunho commented on src/main/java/in/koreatech/koin/domain/version/model/VersionType.java
> +}
### R

다음 글 확인하고 조치 부탁드립니다~!
참고자료: [No newline at end of file](https://velog.io/@junho5336/No-newline-at-end-of-file)

<img width="377" alt="image" src="https://github.com/BCSDLab/KOIN_API_V2/assets/49794401/0ccab746-bbeb-4672-8226-90e603b98f5a">

2024-02-05 07:48 UTC, Choi-JJunho commented on src/main/java/in/koreatech/koin/domain/version/controller/VersionController.java
> +}
### R

불필요한 공백이 있네용
```suggestion
    }
}
```

2024-02-05 07:48 UTC, Choi-JJunho commented on src/main/java/in/koreatech/koin/domain/version/repository/VersionRepository.java
> +}
### R

> 다음 글 확인하고 조치 부탁드립니다~!
참고자료: [No newline at end of file](https://velog.io/@junho5336/No-newline-at-end-of-file)
<img width="377" alt="image" src="https://github.com/BCSDLab/KOIN_API_V2/assets/49794401/0ccab746-bbeb-4672-8226-90e603b98f5a">

ditto

2024-02-05 07:48 UTC, Choi-JJunho commented on src/main/java/in/koreatech/koin/domain/version/service/VersionService.java
> +}
### R

불필요한 공백이네요~

```suggestion
    }
}
```

2024-02-05 07:48 UTC, Choi-JJunho commented on src/test/java/in/koreatech/koin/acceptance/VersionApiTest.java
> +}
### R

불필요한 공백이네요~

```suggestion
    }
}
```

2024-02-08 11:29 UTC, Choi-JJunho approved these changes
고생하셨습니다~
건강이 최고입니다 🥲 아프지마세여

2024-02-08 11:29 UTC, merged