feat: 게시글 단일 조회
BCSDLab/KOIN_API_V2 pull request #173
Opened 2024-01-26 08:53 UTC by songsunkook

# 🔥 연관 이슈

- close #106 

# 🚀 작업 내용

"가장 많이 본 게시글" API를 작업하기에 앞서 본 API 개발이 선행되어야 하기에 이번 작업을 진행했습니다.

1. 게시글 단일 조회 시 게시판 정보와 댓글 목록을 함께 반환합니다.
2. (댓글 작성자와 로그인된 사용자의 일치 여부를 기반으로) 댓글 정보 반환 시 댓글 수정 권한(`grantEdit`)과 댓글 제거 권한(`grantEdit`) 정보를 함께 반환합니다.
3. 게시글 조회 시 로그인된 유저 id와 게시글 id, 로그인 ip 정보를 `article_view_logs` 테이블에 저장합니다.
    1. ![image](https://github.com/BCSDLab/KOIN_API_V2/assets/21010656/2ab6e831-b7d3-447e-a6ab-83cc0aaa5bbe)
    2. 이 때 1시간 뒤를 만료시간으로 함께 저장합니다.
    3. 위 사진에서 `0:0:0:0:0:0:0:1`는 IPv6 기준 localhost(IPv4는 127.0.0.1)을 의미합니다. 로컬 환경에서 테스트해서 저렇게 기입되었습니다.
4. 게시글 조회 시
    1. 조회 기록이 없다면
        1. 조회 기록을 저장합니다. (조회수 UP)
    3. 조회 기록이 있다면
        1. 만료 시간이 지나지 않았다면
            1. 아무 것도 하지 않습니다.
        3. 만료 시간이 지났다면
            1. 조회 기록의 만료 시간을 1시간 뒤로 수정합니다. (조회수 UP)
5. `HttpServletRequest`을 통해 로그인 정보와 접속 IP를 조회합니다.
6. 이번 PR 주제와 다른 내용이 포함되어 있습니다. (이전 PR에서 누락된 커밋 반영)
    - 학과 코드 자료형을 Long에서 String으로 수정했습니다.
    - cc. #147 

# 💬 리뷰 중점사항

조회수 증가 로직은 기존 코인을 따라갔습니다. 비로그인 사용자의 경우 조회수가 오르지 않는 문제가 있습니다. 추후에 업데이트가 필요해 보입니다.

2024-01-28 15:51 UTC, Choi-JJunho requested changes
고생하셨습니다~!
고려해야할 내용이 많음에도 많은 내용을 고려해주셨네요!
코드도 깔끔하게 작성해주셔서 리뷰하기 수월했습니다 👍

몇가지 확인할만한 내용에 대해 코멘트 남겼습니다~ 확인 부탁드릴게요

2024-01-28 15:51 UTC, Choi-JJunho commented on src/main/java/in/koreatech/koin/domain/community/dto/ArticleResponse.java
> +    @JsonProperty("contentSummary") String contentSummary,
### A
이친구는 camelCase라니.. 레거시의 슬픔이군요 😂

2024-01-28 15:51 UTC, Choi-JJunho commented on src/main/java/in/koreatech/koin/domain/community/model/Article.java
> +    @Transient
### A

오 영속화 대상에서 제외시키기 위해 `@Transient`를 사용했군요~!
개인적으로 사용해본적이 없어서 흥미롭다고 생각합니다 👍

2024-01-28 15:51 UTC, Choi-JJunho commented on src/main/java/in/koreatech/koin/domain/community/model/Article.java
> +        parseResult = parseResult.replace("&nbsp", "").strip();
### A
같은 변수에 재할당하는 것보다는 한번 할당할때 builder 쓰는것처럼 처리하는건 어떤가요?

```suggestion
        String parseResult = Jsoup.parse(content).text()
                                                .replace("&nbsp", "").strip();
```

2024-01-28 15:51 UTC, Choi-JJunho commented on src/main/java/in/koreatech/koin/domain/community/repository/ArticleRepository.java
> +    }
### R
오 페이징에 대한 예외를 처리해주셨네요? 꽤나 꼼꼼한 처리가 인상깊네요 👍
다만, 이 경우는 default 메소드로 처리하는게 아니라 그냥 getByBoardId로 선언해두는게 맞다고 봅니다.
만약 아무런 게시글이 없는 게시판이 생성되고 이를 조회한다면 목록이 비어있는 게시판이 나타나는게 정상적인 플로우라고 생각이 드네요.
우리가 List<Entity>를 반환하는 경우에 결과가 없으면 빈 리스트를 반환해주는것과 같은 맥락인거같아요

```suggestion
    Page<Article> getByBoardId(Long boardId, Pageable pageable);
```

2024-01-28 15:51 UTC, Choi-JJunho commented on src/main/java/in/koreatech/koin/domain/community/service/CommunityService.java
> +    @Transactional
### A
조회수 증가 로직이 있어 `@Tx`를 걸게되는군요 :)

2024-01-28 15:51 UTC, Choi-JJunho commented on src/main/java/in/koreatech/koin/domain/community/service/CommunityService.java
> +    private boolean canIncreaseArticleHit(Long articleId, Long userId, String ipAddress) {
### C

게시물이 조회수 증가가 가능한지 확인하는 메소드로 보이네요
`isHittable()`과 같은 네이밍은 어떤가요?

2024-01-28 15:51 UTC, Choi-JJunho commented on src/main/java/in/koreatech/koin/domain/community/service/CommunityService.java
> +        Long userId = getUserId();
### A

getArticle 메소드에서 userId를 받아오면 좋겠다는 생각이 드네요.
지금 구조상으로는 어노테이션에 `@StudentAuth(annonymous = true|false) 라는 옵션을 두고 익명의 사용자도 API를 사용할 수 있도록 구성해봐야겠네요.

추가로 인증 어노테이션 구조를 `@Auth(permit = {ANONYMOUS, STUDENT})` 이런 방식으로 개선해봐야겠군요
해당 부분은 제가 추후 인증방식을 리팩터링하면서 수정하겠습니다

- https://github.com/BCSDLab/KOIN_API_V2/issues/174

2024-01-28 15:51 UTC, Choi-JJunho commented on src/main/java/in/koreatech/koin/domain/community/service/CommunityService.java
> +    }
### A
ditto

> getArticle 메소드에서 userId를 받아오면 좋겠다는 생각이 드네요.
지금 구조상으로는 어노테이션에 `@StudentAuth(annonymous = true|false) 라는 옵션을 두고 익명의 사용자도 API를 사용할 수 있도록 구성해봐야겠네요.
추가로 인증 어노테이션 구조를 `@Auth(permit = {ANONYMOUS, STUDENT})` 이런 방식으로 개선해봐야겠군요
해당 부분은 제가 추후 인증방식을 리팩터링하면서 수정하겠습니다
- https://github.com/BCSDLab/KOIN_API_V2/issues/174

2024-01-28 15:51 UTC, Choi-JJunho commented on src/main/java/in/koreatech/koin/domain/community/service/CommunityService.java
> +    }
### C

RequestContextHolder가 ThreadLocal처럼 요청을 물고있군요!
IP address를 구하기 위한 좋은 방법인것 같네요

다만 서비스 레이어에서 RequestHeader를 다루는것이 계층적으로 다소 어색하다고 느껴지는군요
Controller에서 `@RequestHeader` 어노테이션을 이용해서 바인딩하는건 어떨까요?

> 참고 블로그
- https://html6.tistory.com/1028

2024-01-28 15:51 UTC, Choi-JJunho commented on src/main/java/in/koreatech/koin/domain/community/controller/CommunityController.java
> +        ArticleResponse foundArticle = communityService.getArticle(id);
### C
해당 방식에 대해 두가지 고민이 드는군요..

1. Contoller에서 RequestHeader를 추출해서 넘겨준다.

```suggestion
    public ResponseEntity<ArticleResponse> getArticle(
    @RequestHeader(HttpHeaders.X_FORWARDED_FOR) String ipAddress,
    @PathVariable Long id
    ) {
        ArticleResponse foundArticle = communityService.getArticle(id, ipaddress);
```

2. ClientUtil.getIpAdress 유틸 메소드를 구현한다.

Proxy 서버의 경우 X_FORWARDED_FOR 이외의 헤더에 IP 정보가 담겨올 수도 있다로 하는군요

```java
public static String getClientIP(HttpServletRequest request) {
    String ip = request.getHeader("X-Forwarded-For");
    logger.info("X-FORWARDED-FOR : " + ip);

    if (ip == null) {
        ip = request.getHeader("Proxy-Client-IP");
        logger.info("Proxy-Client-IP : " + ip);
    }
    if (ip == null) {
        ip = request.getHeader("WL-Proxy-Client-IP");
        logger.info("WL-Proxy-Client-IP : " + ip);
    }
    if (ip == null) {
        ip = request.getHeader("HTTP_CLIENT_IP");
        logger.info("HTTP_CLIENT_IP : " + ip);
    }
    if (ip == null) {
        ip = request.getHeader("HTTP_X_FORWARDED_FOR");
        logger.info("HTTP_X_FORWARDED_FOR : " + ip);
    }
    if (ip == null) {
        ip = request.getRemoteAddr();
        logger.info("getRemoteAddr : "+ip);
    }
    logger.info("Result : IP Address : "+ip);

    return ip;
}
```

> 참고글
- https://jeongwoo.tistory.com/60

2024-01-28 15:51 UTC, Choi-JJunho commented on src/main/java/in/koreatech/koin/domain/community/service/CommunityService.java
> +    }
### A

으으음.... 뭔가 더 깔끔하게 만들수 없을까 고민이 되는데 막상 아이디어는 떠오르지않는군요
뭔가 이게 최선인느낌이네요

2024-01-28 15:51 UTC, Choi-JJunho commented on src/main/java/in/koreatech/koin/domain/community/service/CommunityService.java
> +    }
리뷰를 적다보니 다른 의견이 추가로 생겼네요 😅
Controller 쪽 리뷰 확인 부탁드립니다.

2024-01-29 08:25 UTC, songsunkook commented on src/main/java/in/koreatech/koin/domain/community/service/CommunityService.java
> +    }
서비스 레이어에서 Request 관련 정보를 직접적으로 다루는 것이 어색하다는 점에 동의합니다.
다만 준호님께서 추후에 개선하신다고 하셨으니 일단은 이대로 남겨두겠습니다!

2024-01-29 13:16 UTC, Choi-JJunho requested changes
연관관계에 대해 갑자기 궁금해져서 확인 부탁드려요~

2024-01-30 04:13 UTC, songsunkook commented on src/main/java/in/koreatech/koin/domain/community/service/CommunityService.java
> +        Long userId = getUserId();
DDL 상으로는 FK 지정이 되어있지 않아 혹시나 해서 연관관계를 맺지 않았습니다. 

(DDL부터 잘못 설계된 것으로 보이지만) 대상이 명확한 컬럼(ex. user_id)의 경우에는 DDL의 FK 등록 여부에 관계없이 연관관계를 맺어도 괜찮다고 생각하시는지 궁금합니다.

현재 DB 테이블 중에는 FK역할을 하지만 FK로 등록되지 않은 칼럼이 많이 보이기는 합니다.

2024-01-30 08:16 UTC, daheeParkk approved these changes
수고하셨습니다!

2024-01-30 08:16 UTC, daheeParkk commented on src/main/java/in/koreatech/koin/domain/community/model/Article.java
> +    @Transient
### A

`@Transient` 이라는 것을 처음 알았습니다! 
DB에 없으면 이런식으로 할 수 있군요!

2024-01-30 08:16 UTC, daheeParkk commented on src/main/java/in/koreatech/koin/domain/community/service/CommunityService.java
> +    private boolean isHittable(Long articleId, Long userId, String ipAddress) {
### A

조회수에 대해 잘 구현하신 것 같습니다!

2024-01-30 08:27 UTC, Choi-JJunho commented on src/main/java/in/koreatech/koin/domain/community/service/CommunityService.java
> +        Long userId = getUserId();
FK 지정과는 상관없이 그냥 연관관계 맺어도 좋을거같네요
FK는 그냥 제약일 뿐이지 연관관계에 직접적인 영향을 미치지않습니다. `연관관계 != FK`

따라서 `DDL의 FK 등록 여부에 관계없이 연관관계를 맺어도 괜찮다고 생각하시는지 궁금합니다.`
라는 질문에 대한 답변으로는 괜찮다~ 라는 의견입니다.

join할 때 해당 key로 조회하면 연관관계로 구성하는거죠~

2024-01-30 08:30 UTC, songsunkook commented on src/main/java/in/koreatech/koin/domain/community/service/CommunityService.java
> +        Long userId = getUserId();
답변 감사합니다! 저도 제안해주신 방향이 훨씬 깔끔한 코드가 될 것이라는 것에 동의합니다.
연관관계 매핑 형태로 수정하여 다시 올리겠습니다~!

2024-01-30 08:30 UTC, Choi-JJunho commented on src/main/java/in/koreatech/koin/domain/community/service/CommunityService.java
> +        Long userId = getUserId();
JPA가 Table로 관리되는 데이터를 객체 세상의 시점으로 바라보기 위해 사용하는거니까 오히려 id를 사용하는게 JPA를 속상하게 하는게 아닐까 싶네요

추후 지연로딩 성능 최적화를 위해 default_batch_fetch_size를 사용하는 상황을 고려해볼 수 있으므로 연관관계를 안맺을 이유는 없어보이네용

2024-01-30 10:28 UTC, Choi-JJunho approved these changes
고생하셨습니다~
피드백 꼼꼼히 확인해주셔서 감사합니다 😊

2024-01-30 10:28 UTC, merged