refactor: Auth 어노테이션 활용하도록 변경
BCSDLab/KOIN_API_V2 pull request #175
Opened 2024-01-30 17:12 UTC by Choi-JJunho

# 🔥 연관 이슈

- close #174 

# 🚀 작업 내용

1. User 객체가 아닌 userId를 반환합니다.
2. @Auth 객체를 추가했습니다. UserType에 따른 권한을 부여할 수 있습니다.
    1. 로그인이 선택적으로 불필요한 경우에는 (anonymous = true) 옵션을 추가해주시면 됩니다. 이 경우 userId에 null이 반환될 수 있기 때문에 null check를 해줘야합니다.
2. article 조회에 사용되던 ip 조회 로직을 Interceptor 및 ArgumentResovler를 활용한 방식으로 넘겼습니다.
    1. HttpRequest를 호출하는 로직이 비즈니스 레이어까지 내려오는 것이 다소 불안정하다고 느꼈습니다.
    2. Controller에 `@IpAddress String ipAddress` 를 선언하여 host의 ip 주소를 불러올 수 있도록 수정했습니다.

# 💬 리뷰 중점사항

작업 내용 자체는 많지않지만 Interceptor를 구성한 코드가 다소 낯설게 느껴진다면 아래 설명을 참고해주시길 바랍니다.

## ExtractAuthenticationInterceptor

HandlerInterceptor로 구현된 클래스로 Jwt 토큰 파싱 작업을 수행하는 단계입니다.

![image](https://github.com/BCSDLab/KOIN_API_V2/assets/49794401/7df1dab1-aceb-4247-92ce-9cf3a3af478e)

해당 Interceptor에서는 인증정보를 읽어들이며 jwt 토큰의 정보를 파싱하여 AuthContext (인증정보를 저장해두는 객체)에 저장하여 Controller로 넘기게 됩니다.

## AuthContext

```java
@Component
@RequestScope
public class AuthContext {
```

해당 클래스의 상단에 보시면 `@RequestScope`가 선언되어있는 것을 보실 수 있습니다.
아마 Spring Bean Scope에 대해 꼼꼼하게 공부해보셨다면 어렴풋이 기억날 수도 있겠지만 간단하게 다시 설명하면 다음과 같습니다.
> `@ReqeustScope`는 `@Scope("request")`와 같은 의미로
HTTP 요청 하나가 들어오고 나갈 때까지 유지되는 스코프, 각각의 HTTP 요청마다 별도의 빈 인스턴스가 생성되고 관리됩니다.

다시 말해 해당 어노테이션은 Request 시점에만 생존하는 Bean으로 Request가 올 때 Bean이 지연 생성되고 response 시점에 bean의 생명주기가 끝나게 됩니다.
따라서 해당 Scope는 Http Request에 대한 처리를 수행할 때 유용합니다.

참고자료
- https://www.baeldung.com/spring-bean-scopes#1-request-scope

해당 인터셉터 및 ArgumentResolver들은 global 패키지의 WebConfig 클래스에서 선언하고 있으므로 참고 부탁드립니다.
IpAddress에 대한 부분도 동일하게 처리중이므로 확인 부탁드립니다.

2024-01-31 05:01 UTC, songsunkook approved these changes
IP 정보를 자동으로 가져오는 어노테이션이 생기니 관련 기능이 필요할 때 훨씬 편리해진 것 같습니다.
어노테이션으로 인증 절차를 분리한 것도 각 계층의 관심사에 집중할 수 있게 되어 좋아 보입니다.

코드 스타일이 일관적이어서 이해하기 수월했습니다. 고생하셨습니다!

2024-01-31 05:04 UTC, Choi-JJunho commented on src/main/java/in/koreatech/koin/domain/auth/Auth.java
오 좋습니다! 글로벌 내부가 아니라 글로벌과 같은 레이어는 어떤가요?

2024-01-31 06:49 UTC, songsunkook commented on src/main/java/in/koreatech/koin/domain/auth/Auth.java
글로벌과 같은 레이어에 두는 것에 대해 이유가 있을까요??
개인적으로는 auth를 global 외부에 둔다면 global 패키지의 정체성이 모호해질 수도 있다고 생각합니다.

+) global과 같은 레이어에 둔다면 config와 같은 패키지도 상위 레이어로 옮기는 것을 고려해봐야 할 것 같습니다.

2024-01-31 06:51 UTC, Choi-JJunho commented on src/main/java/in/koreatech/koin/domain/auth/Auth.java
아 다른 프로젝트 왔다갔다하다보니 domain이 있다는걸 까먹었네요 ㅠㅠ
말씀하신대로 global에 두는게 좋아보입니다! 👍

2024-01-31 08:10 UTC, songsunkook approved these changes
리뷰를 빠르게 잘 반영해주셨네요! 감사합니다!! 😊

2024-02-01 07:35 UTC, daheeParkk requested changes
수고하셨습니다!

2024-02-01 07:35 UTC, daheeParkk commented on src/main/java/in/koreatech/koin/domain/user/repository/StudentRepository.java
> +        return findById(id).orElseThrow(() -> UserNotFoundException.withDetail("id" + id));
### A

`"id: " + id`로 바꾸는 게 보기 편할 것 같습니다!

2024-02-01 07:35 UTC, daheeParkk commented on src/main/java/in/koreatech/koin/domain/user/controller/UserController.java
> +    public ResponseEntity<Void> logout(@Auth(permit = {USER, STUDENT}) Long userId) {
### C

UserType으로 `USER`와 `STUDENT`가 사용되고 있는데, DB에 users 테이블의 user_type으로는 `STUDENT`와 `OWNER`만 있지 않나요?

2024-02-01 23:45 UTC, Choi-JJunho commented on src/main/java/in/koreatech/koin/domain/user/controller/UserController.java
> +    public ResponseEntity<Void> logout(@Auth(permit = {USER, STUDENT}) Long userId) {
오! 그러네요
생각해보면 학생이 아닌 일반 유저가 가입할 수는 없겠네요 (코인은 학교메일 인증해서 가입)
되려 헷갈릴수 있으니 User 권한은 제거하도록 할게요!

2024-02-02 05:18 UTC, daheeParkk approved these changes

2024-02-02 05:18 UTC, merged