docs: add swagger config
BCSDLab/KOIN_API_V2 pull request #176
Opened 2024-01-31 11:15 UTC by Choi-JJunho

# 🔥 연관 이슈

- close #171

# 🚀 작업 내용

1. Swagger 문서 적용
    1. 기존 문서의 description, example을 최대한 가져와봄
    2. 인증이 필요한 경우 응답에 20x, 401, 403, 404 예외를 선언함
    3. `@Auth` `@IpAddress`와 같은 ArgumentResolver로 정의되는 어노테이션에 `@Hidden` 어노테이션을 정의하여 Swagger 상에서 뜨지 않게 구성함.

# 💬 리뷰 중점사항

Swagger 적용 간 누락된 사항이 없는지 확인 부탁드립니다.

2024-02-02 08:37 UTC, songsunkook requested changes
문서량이 상당한데 하나하나 작성하는 데 힘드셨을 것 같습니다.. 고생하셨습니다!! 🥹
확실히 swagger를 도입하니 문서화가 잘 되어서 좋네요!

DTO 스키마 정보 관련해서 코멘트 남겼으니 확인 부탁드립니다!

2024-02-02 08:37 UTC, songsunkook commented on src/main/java/in/koreatech/koin/domain/land/controller/LandApi.java
> +        @Parameter(hidden = true) @PathVariable Long id
### R
`hidden = true` 속성 때문에 스웨거 상에서 파라미터 입력 창이 표시되지 않습니다!

2024-02-02 08:37 UTC, songsunkook commented on src/main/java/in/koreatech/koin/domain/land/dto/LandListItemResponse.java
>      Double longitude,
### C
앞으로 작업하는 Request, Response DTO들에 대해서는 모두 주석을 달아야 할까요? 확실히 클라이언트에게 좋은 정보가 되는 것은 맞지만 이 부분을 작업하는 데에만 상당한 인력이 소모될 것으로 생각됩니다. 클라이언트가 이 예시(or 설명) 정보를 잘 활용하고 있는지 확인이 필요해 보입니다.
극단적인 예시로 게시글(/articles) 관련 API들은 현재 DTO 주석 작업이 이루어져 있지 않은데, 넘길 데이터 종류가 너무 많아서 주석 매핑이 상당히 오래 걸릴 것 같습니다...

+) 뭔가 스웨거 3으로 넘어오면서 응답 객체 정보 열람이 많이 불편해진 것 같습니다... 😭 제가 방법을 모르는걸까요..

2024-02-02 08:39 UTC, Choi-JJunho commented on src/main/java/in/koreatech/koin/domain/land/controller/LandApi.java
> +        @Parameter(hidden = true) @PathVariable Long id
in=Path로 설정해야하는데 실수했네요 😅

2024-02-02 09:27 UTC, Choi-JJunho commented on src/main/java/in/koreatech/koin/domain/land/dto/LandListItemResponse.java
>      Double longitude,
음? Articles 얼마나있길래??

2024-02-02 09:30 UTC, Choi-JJunho commented on src/main/java/in/koreatech/koin/domain/land/dto/LandListItemResponse.java
>      Double longitude,
참고로 스키마 정보는 여기서 볼 수 있긴해~!
그래도 example 정도는 있으면 좋지 않을까 해서 이왕 쓸거면 다 쓰는게 좋지 않을까 싶긴한데
<img width="1160" alt="image" src="https://github.com/BCSDLab/KOIN_API_V2/assets/49794401/2c26e820-e01f-4355-aa10-5d8b635fe0df">

2024-02-02 09:31 UTC, Choi-JJunho commented on src/main/java/in/koreatech/koin/domain/land/dto/LandListItemResponse.java
>      Double longitude,
좀 많긴하네 ㅋㅋㅋㅋ
이런건 GPT나 코파일럿 도움좀 받아보는것도 좋을듯?
<img width="333" alt="image" src="https://github.com/BCSDLab/KOIN_API_V2/assets/49794401/04e26c2c-84d4-426e-9446-c2c4d69300df">

2024-02-03 01:46 UTC, songsunkook approved these changes
피드백 반영 확인했습니다. 고생하셨습니다!

2024-02-04 08:29 UTC, daheeParkk approved these changes

2024-02-04 08:29 UTC, merged