feat: 인기 게시글 목록 조회
BCSDLab/KOIN_API_V2 pull request #181
Opened 2024-02-08 06:30 UTC by songsunkook

# 🔥 연관 이슈

- close #105 
- close #103 

# 🚀 작업 내용

1. Redis에 최근 게시글 조회 로그를 기록하여 그 데이터로 인기 게시글을 판단합니다. (유효기간: 1일)
2. 스케줄러를 통해 1시간 간격으로 만료된 Redis 게시글 조회 로그를 제거합니다.

### Redis 게시글 조회 로그 토큰 형태
![image](https://github.com/BCSDLab/KOIN_API_V2/assets/21010656/dbaa8222-186f-4018-93c6-9eb13451c278)

# 💬 리뷰 중점사항
현재 인기 게시글 판단 로직은 비효율적이어서 개선이 필요하지만, 이번에 작업한 API는 프로젝트 내에서 우선순위가 매우 떨어지기 때문에 이슈로 남겨두고 보류하기로 했습니다.
- #180

2024-02-11 17:34 UTC, Choi-JJunho requested changes
고생하셨어요~!
코인 마이그레이션 프로젝트의 PR왕!
몇가지 생각해보면 좋을만한 코멘트를 남겼으니 확인 부탁드릴게요~

2024-02-11 17:34 UTC, Choi-JJunho commented on src/main/java/in/koreatech/koin/KoinApplication.java
> +@EnableScheduling
### A
스케줄링을 사용하기 위해 해당 어노테이션을 Application 구동 부에 선언해줘야하는군요 👍

2024-02-11 17:34 UTC, Choi-JJunho commented on src/main/java/in/koreatech/koin/domain/community/model/HotArticle.java
> +    Long id;
### A
해당 id는 Article id겠죠?

2024-02-11 17:34 UTC, Choi-JJunho commented on src/main/java/in/koreatech/koin/domain/community/model/HotArticle.java
> +    List<LocalDateTime> expiredTimes = new ArrayList<>();
### R
Redis의 TTL을 사용하지 않은 이유가 있나요?

```suggestion
    @TimeToLive
    long expiredTime;
```

2024-02-11 17:34 UTC, Choi-JJunho commented on src/main/java/in/koreatech/koin/domain/community/service/CommunityService.java
> +        PageRequest pageRequest = PageRequest.of(criteria.getPage(), criteria.getLimit(), ARTICLES_SORT);
### C
페이징 처리 방식을 보다가 문득 생각이 들었는데 page, limit, sort 정보가 필요하다면 Pageable 객체를 활용해보는건 어떻게 생각하나요?

2024-02-11 17:34 UTC, Choi-JJunho commented on src/main/java/in/koreatech/koin/domain/community/service/CommunityService.java
> +            .toList();
### C
이렇게하면 쿼리가 id개수만큼 쏴지지 않나요? 제가 잘 모를수도 있는 내용이라 유추하는 코드를 드려보자면
`List<Article> getAllByIdIn(List<Long> ids)` 처럼 named 쿼리를 작성하면 in절로 한꺼번에 가져오는걸로 알고있어요~
만약 안된다고하면 JPQL로도 in절을 작성할 수 있습니다.

```java
@Query("select a from Article a where a.id in :ids")
List<Article> getByIds(List<Long> ids);
```

2024-02-11 17:34 UTC, Choi-JJunho commented on src/main/java/in/koreatech/koin/domain/community/service/CommunityService.java
> +            .sorted(Comparator.reverseOrder())
### C
쿼리할때 OrderBy가 안되나요?

2024-02-11 17:34 UTC, Choi-JJunho commented on src/main/java/in/koreatech/koin/domain/community/service/CommunityService.java
> +        });
### C

개인적인 견해를 여기 적어봅니다.

인기 게시글을 위해 많은 로직을 고민하고 꼼꼼하게 규칙을 작성해보려는 시도와 노력은 좋게 보고있습니다.

하지만 장기적으로 봤을 때 공지사항 이외에는 사용중이지 않은 게시판 및 커뮤니티 기능에 대해 너무 많은 코드와 관심사가 쏟아지고있는것은 아닌지 우려가 듭니다.
스케줄링도 돌고 Redis, DB에서 데이터도 기능에 비해 너무나 많은 자원이 호출되고 있다고 생각이 듭니다.

물론 선권님의 노고를 낮게 보려는것은 절대절대 아니지만 과연 이렇게까지 필요할까? 라는 생각입니다.
우리의 1차적인 목표는 고도화된 커뮤니티를 만드는 것이 아니라 안전하고 협업하기 좋은 코드를 작성하는 방향으로 마이그레이션을 진행하고 있다는 부분을 다시한번 생각해주시면 감사하겠습니다.

2024-02-11 18:26 UTC, songsunkook commented on src/main/java/in/koreatech/koin/domain/community/service/CommunityService.java
> +        PageRequest pageRequest = PageRequest.of(criteria.getPage(), criteria.getLimit(), ARTICLES_SORT);
컨트롤러에서 파라미터로 받는 것을 말씀하시는 건가요??

![image](https://github.com/BCSDLab/KOIN_API_V2/assets/21010656/d6eaa61a-b305-4a3a-98a3-52bb93acc29b)

Pageable을 컨트롤러에서 파라미터로 받는 경우 `page`, `size`, `sort(생략가능)`을 지원하는데 기존 API는 `size`가 아닌 `limit`를 인자로 받고 있어서 해당 방식을 사용하지 못했습니다. 혹시 사용 가능한 방법이 있을까요??

2024-02-11 18:26 UTC, songsunkook commented on src/main/java/in/koreatech/koin/domain/community/service/CommunityService.java
> +            .sorted(Comparator.reverseOrder())
RedisRepository는 OrderBy나 Limit를 지원하지 않는 것으로 보입니다.

2024-02-11 18:26 UTC, songsunkook commented on src/main/java/in/koreatech/koin/domain/community/service/CommunityService.java
> +            .toList();
Redis는 JPQL(include Named Query)를 지원하지 않는 것 같습니다...

2024-02-11 18:26 UTC, songsunkook commented on src/main/java/in/koreatech/koin/domain/community/service/CommunityService.java
> +        });
저도 스케줄링을 추가할 때 이번 API가 이 정도 자원을 소모할 정도의 가치가 있는지 고민이 들었습니다. 그래도 이번 API의 로직 상 현재 작성한 구조가 가장 직관적이고 간결하다고 생각하여 이렇게 작성했습니다.

우선순위가 떨어지는 API인 만큼 완성도를 포기하고 복잡도를 최소화해보자면 아래와 같은 로직이 가장 단순해 보입니다.
(이번 API는 Redis를 도입하는 순간 복잡도가 많이 높아질 것으로 우려됩니다.)

**MySQL에 저장된 최상위 10개(or more) 게시글을 기준으로 조회수 정렬한다.**

이 방법으로 수정하는 것이 더 적절하다고 생각하시는지 궁금합니다. 말씀해주시는 방향으로 작업하겠습니다!

2024-02-13 03:14 UTC, Choi-JJunho commented on src/main/java/in/koreatech/koin/domain/community/service/CommunityService.java
> +        });
네네~! 현재로서는 HotArticle이라는 구조를 가져가면서까지 가져갈 필요가 있나 싶긴합니다.
개인적으로는 
> MySQL에 저장된 최상위 10개(or more) 게시글을 기준으로 조회수 정렬한다.

이 구조를 선호합니다~

2024-02-13 04:36 UTC, daheeParkk approved these changes
수고하셨습니다!

2024-02-13 08:43 UTC, Choi-JJunho approved these changes
굿굿 고생하셨습니다~
테스트도 꼼꼼하게 잘 짜주셨네요
많은 생각을 하고 고도화를 했을텐데 과도한 기능으로 없애버려서 괜히 미안한 마음이드네요 🥲

2024-02-13 08:43 UTC, Choi-JJunho commented on src/main/java/in/koreatech/koin/domain/community/model/Article.java
> +    @PostPersist
### A
오 영속화 직전에는 항상 contentSummary를 초기화해주는거군요 👍

2024-02-13 08:43 UTC, Choi-JJunho commented on src/main/java/in/koreatech/koin/domain/community/service/CommunityService.java
> +        PageRequest pageRequest = PageRequest.of(criteria.getPage(), criteria.getLimit(), ARTICLES_SORT);
### A
Pageable Custom이 가능할거같은데... 결국 전체적으로 쓰여야하는 내용이니 굳이 커스텀할 이유는 없어보이네요
차후에 전체적으로 페이징 관련 리팩터링을 해봐야겠네요
지금은 이대로 진행하죠!

2024-02-13 09:07 UTC, songsunkook commented on src/main/java/in/koreatech/koin/domain/community/model/Article.java
> +    @PostPersist
정확히는 영속화 직후입니다!
PostLoad 만으로는 영속화(객체 생성) 시 해당 엔티티에 초기화가 안되서 영속화 시점에도 초기화를 수행하도록 추가했습니다. 😊

2024-02-13 09:09 UTC, merged