feat: 사장님 정보 조회
BCSDLab/KOIN_API_V2 pull request #182
Opened 2024-02-11 16:47 UTC by songsunkook

# 🔥 연관 이슈

- close #116 

# 🚀 작업 내용

1. 로그인된 사장님의 정보를 반환합니다.
2. 서비스에서 Repository에 접근하는 로직을 최소화하고 연관관계를 최대한 응용해보았습니다.

# 💬 리뷰 중점사항

2024-02-11 17:12 UTC, Choi-JJunho requested changes
와우.. 엄청난 열정!
테스트코드보고 놀랐습니다 ㅋㅋㅋㅋㅋㅋ
몇가지 코멘트 남겼으니 확인 부탁드려요~

2024-02-11 17:12 UTC, Choi-JJunho commented on src/main/java/in/koreatech/koin/domain/owner/repository/OwnerRepository.java
> +    Owner findById(Long ownerId);
### C
findById를 선언하면 DataAccessException이였나? 가 아마 발생할텐데 이 에러는 핸들링 및 예외메시지를 신경쓰기가 어려울거같아요.
findById 쿼리로는 Optional로 조회하고 저희가 선언하는 CustomException이 발생하도록 구성하는건 어떨까요?

```suggestion
    Optional<Owner> findById(Long ownerId);
    
    default Owner getById(Long ownerId) {
        return findById(ownerId).orElseThrow(() -> throw new CustomException());
    }
```

2024-02-11 17:12 UTC, Choi-JJunho commented on src/main/java/in/koreatech/koin/domain/owner/service/OwnerService.java
> +@RequiredArgsConstructor
### A
사소하지만 Transactional(readOnly=true)를 걸어주는거 어때요?

2024-02-11 17:12 UTC, Choi-JJunho commented on src/main/java/in/koreatech/koin/domain/user/model/UserType.java
> +    OWNER("OWNER", "사장님"),
### A
사장님 등장 >_0

2024-02-11 17:12 UTC, Choi-JJunho commented on src/test/java/in/koreatech/koin/acceptance/OwnerApiTest.java
> +    @DisplayName("로그인된 사장님 정보를 조회한다.")
### A
와우... 테스트 살벌하게 짰네요

2024-02-11 17:12 UTC, Choi-JJunho commented on src/main/java/in/koreatech/koin/domain/owner/domain/Owner.java
> +    private List<Shop> shops = new ArrayList<>();
### C
저는 개인적으로 양방향 관계에 참 조심스러워 지는 편인데
자칫 잘못하면 순환참조가 걸려버릴수도 있고 cascade같은거 잘못썼다가 디비 망가지고 난리날바엔 쿼리 하나 더 작성하는게 좋다고 생각해요

이럴 땐 사장님은 반드시! shop을 가지고 있어야만 하는가? 라는 질문에 한번 생각해보시는것을 추천드려요

아래 Attachment는 가입 조건이니까 이해가 되지만 초기 가입 시점에서 상점이 없는 사장님이 있을 수도 있고 사장님이 폐업한 경우도 있을 수 있을 것같네요
모든 상황에서 사장님은 상점을 가져야만 할까요?

2024-02-11 18:27 UTC, songsunkook commented on src/main/java/in/koreatech/koin/domain/owner/domain/OwnerAttachment.java
> +    public static final int NOT_FOUND_IDX = -1;
헉.. 날카로운 지적 감사합니다..!

2024-02-11 18:32 UTC, songsunkook commented on src/main/java/in/koreatech/koin/domain/owner/dto/OwnerResponse.java
> +    List<InnerShopResponse> shops
깜빡했네요.. 추가하겠습니다!

2024-02-11 18:34 UTC, songsunkook commented on src/main/java/in/koreatech/koin/domain/owner/service/OwnerService.java
> +@RequiredArgsConstructor
! 추가하겠습니다!

2024-02-11 18:39 UTC, songsunkook commented on src/main/java/in/koreatech/koin/domain/owner/repository/OwnerRepository.java
> +    Owner findById(Long ownerId);
외부에서는 Repository의 `find...` 메서드를 가급적 호출하지 않는 방향으로 작성해야겠네요. 감사합니다!

2024-02-11 19:06 UTC, songsunkook commented on src/main/java/in/koreatech/koin/domain/owner/domain/Owner.java
> +    private List<Shop> shops = new ArrayList<>();
연관관계 매핑을 진행하지 않은 저번과 달리 이번에는 연관관계를 적극 활용한다는 점을 인지하며 작업했습니다.
양방향 연관관계도 주저없이 사용했고, 그 결과 Service 코드는 간결해졌으나 테스트 코드 작성 시 연관관계에 관해 수많은 에러가 나왔습니다.

말씀해주신 내용을 듣고 찾아보니 양방향 연관관계는 얻는 편의성에 비해 위험성이 많다는 것을 알 수 있었습니다.
앞으로 양방향 연관관계는 최대한 지양하도록 하고, 이번 API에서도 양방향 연관관계를 제거하여 다시 작성해오겠습니다!
새로운 것을 알려주셔서 감사합니다 😊

[양방향 연관관계 주의사항 관련 글](https://www.inflearn.com/questions/747142/jpa-%EC%96%91%EB%B0%A9%ED%96%A5-%EC%97%B0%EA%B4%80%EA%B4%80%EA%B3%84-%EA%B4%80%EB%A0%A8%ED%95%98%EC%97%AC-%EC%A7%88%EB%AC%B8-%EB%93%9C%EB%A6%BD%EB%8B%88%EB%8B%A4)

2024-02-13 08:20 UTC, Choi-JJunho approved these changes
굿굿~! 컨벤션만 확인해주세요

2024-02-13 08:20 UTC, Choi-JJunho commented on src/main/java/in/koreatech/koin/domain/owner/repository/OwnerAttachmentRepository.java
> +    List<OwnerAttachment> findAllByOwner(Owner owner);
### A
byOwner vs byOwnerId
어떤걸로 통일할까요

2024-02-13 08:20 UTC, Choi-JJunho commented on src/main/java/in/koreatech/koin/domain/owner/controller/OwnerController.java
> +    public ResponseEntity<OwnerResponse> getOwner(@Auth(permit = {OWNER}) Long ownerId) {
### A
```suggestion
    public ResponseEntity<OwnerResponse> getOwner(
        @Auth(permit = {OWNER}) Long ownerId
    ) {
```
엔터로 구분해서 보면 조금 더 잘보일거같은데 어떻게 생각하나요?

2024-02-13 08:27 UTC, songsunkook commented on src/main/java/in/koreatech/koin/domain/owner/repository/OwnerAttachmentRepository.java
> +    List<OwnerAttachment> findAllByOwner(Owner owner);
후자로 통일하겠습니다!

2024-02-13 08:28 UTC, songsunkook commented on src/main/java/in/koreatech/koin/domain/owner/controller/OwnerController.java
> +    public ResponseEntity<OwnerResponse> getOwner(@Auth(permit = {OWNER}) Long ownerId) {
동의합니다. 수정하겠습니다!

2024-02-13 08:46 UTC, daheeParkk requested changes
수고하셨습니다!

2024-02-13 08:46 UTC, daheeParkk commented on src/main/java/in/koreatech/koin/domain/owner/service/OwnerService.java
> +    public OwnerResponse getOwnerShops(Long ownerId) {
### C

사장님 정보 조회니까 `getOwner`가 더 괜찮지 않을까요?

2024-02-13 09:03 UTC, songsunkook commented on src/main/java/in/koreatech/koin/domain/owner/service/OwnerService.java
> +    public OwnerResponse getOwnerShops(Long ownerId) {
헐 세상에.. API 수정하다가 네이밍 수정하는 걸 깜빡해버렸네요... 감사합니다!!

2024-02-13 09:10 UTC, daheeParkk approved these changes

2024-02-13 09:10 UTC, merged