feat: 사장님 회원가입 인증번호 전송 요청
BCSDLab/KOIN_API_V2 pull request #184
Opened 2024-02-20 07:54 UTC by daheeParkk

# 🔥 연관 이슈

- close #124 

# 🚀 작업 내용

1. 이메일 형식과 이메일이 DB에 존재하는지 검사
2. 메일 전송 
3. 레디스에 이메일 저장
4. 슬랙에 알림

- 테스트
  - 사장님이 회원가입 인증번호 전송 요청을 한 경우 테스트
    -  200 응답 확인
    - 레디스에서 조회해도 에러가 안 나는지 확인
  - 사장님 회원가입 인증번호 전송 요청 이벤트 발생 시 **슬랙 전송 이벤트가 발생**하는지 테스트

# 💬 리뷰 중점사항
- random과 슬랙, 이메일은 global에 domain 패키지를 만들어 넣었는데 괜찮은 위치&패키지명인지 고민됩니다.
- 슬랙 알림은 서비스 로직과 관심사가 다르기 때문에 스프링 이벤트를 적용시켰습니다. 
  - 슬랙 알림 전송이 실패해도 200 응답을 반환합니다.

해당 api를 작업하면서 작성한 글입니다. 스프링 이벤트, `@Transactional(propagation = Propagation.REQUIRES_NEW)`, 테스트에 대해 적었으니 참고해주세요!
https://flat-sprout-d3b.notion.site/POST-owers-verification-email-26102ea01371413fab0ed3e08222b7d0?pvs=4

2024-02-21 07:05 UTC, Choi-JJunho requested changes
생각보다 규모가 큰 작업을 맡으셨네요
고생하셨습니다
일단 현재 올리신 코드에서 고칠만한 부분에 대한 코멘트를 남겼으니 확인 부탁드릴게요

2024-02-21 07:05 UTC, Choi-JJunho commented on src/main/java/in/koreatech/koin/domain/owner/service/OwnerService.java
> +        slackService.noticeEmailVerification(ownerInVerification);
### R

슬랙 발송이 실패하면 회원가입 로직 자체가 실패해버립니다
슬랙 발송은 서비스 사용자의 관심사가 전혀 아니겠죠?
어떻게 해결할 수 있을까요 여러가지 키워드가 있습니다.

AOP, Spring Event, `@TransactionalEventListener`
한번 키워드 기반으로 학습해보시고 나중에 이 주제로 같이 페어하면서 리팩터링해보죠

2024-02-22 05:48 UTC, daheeParkk commented on src/main/java/in/koreatech/koin/domain/owner/dto/VerifyEmailRequest.java
> +    @NotBlank(message = "이메일을 입력해주세요.") String email
수정하겠습니다!

2024-02-22 05:49 UTC, daheeParkk commented on src/main/java/in/koreatech/koin/domain/owner/service/OwnerService.java
> +    public void requestVerificationToRegister(VerifyEmailRequest request) {
requestSignUpEmailVerification()는 어떨까요?

2024-02-22 06:45 UTC, daheeParkk commented on src/main/java/in/koreatech/koin/domain/owner/service/OwnerService.java
> +        validateEmailUniqueness(email);
좋은 것 같습니다! 이메일이 존재하는 지를 검증하는 게 더 잘 드러나는 것 같습니다

2024-02-22 06:46 UTC, daheeParkk commented on src/main/java/in/koreatech/koin/global/common/RandomGenerator.java
> +    public static final int CERTIFICATION_NUMBER_ORIGIN = 0;
public인 것을 못 봤습니다ㅠㅠ 
private으로 바꾸겠습니다

2024-02-22 06:47 UTC, daheeParkk commented on src/main/java/in/koreatech/koin/global/common/email/config/AwsSesConfig.java
> +            .withRegion(Regions.US_WEST_2)
`ap-northeast-2`이 있었네요..!

2024-02-22 06:54 UTC, daheeParkk commented on src/main/java/in/koreatech/koin/global/common/email/model/Domain.java
> +public class Domain {
이메일에서 ‘@’ 뒷 부분을 도메인이라고 했습니다!

2024-02-23 11:49 UTC, daheeParkk commented on src/main/java/in/koreatech/koin/global/common/RandomGenerator.java
> +public class RandomGenerator {
숫자 생성 함수는 전역적으로 사용되기 때문에 static으로 해야 인스턴스를 생성하지 않아 메모리가 절약된다고 생각했습니다!

2024-02-23 11:53 UTC, daheeParkk commented on src/main/java/in/koreatech/koin/global/common/RandomGenerator.java
> +    private static final int CERTIFICATION_NUMBER_BOUND = 1_000_000;
인증번호 생성 클래스를 따로 만들어 RandomGenerator를 상속 받는 게 좋을 것 같습니다..!ㅠㅠ

2024-02-23 11:54 UTC, daheeParkk commented on src/main/java/in/koreatech/koin/global/common/email/model/Domain.java
> +            return attribute != null;
기존 코인 코드에서 MX 검증을 하고 있길래 여기에서도 해야겠지 하고 가져왔습니다.
다시 생각해보니 보낼 수 있는 이메일인지 검사(MX 검증)보다는 이메일 형식 검사만 있어도 될 것 같습니다!

2024-02-23 11:56 UTC, daheeParkk commented on src/main/java/in/koreatech/koin/global/common/email/model/Email.java
> +    }
기존 코인 코드에서 @Email을 사용하고 있지 않길래 찾아봤더니 @Email은 정규표현식 패턴 검사가 충분하지 않다고 나와있었습니다! 
그래서 정규표현식 검사를 구현했지만 @Email에서 정규식을 재정의 할 수 있다는 것을 알게되었습니다,, 
옵션으로 재정의하는게 코드가 더 간단할 것 같으니 @Email로 바꾸겠습니다!

2024-02-23 11:57 UTC, daheeParkk commented on src/main/java/in/koreatech/koin/global/common/email/model/LocalParts.java
> +public class LocalParts {
이메일의 ‘@’ 앞부분과 뒷부분 각각을 검사하기위해 객체로 나눠놨는데 MX 검증을 안하고 @Email을 사용해 정규표현식 검사만 한다면 필요 없을 것 같습니다..!

2024-02-23 11:59 UTC, daheeParkk commented on src/main/java/in/koreatech/koin/global/common/email/model/Mail.java
> +    private final VelocityContext velocityContext = new VelocityContext();
시간, 이메일 등의 요소가 더 추가된 다른 폼이 생긴다면 다른 Mail 객체를 만들지 않고, 필드를 더 추가하여 그에 따른 converToMap메서드를 만들면 될 것 같습니다!

2024-02-23 12:02 UTC, daheeParkk commented on src/main/java/in/koreatech/koin/global/common/email/config/AwsSesConfig.java
> +package in.koreatech.koin.global.common.email.config;
global 안에서도 email과 slack, RandomGenerator는 config, exception들과는 다르기 때문에 분리해뒀습니다!
global과 common은 같은 의미로 쓰이는 것 같은데, common을 domain으로 바꾸는 건 어떨까요?

2024-02-23 12:03 UTC, daheeParkk commented on src/main/java/in/koreatech/koin/global/common/slack/model/Notice.java
> +public class Notice {
SlackNotification이 좋은 것 같습니당

2024-02-23 12:03 UTC, daheeParkk commented on src/main/java/in/koreatech/koin/domain/owner/service/OwnerService.java
> +        slackService.noticeEmailVerification(ownerInVerification);
슬랙 발송이 실패해도 서비스 로직은 실패하지 않도록 하겠습니다..!
알려주신 키워드로 공부해보겠습니다!

2024-02-23 13:31 UTC, daheeParkk commented on src/main/java/in/koreatech/koin/global/common/email/config/AwsSesConfig.java
> +            .withRegion(Regions.US_WEST_2)
기존 코인 코드와 같이 US_WEST_2으로 해야 메일이 보내집니다..!
AWS SES 설정에 US_WEST_2으로 되어있는 것 아닐까요?

2024-02-26 08:44 UTC, songsunkook requested changes
코드에서 많이 고민한 흔적이 보이는 것 같아요..!
큰 작업이었을텐데 고생하셨습니다!
개인적인 의견 남겨드렸으니 확인 부탁드립니다!

2024-02-26 08:44 UTC, songsunkook commented on src/test/java/in/koreatech/koin/acceptance/OwnerApiTest.java
> +    @DisplayName("사장님이 회원가입 인증번호 전송 요청을 한다. - 슬랙 전송 실패")
### R
슬랙 전송 실패가 API 실패 응답으로 이어져야 할지는 고민이 필요할 것 같아요.
실제로 메일도 가고 레디스에 저장도 된다면 회원가입 인증 요청 자체는 성공했으니 성공이라고 봐도 되지 않을까요??

2024-03-06 10:01 UTC, daheeParkk commented on src/main/java/in/koreatech/koin/domain/owner/service/OwnerService.java
> +        EmailAddress email = new EmailAddress(request.email());
안에 검증 로직이 있으니 팩토리 메서드를 이용하는게 좋을 것 같네요!

2024-03-06 10:01 UTC, daheeParkk commented on src/main/java/in/koreatech/koin/global/domain/email/model/Mail.java
> +    private final Map<String, Object> model = new HashMap<>();
사용하지 않는 변수를 지우지 못했습니다ㅠㅠ 지우겠습니다..!

2024-03-06 10:02 UTC, daheeParkk commented on src/main/java/in/koreatech/koin/global/domain/slack/model/SlackNotification.java
> +        attachment.add(addColor(COLOR_GOOD, user.getEmail() + EMAIL_VERIFICATION_REQUEST_SUFFIX));
두 줄보다 한 줄이 좋을 것 같네요!

2024-03-06 10:03 UTC, daheeParkk commented on src/test/java/in/koreatech/koin/acceptance/OwnerApiTest.java
> +    @DisplayName("사장님이 회원가입 인증번호 전송 요청을 한다. - 슬랙 전송 실패")
스프링 이벤트를 적용하여 슬랙 전송이 실패해도 200 응답을 반환하도록 하겠습니다!

2024-03-08 04:48 UTC, songsunkook approved these changes
스프링 이벤트 학습하고 적용하는 과정이 쉽지 않았을텐데 고생하셨습니다!

2024-03-10 16:15 UTC, Choi-JJunho approved these changes
컨벤션만 수정해주면 좋을거같아~

2024-03-11 02:12 UTC, daheeParkk commented on src/main/java/in/koreatech/koin/domain/owner/model/OwnerEmailRequestEvent.java
> +public record OwnerEmailRequestEvent(String email) {
다른 record와 같이 세로로 세우는게 좋을 것 같습니당..!

2024-03-11 02:12 UTC, daheeParkk commented on build.gradle
> +    implementation 'com.amazonaws:aws-java-sdk-ses:1.12.188'
다른 코드를 참고하느라 최신 버전을 확인하지 못했습니다,, 적용해보겠습니다!

2024-03-11 02:12 UTC, daheeParkk commented on src/main/java/in/koreatech/koin/domain/owner/model/OwnerInVerification.java
> +@AllArgsConstructor(access = AccessLevel.PRIVATE)
넹

2024-03-11 02:13 UTC, daheeParkk commented on src/main/java/in/koreatech/koin/domain/user/model/User.java
> +        String authToken, String authExpiredAt, String resetToken, String resetExpiredAt) {
한줄로 하는게 변수명 알아보기 편한 것 같네요..! 수정하겠습니다

2024-03-11 02:34 UTC, daheeParkk commented on src/main/java/in/koreatech/koin/domain/user/model/User.java
> +        String authToken, String authExpiredAt, String resetToken, String resetExpiredAt) {
해봤는데 모양이 조금 이상한 것 같아요,, 너무 길어서 읽기 불편하지 않을까요..?
```java
@Builder
    public User(
        String password, 
        String nickname, 
        String name, 
        String phoneNumber, 
        UserType userType,
        String email,
        UserGender gender, 
        Boolean isAuthed, 
        LocalDateTime lastLoggedAt, 
        String profileImageUrl,
        Boolean isDeleted,
        String authToken, 
        String authExpiredAt, 
        String resetToken, 
        String resetExpiredAt) {
        this.password = password;
        this.nickname = nickname;
        this.name = name;
        this.phoneNumber = phoneNumber;
        this.userType = userType;
        this.email = email;
        this.gender = gender;
        this.isAuthed = isAuthed;
        this.lastLoggedAt = lastLoggedAt;
        this.profileImageUrl = profileImageUrl;
        this.isDeleted = isDeleted;
        this.authToken = authToken;
        this.authExpiredAt = authExpiredAt;
        this.resetToken = resetToken;
        this.resetExpiredAt = resetExpiredAt;
    }
```

2024-03-11 02:35 UTC, daheeParkk commented on src/main/java/in/koreatech/koin/domain/user/model/User.java
> +        String authToken, String authExpiredAt, String resetToken, String resetExpiredAt) {
일정하게 나열하기만 해도 괜찮을 것 같습니다!
```java
public User(String password, String nickname, String name, String phoneNumber, UserType userType,
        String email, UserGender gender, Boolean isAuthed, LocalDateTime lastLoggedAt, String profileImageUrl,
        Boolean isDeleted, String authToken, String authExpiredAt, String resetToken, String resetExpiredAt)
```

2024-03-11 02:36 UTC, Choi-JJunho commented on src/main/java/in/koreatech/koin/domain/user/model/User.java
> +        String authToken, String authExpiredAt, String resetToken, String resetExpiredAt) {
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ 그래요 일정하게 나열하고 생성자 private으로만 선언 부탁드려요 (빌더만쓰게끔)

2024-03-11 02:37 UTC, Choi-JJunho commented on src/main/java/in/koreatech/koin/domain/owner/model/OwnerInVerification.java
> +@AllArgsConstructor(access = AccessLevel.PRIVATE)
음~~ 다른 코드들도 해야하는데 까먹은거같네요
시간 좀 남는다면 다른친구들도 static import 슥슥 해줄래요?

2024-03-11 02:38 UTC, daheeParkk commented on src/main/java/in/koreatech/koin/domain/owner/model/OwnerInVerification.java
> +@AllArgsConstructor(access = AccessLevel.PRIVATE)
네넹

2024-03-11 02:38 UTC, daheeParkk commented on src/main/java/in/koreatech/koin/domain/user/model/User.java
> +        String authToken, String authExpiredAt, String resetToken, String resetExpiredAt) {
넵!

2024-03-11 06:42 UTC, Choi-JJunho approved these changes
거의 한달넘게 걸린거같은데 작업이 꽤 커서 힘들었을텐데도 끝까지 해내셨군요
고생하셨습니다.. 👍

2024-03-11 06:43 UTC, merged