feat: 버스 남은 시간 조회 - 셔틀버스, 등하교 버스
BCSDLab/KOIN_API_V2 pull request #185
Opened 2024-02-28 23:10 UTC by songsunkook

# 🔥 연관 이슈

- #99 (미완)

# 🚀 작업 내용

## 주요 로직
1. mongoDB에서 (findByBusType) 버스 정보를 불러옵니다.
2. 버스 정보 중 노선 정보를 꺼내 적절한지 판단합니다.
    - 운행 요일인가
    - 노선 상에 요청받은 출발지 -> 목적지 경로가 포함되어 있는가
    - 현재 시각이 출발하는 시간 전인가
3. busType과 함께 다음, 다다음 버스가 올 때까지 남은 시간(초)을 반환합니다.

## 주요 변경 사항
1. mongoDB TestContainer 추가
2. LocalTime() 대신 LocalTime(clock) 적용 (mocking 필요한 부분만)
3. mongoDB 버전을 올렸습니다. (3.4.24 -> 최신 버전)

# 💬 리뷰 중점사항

1. `LocalTime.now()`를 mocking하기 위해 Clock을 사용했습니다. 이로 인해 비즈니스 로직이 못생겨졌는데 이에 대해 의견 부탁드립니다.
    - ex) `LocalTime.now()` -> `LocalTime.now(clock)`
2. mocking이 안되는 오류가 확인되어 조치하여 해결한 상태인데, 그 방법이 적절한지 모르겠습니다.
    - 에러 상황: 테스트 클래스를 하나만 실행할 때는 정상적으로 동작. 여러 클래스를 한 번에 실행하면 에러 발생(github action 포함)
    - 에러 원인: org.mockito.exceptions.misusing.UnfinishedStubbingException
        - mocking되지 않은 객체 사용
        - 작성한 `when().thenReturn()`문이 동작하지 않음
    - 예측한 근본적인 원인: `BusApiTest` 클래스에서 모킹 객체의 선언 및 초기화가 정상적으로 이루어지지 못함
    - 해결한 방법: mocking되는 객체를 자식 클래스(`BusApiTest`)가 아닌 부모 클래스(`AcceptanceTest`)에서 선언
        - 초기화는 기존과 같이 자식 클래스 메서드에서 진행

## 참고사항
셔틀, 등하교 버스는 버전 최신화가 BATCH 젠킨스 동작 시 이루어지기 때문에 조회 로직의 코드 상에서는 버전 최신화가 이루어지지 않습니다.
(이후에 올릴 시내버스 API는 OPEN API를 사용하기 때문에 조회 시 버전 최신화가 이루어집니다.)

## 기타 변경사항
IllegalArgumentException이 반환될 경우 응답 결과를 수정하였습니다. 기존에 UserService만 사용중이었고, 실제 코인 응답과 비교했을 때 수정하는 방향이 적절하다고 판단했습니다. (이번 API에서 IllegalArgumentException을 반환하려고 했으나 응답 형태가 코인과 일치하지 않아 수정했습니다.)

2024-03-06 09:30 UTC, songsunkook commented on src/test/java/in/koreatech/koin/AcceptanceTest.java
> +            DockerImageName.parse("mongo:7.0"))
<img src="https://github.com/BCSDLab/KOIN_API_V2/assets/21010656/e4e93da9-fe1c-4f04-bd4c-0446741a9403" width=240px>

2024-03-06 09:30 UTC, songsunkook commented on src/test/java/in/koreatech/koin/acceptance/BusApiTest.java
> +        when(clock.getZone()).thenReturn(Clock.systemDefaultZone().getZone());
트러블슈팅 도와주셔서 감사합니다 ㅠㅠ

2024-03-07 00:30 UTC, Choi-JJunho requested changes
고생했어~! enum 부분에서 아주 쬐~ 끔 바꾸면 좋겠는 부분 있어서 한번만 봐줘~

2024-03-07 00:30 UTC, Choi-JJunho commented on src/main/java/in/koreatech/koin/domain/bus/model/BusCourse.java
> +    public BusCourse(String busType, String region, String direction, List<Route> routes) {
### A
builder만 사용하도록 제어하게 접근제어자를 private으로 두는거 어때요

2024-03-07 00:30 UTC, Choi-JJunho commented on src/main/java/in/koreatech/koin/domain/bus/model/BusStation.java
> +    private final String name;
### C
name이라는 네이밍은 enum에서 기본적으로 사용하고 있는 이름이네요~
BusStation.name()
BusStation.getName()
두개가 생길텐데 좀 헷갈릴 수도 있겠죠?

2024-03-07 00:30 UTC, Choi-JJunho commented on src/main/java/in/koreatech/koin/domain/bus/model/BusStation.java
> +    }
### R

위에서 이야기한 것 처럼 name이라는 이름은 이미 enum에 선언되어있어요~
클라이언트에서 보내준 값을을 대소문자 상관없이 비교하면 굳이 같은값을 두번 선언할 필요가 없겠죠 (name, 기존 Enum name)

```suggestion
    public static BusStation from(String busStationName) {
        return Arrays.stream(values())
            .filter(busStation -> busStation.name.equalsIgnoreCase(busStationName))
            .findAny()
            .orElseThrow(() -> BusStationNotFoundException.withDetail("busStation: " + busStationName));
    }
```

2024-03-07 00:30 UTC, Choi-JJunho commented on src/main/java/in/koreatech/koin/domain/bus/model/BusType.java
> +    }
### R
> 위에서 이야기한 것 처럼 name이라는 이름은 이미 enum에 선언되어있어요~
클라이언트에서 보내준 값을을 대소문자 상관없이 비교하면 굳이 같은값을 두번 선언할 필요가 없겠죠 (name, 기존 Enum name)

ditto

```suggestion
    public static BusType from(String busTypeName) {
        return Arrays.stream(values())
            .filter(busType -> busType.name.equalsIgnoreCase(busTypeName))
            .findAny()
            .orElseThrow(() -> BusStationNotFoundException.withDetail("busType: " + busTypeName));
    }
```

2024-03-07 00:30 UTC, Choi-JJunho commented on src/main/java/in/koreatech/koin/domain/bus/model/Route.java
> +    public Route(String routeName, List<String> runningDays, List<ArrivalNode> arrivalInfos) {
### C

이친구도 private하는거 어떤가요~?
만약 생성자가 하나 뿐이라서 리플렉션 대상이 안되어 문제가 생긴다면 protected로라도 선언해주면 좋을 것 같아요~

2024-03-07 00:30 UTC, Choi-JJunho commented on src/main/java/in/koreatech/koin/domain/bus/model/Route.java
> +public class Route {
### A

just 궁금증인데 얘는 record로 선언하면 동작 안하나?

2024-03-07 00:30 UTC, Choi-JJunho commented on src/main/java/in/koreatech/koin/domain/bus/controller/BusController.java
> +        @RequestParam String arrival
enum에 선언해둔 정적 팩토리 메소드로 선언해둔 string -> enum의 파싱 로직에다가 `@JsonCreator` 달아두면 여기에 Enum을 선언해서 바로 사용할 수 있을거같은데 한번 수정해보겠어요?
```suggestion
        @RequestParam(value = "bus_type") BusType busType,
        @RequestParam BusStation depart,
        @RequestParam BusStation arrival
```
잘 모르겠으면 INTERNAL 코드 한번 참고해보세용 (잘 모르겠으면 다희한테도 물어보세유 저번에 알려줬었는데)

2024-03-07 01:18 UTC, songsunkook commented on src/main/java/in/koreatech/koin/domain/bus/model/BusStation.java
> +    }
ignoreCase는 생각지도 못했네요..  👍

2024-03-07 05:09 UTC, songsunkook commented on src/main/java/in/koreatech/koin/domain/bus/model/Route.java
> +public class Route {
Route 자체는 잘 되는 것 같은데 내부의 ArrivalNode의 필드들이 null 초기화 되네요..
MongoDB이지만 엔티티 클래스인만큼 record를 사용하는 것은 많이 불안정해보입니다.

2024-03-08 02:43 UTC, songsunkook commented on src/main/java/in/koreatech/koin/domain/bus/controller/BusController.java
> +        @RequestParam String arrival
이런 기능이 있는 줄 몰랐네요..!! 정말 좋은 것 같습니다. 👍

다만 적용하는 과정에서 몇 가지 이슈가 발생했습니다.
1. `@RequestParam`을 사용하면 enum 매핑에 `@JsonCreator`를 활용할 수 없습니다.
    - 매핑 자체는 가능했습니다. 다만 `@JsonCreator`를 통해 생성 로직을 제어하기 위해서는 `@RequestBody`를 사용해야만 합니다.
    - `@RequestParam` 사용 시 `valueOf()`메서드를 사용하기에 로직을 임의로 수정할 수 없습니다.
    - 현재 enum 요소들의 네이밍은 UPPER_CASE로 통일되어 있는데, API 요청에 대해서도 대문자로 받아야 합니다.
        - 기존에는 소문자로 받았기에 하위호환성이 우려됩니다. (대문자로 안받으면 에러 발생)
2. `@RequestBody`로 변경하면 API 요청 구조가 달라집니다.
    - 기존에는 파라미터로 받던 것을 body로 받으니 하위호환성 이슈가 발생합니다.
3. `@RequestBody`로 변경하면 POST(PUT) 요청으로 변경해야 합니다.
    - 당연히 하위호환성 이슈가 발생합니다. (기존: GET)
    - 단순 조회 요청을 POST로 받는 것이 적절한지 의심됩니다.

결론을 내리자면 저는 개인적으로 이번 API에서 제안해주신 기능을 사용하지 않는 것이 적절하다고 생각합니다.
선배님의 의견은 어떤지 궁금합니다.

+) 혹시 내용 중에 잘못된 부분이 있다면 말씀해주시면 감사하겠습니다.

2024-03-08 02:45 UTC, Choi-JJunho commented on src/main/java/in/koreatech/koin/domain/bus/controller/BusController.java
> +        @RequestParam String arrival
오~! RequsetParam의 경우 valueof() 메소드를 사용하는군요
확실히 말한대로 이번 경우는 사용하지 않는 편이 좋은 것 같아요
알아보고 정리해줘서 고맙습니다 👍

2024-03-08 03:10 UTC, songsunkook commented on src/main/java/in/koreatech/koin/domain/bus/controller/BusController.java
> +        @RequestParam String arrival
아시는 내용일 수도 있지만 간단하게 언급만 하겠습니다

Converter를 사용하면 `@RequestParam`을 유지하면서 자동으로 임의의 로직을 통해 형변환을 진행할 수 있습니다.
기존 코인에서 컨버터를 사용한 사례가 있었는데, 스프링 부트에서는 훨씬 쉽게 구현이 가능해서 마음에 들었습니다.
다만 enum은 covertor을 implement하는 것이 불가능하다 보니 Converter 클래스를 새로 작성해야 합니다.
결국 계층 하나가 더 생기는 것이기에 오히려 더 불편해질 수 있겠다는 생각이 듭니다.
지금은 이대로 유지하겠습니다.

참고) https://github.com/BCSDLab/KOIN_API/pull/297

2024-03-12 03:31 UTC, songsunkook commented on src/main/java/in/koreatech/koin/domain/bus/exception/BusStationNotFoundException.java
> +public class BusStationNotFoundException extends DataNotFoundException {
`BusStation.java`에서 사용중입니다!

2024-03-12 03:31 UTC, songsunkook commented on src/main/java/in/koreatech/koin/domain/bus/exception/BusTypeNotFoundException.java
> +public class BusTypeNotFoundException extends DataNotFoundException {
`BusType.java`에서 사용하려고 작성했는데 다른 예외를 쓰고 있었네요.
수정하겠습니다. 감사합니다~

2024-03-12 03:35 UTC, songsunkook commented
## 기타 변경사항
IllegalArgumentException이 반환될 경우 응답 결과를 수정하였습니다. 기존에 UserService만 사용중이었고, 실제 코인 응답과 비교했을 때 수정하는 방향이 적절하다고 판단했습니다.

2024-03-12 13:33 UTC, Choi-JJunho approved these changes
진짜 고생했습니다
100만년짜리 PR...

2024-03-13 06:15 UTC, daheeParkk approved these changes

2024-03-13 06:16 UTC, merged