feat: 닉네임 중복 체크
BCSDLab/KOIN_API_V2 pull request #189
Opened 2024-03-09 03:56 UTC by kwoo28

# 🔥 연관 이슈

- close #18 

# 🚀 작업 내용

1. 회원 탈퇴 반환 타입을 수정합니다.
2. 데이터가 중복될때 예외를 발생시킬 수 있는 전역예외를 추가합니다.
- 409상태코드와 함께 ErrorResponse객체의 형태로 {"code" : 0, "message" : "이미 존재하는 데이터입니다."}를 반환합니다.
3. 닉네임 중복을 체크합니다.

# 💬 리뷰 중점사항

데이터가 중복됐을때에 대한 마땅한 예외처리가 기존 로직에서 보이지않아, 따로 전역 커스텀예외를 적용했습니다.
하지만 이렇게 구현한다면 이미 다른 사람이 비슷한 데이터 중복 로직을 구현중이라면, merge충돌이 일어나거나 일관성이 부족한 코드가 될것같아, 해당 구현에 대해 올바른 예외처리 방식이 무엇일지 고민해야할 것 같습니다.

2024-03-10 16:32 UTC, Choi-JJunho requested changes
1등 PR~🥇
첫 PR을 굉장히 빠르게 올려주셨네요
몇가지 코멘트 남겼으니 리뷰 확인 부탁드릴게요

2024-03-10 16:32 UTC, Choi-JJunho commented on src/test/java/in/koreatech/koin/acceptance/UserApiTest.java
> +    void checkDuplicationOfNickname(){
### C

닉네임 중복이 아닌 경우도 테스트 추가해주세요~!

2024-03-10 16:32 UTC, Choi-JJunho commented on src/main/java/in/koreatech/koin/domain/user/service/UserService.java
> +        }
### A

try-catch 문도 괜찮은데 Optional을 활용하는건 어떨까요?
getBy를 사용한다면 UserNotFoundException을 한번 더 처리해야하는 로직의 복잡성이 생기는 것 같네요

```suggestion
        userRepository.findByNickname(nickname).ifPresent(user -> {
            throw AlreadyExistNicknameException.withDetail("nickname: " + nickname);
        });
```

2024-03-10 16:32 UTC, Choi-JJunho commented on src/main/java/in/koreatech/koin/global/exception/AlreadyExistDataException.java
> +public class AlreadyExistDataException extends RuntimeException{
### R

라인 포맷팅 한번 해주세요
```suggestion
public class AlreadyExistDataException extends RuntimeException {
```

2024-03-10 16:32 UTC, Choi-JJunho commented on src/main/java/in/koreatech/koin/domain/user/controller/UserController.java
> +        @RequestParam("nickname") String nickname) {
### R

validation을 활용하면 아래 검증을 어노테이션으로 대체할 수도 있습니다.

```suggestion
        @Valid @NotBlank @Size(max=10) 
        @RequestParam("nickname") String nickname) {
```

2024-03-11 00:01 UTC, songsunkook approved these changes
첫 PR인데도 잘 작성해주셨네요!
기존 구조를 이해하는 것이 힘들었을텐데 고생하셨습니다~
PR이 머지되기 전이어도 리뷰를 기다리는 상황이라면 바로 다음 작업을 해도 좋을 것 같습니다

2024-03-11 06:20 UTC, 20HyeonsuLee reviewed
코드 작성하시느라 고생하셨습니다! 전반적으로 깔끔하게 작성해주셨네요.
코드를 보다가 예외처리하신부분에 대해서 궁금한점에 대해서 코멘트 남겼습니다!

2024-03-11 06:20 UTC, 20HyeonsuLee commented on src/main/java/in/koreatech/koin/domain/user/controller/UserApi.java
> +    @ApiResponses(
# A
스웨거에 200, 401, 403, 404, 409, 422에 대한 응답코드들이 있던데  이렇게 그것에 대한 내용도 혹시 추가된건가요??

2024-03-11 06:20 UTC, 20HyeonsuLee commented on src/main/java/in/koreatech/koin/domain/user/controller/UserController.java
> +        if (nickname.length() > 10) {
# A
스웨거를 확인해보니 422상태코드를 반환하는거로 되어있는데 IllegalArgumentException로 처리한 이유가 궁금합니다

2024-03-11 07:07 UTC, kwoo28 commented on src/main/java/in/koreatech/koin/domain/user/controller/UserApi.java
> +    @ApiResponses(
닉네임 중복 체크같은경우 중복이 아닐땐 200을 반환하고, 중복일시 409를 반환한다라고만 나와있어서 200과 409에 대한 반환만 처리했습니다.

2024-03-11 07:08 UTC, kwoo28 commented on src/main/java/in/koreatech/koin/domain/user/controller/UserController.java
> +        if (nickname.length() > 10) {
제약조건 위반할땐 422를 반환하게 되어있는데, 400으로 반환하게 했었네요. 수정해야겠네요.. 감사합니다.

2024-03-11 07:14 UTC, kwoo28 commented on src/main/java/in/koreatech/koin/domain/user/controller/UserApi.java
> +    @ApiResponses(
401, 403, 404에 대한 응답이 나올 경우가 없어서 추가 안했는데, 한번 더 점검해보겠습니다.

2024-03-11 07:15 UTC, kwoo28 commented on src/test/java/in/koreatech/koin/acceptance/UserApiTest.java
> +    @DisplayName("닉네임 중복 체크")
확실히 그렇게 적는게 테스트 의도가 잘보이겠군요!

2024-03-11 07:16 UTC, kwoo28 commented on src/test/java/in/koreatech/koin/acceptance/UserApiTest.java
> +            .get("/user/check/nickname?nickname=주노")
오타 날 이유도없고, 그게 더 명확하겠군요. 감사합니다

2024-03-11 07:17 UTC, kwoo28 commented on src/main/java/in/koreatech/koin/global/exception/AlreadyExistDataException.java
> +public class AlreadyExistDataException extends RuntimeException{
헉 알겠씁니다!

2024-03-11 07:20 UTC, kwoo28 commented on src/main/java/in/koreatech/koin/domain/user/service/UserService.java
> +        }
저도 이부분에 대해서 어덯게 처리해야할지 애매했는데, 알려주신 훨씬 좋은 코드방식이 있었군요. 수정해보겠습니다.! 감사합니다.

2024-03-11 07:22 UTC, kwoo28 commented on src/main/java/in/koreatech/koin/domain/user/controller/UserController.java
> +        @RequestParam("nickname") String nickname) {
근데 혹시 그렇게하면 현재 GlobalExceptionHandler에 있는 handleMethodArgumentNotValidException 메서드에 필터링돼서 422가 반환되어야하는데, 400으로 반환되지 않을까요??

2024-03-11 08:09 UTC, 20HyeonsuLee approved these changes

2024-03-14 01:43 UTC, Choi-JJunho requested changes
고생하셨습니다~
마지막으로 코멘트 확인해주세요~!
반영 확인하고 approve 하겠습니다

2024-03-14 01:43 UTC, Choi-JJunho commented on src/main/java/in/koreatech/koin/domain/user/dto/NicknameCheckExistsRequest.java
> +}
### R
<img width="539" alt="image" src="https://github.com/BCSDLab/KOIN_API_V2/assets/49794401/f04a13ff-6877-4828-bdad-e8ab0ce3743e">

마지막줄 개행 관련해서 설정 부탁드려요~

> 참고자료: https://velog.io/@junho5336/No-newline-at-end-of-file

2024-03-14 01:43 UTC, Choi-JJunho commented on src/test/java/in/koreatech/koin/acceptance/UserApiTest.java
> +            .get("/user/check/nickname?nickname=" + "철".repeat(11))
### A
String.repeat 굿~!

아래처럼 파라미터를 분리해보는건 어떤가요?
```suggestion
            .get("/user/check/nickname)
            .param("nickname", "철".repeat(11))
```

참고 코멘트
- https://github.com/BCSDLab/KOIN_API_V2/pull/192#discussion_r1522549885

2024-03-14 05:10 UTC, kwoo28 commented on src/main/java/in/koreatech/koin/domain/user/dto/NicknameCheckExistsRequest.java
> +}
넵!

2024-03-15 08:42 UTC, Choi-JJunho approved these changes

2024-03-15 08:42 UTC, merged