feat : 강의 목록 조회(학기별)
BCSDLab/KOIN_API_V2 pull request #192
Opened 2024-03-11 15:00 UTC by dradnats1012

# 🔥 연관 이슈

# 주요 변경사항
1. timetable 관련 패키지 추가
2. Lecture Entity 생성

# 🚀 작업 내용

1. 쿼리를 통해서 필요한 학기를 받습니다.
4. DB에서 해당하는 학기의 강의 목록을 불러옵니다.
- 존재하지 않는 학기를 요청하면 에러처리

# 💬 리뷰 중점사항
- 첫 PR이다보니 잘못된 부분이 있을 것 같습니다. 이상한 부분이 조금이라도 있으면 바로 리뷰 남겨주세요!

- 테스트를 진행하는데 다른 케이스가 있을 것 같은데 더 이상은 생각나지 않아 일단 3개만 작성했습니다. 혹시 이런 경우도 있을 것 같다고 생각하시면 리뷰 부탁드립니다.

- 존재하지 않는 학기를 요청하면 오류를 보내는데 이 부분이 어색한 것 같아서 고쳐야할 것 같으면 리뷰 부탁드립니다

2024-03-11 15:41 UTC, Choi-JJunho requested changes
고생하셨습니다~!
Good First PR~~
컨벤션만 꼼꼼하게 봐주시면 좋을 것 같아요!

2024-03-11 15:41 UTC, Choi-JJunho commented on src/main/java/in/koreatech/koin/domain/timetable/repository/LectureRepository.java
> +    ArrayList<Lecture> findBySemester(String semesterDate);
### R

List로 선언해주세요~ 구현체로 선언하면 확장성이 제한적이겠죠?

2024-03-11 15:41 UTC, Choi-JJunho commented on src/main/java/in/koreatech/koin/domain/timetable/repository/LectureRepository.java
> +    Boolean existsBySemester(String semesterDate);
### R
줄바꿈도 신경써주세요~
```suggestion
public interface LectureRepository extends JpaRepository<Lecture, Long> {
    ArrayList<Lecture> findBySemester(String semesterDate);
    
    Boolean existsBySemester(String semesterDate);
```

2024-03-11 15:41 UTC, Choi-JJunho commented on src/main/java/in/koreatech/koin/domain/timetable/service/LectureService.java
> +        if(!lectureRepository.existsBySemester(semester)){
### R

메소드 첫줄은 붙여써주세요
```suggestion
    public List<LectureResponse> getLecturesBySemester(String semester) {
        if(!lectureRepository.existsBySemester(semester)){
```

2024-03-11 15:41 UTC, Choi-JJunho commented on src/main/java/in/koreatech/koin/domain/timetable/service/LectureService.java
> +            throw SemesterNotFoundException.withDetail(semester + "는 ");
### R
예외메시지 작성하다 마신거같아요~~

2024-03-11 15:41 UTC, Choi-JJunho commented on src/main/java/in/koreatech/koin/domain/timetable/service/LectureService.java
> +
### R
클래스 첫줄은 띄워써주세요
```suggestion
public class LectureService {

    private final LectureRepository lectureRepository;

```

2024-03-11 15:41 UTC, Choi-JJunho commented on src/test/java/in/koreatech/koin/acceptance/LectureApiTest.java
> +            .professor("허준기")
### A

허교수님 👍

2024-03-11 15:41 UTC, Choi-JJunho commented on src/main/java/in/koreatech/koin/domain/timetable/model/Lecture.java
> +
### R
불필요한 개행이네요

2024-03-11 15:41 UTC, Choi-JJunho commented on src/main/java/in/koreatech/koin/domain/timetable/service/LectureService.java
> +    private final LectureRepository lectureRepository;
### R
클래스 첫줄을 띄워주세요~
```suggestion
public class LectureService {

    private final LectureRepository lectureRepository;
```

2024-03-11 15:41 UTC, Choi-JJunho commented on src/main/java/in/koreatech/koin/domain/timetable/controller/LectureController.java
> +    public ResponseEntity<List<LectureResponse>> getLectureList(@RequestParam(name = "semester_date") String semester) {
### C

개행을 해주면 조금 더 읽기 수월할 것 같아요
```suggestion
    public ResponseEntity<List<LectureResponse>> getLectureList(
        @RequestParam(name = "semester_date") String semester
    ) {
```

2024-03-11 15:41 UTC, Choi-JJunho commented on src/test/java/in/koreatech/koin/acceptance/LectureApiTest.java
> +        Lecture request1 = Lecture.builder()
### A
request말고 lecture1, lecture2는 어떤가요?
개인적으로 request라는 변수명은 API의 request값이라고는 생각이 드네요

2024-03-11 16:07 UTC, dradnats1012 commented on src/main/java/in/koreatech/koin/domain/timetable/service/LectureService.java
> +            throw SemesterNotFoundException.withDetail(semester + "는 ");
문장으로 만들려고 이렇게 구성하게 됐는데 그냥 메세지랑 학기만 띄우겠습니다!

2024-03-11 16:08 UTC, dradnats1012 commented on src/test/java/in/koreatech/koin/acceptance/LectureApiTest.java
> +        Lecture request1 = Lecture.builder()
변수명 수정하겠습니다!

2024-03-12 00:14 UTC, Choi-JJunho requested changes
고생하셨습니다
몇가지 누락된 내용이 있어서 확인해주세요~

2024-03-12 00:14 UTC, Choi-JJunho commented on src/main/java/in/koreatech/koin/domain/timetable/repository/LectureRepository.java
> +public interface LectureRepository extends JpaRepository<Lecture, Long> {
### R

저희 Repository를 사용하는게 컨벤션입니다~!

```suggestion
public interface LectureRepository extends Repository<Lecture, Long> {
```

2024-03-12 00:14 UTC, Choi-JJunho commented on src/main/java/in/koreatech/koin/domain/timetable/service/LectureService.java
> +    private final LectureRepository lectureRepository;
여기 반영이 안된거같네요~

2024-03-12 00:14 UTC, Choi-JJunho commented on src/main/java/in/koreatech/koin/domain/timetable/service/LectureService.java
> +        return lectures.stream()
### C

여기는 굳이 안띄워도 될거같아요
```suggestion
        List<Lecture> lectures = lectureRepository.findBySemester(semester);
        if (lectures.isEmpty()) {
            throw SemesterNotFoundException.withDetail(semester);
        }
        return lectures.stream()
```

2024-03-12 00:14 UTC, Choi-JJunho commented on src/test/java/in/koreatech/koin/acceptance/LectureApiTest.java
> +        Lecture request1 = Lecture.builder()
여기도 반영이 안된거같아요~

2024-03-12 00:32 UTC, songsunkook requested changes
첫 PR 고생하셨습니다! 코드가 너무 깔끔하게 잘되어있네요..!!
몇 가지 수정이 필요해 보이는 부분 코멘트 남겨드렸으니 확인 부탁드립니다!

2024-03-12 00:32 UTC, songsunkook commented on src/main/java/in/koreatech/koin/domain/timetable/controller/LectureApi.java
> +@Tag(name = "(Normal) Lecture: 강의", description = "강의 정보를 관리한다")
### R
강의 대신 시간표는 어떨까요??

2024-03-12 00:32 UTC, songsunkook commented on src/main/java/in/koreatech/koin/domain/timetable/dto/LectureResponse.java
> +    String classTime
### R
기존 코인에서는 해당 내용을 문자열이 아니라 리스트로 반환하는데 수정이 필요할 것 같습니다!

2024-03-12 00:32 UTC, songsunkook commented on src/main/java/in/koreatech/koin/domain/timetable/dto/LectureResponse.java
> +@JsonNaming(value = SnakeCaseStrategy.class)
### A
static import 👍

2024-03-12 01:45 UTC, dradnats1012 commented on src/main/java/in/koreatech/koin/domain/timetable/repository/LectureRepository.java
> +public interface LectureRepository extends JpaRepository<Lecture, Long> {
변경하겠습니다!

2024-03-12 01:51 UTC, dradnats1012 commented on src/main/java/in/koreatech/koin/domain/timetable/controller/LectureApi.java
> +@Tag(name = "(Normal) Lecture: 강의", description = "강의 정보를 관리한다")
db에 `timetables`라는 테이블이 있어서 강의라고 했는데 그러면 `timetables`는 어떤 테이블인지 궁금합니다

2024-03-12 01:52 UTC, dradnats1012 commented on src/main/java/in/koreatech/koin/domain/timetable/dto/LectureResponse.java
> +    String classTime
확인해보겠습니다!

2024-03-12 03:20 UTC, dradnats1012 commented on src/main/java/in/koreatech/koin/domain/timetable/controller/LectureApi.java
> +@Tag(name = "(Normal) Lecture: 강의", description = "강의 정보를 관리한다")
`timetables`는 `users` 테이블과 연관이 되어있어서 말 그대로 해당 사용자의 시간표를 나타내는 것 같고
`lectures`는 연관 관계 없이 있는 걸로 보아 말 그대로 모든 강의를 저장해 놓은 것 같아서 `강의`로 하려고 하는데 의견이 궁금합니다!

2024-03-12 13:34 UTC, songsunkook requested changes
피드백 잘 반영해주셨네요!
마지막으로 네이밍 관련해서 코멘트 남겨드렸으니 조금만 더 확인 부탁드립니다..!!

2024-03-12 13:34 UTC, songsunkook commented on src/main/java/in/koreatech/koin/domain/timetable/controller/TimeTableApi.java
> +    ResponseEntity<List<LectureResponse>> getLectureList(
### C
네이밍에 자료형을 포함하는건 지양하는 게 좋을 것 같습니다!

2024-03-12 13:34 UTC, songsunkook commented on src/main/java/in/koreatech/koin/domain/timetable/controller/TimeTableController.java
> +public class TimeTableController implements TimeTableApi {
### C
정말 별거 아닌 내용이지만..
TimeTable은 시간표라는 뜻의 `timetable`인데, 카멜 케이스가 잘못 적용된 것 같습니다. `TimetableController`가 더 적절하지 않을까요?

2024-03-12 13:34 UTC, songsunkook commented on src/main/java/in/koreatech/koin/domain/timetable/dto/LectureResponse.java
> +            .toList();
### A
stream 👍

2024-03-12 13:34 UTC, songsunkook commented on src/test/java/in/koreatech/koin/acceptance/TimeTableApiTest.java
### A
테스트가 살벌하네요.... ㅋㅋㅋㅋ 
👍

2024-03-13 05:37 UTC, songsunkook approved these changes
고생하셨습니다!! 😄

2024-03-13 05:37 UTC, songsunkook commented on src/test/java/in/koreatech/koin/acceptance/TimetableApiTest.java
> +            .get("/lectures?semester_date=20192")
### A
```suggestion
            .param("semester_date", lecture1.getSemester())
            .get("/lectures")
```
이렇게 바꿔보는 건 어떨까요??

2024-03-13 05:37 UTC, dradnats1012 commented on src/main/java/in/koreatech/koin/domain/timetable/controller/TimeTableApi.java
> +    ResponseEntity<List<LectureResponse>> getLectureList(
지우겠습니다!

2024-03-13 05:39 UTC, Choi-JJunho approved these changes
고생하셨습니다 👍

2024-03-13 05:40 UTC, dradnats1012 commented on src/test/java/in/koreatech/koin/acceptance/TimetableApiTest.java
> +            .get("/lectures?semester_date=20192")
이렇게 하면 좀 더 깔끔한 것 같네요
바꿔보겠습니다!

2024-03-13 05:41 UTC, songsunkook commented
추가 작업 완료되는대로 스쿼시 머지 직접 하셔도 좋을 것 같아요

2024-03-13 06:04 UTC, merged