feat : 식단 Api 구현
BCSDLab/KOIN_API_V2 pull request #193
Opened 2024-03-11 17:55 UTC by Choon0414

# 🔥 연관 이슈

- close #111 

# 🚀 작업 내용

1. 식단 Api를 구현했습니다.
2. DB에서 요청하는 날짜에 해당하는 식단을 불러옵니다.
3. 요청하는 날짜의 형식에 따른 예외처리를 합니다.
- 잘못된 형식의 날짜 400 상태코드 반환
- null 값의 경우 오늘 날짜를 입력

# 💬 리뷰 중점사항

- 잘못된 형식의 날짜를 입력 받는 경우 Not Found와는 다른 예외인 것 같아 우선 400번으로 처리했는데 Precondition Failed를 추가하는 것이 좋을지 궁금합니다.

2024-03-12 01:12 UTC, Choi-JJunho requested changes
빠른 리뷰 슬쩍 올려봅니다
코멘트 확인한번 부탁드릴게요~

2024-03-12 01:25 UTC, Choon0414 commented on src/main/java/in/koreatech/koin/domain/dining/dto/DiningResponse.java
> +        + " \"오이소박이양념무침\", \"총각김치\", \"생야채샐러드&D\", \"누룽지탕\"]")
단순히 여러 줄의 문자열을 처리하는 기능만 있는 줄 알았는데 '\' 없이 바로 사용 가능한 것은 몰랐네요. 감사합니다!

2024-03-12 01:26 UTC, Choon0414 commented on src/main/java/in/koreatech/koin/domain/dining/dto/DiningResponse.java
> +    Integer price_cash,
넵 수정하겠습니다

2024-03-12 01:30 UTC, Choon0414 commented on src/main/java/in/koreatech/koin/domain/dining/service/DiningService.java
> +        }
수정하겠습니다.
라인 포맷팅 하는 습관 빨리 들일게요!

2024-03-12 01:32 UTC, Choon0414 commented on src/main/java/in/koreatech/koin/domain/dining/service/DiningService.java
> +    public List<DiningResponse> getDinings(String from) {
적는 내내 받아와서 변환할 생각만 하고 처음부터 LocalDate로 받을 생각은 못했네요. 참고해서 수정하겠습니다!

2024-03-12 13:22 UTC, songsunkook requested changes
첫 PR 고생하셨습니다! 👍  잘 작성해주신 것 같아요!
몇 가지 코멘트 남겨드렸으니 확인 부탁드립니다~

2024-03-12 14:08 UTC, Choon0414 commented on src/main/java/in/koreatech/koin/domain/dining/dto/DiningResponse.java
> +    String menu
생각만하고 깜빡했네요 수정하겠습니다!

2024-03-12 14:08 UTC, Choon0414 commented on src/main/java/in/koreatech/koin/domain/dining/dto/DiningResponse.java
> +@JsonNaming(value = PropertyNamingStrategies.SnakeCaseStrategy.class)
넵 수정하겠습니다!

2024-03-12 14:08 UTC, Choon0414 commented on src/main/java/in/koreatech/koin/global/exception/GlobalExceptionHandler.java
> +    }
좀 더 공부해보고 수정하겠습니다!

2024-03-14 17:58 UTC, seongjae6751 requested changes
이것만 하고 리뷰 해야지 하고 계속 미루다가 이제야 리뷰를 남기네요..ㅠ
늦게 남겨서 죄송합니다
지금 updated_at에 대한 정보가 누락 되어 있는 것 같은데 체크 한번 해주시면 감사하겠습니다. 고생 많으셨습니다..!

2024-03-14 17:58 UTC, seongjae6751 commented on src/main/java/in/koreatech/koin/domain/dining/model/Dining.java
> +public class Dining {
R
swagger로 응답 값을 보니까 updated_at 정보가 있던데 여기도 역시 BaseEntity를 상속 받아서 정보를 가져가야 할 것 같아요..!

2024-03-14 17:58 UTC, seongjae6751 commented on src/main/java/in/koreatech/koin/domain/dining/dto/DiningResponse.java
R
여기도 역시 updated_at의 정보가 없는 것 같네요..!

2024-03-16 16:47 UTC, Choon0414 commented on src/main/java/in/koreatech/koin/domain/dining/dto/DiningResponse.java
지적 감사합니다! created_at, updated_at 추가했습니다.

2024-03-17 07:14 UTC, songsunkook requested changes
수정이 필요한 부분들에 대해 코멘트 남겨드렸습니다.
하다가 모르는 부분이 있다면 부담없이 말씀해주세요!
캠퍼스 팀 영양사 페이지 구현을 위해서는 이번 작업이 선행되어야 하기 때문에 어느 정도 우선순위를 높게 두고 작업해주시면 감사하겠습니다!

2024-03-17 14:00 UTC, Choon0414 commented on src/main/java/in/koreatech/koin/domain/dining/model/Dining.java
> +    private Integer kcal;
가격이랑 칼로리는 수의 범위가 크지 않을 것 같아 Integer로 남겨두었습니다!

2024-03-18 05:06 UTC, seongjae6751 approved these changes

2024-03-18 10:51 UTC, Choon0414 commented on src/main/java/in/koreatech/koin/domain/dining/exception/InvalidFormatException.java
넵 삭제했습니다!

2024-03-18 11:05 UTC, Choon0414 commented on src/main/java/in/koreatech/koin/domain/dining/model/Dining.java
> +@JsonNaming(SnakeCaseStrategy.class)
@JsonNaming의 용도를 단순히 통일성을 위한 것으로 혼동했습니다. 수정했습니다!

2024-03-19 07:17 UTC, Choi-JJunho approved these changes
간단한 컨벤션 외에는 잘 반영해주셨네요~
2개만 확인해주세용

2024-03-19 07:17 UTC, Choi-JJunho commented on src/test/java/in/koreatech/koin/acceptance/DiningApiTest.java
> +public class DiningApiTest extends AcceptanceTest {
반영이 안된거같네요~

2024-03-19 07:17 UTC, Choi-JJunho commented on src/test/java/in/koreatech/koin/acceptance/DiningApiTest.java
> +
> 반영이 안된거같네요~

이것두

2024-03-19 08:13 UTC, Choi-JJunho approved these changes
굿~ 고생하셨습니다

2024-03-19 08:13 UTC, Choi-JJunho commented on build.gradle
> -    implementation 'com.mysql:mysql-connector-j'
### A

뭔가 했는데 중복 선언이였군요 👍

2024-03-19 08:17 UTC, songsunkook approved these changes
고생하셨습니다!

2024-03-19 08:17 UTC, songsunkook commented on src/test/java/in/koreatech/koin/acceptance/DiningApiTest.java
> +        when(clock.getZone()).thenReturn(Clock.systemDefaultZone().getZone());
👍

2024-03-19 08:18 UTC, merged