feat: 이메일 중복 체크
BCSDLab/KOIN_API_V2 pull request #194
Opened 2024-03-12 02:48 UTC by ImTotem

# 🔥 연관 이슈

- close #17 

# 🚀 작업 내용

1. 이메일의 중복을 체크합니다.
    - 중복이면 422 반환
    - 잘못된 입력이면 400 반환

# 💬 리뷰 중점사항
1. 파라미터가 `email`이 아닌 `address`인 이유가 있나요?

2024-03-12 02:55 UTC, Choi-JJunho requested changes
깔끔하게 잘 작성해주셨네요~! 굿굿~!
코멘트 확인하여 테스트 두개만 더 추가해주세요~~
테스트 추가 확인하고 Approve 하겠습니다

> 파라미터가 email이 아닌 address인 이유가 있나요?

무차별적인 레거시의 잔해입니다.. ㅋㅋㅋㅋ
클라이언트가 이미 저거로 개발해버려서 마이그레이션하는 저희 입장에서는 맞춰줘야하죵..

2024-03-12 02:55 UTC, Choi-JJunho commented on src/main/java/in/koreatech/koin/domain/user/controller/UserController.java
> +        @NotBlank(message = "이메일을 입력해주세요.")
### C
이거 동작하나요?
테스트에 이메일 형식이 잘못된 경우, 이메일을 보내지 않은 경우를 추가해보시겠어요~?

> 만약 동작하지 않는다면 `@Valid` 어노테이션을 함께 선언해보세요

2024-03-12 03:10 UTC, ImTotem commented on src/main/java/in/koreatech/koin/domain/user/controller/UserController.java
> +        @NotBlank(message = "이메일을 입력해주세요.")
아앗
`@Valid` 어노테이션을 함께 선언해도 200을 반환하네요 ㅠㅠ

2024-03-12 03:33 UTC, Choi-JJunho commented on src/main/java/in/koreatech/koin/domain/user/controller/UserController.java
> +        @NotBlank(message = "이메일을 입력해주세요.")
그러면 메소드 레벨에 `@Validated` 달아보시죵

2024-03-12 15:04 UTC, kwoo28 approved these changes
수고하셨습니다. 저랑 겹치는 로직이여서, 궁금한점이 생겨 리뷰 남겨봅니다!

2024-03-12 15:04 UTC, kwoo28 commented on src/main/java/in/koreatech/koin/domain/user/service/UserService.java
> +            throw DuplicationEmailException.withDetail("email: " + email);
###A

혹시 DuplicationEmailException에 대한 예외처리를 추가하신건가요?? 추가된 커밋에 해당 파일이 안보이네요.. 그리고 서로 중복데이터 로직이 비슷한데, 예외처리 방식을 다르게하면 Merge후에 번잡해질것같아서 맞추는것도 좋을것같아요. !

2024-03-12 15:25 UTC, ImTotem commented on src/main/java/in/koreatech/koin/domain/user/service/UserService.java
> +            throw DuplicationEmailException.withDetail("email: " + email);
기존에 `global.domain.email.exception.DuplicationEmailException`이 존재합니다. 이를 이용해서 작성했습니다.
`DuplicationEmailException`이 `DuplicationException`을 상속받아서 구현되어있고, `GlobalExceptionHandler`에서 `DuplicationException`을 처리하고 있어서 `DuplicationException`을 상속받아서 작성하는것도 좋은 방법인 것 같아요!

2024-03-12 15:36 UTC, kwoo28 commented on src/main/java/in/koreatech/koin/domain/user/service/UserService.java
> +            throw DuplicationEmailException.withDetail("email: " + email);
아... #184 만들어 두셧는데, 제가 최신코드로 업데이트를 안해서 못봤네요...ㅋㅋ 감사합니다.

2024-03-13 05:25 UTC, ImTotem commented on src/main/java/in/koreatech/koin/domain/user/controller/UserApi.java
> +            @ApiResponse(responseCode = "409", content = @Content(schema = @Schema(hidden = true)))
추가했습니다!

2024-03-13 05:29 UTC, Choi-JJunho approved these changes
굿굿 고생하셨습니다 라인 포맷팅 한번만 확인해주세요~

2024-03-13 05:29 UTC, Choi-JJunho commented on src/main/java/in/koreatech/koin/domain/user/service/UserService.java
> +        userRepository.findByEmail(request.email()).ifPresent( user -> {
### C
라인 포맷팅 하면 이친구가 조금 더 친해질 수 있을거같은데~ 확인해주시겠어요?
```suggestion
        userRepository.findByEmail(request.email()).ifPresent(user -> {
```

2024-03-13 05:44 UTC, dradnats1012 commented
고생하셨습니다!

2024-03-13 05:51 UTC, ImTotem commented on src/main/java/in/koreatech/koin/domain/user/service/UserService.java
> +        userRepository.findByEmail(request.email()).ifPresent( user -> {
수정했습니다~

2024-03-13 05:59 UTC, dradnats1012 approved these changes
고생하셨습니다!

2024-03-13 06:00 UTC, merged