feat : 학기 조회(전학기)
BCSDLab/KOIN_API_V2 pull request #196
Opened 2024-03-13 06:08 UTC by duehee

# 🔥 연관 이슈

- close #30

# 주요 변경사항

1. TimeTable 패키지 생성 후 get-Semester API 추가

# 🚀 작업 내용

1. DB에 저장된 학기에 대한 모든 정보를 가져옵니다.

# 💬 리뷰 중점사항

1. 아마 준기님이 작성하신 내용과 같은 패키지를 사용하여 충돌이 일어날 수 있을 것 같습니다.
-> 기존 코인에서 사용하던 패키지와 같은 곳에 존재하여 일단 생성하여 진행하였습니다.

3. 테스트에서, "생성된 객체의 예상 순서가 실제 순서와 같지 않으면?" 이라는 의견을 받았는데, 
    이에 대해 어떻게 하면 좋을지에 대해 의견 부탁드립니다.

4. 첫 PR이고, 어색한 부분이 많을 것 같습니다. 수정할 점이 있다면 말씀 많이 부탁드립니다.

2024-03-13 08:57 UTC, dradnats1012 requested changes
고생하셨습니다!

2024-03-13 08:57 UTC, dradnats1012 commented on src/main/java/in/koreatech/koin/domain/TimeTable/controller/SemesterApi.java
## R

`TimetableApi` 에 넣는 게 좋을 것 같아요

2024-03-13 08:57 UTC, dradnats1012 commented on src/main/java/in/koreatech/koin/domain/TimeTable/controller/SemesterController.java
## R

이것도 `TimetableController`에 넣는 게 좋을 것 같아요!

2024-03-13 08:57 UTC, dradnats1012 commented on src/main/java/in/koreatech/koin/domain/TimeTable/controller/SemesterApi.java
> +
## C
불필요한 공백 같습니다!

2024-03-13 08:57 UTC, dradnats1012 commented on src/main/java/in/koreatech/koin/domain/TimeTable/repository/SemesterRepository.java
> +
## R
불필요한 공백 같습니다!

2024-03-13 13:34 UTC, ImTotem requested changes
고생하셨습니다!

2024-03-13 13:34 UTC, ImTotem commented on src/main/java/in/koreatech/koin/domain/TimeTable/controller/SemesterController.java
> +    {
### R

다른 라인처럼 포맷 맞춰줘야 할 것 같아요~!

```suggestion
    public ResponseEntity<List<SemesterResponse>> getSemesters() {
```

2024-03-13 17:03 UTC, duehee commented on src/main/java/in/koreatech/koin/domain/TimeTable/repository/SemesterRepository.java
> +
다른 Repository를 참고 했을 때, 비슷하게 작성이 된 부분이 많아서 공백을 주었습니다!

2024-03-13 17:03 UTC, duehee commented on src/main/java/in/koreatech/koin/domain/TimeTable/controller/SemesterApi.java
> +
공백 처리하도록 하겠습니다!

2024-03-13 17:03 UTC, duehee commented on src/main/java/in/koreatech/koin/domain/TimeTable/controller/SemesterApi.java
코드를 작성할 때, 기본적으로 Semester에 관하여 코드를 작성했는데, 준기님이 작성하긴 TimetableApi에 종합적으로 작성하는 것이 좋아보이네요 :D

2024-03-13 17:25 UTC, duehee commented on src/main/java/in/koreatech/koin/domain/TimeTable/controller/SemesterController.java
말씀하신 내용 반영하여 커밋 추가했습니다!!

2024-03-14 01:57 UTC, Choi-JJunho approved these changes
> 컨벤션 위주 코멘트가 많아 오프라인 리뷰 진행

고생하셨습니다~ 👍

2024-03-14 02:10 UTC, merged