feat : BCSD Lab 활동 api구현
BCSDLab/KOIN_API_V2 pull request #207
Opened 2024-03-15 03:51 UTC by seongjae6751

# 🔥 연관 이슈

- close #97 

# 🚀 작업 내용

1.BCSD Lab 활동 api를 구현했습니다.
DB에서 요청하는 연도에 해당하는 활동 내역을 가져옵니다.
DB에서 image_url을 갖고 오면 string의 형태인데 응답 값이 리스트의 형태여서 리스트로 변환하는 작업을 해줬습니다.
반환 값을 {"Activity":[ ]"}의 형태로 만들어주기 위해 map으로 감싸주는 작업을 했습니다.

# 💬 리뷰 중점사항
swagger의 응답 값을 맞추려고 db에서 값을 가져와서 데이터를 가공하는 로직이 많이 있는데(service로직) 이게 맞게 구현한 것인지 최선으로 구현한 것이 맞는 것인지 잘 모르겠습니다.. 많이 부족한 코드 리뷰 남겨주시면 더 공부하고 수정하도록 하겠습니다..! 감사합니다

2024-03-17 14:08 UTC, Choi-JJunho requested changes
고생하셨습니다~
코멘트 확인하여 수정해주세요~

2024-03-17 14:08 UTC, Choi-JJunho commented on src/main/java/in/koreatech/koin/domain/activity/repository/ActivityRepository.java
> +    List<Activity> findAllByIsDeleted(boolean bool);
### R

변수명을 bool 보다는 isDeleted라고 선언하는게 좋지 않을까요?
이름을 통해 어떤 역할을 하는지 알 수 있어야한다는 생각으로 접근해보면 좋을 것 같아요

```suggestion
    List<Activity> findAllByIsDeleted(boolean isDeleted);
```

2024-03-17 14:08 UTC, Choi-JJunho commented on src/main/java/in/koreatech/koin/domain/activity/service/ActivityService.java
> +public class ActivityService {
### R

명시적으로 Transactional(readOnly=true) 추가해주면 좋을 것 같아요

```suggestion
@Service
@Transactional(readOnly=true)
@RequiredArgsConstructor
public class ActivityService {
```

2024-03-17 14:08 UTC, Choi-JJunho commented on src/main/java/in/koreatech/koin/domain/activity/service/ActivityService.java
> +    }
### R

단순이 클라이언트에게 반환하는 결과값을 만드는 로직이 Service가 집중해야하는 부분일까요?
이런건 DTO로 만들 수는 없을까요?
아래 변환과정이 Service에서는 중요해보이지는 않아보이네요

DTO로 분리해보면 좋겠습니다

2024-03-17 14:08 UTC, Choi-JJunho commented on src/test/java/in/koreatech/koin/acceptance/ActivityApiTest.java
> +                "https://static.koreatech.in/upload/a26brbr.png")
### C
테스트 데이터는 혹시 모르니 실제 사용중인 이미지는 넣지 않아도 될 것 같아요
```suggestion
                "https://testimage.com/test.png")
```

2024-03-17 14:08 UTC, Choi-JJunho commented on src/test/java/in/koreatech/koin/acceptance/ActivityApiTest.java
> +            .get("/activities?year=2019")
### R

param으로 분리해보는건 어떨까요?

참고 코멘트
- https://github.com/BCSDLab/KOIN_API_V2/pull/192#discussion_r1522549885

2024-03-17 14:08 UTC, Choi-JJunho commented on src/test/java/in/koreatech/koin/acceptance/ActivityApiTest.java
> +            .then().log().all()
### R

log().all()은 빼주세요~
```suggestion
            .then()
```

2024-03-17 14:08 UTC, Choi-JJunho commented on src/test/java/in/koreatech/koin/acceptance/ActivityApiTest.java
> +
### R

불필요한 개행들은 제거해주세요
```suggestion
    }
```

2024-03-18 05:44 UTC, seongjae6751 commented on src/main/java/in/koreatech/koin/domain/activity/controller/ActivityController.java
> +    @Autowired
정말 간단한 부분인데 놓쳤네요ㅠ 생성자 주입 방식으로 바꿨습니다!

2024-03-18 05:45 UTC, seongjae6751 commented on src/main/java/in/koreatech/koin/domain/activity/controller/ActivityController.java
> +        return ResponseEntity.ok(activityService.getActivities(year));
가독성과 디버깅 용이성 때문에 그런 것일까요?? 수정하였습니다!

2024-03-18 05:45 UTC, seongjae6751 commented on src/main/java/in/koreatech/koin/domain/activity/model/Activity.java
> +    public Activity(Long id, String title, String description, String imageUrls, LocalDate date, Boolean isDeleted) {
private으로 사용해도 다른 곳에서 쓸 수 있군요..! 해당 부분에 대해 공부하도록 하겠습니다 감사합니다!

2024-03-18 05:45 UTC, seongjae6751 commented on src/main/java/in/koreatech/koin/domain/activity/repository/ActivityRepository.java
> +    List<Activity> getActivitiesByYear(@Param("year") String year);
Activity 엔티티 필드에 year정보가 없어서 namedQuery로는 작성을 못할 것 같습니다..!

2024-03-18 06:27 UTC, seongjae6751 commented on src/test/java/in/koreatech/koin/acceptance/ActivityApiTest.java
> +            .get("/activities?year=2019")
이렇게도 할 수 있군요..! 적용하였습니다!

2024-03-18 11:35 UTC, Choon0414 requested changes
첫 PR 고생하셨습니다! 리뷰 드립니다.

2024-03-18 14:26 UTC, Choon0414 requested changes

2024-03-18 14:26 UTC, Choon0414 commented on src/main/java/in/koreatech/koin/domain/activity/controller/ActivityController.java
> +        var response = activityService.getActivities(year);
**A**

var를 사용하신 이유가 궁금합니다!

2024-03-18 16:09 UTC, seongjae6751 commented on src/main/java/in/koreatech/koin/domain/activity/service/ActivityService.java
> +    }
수정했습니다!

2024-03-19 07:52 UTC, Choi-JJunho requested changes
몇가지 코멘트만 더 확인해주세요~

2024-03-19 07:52 UTC, Choi-JJunho commented on src/main/java/in/koreatech/koin/domain/activity/controller/ActivityController.java
> +
### R
불필요한 공백이 있군요~

2024-03-19 07:52 UTC, Choi-JJunho commented on src/main/java/in/koreatech/koin/domain/activity/controller/ActivityController.java
> +        var response = activityService.getActivities(year);
저도 궁금합니다~

2024-03-19 07:52 UTC, Choi-JJunho commented on src/main/java/in/koreatech/koin/domain/activity/dto/ActivitiesResponseDTO.java
> +public class ActivitiesResponseDTO {
### R
다른 DTO들의 네이밍에도 DTO가 붙어있나요?
전체적으로 네이밍을 맞춰주면 좋겠네요

2024-03-19 07:52 UTC, Choi-JJunho commented on src/main/java/in/koreatech/koin/domain/activity/dto/ActivityResponse.java
> +    LocalDate date,
### C

`@JsonFomat(pattern="yyyy-MM-dd")`로 포맷을 명시해주는건 어떨까요

2024-03-19 07:52 UTC, Choi-JJunho commented on src/main/java/in/koreatech/koin/domain/activity/dto/ActivityResponse.java
> +    @Schema(description = "이미지 URL 목록", example = "null")
### A

example이 null이면 살짝 억울할거같은데 이왕이면 값 채워주는거 어떤가요

2024-03-19 07:52 UTC, Choi-JJunho commented on src/main/java/in/koreatech/koin/domain/activity/dto/ActivityResponse.java
> +    public static ActivityResponse from(Activity activity, List<String> imageUrls) {
### R

정적 팩토리 메소드에서 인자가 2개 이상이면 `of` 네이밍이 더 적절할거같아요!
참고자료: https://tecoble.techcourse.co.kr/post/2020-05-26-static-factory-method/

2024-03-19 07:52 UTC, Choi-JJunho commented on src/test/java/in/koreatech/koin/acceptance/ActivityApiTest.java
> +    @DisplayName("Year 파라미터 없이 모든 BCSD Lab 활동 내역을 조회한다.")
### A

진짜 사소한 취향차이
```suggestion
    @DisplayName("BCSD Lab 활동 내역을 조회한다 - 파라미터가 없는 경우 전체조회")
```

2024-03-19 07:52 UTC, Choi-JJunho commented on src/test/java/in/koreatech/koin/acceptance/ActivityApiTest.java
> +            }
### C

activity 2는 검증 안해준 이유가 있을까요?

2024-03-19 11:03 UTC, seongjae6751 commented on src/main/java/in/koreatech/koin/domain/activity/dto/ActivityResponse.java
> +    public static ActivityResponse from(Activity activity, List<String> imageUrls) {
원래 of로 썼다가 entity와 dto의 연관관계로 작명을 하는 것이라는 이야기를 듣고 from으로 바꿨었는데 원래 of가 맞았나 보네요ㅠ 수정했습니다!

2024-03-19 11:10 UTC, seongjae6751 commented on src/main/java/in/koreatech/koin/domain/activity/controller/ActivityController.java
> +
공백 계속 나름 신경 쓰고 있는데 계속 이런 일이 발생하네요; 수정하였습니다!

2024-03-19 11:17 UTC, seongjae6751 commented on src/test/java/in/koreatech/koin/acceptance/ActivityApiTest.java
> +            }
테스트 상에서 첫 번째 것이랑 마지막 것인 세 번째 것만 통과하면 순서가 맞게 들어 갔다고 생각할 수 있지 않나 싶어서 굳이 두 번째 것은 테스트 코드를 안 만들었습니다..! 두 번째 것도 만드는 것이 좋을까요?

2024-03-19 11:22 UTC, Choi-JJunho commented on src/test/java/in/koreatech/koin/acceptance/ActivityApiTest.java
> +            }
이왕 하는거 세개 다 해주죠 ㅋㅋㅋ

2024-03-19 12:03 UTC, seongjae6751 commented on src/main/java/in/koreatech/koin/domain/activity/dto/ActivitiesResponseList.java
> +public class ActivitiesResponseList {
ActivityResponse라는 이름의 dto가 있어서 헷갈릴 까봐 ActivitiesResponse라는 이름은 사용하지 않으려고 List를 붙였는데 오히려 더 안 좋을 수도 있군요..! ActivityResponseGroup으로 이름을 바꾸려 하는데 괜찮을지 모르겠네요... 항상 많이 배웁니다! 감사합니다😄

2024-03-19 12:07 UTC, Choi-JJunho commented on src/main/java/in/koreatech/koin/domain/activity/dto/ActivitiesResponseList.java
> +public class ActivitiesResponseList {
ActivityResponse로도 충분할거같다는 의견입니다

2024-03-19 12:10 UTC, seongjae6751 commented on src/main/java/in/koreatech/koin/domain/activity/dto/ActivitiesResponseList.java
> +public class ActivitiesResponseList {
다른 도메인의 dto들을 보니까 s로 붙여서 구분하는 dto들이 이미 있네요..! ActivitiesResponse라는 이름으로 변경하겠습니다! 알려주신 것들 잘 정리해서 다음에는 같은 행동들 하지 않겠습니다! 감사합니다!! 🙇

2024-03-19 12:13 UTC, Choi-JJunho approved these changes
고생하셨습니다 👏

2024-03-19 12:23 UTC, Choon0414 approved these changes
어려운 부분 많았을텐데 고생많으셨습니다!!

2024-03-20 02:14 UTC, merged