Feature/39 get shop menu
BCSDLab/KOIN_API_V2 pull request #208
Opened 2024-03-15 16:27 UTC by 20HyeonsuLee

# 🔥 연관 이슈

- close #39 

# 🚀 작업 내용

1. 특정 상점의 모든 메뉴를 조회하는 api를 구현했습니다.
2. 해당 상점의 마지막 메뉴 업데이트 날짜를 제공하도록 하였습니다.
3. 꼼꼼한 테스트를 위해 메뉴 3개를 넣어서 최대한 많은 경우를 테스트했습니다.

# 💬 리뷰 중점사항
테스트코드가 조금 복잡하다고 느꼈습니다. 테스트코드를 어떻게 개선할 수 있을지, 또 테스트코드가 올바르게 작성되었는지 위주로 봐주시면 감사하겠습니다.

2024-03-17 13:50 UTC, Choi-JJunho requested changes
응답이 꽤나 괴랄해서 고생많으셨네요.. ㄷㄷㄷ
몇가지 코멘트 확인 부탁드려요~

2024-03-17 13:50 UTC, Choi-JJunho commented on src/main/java/in/koreatech/koin/domain/shop/dto/MenuDetailResponse.java
> +            log.warn("{}는 옵션이 하나 이상인 메뉴입니다. createForMultipleOption 메서드를 이용해야 합니다.", menu);
### A
상세한 로깅 좋네요

2024-03-17 13:50 UTC, Choi-JJunho commented on src/main/java/in/koreatech/koin/domain/shop/dto/ShopMenuResponse.java
> +        LocalDateTime lastUpdatedDate = LocalDateTime.of(1900,1,1,0,0);
### A

마지막으로 업데이트된 날짜를 넣기 위해 선언해뒀군요 😯

2024-03-17 13:50 UTC, Choi-JJunho commented on src/main/java/in/koreatech/koin/domain/shop/dto/ShopMenuResponse.java
> +        int count = 0;
### C
메뉴 개수면 menuCategories.size()로 충분하지 않나요?

2024-03-17 13:50 UTC, Choi-JJunho commented on src/main/java/in/koreatech/koin/domain/shop/dto/ShopMenuResponse.java
> +        }
### A
흠.. 좀더 이쁘게 짤 수 있을거같은데 지금 당장 생각은 안나니 일단 보류..
라인 포맷팅 한번 해주세요

2024-03-17 13:50 UTC, Choi-JJunho commented on src/main/java/in/koreatech/koin/domain/shop/dto/ShopMenuResponse.java
> +        public static InnerMenuCategoriesResponse of(MenuCategory menuCategory) {
### A
인자가 하나인건 of가 아니라 from으로 네이밍해주세요

참고자료: https://tecoble.techcourse.co.kr/post/2020-05-26-static-factory-method/

2024-03-17 13:50 UTC, Choi-JJunho commented on src/main/java/in/koreatech/koin/domain/shop/dto/ShopMenuResponse.java
> +        @JsonNaming(value = PropertyNamingStrategies.SnakeCaseStrategy.class)
### A

별건 아니지만 static import 한번 해주면 좋겠네요
```suggestion
        @JsonNaming(value = SnakeCaseStrategy.class)
```

2024-03-17 13:50 UTC, Choi-JJunho commented on src/main/java/in/koreatech/koin/domain/shop/dto/ShopMenuResponse.java
> +            public static InnerMenuResponse of(MenuCategoryMap menuCategoryMap) {
### A
> 인자가 하나인건 of가 아니라 from으로 네이밍해주세요

ditto

2024-03-17 13:50 UTC, Choi-JJunho commented on src/main/java/in/koreatech/koin/domain/shop/service/ShopService.java
> +        return ShopMenuResponse.createShopMenuResponse(menuCategories);
### C

그냥 from이라는 네이밍은 어때요?

2024-03-17 13:50 UTC, Choi-JJunho commented on src/test/java/in/koreatech/koin/acceptance/ShopApiTest.java
> +        // when then
### R
when인가요 then인가요

2024-03-17 13:50 UTC, Choi-JJunho commented on src/test/java/in/koreatech/koin/acceptance/ShopApiTest.java
> +            .log().all()
### R

log 코드는 빼주시죠~!

2024-03-17 14:33 UTC, 20HyeonsuLee commented on src/main/java/in/koreatech/koin/domain/shop/dto/ShopMenuResponse.java
> +        int count = 0;
MenuCategory객체 내부에 메뉴가 여러개 있을 수 있는 구조라서 전부 순회했습니다ㅠ

ex)
menu_categories[
       카테고리1[
              메뉴1
              메뉴2
              .
              .
       카테고리2[
              메뉴1
              메뉴2
              .
              .
       ]
]

2024-03-17 14:33 UTC, 20HyeonsuLee commented on src/main/java/in/koreatech/koin/domain/shop/dto/ShopMenuResponse.java
> +        }
라인 포맷팅 완료했습니다!

2024-03-17 14:35 UTC, 20HyeonsuLee commented on src/main/java/in/koreatech/koin/domain/shop/dto/ShopMenuResponse.java
> +        public static InnerMenuCategoriesResponse of(MenuCategory menuCategory) {
정적팩토리메소드에도 컨벤션이 있었군요..!

2024-03-17 14:40 UTC, 20HyeonsuLee commented on src/test/java/in/koreatech/koin/acceptance/ShopApiTest.java
> +        // when then
의미없는 주석인것같아서 제거했습니다!

2024-03-17 14:59 UTC, 20HyeonsuLee commented on src/main/java/in/koreatech/koin/domain/shop/dto/ShopMenuResponse.java
> +        }
이부분은 짜면서 좀 이상하다고 느끼긴 했는데 딱히 생각이 안나서 그대로 짰던것같습니다.
지금 생각나는건 MenuCategoryMap을 InnerMenuResponse로 변환하는 from함수에서 count랑 최신날짜 업데이트를 해주면 좋겠다는 생각이 드는데 count랑 localdatetime을 어떻게 변수로 관리해줘야할지는 고민이 되네요.. 좋은 방법 생각나면 말씀해주세요!

2024-03-18 02:06 UTC, Choi-JJunho approved these changes
고생하셨습니다~
복잡한 응답값이라서 머리 많이 아팠을텐데 잘 해주셨네요 👍

2024-03-18 02:06 UTC, Choi-JJunho commented on src/main/java/in/koreatech/koin/domain/shop/dto/MenuDetailResponse.java
> +                                 List<Long> categoryIds, List<String> imageUrls) {
### C

필드 파악이 용이하도록 필드 하나에 한줄로 작성하는건 어떨까요?
추가로 Swagger 코드 추가해야할 것 같아요~

2024-03-18 05:52 UTC, kwoo28 requested changes
전체메뉴조회 공부하시느라 시간 많이 들이셨을텐데 수고 많으셨습니다.
리뷰 남깁니다.

2024-03-18 05:52 UTC, kwoo28 commented on src/main/java/in/koreatech/koin/domain/shop/service/ShopService.java
> +        List<MenuCategory> menuCategories = menuCategoryRepository.findAllByShopId(shopId);
## C

menuCategoryRepository에서 findAllByShopId 메서드에 대해 조회된 데이터가 없을때에 대한 예외처리 부분이 안보이는것같은데 따로 예외처리 안해도 상관없는건가요??

2024-03-19 07:21 UTC, songsunkook approved these changes
깔끔하게 잘 작성해주셨네요. 고생하셨습니다!

2024-03-19 09:40 UTC, 20HyeonsuLee commented on src/main/java/in/koreatech/koin/domain/shop/service/ShopService.java
> +        List<MenuCategory> menuCategories = menuCategoryRepository.findAllByShopId(shopId);
findAll이라서 List형태로 반환할거라서 따로 예외처리는 안했어요~

2024-03-19 11:08 UTC, kwoo28 approved these changes

2024-03-19 11:09 UTC, merged