feat: 시간표 기능 구현
BCSDLab/KOIN_API_V2 pull request #212
Opened 2024-03-19 11:22 UTC by kwoo28

# 🔥 연관 이슈

- close #28

# 🚀 작업 내용

1. 시간표를 생성합니다.
2. 시간표를 삭제합니다.
3. 시간표를 수정합니다.
4. 시간표를 조회합니다.

# 💬 리뷰 중점사항
1. request 이용 방식과 service계층에서 dto를 entity로 변경하는 부분에서 이렇게 하는게 올바른건지 봐주시면 감사하겠습니다.
2. 삭제나 수정부분을 entity를 변경하는 방식으로 했는데 맞게 한 방식인지 애매한것같습니다.

2024-03-20 02:59 UTC, Choi-JJunho requested changes
CRUD 작업에 테스트까지 꼼꼼하게 잘 작성해주셨네요~ 👍
몇가지 내용들 확인이 필요해서 코멘트 확인 부탁드릴게요~

2024-03-20 02:59 UTC, Choi-JJunho commented on src/main/java/in/koreatech/koin/domain/timetable/dto/TimeTableRequest.java
> +    public static TimeTable toEntity(User user, Semester semester, InnerTimeTableRequest request){
### C

toEntity vs toTimeTable 어떤 네이밍이 적절하다고 생각하시나요?

2024-03-20 02:59 UTC, Choi-JJunho commented on src/main/java/in/koreatech/koin/domain/timetable/dto/TimeTableRequest.java
> +@JsonNaming(value = PropertyNamingStrategies.SnakeCaseStrategy.class)
### C

static import 한번 해주면 좋겠네요
```suggestion
@JsonNaming(value = SnakeCaseStrategy.class)
```

2024-03-20 02:59 UTC, Choi-JJunho commented on src/main/java/in/koreatech/koin/domain/timetable/dto/TimeTableRequest.java
> +    @Valid
### A

`@Valid` 를 붙인 이유가 있나요
잘 몰라서 그러는데 inner class에 대해서는 객체 내부에서 다시 붙여줘야만 동작하는걸까요?

2024-03-20 02:59 UTC, Choi-JJunho commented on src/main/java/in/koreatech/koin/domain/timetable/dto/TimeTableResponse.java
> +    private static List<Integer> toListClassTime(String classTime) {
### R

toListClassTime 이라는 네이밍을 보고는 어떤 역할을 수행하는지가 와닿지 않네요
좀더 직관적인 이름 없을까요?

2024-03-20 02:59 UTC, Choi-JJunho commented on src/main/java/in/koreatech/koin/domain/timetable/dto/TimeTableResponse.java
> +        classTime = classTime.substring(1, classTime.length() - 1);
### R

1. 기존값을 재할당하게 되면서 아래 로직에서 해당 변수 값에 대해 혼동이 올 수 있음
    - 변수로 추출하여 별도의 값으로 선언하면 좋겠음
3. substring을 하는 이유가 직관적이지 않음
    - 예상하기로는 `[`, `]`을 제거하려는 목적으로 이해했으나 해당 로직을 바로 봤을 때 어떤 의미인지 잘 모르겠음
    - 1 이라는 값을 INITIAL_BRACE_INDEX와 같은 상수로 추출하여 로직을 보다 명확하게 명시하면 좋겠음

2024-03-20 02:59 UTC, Choi-JJunho commented on src/main/java/in/koreatech/koin/domain/timetable/dto/TimeTableResponse.java
> +                .collect(Collectors.toList());
### R

로직을 좀더 간단하게 표현해보시죠
```suggestion
            return Arrays.stream(classTime.split(", "))
                .map(Integer::parseInt)
                .toList()
```

2024-03-20 02:59 UTC, Choi-JJunho commented on src/main/java/in/koreatech/koin/domain/timetable/dto/TimeTableResponse.java
> +            return new ArrayList<>();
### A
Collections.emptyList() 라는 친구도 있답니다 :)

2024-03-20 02:59 UTC, Choi-JJunho commented on src/main/java/in/koreatech/koin/domain/timetable/dto/TimeTableResponse.java
> +@JsonNaming(value = PropertyNamingStrategies.SnakeCaseStrategy.class)
### C

> static import 한번 해주면 좋겠네요

ditto

2024-03-20 02:59 UTC, Choi-JJunho commented on src/main/java/in/koreatech/koin/domain/timetable/dto/UpdateTimeTableRequest.java
> +@JsonNaming(value = PropertyNamingStrategies.SnakeCaseStrategy.class)
### C

> static import 한번 해주면 좋겠네요

ditto

2024-03-20 02:59 UTC, Choi-JJunho commented on src/main/java/in/koreatech/koin/domain/timetable/dto/TimeTableRequest.java
> +        ]
### R

example 형태가 이게 맞나요?
실제로 swagger에서 어떻게 뜨는지 확인해주시면 좋겠습니다
의미 없는 값이라면 굳이 선언 안해도될거같네요

2024-03-20 02:59 UTC, Choi-JJunho commented on src/main/java/in/koreatech/koin/domain/timetable/exception/TimeTableNotFoundException.java
> +    public TimeTableNotFoundException(String message) {
### R

여백 하나 주면 좋겠네요
```suggestion
    private static final String DEFAULT_MESSAGE = "존재하지 않는 시간표입니다.";
    
    public TimeTableNotFoundException(String message) {
```

2024-03-20 02:59 UTC, Choi-JJunho commented on src/main/java/in/koreatech/koin/domain/timetable/model/TimeTable.java
> +
### R

불필요한 공백
```suggestion

```

2024-03-20 02:59 UTC, Choi-JJunho commented on src/main/java/in/koreatech/koin/domain/timetable/repository/TimeTableRepository.java
> +    default List<TimeTable> getByUserIdAndSemesterId(Long userId, Long semesterId){
### R
라인 포맷팅
```suggestion
    default List<TimeTable> getByUserIdAndSemesterId(Long userId, Long semesterId) {
```

2024-03-20 02:59 UTC, Choi-JJunho commented on src/main/java/in/koreatech/koin/domain/timetable/repository/TimeTableRepository.java
> +        }
### A

List가 비어있으면 예외인가요?
설계자의 의도에 따라 다르겠지만 이참에 `놀람 최소화 원칙`이라는 것에 대해 한번 생각해보면 좋을 것 같네요

위 설계가 틀렸다는건 아니고 예외를 발생시킬만한지 생각해보면 좋겠다는 의미입니다

참고자료: https://ko.wikipedia.org/wiki/%EB%86%80%EB%9E%8C_%EC%B5%9C%EC%86%8C%ED%99%94_%EC%9B%90%EC%B9%99

2024-03-20 02:59 UTC, Choi-JJunho commented on src/main/java/in/koreatech/koin/domain/timetable/service/TimetableService.java
> +    public List<TimeTableResponse> getTimeTables(Long userId, String semester){
### R

라인 포맷팅을 습관화 해주세용~

`Ctrl + Alt + L`
```suggestion
    public List<TimeTableResponse> getTimeTables(Long userId, String semester) {
```

2024-03-20 02:59 UTC, Choi-JJunho commented on src/main/java/in/koreatech/koin/domain/timetable/service/TimetableService.java
> +        for(UpdateTimeTableRequest.InnerTimeTableRequest timeTableRequest : timeTableRequests){
### A

이정도는 합쳐도 무관하다고 생각하는데 어떤가요
```suggestion
        for (UpdateTimeTableRequest.InnerTimeTableRequest timeTableRequest : request.timetable()) {
```

2024-03-20 02:59 UTC, Choi-JJunho commented on src/test/java/in/koreatech/koin/acceptance/TimetableApiTest.java
> +                        .containsExactlyInAnyOrderElementsOf(List.of(14, 15, 16, 17, 204, 205, 206, 207));
### A
꼼꼼하네요 👍

2024-03-20 02:59 UTC, Choi-JJunho commented on src/test/java/in/koreatech/koin/acceptance/TimetableApiTest.java
> +    @DisplayName("시간표 삭제한다.")
### A 
```suggestion
    @DisplayName("시간표를 삭제한다.")
```

2024-03-20 02:59 UTC, Choi-JJunho commented on src/test/java/in/koreatech/koin/acceptance/TimetableApiTest.java
> +    }
### A

조금 더 꼼꼼하게 조회 API를 한번 더 호출하여 404가 뜨는지까지 확인하면 좋겠네요

2024-03-20 04:59 UTC, kwoo28 commented on src/main/java/in/koreatech/koin/domain/timetable/dto/TimeTableRequest.java
> +    public static TimeTable toEntity(User user, Semester semester, InnerTimeTableRequest request){
확실히 해당 메서드명을 보았을때 명시적으로 어떤 객체로 반환할수 있는지 파악이 용이해서 toTimeTable로 하는것이 좋아보이네요..

2024-03-20 05:01 UTC, kwoo28 commented on src/main/java/in/koreatech/koin/domain/timetable/dto/TimeTableRequest.java
> +    @Valid
넵. 객체 내부에서 안붙이면 검증이 안되더라구요..

2024-03-20 05:02 UTC, kwoo28 commented on src/main/java/in/koreatech/koin/domain/timetable/service/TimetableService.java
> +        for(UpdateTimeTableRequest.InnerTimeTableRequest timeTableRequest : timeTableRequests){
그러네요.. 굳이 지역변수를 따로 둘 의미가 없네요

2024-03-20 07:45 UTC, duehee requested changes
기능 구현하시느라 고생 많으셨습니다!

많이 리뷰하지는 못헀지만, 반영해주시면 감사하겠습니다 :D

2024-03-20 07:45 UTC, duehee commented on src/main/java/in/koreatech/koin/domain/timetable/controller/TimetableApi.java
> +        @RequestBody UpdateTimeTableRequest request,
### C
이름을 `UpdateTimeTableRequest`보단, `TimeTableUpdateRequest`처럼 사용하는 건 어떨까요?
현재 사용하고 있는 테이블들은 Domain + 처리 할 내용 + Request(Response)로 사용하는 경우가 많은 것 같아요.

2024-03-20 08:16 UTC, kwoo28 commented on src/main/java/in/koreatech/koin/domain/timetable/controller/TimetableApi.java
> +        @RequestBody UpdateTimeTableRequest request,
그렇군요! 좋은 정보 감사합니다. 수정해보겠습니다

2024-03-20 08:16 UTC, kwoo28 commented on src/main/java/in/koreatech/koin/domain/timetable/dto/TimeTableRequest.java
> +    @JsonNaming(value = PropertyNamingStrategies.SnakeCaseStrategy.class)
반영했습니다!

2024-03-20 08:40 UTC, Choi-JJunho requested changes
아주 빠르네요 굿굿 👍
중복로직 하나만 확인해주세요~

2024-03-20 08:40 UTC, Choi-JJunho commented on src/main/java/in/koreatech/koin/domain/timetable/dto/TimeTableRequest.java
> +    public static TimeTable toTimeTable(User user, Semester semester, InnerTimeTableRequest request) {
### C

이거 InnerClass를 인자로 받아와야할까요?
this로 접근해도 될거같은데

2024-03-20 08:40 UTC, Choi-JJunho commented on src/main/java/in/koreatech/koin/domain/timetable/dto/TimeTableResponse.java
> +            classTime.length() - INITIAL_BRACE_INDEX);
### C

같은 1이지만 의미하는 값이 다른거같아요~
```suggestion
            classTime.length() - 1);
```

2024-03-20 08:40 UTC, Choi-JJunho commented on src/main/java/in/koreatech/koin/domain/timetable/service/TimetableService.java
> +        return getTimeTables(userId, semester.getSemester());
### R

getTimeTables을 재사용하면서 다음 로직이 중복되어 사용되고있네요~
```java
Semester semester = semesterRepository.getBySemester(request.semester());
```
이로 인해 불필요한 조회 쿼리가 발생할거같은데 조회 로직이 중복되지 않도록 수정할 수 있을까요?

2024-03-20 09:05 UTC, kwoo28 commented on src/main/java/in/koreatech/koin/domain/timetable/service/TimetableService.java
> +        return getTimeTables(userId, semester.getSemester());
헉... 그러네요.. 대단하십니다.. 생성, 수정이 조회를 통해 중복쿼리가 사용되고 있어서, TimeTableresponse를 반환하는 메서드를 따로 추출해서 중복 로직을 수정해보겠습니다.

2024-03-20 09:58 UTC, Choi-JJunho requested changes
반영속도 왤캐 빠르죠..ㄷㄷ
좋습니다 👍
마지막이될거같은데 코멘트 한번 확인해주세요~

2024-03-20 09:58 UTC, Choi-JJunho commented on src/main/java/in/koreatech/koin/domain/timetable/service/TimetableService.java
> +        List<TimeTable> timeTables = timeTableRepository.getByUserIdAndSemesterId(userId, semesterEntity.getId());
### A
찐찐막!!
어짜피 id 사용할거면 entity 넘기지 말고 semesterId 넘기면 안되나요?
```suggestion
    private List<TimeTableResponse> getTimeTableResponse(Long userId, Long semesterId) {
        List<TimeTable> timeTables = timeTableRepository.getByUserIdAndSemesterId(userId, semesterId);
```

2024-03-20 09:58 UTC, Choi-JJunho commented on src/main/java/in/koreatech/koin/domain/timetable/repository/TimeTableRepository.java
> +    List<TimeTable> findByUserIdAndSemesterId(Long userId, Long semesterId);
### C

List 형태를 반환하니까 findAllBy.. 네이밍이 적절해보이네요

2024-03-20 09:58 UTC, Choi-JJunho commented on src/main/java/in/koreatech/koin/domain/timetable/repository/TimeTableRepository.java
> +    }
### C

별도로 exception 처리를 안해주는데 굳이 getBy로 감쌀 이유는 없어보입니다.

2024-03-20 10:19 UTC, kwoo28 commented on src/main/java/in/koreatech/koin/domain/timetable/repository/TimeTableRepository.java
> +    }
아 exception 처리를 안해줄땐 getBy를 안쓰이는군요. 메소드 통일해야하는줄 알았네요

2024-03-20 10:19 UTC, kwoo28 commented on src/main/java/in/koreatech/koin/domain/timetable/service/TimetableService.java
> +        List<TimeTable> timeTables = timeTableRepository.getByUserIdAndSemesterId(userId, semesterEntity.getId());
생각없이 메소드 추출하고 복붙했었던것같습니다..ㅋㅋ 한번더 점검하는 습관 들여보도록 하겠습니다.

2024-03-20 10:19 UTC, kwoo28 commented on src/main/java/in/koreatech/koin/domain/timetable/repository/TimeTableRepository.java
> +    List<TimeTable> findByUserIdAndSemesterId(Long userId, Long semesterId);
JPA에선 findBy~밖에 못쓰는줄 알았네요..

2024-03-20 10:29 UTC, duehee approved these changes
리뷰 반영 확인헀습니다!
코드 작성하시느라 고생 많으셨습니다 :D

2024-03-20 15:20 UTC, seongjae6751 approved these changes
칭찬만 달면 그럴 것 같아서 옥의 티라도 잡으려고 한참 봤는데 도저히 안 보이네요.. 고생 많으셨습니다!!

2024-03-20 15:20 UTC, seongjae6751 commented on src/main/java/in/koreatech/koin/domain/timetable/dto/TimeTableRequest.java
> +    public record InnerTimeTableRequest(
inner class를 잘 활용 하셨네요 👍

2024-03-21 00:15 UTC, kwoo28 commented on src/main/java/in/koreatech/koin/domain/timetable/controller/TimetableController.java
> +        @Auth(permit = {STUDENT}) Long userId
감사합니다!

2024-03-21 00:16 UTC, kwoo28 commented on src/main/java/in/koreatech/koin/domain/timetable/dto/TimeTableRequest.java
> +    public record InnerTimeTableRequest(
저도 이 부분 어덯게 처리해야할지 첨에 고민 많이했습니다 ㅋㅋ 👍

2024-03-21 00:31 UTC, merged