ㄹix: 복덕방 전제 조회 응답 객체 미스매치 수정
BCSDLab/KOIN_API_V2 pull request #215
Opened 2024-03-20 06:35 UTC by seongjae6751

# 🔥 연관 이슈
- close #188 

# 🚀 작업 내용
1. 복덕방 전체 조회(get-lands)의 응답 객체가 미스매치 되어 있는 것을 수정해줬습니다.(반환 값을 list에서 key:value의 형태로 바꾸어 줬습니다.) -> ex) {lands : [ ]}의 형태로 만들어줬습니다.
2. 복덕방 전체 조회의 응답 객체를 맡은 dto의 이름에 자료형(list)가 들어가 있어서 LandsResponse로 이름을 바꿔줬습니다.
3. 전체 조회 관련 테스트 코드를 추가 작성해줬습니다.

# 💬 리뷰 중점사항
key:value 형태로 묶어주기 위해서 dto를 하나 더 만들었는데 dto의 이름을 적당하게 잘 작명 한 것인지 모르겠습니다. 그 외 수정 했으면 하는 부분이 있다면, 말씀 해주시면 성실하게 수정하도록 하겠습니다.!

2024-03-20 08:01 UTC, kwoo28 approved these changes
수고 많으셨습니다. 리뷰 남겨요

2024-03-20 08:01 UTC, kwoo28 commented on src/main/java/in/koreatech/koin/domain/land/dto/LandsResponse.java
> +public record LandsResponse(
## A

전 갠적으로 LandsResponse -> LandItemResponse로 하고 LandsGroupResonse -> LandsResponse가 좋을것같다는 입장입니다.. 
물론 제 입장입니다.

2024-03-20 11:17 UTC, duehee requested changes
수정하시느라 고생하셨습니다 :D
아래 원경님께서 작성해주신 DTO에 관한 점 확인해주시면 감사하겠습니다!!

2024-03-20 11:17 UTC, duehee commented on src/main/java/in/koreatech/koin/domain/activity/dto/ActivityResponse.java
> +    @Schema(description = "이미지 URL 목록", example = """
### A
Text block을 사용하셨네요👍 더 읽기 좋아진 것 같아요!

2024-03-20 11:17 UTC, duehee commented on src/main/java/in/koreatech/koin/domain/land/dto/LandsGroupResponse.java
> +public class LandsGroupResponse {
코드 컨벤션에서 DTO는 record로 작성하도록 되어있는데, 저도 궁금합니다!

2024-03-21 11:11 UTC, seongjae6751 commented on src/main/java/in/koreatech/koin/domain/land/dto/LandsGroupResponse.java
> +public class LandsGroupResponse {
허허 코드 컨벤션도 읽어 봤는데 놓친 부분이네요 짚어주셔서 감사합니다!

2024-03-21 11:13 UTC, seongjae6751 commented on src/main/java/in/koreatech/koin/domain/land/dto/LandsResponse.java
> +public record LandsResponse(
작명 때문에 정말 고민을 많이 했는데 LandItemResponse로 하면 단일 조회 dto인 LandResponse랑 이름이 모호한 것 같아서, 확실하게 구분을 지어 주고 싶어 여러 개를 조회 해서 응답해주는 dto 작명을 LandsRespone로 했습니다..!

2024-03-21 13:09 UTC, duehee approved these changes
리뷰 반영 감사합니다~

2024-03-22 06:30 UTC, Choi-JJunho approved these changes
고생하셨습니다 👍

2024-03-22 06:31 UTC, merged