feat : 회원 정보 수정
BCSDLab/KOIN_API_V2 pull request #236
Opened 2024-03-23 12:38 UTC by duehee

# 🔥 연관 이슈

- close #23 

# 🚀 작업 내용

1. 회원 정보 수정 추가했습니다.
- 기존 Swagger에서 사용하던 Request 유형에서 Password를 제외하고 작성했습니다.(다른 이슈로 할당 예정)
- 기존에 사용하던 학번/학부 예외처리를 422번이 아닌 404번 오류으로 작성했습니다.(트랙장님 의견)
- 학번에 관한 오류는 현재 10자리가 아니면 오류가 발생하도록 했습니다.(23년 이후 학번처리에 대한 의견이 필요)

2. 학부/학과에 대한 ENUM 추가했습니다.
- 24년 기준, 나뉜 학부도 추가해서 작성했습니다.
(현재 존재하는 학부/과 : 기계공학부, 컴퓨터공학부, 메카트로닉스공학부, 전기전자통신공학부, 디자인공학부, 건축공학부, 화학생명공학부, 에너지신소재공학부, 산업경영학부, 고용서비스정책학과)
- 기존 존재하던 TEST의 내용도 수정 완료했습니다.

# 💬 리뷰 중점사항
기능 작성하는 시간이 조금 오래 걸렸습니다. 기존에 회원 정보 수정에 있던 내용인 비밀번호 관련이슈는 User 팀의 스레드에 올려놓았습니다.

작성하며 헤맨 부분이 많아서, 리뷰 작성해주시면 감사하겠습니다! 감사합니다 :D

2024-03-24 06:19 UTC, kwoo28 approved these changes
기존 코인 보면서 해석하고 코마거치는 과정이 쉽진 않았을텐데 수고 많으셨습니다!
리뷰 남기겠습니다.

2024-03-24 06:19 UTC, kwoo28 commented on src/main/java/in/koreatech/koin/domain/user/service/StudentService.java
> +            .build();
## C

필드4개를 변경시키고자 User객체를 한개 더만드신건가요? User클래스에서 변경시키고자 하는 필드만 받는 메서드를 만드는게 어떨까요?

2024-03-24 06:19 UTC, kwoo28 commented on src/main/java/in/koreatech/koin/domain/user/service/StudentService.java
> +            .build();
## C

이것도 User와 마찬가지로...

2024-03-24 06:19 UTC, kwoo28 commented on src/main/java/in/koreatech/koin/domain/user/service/StudentService.java
> +            throw new StudentNumberNotValidException(
## C

이 부분은 예외를 만들어서 처리하기보다 Request에서 @Valid로 학번의 형식을 거르는 방법은 어떤가요?

2024-03-24 11:32 UTC, seongjae6751 requested changes
고생하셨습니다! 리뷰 드립니다

2024-03-24 11:32 UTC, seongjae6751 commented on src/main/java/in/koreatech/koin/domain/user/controller/UserApi.java
> +            @ApiResponse(responseCode = "422", content = @Content(schema = @Schema(hidden = true)))
A
사소한 거지만 422 안 쓰기로 했으면 빼도 될 것 같네요~

2024-03-25 02:34 UTC, duehee commented on src/main/java/in/koreatech/koin/domain/user/model/User.java
> +        }
기존 코인 API에서 update 메소드를 이용했는데, 이 구문에는 모든 값에 처리가 되어있어서 같이 작성해보았습니다!

2024-03-25 02:42 UTC, duehee commented on src/main/java/in/koreatech/koin/domain/user/service/StudentService.java
> +            .build();
User 객체에서 @Bulider를 이미 사용하고 있는 메소드가 있어서 추가적인 @Builder를 작성하지 않았습니다.
제가 기존에 사용하던 방법인 새 update 객체를 생성하여 적용하는 방법이 효율이 좋지 않은가에 대해선 한 번 생각해보겠습니다 :D

2024-03-25 02:42 UTC, duehee commented on src/main/java/in/koreatech/koin/domain/user/service/StudentService.java
> +            .build();
위의 사항과 동일하여 한 번 생각해보겠습니다!!

2024-03-25 02:43 UTC, duehee commented on src/main/java/in/koreatech/koin/domain/user/dto/StudentUpdateRequest.java
> +        String studentNumber
기존 레거시 코드에는 학번이 50으로 되어있어서 이렇게 작성해보았는데, 확인해보고 수정 해보겠습니다!

2024-03-25 02:44 UTC, duehee commented on src/main/java/in/koreatech/koin/domain/user/service/StudentService.java
> +            throw new StudentNumberNotValidException(
그렇게 코드를 작성한다면 더 깔끔하게 처리할 수도 있겠네요!

2024-03-25 02:56 UTC, songsunkook commented on src/main/java/in/koreatech/koin/domain/user/model/User.java
> +        }
수정이 필요한 필드가 있다면 해당 필드(들)만 수정하는 메서드를 작성하는 게 좋을 것 같아요~
사이드이펙트가 발생할 여지가 많아 보입니다.

2024-03-25 04:57 UTC, duehee commented on src/main/java/in/koreatech/koin/domain/user/model/User.java
> +        }
추가적으로 수정해서 작성했습니다~

2024-03-25 05:13 UTC, songsunkook requested changes

2024-03-25 05:13 UTC, songsunkook commented on src/main/java/in/koreatech/koin/domain/user/model/User.java
> +    }
### R
네이밍이 일관적이지 못한 것 같아요
User를 매개변수로 받았을 때 해당 변수에서 어떤 내용을 update해주는 것인지 알 수 없을 것 같습니다.
좀 더 리팩토링이 필요해 보여요~

+) Student도 수정해주세요

2024-03-25 07:14 UTC, duehee commented on src/main/java/in/koreatech/koin/domain/user/model/User.java
> +    }
각 이름 userInfoUpdate, studentInfoUpdate로 수정 완료했습니다!

2024-03-26 00:19 UTC, songsunkook requested changes
테스트 꼼꼼하게 작성해주셨네요!
코멘트 남겨드렸으니 확인 부탁드립니다~

2024-03-26 00:19 UTC, songsunkook commented on src/main/java/in/koreatech/koin/domain/user/dto/StudentUpdateResponse.java
> +    @Schema(description = "전공{기계공학부, 컴퓨터공학부, 메카트로닉스공학부, 전기전자통신공학부, 디자인공학부, 건축공학부, 화학생명공학부, 에너지신소재공학부, 산업경영학부, 고용서비스정책학과}", example = "컴퓨터공학부")
### C
>저희 코딩 컨벤션에 한 줄당 최대 길이가 정해져있지 않았나요??
중간에 개행을 넣을 수 있을 것 같아요

22

2024-03-26 00:19 UTC, songsunkook commented on src/main/java/in/koreatech/koin/domain/user/exception/StudentDepartmentNotValidException.java
> +public class StudentDepartmentNotValidException extends DataNotFoundException {
### A
`StudentDepartmentNotValidException `보다는 `StudentDepartmentNotFoundException`가 더 적절한 네이밍일 것 같아요

2024-03-26 00:19 UTC, songsunkook commented on src/main/java/in/koreatech/koin/domain/user/exception/StudentNumberNotValidException.java
> +public class StudentNumberNotValidException extends DataNotFoundException {
### A
>`StudentDepartmentNotValidException `보다는 `StudentDepartmentNotFoundException`가 더 적절한 네이밍일 것 같아요

22

2024-03-26 00:19 UTC, songsunkook commented on src/main/java/in/koreatech/koin/domain/user/service/StudentService.java
> +            .build();
개인적으로 Builder를 타 객체 정보 수정을 위한 임시 객체 생성에 사용하는 것은 선호하지 않습니다. user.update 메서드에 파라미터로 User를 주는 것보다 수정이 필요한 각각의 변수를 할당하는 것이 훨씬 가독성에 좋지 않을까 싶습니다.
(user.update에 User 객체를 통째로 주면 호출자 입장에서는 어떤 필드가 사용될지 예측할 수 없습니다)

2024-03-26 00:19 UTC, songsunkook commented on src/test/java/in/koreatech/koin/acceptance/UserApiTest.java
> +    @DisplayName("학생이 정보를 수정한다 - 이미 있는 닉네임이라면 409")
### A
이걸 빨리 적용했어야 했는데 ;-;

2024-03-26 09:17 UTC, duehee commented on src/main/java/in/koreatech/koin/domain/user/exception/StudentDepartmentNotValidException.java
> +public class StudentDepartmentNotValidException extends DataNotFoundException {
형식이 맞지 않을때에 예외를 처리하는 것이어서 Valid를 사용했는데, 이름을 짓는다면 예외에 대한 이름을 짓는 게 맞는지, 아니면 여기서는 반환하는 값이 404여서 Not Found를 쓰는 게 맞는지 궁금합니다!

2024-03-27 02:44 UTC, Choi-JJunho requested changes
고생하셨습니다~
코멘트 몇개 확인부탁할게요

2024-03-27 02:44 UTC, Choi-JJunho commented on src/main/java/in/koreatech/koin/domain/user/dto/StudentResponse.java
> +            student.getDepartment().toString(),
### C

toString, getValue가 혼용되어 사용되고있는 것 같아요~
```suggestion
            student.getDepartment().getValue(),
```

2024-03-27 02:44 UTC, Choi-JJunho commented on src/main/java/in/koreatech/koin/domain/user/exception/StudentDepartmentNotValidException.java
> +public class StudentDepartmentNotValidException extends DataNotFoundException {
형식이 맞지 않는 오류라면 DataNotFoundException을 상속하는게 옳은 방향일까요~?

2024-03-27 02:44 UTC, Choi-JJunho commented on src/main/java/in/koreatech/koin/domain/user/exception/StudentNumberNotValidException.java
> +
### R

불필요한 공백 발견~

2024-03-27 02:44 UTC, Choi-JJunho commented on src/main/java/in/koreatech/koin/domain/user/service/StudentService.java
> +        user.userInfoUpdate(studentUpdateRequest.nickname(), studentUpdateRequest.name(),
### R
info라는 네이밍이 다소 추상적이게 다가올 수 있어요
그냥 `update`는 어떨까요?

```suggestion
        user.update(studentUpdateRequest.nickname(), studentUpdateRequest.name(),
```

참고자료: https://github.com/Yooii-Studios/Clean-Code/blob/master/Chapter%2002%20-%20%EC%9D%98%EB%AF%B8%20%EC%9E%88%EB%8A%94%20%EC%9D%B4%EB%A6%84.md#%EC%9D%98%EB%AF%B8-%EC%9E%88%EA%B2%8C-%EA%B5%AC%EB%B6%84%ED%95%98%EB%9D%BC%EB%B6%88%EC%9A%A9%EC%96%B4-noise-word-%EB%A5%BC-%EC%93%B0%EC%A7%80-%EB%A7%90%EC%9E%90

2024-03-27 02:44 UTC, Choi-JJunho commented on src/main/java/in/koreatech/koin/domain/user/service/StudentService.java
> +        student.studentInfoUpdate(studentUpdateRequest.studentNumber(),
### R

> info라는 네이밍이 다소 추상적이게 다가올 수 있어요
그냥 update는 어떨까요?

ditto

2024-03-27 02:44 UTC, Choi-JJunho commented on src/test/java/in/koreatech/koin/acceptance/UserApiTest.java
> +                    .isEqualTo(student.getDepartment().name());
### R
name이랑 같아야하는게 맞아요? getValue 랑 같아야하는거 아닌가??

2024-03-27 04:26 UTC, duehee commented on src/test/java/in/koreatech/koin/acceptance/UserApiTest.java
> +                    .isEqualTo(student.getDepartment().name());
앗.. StudentDepartment ENUM 추가 이후 수정하지 않은 것 같습니다!

2024-03-27 04:27 UTC, duehee commented on src/main/java/in/koreatech/koin/domain/user/service/StudentService.java
> +        user.userInfoUpdate(studentUpdateRequest.nickname(), studentUpdateRequest.name(),
그렇다면 패스워드를 수정하는 메소드가 추가된다면, 그 메소드 이름을 따로 설정하는 것이 더 나을 수 있을 거 같네요!

2024-03-27 04:31 UTC, duehee commented on src/main/java/in/koreatech/koin/domain/user/dto/StudentResponse.java
> +            student.getDepartment().toString(),
Department 관련해서 추가하며 다른 요소들을 너무 신경쓰지 않은 것 같네요..! :<

2024-03-27 05:51 UTC, seongjae6751 approved these changes

2024-03-27 06:01 UTC, Choi-JJunho requested changes
고생하셨습니다~
Approve의 길은 멀고도 험하죠 ㅋㅋㅋ
코멘트 확인 부탁드릴게요~

2024-03-27 06:01 UTC, Choi-JJunho commented on src/main/java/in/koreatech/koin/domain/user/service/StudentService.java
> +            throw new StudentNumberNotValidException(
이거 반영이 안된거같아요~

2024-03-27 06:01 UTC, Choi-JJunho commented on src/main/java/in/koreatech/koin/domain/user/dto/StudentUpdateRequest.java
> +        String studentNumber
### R

아래 코멘트에서 나온 내용을 여기에 적용시켜보면 될 것 같아요
- https://github.com/BCSDLab/KOIN_API_V2/pull/236/files#r1536745436

2024-03-28 06:05 UTC, duehee commented on src/main/java/in/koreatech/koin/domain/user/model/User.java
> +        }
현재 업데이트 대상인 필드들은 NN이 걸려있지 않습니다!(DB)
확인하여 업데이트 수정해보았습니다! 확인해주시면 감사하겠습니당

2024-03-28 06:05 UTC, duehee commented on src/main/java/in/koreatech/koin/domain/user/model/UserGender.java
> +                .orElseThrow(() -> new IllegalArgumentException("잘못된 성별 인덱스 입니다. index : " + index));
이 사항은 추가적으로 custumException 작성해보았습니다!

2024-03-28 06:05 UTC, duehee commented on src/main/java/in/koreatech/koin/domain/user/service/StudentService.java
> +            throw new StudentNumberNotValidException(
반영하여 원래 있던 예외처리 구문을 삭제했습니다!

2024-03-28 11:55 UTC, songsunkook requested changes
거의 다 온 것 같은데 조금만 더 힘내봅시다..!
화이팅~

2024-03-28 11:55 UTC, songsunkook commented on src/main/java/in/koreatech/koin/domain/user/model/Student.java
> +    private StudentDepartment department;
### R
major에서 department로 컬럼명을 다르게 매핑한 이유가 있나요? DB와 헷갈릴 것 같아요

+) 중요한 내용인데, 이거 잘 실행되나요? **에러 납니다.** 푸시 전에는 로컬에서 반드시 실행해보시기 바랍니다.

2024-03-28 11:55 UTC, songsunkook commented on src/main/java/in/koreatech/koin/domain/user/service/StudentService.java
> +        }
### C
짜잘한 내용이지만 닉네임 검증 로직은 메서드를 분리하는 것도 좋아 보이네요

2024-03-28 13:15 UTC, duehee commented on src/main/java/in/koreatech/koin/domain/user/service/StudentService.java
> +        }
따로 Service 내 메소드를 작성하도록 하겠습니다!!!

2024-03-29 03:28 UTC, Choi-JJunho approved these changes
고생하셨습니다~
작은 컨벤션들만 확인 부탁드릴게요

2024-03-29 03:28 UTC, Choi-JJunho commented on src/main/java/in/koreatech/koin/domain/user/dto/StudentUpdateResponse.java
> +    @Schema(description = "이름 \n", example = "최준호")
### R
> 불필요한 내용같네요

ditto
```suggestion
    @Schema(description = "이름", example = "최준호")
```

2024-03-29 03:28 UTC, Choi-JJunho commented on src/main/java/in/koreatech/koin/domain/user/service/StudentService.java
> +
### A

개인 취향입니다만 메소드 내부에 있는 친구들은 붙여줘도 좋지 않을까용
```suggestion
        Student student = studentRepository.getById(userId);
        User user = student.getUser();
        if (studentUpdateRequest.nickname() != null &&
            userRepository.existsByNickname(studentUpdateRequest.nickname())) {
            throw DuplicationNicknameException.withDetail("nickname : " + studentUpdateRequest.nickname());
        }
        user.update(studentUpdateRequest.nickname(), studentUpdateRequest.name(),
            studentUpdateRequest.phoneNumber(), UserGender.from(studentUpdateRequest.gender()));
        student.update(studentUpdateRequest.studentNumber(),
            StudentDepartment.from(studentUpdateRequest.major()));
        studentRepository.save(student);

```

2024-03-29 03:28 UTC, Choi-JJunho commented on src/test/java/in/koreatech/koin/acceptance/UserApiTest.java
> +        studentRepository.save(student);
### A

어짜피 인증에서 거르는 테스트면 저장 안해도되지않을까요

2024-03-29 03:40 UTC, duehee commented on src/main/java/in/koreatech/koin/domain/user/service/StudentService.java
> +
저는 주로 작동하는 단위로 끊는 편인데, 코드 내에서는 스타일 통일 해보겠습니당

2024-03-29 03:43 UTC, duehee commented on src/test/java/in/koreatech/koin/acceptance/UserApiTest.java
> +        studentRepository.save(student);
테스트 상단의 get /user/student/me 401번 오류 검증 과정과 동일하게 구성해보았습니다!

2024-03-29 03:54 UTC, duehee commented on src/main/java/in/koreatech/koin/domain/user/model/Student.java
> +    private StudentDepartment department;
기존에 작성되어있던 Student의 major 매핑의 컬럼명이 department여서 동일하게 Enum 생성하는 과정에서 이름 사용했습니다!

2024-03-29 16:28 UTC, duehee commented
이번에 로컬 환경에서 확인하면서 작동해본 결과, 오류가 많이 발생해서 추가한 사항들입니다!
gender, department 등 현재 enum으로 작동하고 있는 코드들에 null 값을 허용하도록 메소드를 조금 수정했습니다.
(.ordinal() 사용 시 intValue() 호출로 인한 Npe 발생 및 department.getValue() 사용 간 동일한 npe 발생)
무분별한 null 사용은 문제가 될 수 있지만, DB 상으로 null 값이 문제가 없는 사항들이라 판단하여 추가했습니다.
코드가 조금 지저분한 점은 있지만, 감안하여 작성해봤습니다. 어떻게 수정하면 좋을지 의견 있으시다면 달아주세요!

2024-03-30 03:40 UTC, songsunkook requested changes
자세한 내용은 DM으로 설명해드렸으니 좀 더 고민해보고 알려주세요
아직 500에러 날겁니다

2024-03-30 06:01 UTC, songsunkook requested changes

2024-03-30 06:01 UTC, songsunkook commented on src/main/java/in/koreatech/koin/domain/user/service/StudentService.java
> +    }
### R
이렇게 검증이 필요하다면 차라리 enum 클래스로 빼서 검증하는 건 어떨까요?

2024-03-30 06:51 UTC, duehee commented on src/main/java/in/koreatech/koin/domain/user/service/StudentService.java
> +    }
수정 완료했습니다!!!!!

2024-03-30 07:21 UTC, songsunkook approved these changes
코멘트 70개의 전설..
정말 고생하셨습니다 ! 👍

2024-03-30 07:22 UTC, merged