feat : 영양사 품절 정보 입력
BCSDLab/KOIN_API_V2 pull request #238
Opened 2024-03-23 16:18 UTC by dradnats1012

# 🔥 연관 이슈

- close #220 

# 🚀 작업 내용

1. dining_menus 테이블에 sold_out 컬럼 추가
2. 영양사가 `coop/dining/soldout` 경로로 메뉴아이디와 품절 여부 요청
3. 로직 관련 클래스 추가
4. 권한 `COOP`이 아닐 경우 권한 오류

# 💬 리뷰 중점사항
- update 관련 쿼리이다보니 테스트를 어떤식으로 진행할지 몰라 테스트 관련 jpa를 추가해서 테스트를 진행했는데 다른 방법이 생각나시면 알려주세요ㅠㅠ
- 원래 품절요청만 보낼 수 있고 반대로 돌리는것은 못하도록 짜려고 했는데 추후에 확장할 수도 있어서 품절 취소도 가능하도록 짰습니다. 요청을 보낼때 품절만 보내도록 해야할 것 같아요
- 많은 피드백 부탁드립니당 - 더 좋은 방법이 있으시면 바로 말해주세요!

2024-03-23 17:14 UTC, Choon0414 requested changes
늦은 시간까지 고생하셨어요!

2024-03-23 17:14 UTC, Choon0414 commented on src/test/java/in/koreatech/koin/acceptance/DiningApiTest.java
> +    @DisplayName("품절 요청을 보낸다")
### A ###

'영양사 권한으로 품절 요청을 보낸다'처럼 구체적으로 적어도 좋을 것 같아요!

2024-03-24 04:07 UTC, dradnats1012 commented on src/main/java/in/koreatech/koin/domain/dining/controller/CoopDiningController.java
> +    @PostMapping("/coop/dining/soldout")
하나만 바꾸는 거라 patch가 적절해 보이네요 
감사합니다!!!

2024-03-24 04:07 UTC, dradnats1012 commented on src/main/java/in/koreatech/koin/domain/dining/controller/CoopDiningApi.java
> +        @RequestBody SoldOutRequest soldOutRequest
확인 못했네요 ㅠㅠ 👍

2024-03-24 07:58 UTC, songsunkook requested changes
도메인 팀으로써의 첫 PR 고생하셨습니다! 👍
Repository에 관해 주로 코멘트 남겨드렸으니 확인 부탁드립니다

2024-03-24 07:58 UTC, songsunkook commented on src/main/java/in/koreatech/koin/domain/dining/repository/DiningRepository.java
> +    Long findSoldOut();
### R
객체를 조회하여 필드를 조회할 수도 있지 않을까요?

+) 저렇게 실행하면 품절된 모든 메뉴가 반환되지 않나요? 그럼 품절된 메뉴가 2개 이상 존재할 시 반환 타입이 맞지 않아 에러가 발생할 것 같습니다. 추가로 메뉴가 오랜 기간 누적된다면 극단적인 경우 10년 전 품절된 메뉴까지 불러오게 될 것 같습니다.

2024-03-24 07:58 UTC, songsunkook commented on src/main/java/in/koreatech/koin/domain/dining/repository/DiningRepository.java
> +    void updateSoldOut(@Param("menuId") Long menuId, @Param("soldOut") Boolean soldOut);
### R
네이티브 쿼리를 반드시 사용해야만 했나요?? 어떤 근거로 사용하신 것인지 궁금합니다.

2024-03-24 08:39 UTC, dradnats1012 commented on src/main/java/in/koreatech/koin/domain/dining/controller/CoopDiningController.java
> +    private final CoopDiningService soldOutService;
처음에 클래스명을 SoldOutService로 했다가 변경했는데 변수명은 변경이 안된것 같네요 :(
감사합니다!

2024-03-25 04:32 UTC, dradnats1012 commented on src/main/java/in/koreatech/koin/domain/dining/service/CoopDiningService.java
> +@Transactional
수정하겠습니다!

2024-03-25 04:45 UTC, dradnats1012 commented on src/main/java/in/koreatech/koin/domain/dining/repository/DiningRepository.java
> +    Long findSoldOut();
객체를 조회하여 `soldOut` 값과 비교하는 방법으로 변경했습니다!
이 방법을 생각 못해서 통과하는 테스트를 만들기 위해 그랬던 것 같습니다

2024-03-25 04:46 UTC, dradnats1012 commented on src/main/java/in/koreatech/koin/domain/dining/repository/DiningRepository.java
> +    void updateSoldOut(@Param("menuId") Long menuId, @Param("soldOut") Boolean soldOut);
jpa 명명법을 사용해서 특정 컬럼 값 하나만 바꾸는 방법을 찾지 못해 네이티브 쿼리를 사용했습니다!

2024-03-26 06:26 UTC, Choon0414 approved these changes
리뷰 반영 엄청 빨리 해주셨네요. 고생하셨습니다!

2024-03-26 06:26 UTC, Choon0414 commented on src/main/java/in/koreatech/koin/domain/coop/service/CoopService.java
> +        dining.setSoldOut(soldOutRequest.soldOut());
### C ###

좋은 방법이네요! 하나 배워갑니다.
추가로 setter를 통해 하나를 변경해도 모든 컬럼에 대한 update 요청이 전송된다고 합니다.
그래서 필드가 클 경우 엔티티에 `@DynamicUpdate`를 추가해서 수정된 칼럼만 update 요청하는 방법도 있다고 하니 참고하셔도 좋을 것 같아요!
[@DynamicUpdate 참고자료](https://rudaks.tistory.com/entry/spring-data-jpa%EC%9D%98-DynamicUpdate)

2024-03-26 06:43 UTC, songsunkook commented on src/main/java/in/koreatech/koin/domain/coop/service/CoopService.java
> +        dining.setSoldOut(soldOutRequest.soldOut());
오 신기하네요..!!
다만 실제로 사용할 경우는 많이 드물 것 같아요
[참고자료](https://www.inflearn.com/questions/16697/%EC%97%85%EB%8D%B0%EC%9D%B4%ED%8A%B8-%EA%B3%A0%EA%B2%AC-%EA%B5%AC%ED%95%A9%EB%8B%88%EB%8B%A4)

2024-03-26 11:29 UTC, songsunkook approved these changes
고생하셨습니다!! 👍👍

2024-03-26 11:30 UTC, merged