feat: 메뉴 변경 여부 추가
BCSDLab/KOIN_API_V2 pull request #250
Opened 2024-03-28 06:37 UTC by ImTotem

# 🔥 연관 이슈

- close #222 

# 🚀 작업 내용

1. 메뉴 변경 여부 추가

# 💬 리뷰 중점사항

2024-03-28 09:51 UTC, Choi-JJunho requested changes
Flyway로 컬럼추가해주세요

2024-03-30 07:18 UTC, dradnats1012 approved these changes
고생하셨습니다!

2024-03-30 07:20 UTC, Choon0414 approved these changes
고생하셨습니다!!

2024-04-01 05:34 UTC, Choi-JJunho approved these changes
여기저기 갔다오다보니 늦었네요 😅
고생하셨습니다

2024-04-01 05:34 UTC, merged