Feature/254 notification detail
BCSDLab/KOIN_API_V2 pull request #269
Opened 2024-03-30 13:33 UTC by Choon0414

# 🔥 연관 이슈

- close #254 

# 🚀 작업 내용

1. 구독 알림 관련 Api를 작성하였습니다.

# 💬 리뷰 중점사항
전체 구독은 `deviceToken`의 등록과 삭제로 여부를 판단하고
특정 알림 구독은 notification_subscribe 테이블 내에서 `user_id`로 `type`을 조회하여 여부를 판단합니다.

다음부턴 브랜치 생성 유의해서 이전 로그는 안남기도록 하겠습니다.

2024-03-30 14:32 UTC, songsunkook requested changes
다들 고생하셨습니다!
조금만 수정 부탁드려요

2024-03-30 14:32 UTC, songsunkook commented on src/main/resources/db/migration/V5__add_notification_subscribe_table.sql
> +    user_id        BIGINT                NOT NULL,
### R
이거 fk 설정중에 에러날수도 있을 것 같아요! 
```suggestion
    user_id        BIGINT UNSIGNED                NOT NULL,
```

2024-03-31 03:53 UTC, ImTotem requested changes
수고하셨습니다!

2024-03-31 03:53 UTC, ImTotem commented on src/main/resources/db/migration/V5__add_notification_subscribe_table.sql
> +    user_id        BIGINT                NOT NULL,
### C

늦게 머지될 쪽이 V6__ 으로 바꿔야 되겠네요

#250

2024-03-31 03:53 UTC, ImTotem commented on src/test/java/in/koreatech/koin/acceptance/NotificationApiTest.java
> +            .log().all()
### C
`.log().all()`은 로컬에서 디버깅용으로 사용하고 푸시할 때는 지워주세요
> <img width="488" alt="image" src="https://github.com/BCSDLab/KOIN_API_V2/assets/46699595/be41b0a8-0f4d-4ff3-a9c0-68690444ebed">

2024-03-31 03:53 UTC, ImTotem commented on src/test/java/in/koreatech/koin/acceptance/NotificationApiTest.java
> +            .log().all()
> ### C
> `.log().all()`은 로컬에서 디버깅용으로 사용하고 푸시할 때는 지워주세요

22

2024-03-31 03:53 UTC, ImTotem commented on src/test/java/in/koreatech/koin/acceptance/NotificationApiTest.java
> +            .then().log().all()
> ### C
> `.log().all()`은 로컬에서 디버깅용으로 사용하고 푸시할 때는 지워주세요

333

2024-03-31 03:53 UTC, ImTotem commented on src/test/java/in/koreatech/koin/acceptance/NotificationApiTest.java
> +            .then().log().all()
> ### C
> `.log().all()`은 로컬에서 디버깅용으로 사용하고 푸시할 때는 지워주세요

4444

2024-03-31 05:43 UTC, Choon0414 commented on src/main/java/in/koreatech/koin/global/domain/notification/exception/SubscribeNotFoundException.java
> +public class SubscribeNotFoundException extends DuplicationException {
DataNotFoundException을 상속받도록 수정했습니다!

2024-03-31 05:45 UTC, Choon0414 commented on src/main/resources/db/migration/V5__add_notification_subscribe_table.sql
> +    user_id        BIGINT                NOT NULL,
user_id가 unsigned int로 되어있어서 일단 user_id와 같게 수정했습니다!
나중에 두 개를 같이 unsigned bigint로 수정하는게 좋을 것 같아요

2024-03-31 05:45 UTC, Choon0414 commented on src/test/java/in/koreatech/koin/acceptance/NotificationApiTest.java
> +            .log().all()
수정했습니다!

2024-04-01 00:38 UTC, songsunkook approved these changes
리뷰 반영 확인했습니다! 고생하셨습니당 👍

2024-04-01 00:38 UTC, songsunkook commented on src/main/resources/db/migration/V5__add_notification_subscribe_table.sql
### A
라인 포맷팅 한 번만 해주세요~

2024-04-01 01:00 UTC, ImTotem approved these changes

2024-04-01 01:01 UTC, Choi-JJunho approved these changes
고생하셨습니다~
테스트 통과랑 자잘한 부분은 수정했습니다

2024-04-01 01:01 UTC, merged