Feature/24 user student register
BCSDLab/KOIN_API_V2 pull request #271
Opened 2024-03-31 15:04 UTC by kwoo28

# 🔥 연관 이슈

- close #24

# 🚀 작업 내용

1. 학생 회원가입시 DB에 저장합니다.

2. 가입시 이메일에 인증폼이 전송되며, 슬랙에 이벤트를 발생시킵니다.

# 💬 리뷰 중점사항
1. 인증확인시 폼을 modelAndView를 통해 폼을 반환시키는데, 이러한 방법이 효율적인지 궁금합니다.

2024-04-01 05:07 UTC, Choi-JJunho requested changes
고생하셨습니다~
가장 핵심 기능이라고 생각되는 부분을 빠르게 구현해주셨네요 👍
핵심인만큼 꼼꼼히 살펴봐야할 부분도 많은 것 같아요
코멘트 확인해주세요

2024-04-01 05:07 UTC, Choi-JJunho commented on src/main/java/in/koreatech/koin/global/exception/GlobalExceptionHandler.java
> +    }
잘못된 이메일 형식, 학번형식과 같은정보는 400 예외가 적절하다고 생각하는데 어떻게 생각하시나요?

MDN 및 RFC에 표기되어있기로는 내용에 의하면 xml 형태의 문법이 잘못 이뤄진 경우에 422에러를 사용한다고 이야기하고있습니다.
물론 팀 내에서 정의하고 사용하기에 따라 다르겠지만 딱히 정해져있지 않은 지금으로는 `사용자의 잘못된 입력으로 발생하는 예외이므로 400을 반환해야한다.`라는 입장입니다.

참고자료:
- https://www.rfc-editor.org/rfc/rfc4918#section-11.2
- https://stackoverflow.com/questions/16133923/400-vs-422-response-to-post-of-data

2024-04-01 05:07 UTC, Choi-JJunho commented on src/main/resources/mail/error_config.html
> +    location.href = '//koreatech.in';
### A
단순 궁금한건데 앞에 프로토콜이 없어도 되는건가용

2024-04-01 05:07 UTC, Choi-JJunho commented on src/main/resources/mail/error_config.html
> +</head>
### R
로컬에서 해당 인증폼이 발행되는 시나리오를 수행하고 발행되는 메일 캡쳐해서 PR 본문에 올려주세요

ex) 
<img width="1103" alt="image" src="https://github.com/BCSDLab/KOIN_API_V2/assets/49794401/76af53be-c2eb-4fd0-9aa4-24394829d4f1">

2024-04-01 05:07 UTC, Choi-JJunho commented on src/test/java/in/koreatech/koin/acceptance/UserApiTest.java
> +
### R
불필요한 공백

2024-04-01 05:31 UTC, kwoo28 commented on src/main/java/in/koreatech/koin/domain/user/service/StudentService.java
> +        Optional<User> user = userRepository.findByAuthToken(request.authToken());
현재 로직은 findByAuthToken을 통해 해당 유저가 null값이라면 error_config폼으로 반환시켜주려 했습니다. 근데 예외처리를 사용하는 getBy를 이용하게되면 폼으로 반환시키지 못할것같아 findBy를 사용했습니다.

2024-04-01 05:31 UTC, kwoo28 commented on src/main/java/in/koreatech/koin/domain/dept/model/Dept.java
> +        return true;
넵!

2024-04-01 05:31 UTC, kwoo28 commented on src/main/java/in/koreatech/koin/domain/user/model/AuthResult.java
> +
넵 숙지하겠습니다.

2024-04-01 05:32 UTC, kwoo28 commented on src/main/java/in/koreatech/koin/domain/user/service/StudentService.java
> +    }
불필요한 공백이 많은것보다 붙이는게 가독성이 좋은것같네요!

2024-04-01 05:39 UTC, kwoo28 commented on src/main/java/in/koreatech/koin/global/auth/SHA256Util.java
> +public class SHA256Util {
기존 코인이 SHA256Util를 이용해서 authToken을 암호화해서 사용했습니다.  이미 구현되어있는 JwtProvider의 createTemporaryToken()메서드를 이용하는 방식으로 고치겠습니다

2024-04-01 05:41 UTC, kwoo28 commented on src/main/java/in/koreatech/koin/domain/user/model/AuthResult.java
> +@RequiredArgsConstructor(staticName = "of")
기존 코인에서 이렇게 사용해서 그대로 적었던것같습니다.. 다시 고치겠습니다!

2024-04-01 05:46 UTC, kwoo28 commented on src/main/java/in/koreatech/koin/domain/user/service/StudentService.java
> +    }
같은방식입니다.. 잊고있었네요. IPAddress 사용하겠습니다.

2024-04-01 06:23 UTC, kwoo28 commented on src/main/java/in/koreatech/koin/domain/user/model/User.java
> +    }
그게 좋아보이네요.!

2024-04-01 06:26 UTC, kwoo28 commented on src/main/java/in/koreatech/koin/global/date/DateUtil.java
> +}
어..토큰 만료시간을 현재 시각에서 +1시간을 추가할 용도로 코인에서 쓰이길래 사용했습니다.

2024-04-01 06:26 UTC, kwoo28 commented on src/main/java/in/koreatech/koin/global/domain/email/model/EmailAddress.java
> +    public void validatePortalEmail() {
좋은것같습니다.

2024-04-01 06:28 UTC, kwoo28 commented on src/main/resources/mail/error_config.html
> +</head>
넵

2024-04-01 06:30 UTC, kwoo28 commented on src/main/resources/mail/error_config.html
> +    location.href = '//koreatech.in';
네..로컬에서 사용했을때 없어도 작동하길래 문제없는것같았습니다

2024-04-01 08:28 UTC, kwoo28 commented on src/main/java/in/koreatech/koin/domain/user/service/StudentService.java
> +    }
다시 보니까 IPAddress는 클라이언트 ip를 얻는 과정이고, getHost()는 서버호스트를 얻어오는 과정이라 작성하는게 맞다고 생각합니다...

2024-04-01 16:32 UTC, kwoo28 commented on src/main/java/in/koreatech/koin/global/auth/SHA256Util.java
> +public class SHA256Util {
authToken은 SHA256삭제하고 passwordEncoder.encode(authExpiredAt)를 통해 암호화 시키는 방식으로 변경했습니다.

2024-04-01 16:35 UTC, kwoo28 commented on src/main/java/in/koreatech/koin/domain/dept/model/Dept.java
> +        return true;
StudentRegisterRequest를 student로 변환하는 과정에서 UserIdentity는 0으로 설정해서, null값이거나 다른 값이 들어갈 상황이 나오지 않기때문에, request에서 학번의 길이만10인지 검증하고, service에서 학번년도를 1992년에서 현재년도에 해당하는지 검증하는 로직으로 수정했습니다.

2024-04-02 01:04 UTC, Choi-JJunho requested changes
코멘트 몇개 확인 부탁드려욥

2024-04-02 01:04 UTC, Choi-JJunho commented on src/main/java/in/koreatech/koin/global/domain/email/model/EmailAddress.java
> +    private static final String domainSeparator = "@";
### R

상수는 대문자로 적어주세요~
```suggestion
    private static final String DOMAIN_SEPARATOR = "@";
```

참고: https://www.oracle.com/java/technologies/javase/codeconventions-namingconventions.html

2024-04-02 01:04 UTC, Choi-JJunho commented on src/main/java/in/koreatech/koin/global/domain/email/model/EmailAddress.java
> +    private static final String PORTAL_DOMAIN = "koreatech.ac.kr";
### R
```suggestion
    private static final String KOREATECH_DOMAIN = "koreatech.ac.kr";
```

2024-04-02 02:15 UTC, kwoo28 commented on src/main/java/in/koreatech/koin/domain/dept/model/Dept.java
> +    }
여기서 예외반환도 처리할 수 있으니 로직이 단순해지네요. 감사합니다

2024-04-02 02:15 UTC, kwoo28 commented on src/main/java/in/koreatech/koin/domain/user/dto/StudentRegisterRequest.java
> +        example: asdf1234!
수정했습니다!

2024-04-02 02:15 UTC, kwoo28 commented on src/main/java/in/koreatech/koin/global/domain/email/model/EmailAddress.java
> +    private static final String domainSeparator = "@";
넵. 수정했습니다

2024-04-02 02:16 UTC, kwoo28 commented on src/main/java/in/koreatech/koin/global/domain/email/model/EmailAddress.java
> +    private static final String PORTAL_DOMAIN = "koreatech.ac.kr";
수정했습니다.

2024-04-02 02:16 UTC, kwoo28 commented on src/main/java/in/koreatech/koin/global/exception/DataInvalidException.java
> +}
수정햇습니다.

2024-04-02 02:16 UTC, kwoo28 commented on src/main/java/in/koreatech/koin/global/domain/email/form/StudentRegistrationData.java
> +        return Map.of("contextPath", contextPath, "authToken", authToken);
이게 더 보기 편한것같네요! 수정하겠습니다.

2024-04-02 02:17 UTC, kwoo28 commented on src/main/java/in/koreatech/koin/domain/user/service/StudentService.java
> +    }
@IpAddress어노테이션처럼 @Host어노테이션을 지정하여 파라미터를 통해 서버호스트를 얻어오는 방식은 어떨까요?

2024-04-02 03:08 UTC, kwoo28 commented on src/main/java/in/koreatech/koin/domain/user/service/StudentService.java
> +    public static final String MAIL_SUCCESS_REGISTER_CONFIG = "success_register_config";
잘못둔것같습니다.. Service에 public으로 상수를 둘 이유가 없네요.. 수정해보겠습니다.!

2024-04-02 04:09 UTC, Choi-JJunho commented on src/main/java/in/koreatech/koin/domain/user/service/StudentService.java
> +    }
어떤 호스트인지도 명시할수 있게 만들어도 좋아보이네요
ex) `@Host(server=true)`

2024-04-02 05:27 UTC, songsunkook commented
### A
기존 코인 이메일 폼 보면 제가 리마스터한 폼(약간의 버그가 첨부된)이 있는데 그걸로 적용하기는 힘들까요??
나중에 시간되면 해보면 좋을 것 같아요
<img width="1291" alt="image" src="https://github.com/BCSDLab/KOIN_API_V2/assets/21010656/613e34cf-8132-4845-b22e-070763794583">
백그라운드 이미지가 오른쪽에 붙어있어야 하는데 지메일에서는 왼쪽에 붙고, 네이버에서는 위로 분리되더라구요.. 고치면 참 예쁜데

2024-04-02 15:52 UTC, kwoo28 commented on src/main/java/in/koreatech/koin/global/date/DateUtil.java
> +}
clock을 이용하면 테스트시 시간을 조종할 수 있어서 유용해서 그런걸까요?? 그리고 굳이 DateUtil을 쓰지 않아도 시간을 추가시켜주는 기능이 LocalDate에 있었군요...

2024-04-02 16:31 UTC, duehee requested changes
어우 고생하셨습니다..!!
비밀번호 찾기 구현하며 회원가입 레거시도 보고 있는데 너무 어지럽더라구요..
저도 추가적으로 찾게 된다면 코멘트 더 드리겠습니당 :D

2024-04-02 17:21 UTC, kwoo28 commented on src/main/java/in/koreatech/koin/domain/user/dto/StudentRegisterRequest.java
> +    @Schema(description = "전공{기계공학부, 컴퓨터공학부, 메카트로닉스공학부, 전기전자통신공학부, 디자인건축공학부, 에너지신소재화학공학부, 산업경영학부}", example = "컴퓨터공학부")
수정하겠습니다!

2024-04-03 01:48 UTC, daheeParkk approved these changes
수고하셨습니다 😋

2024-04-03 01:48 UTC, daheeParkk commented on src/main/java/in/koreatech/koin/domain/user/model/AuthResult.java
> +    public ModelAndView toModelAndViewForStudent() {
### A

`ModelAndView` 이런 것도 있군요..! 사용하기 편리해 보여서 좋은 것 같습니다!

2024-04-03 01:48 UTC, daheeParkk commented on src/main/java/in/koreatech/koin/domain/user/service/StudentService.java
> +        mailService.sendMail(request.email(), new StudentRegistrationData(host, student.getUser().getAuthToken()));
### A

host는 왜 필요한 건가요?

2024-04-03 02:39 UTC, kwoo28 commented on src/main/java/in/koreatech/koin/domain/user/service/StudentService.java
> +        mailService.sendMail(request.email(), new StudentRegistrationData(host, student.getUser().getAuthToken()));
회원가입 인증폼에서 인증버튼 누를시 서버의 api인증 요청이 될수있게 하려면 서버호스트를 얻어와야돼서 필요하다고 생각했습니다.

2024-04-03 03:22 UTC, seongjae6751 requested changes
어려운 부분인데 정말 빠르게 구현해주셨네요
이번 부분에서 저는 공부해야 할 부분이 엄청 많은 것 같습니다
추가로 공부하면서 보이는 것 있으면 리뷰 계속 달게요
정말 고생 많으셨습니다!

2024-04-03 04:45 UTC, Choi-JJunho requested changes
고생하셨습니다~
여기도 conversation 100개가 예상되는군요
코멘트 확인해주세요~

2024-04-03 04:45 UTC, Choi-JJunho commented on src/main/java/in/koreatech/koin/domain/user/dto/StudentRegisterRequest.java
> +        User user = User.builder()
### A
붙여주는거 어떤가요

2024-04-03 04:45 UTC, Choi-JJunho commented on src/main/java/in/koreatech/koin/domain/user/dto/StudentRegisterRequest.java
> +        LocalDateTime authExpiredAt = LocalDateTime.now().plusHours(1);
### R
clock을 인자로 받을수있도록 구성해야할것 같아요

2024-04-03 04:45 UTC, Choi-JJunho commented on src/main/java/in/koreatech/koin/domain/user/dto/StudentRegisterRequest.java
> +            .authToken(passwordEncoder.encode(authExpiredAt))
### C
해당 authToken의 활용처가 궁금합니다
단순히 만료일자를 계산하는 값이라면 굳이 필요한 값인가 싶네요?
Redis를 사용하면 안되는건가요?

2024-04-03 04:45 UTC, Choi-JJunho commented on src/main/java/in/koreatech/koin/domain/user/model/User.java
> +    }
### C
이 메소드 재사용성이 높은 로직인가요?
유저 객체가 주체적으로 수행해야할 작업이 맞나요?

2024-04-03 04:45 UTC, Choi-JJunho commented on src/main/java/in/koreatech/koin/domain/user/service/StudentService.java
> +        if (admissionYear.compareTo("1992") < 0
### C
equals를 사용하지않고 compareTo를 사용한 이유가있나요?
처음 봤을 때 해당 로직이 무엇을 검증하는지 직관적으로 이해할 수 있나요?

2024-04-03 04:45 UTC, Choi-JJunho commented on src/main/java/in/koreatech/koin/domain/user/service/StudentService.java
> +            || admissionYear.compareTo((new LocalDate()).toString().substring(0, 4)) > 0) {
### R
이 로직을 봤을때 의문점이 너무 많이 들어요

1. new LocalDate() 를 했을 때 무슨 값이 나오나요?
2. LocalDate를 toString() 했을 때 무슨 값이 나오나요?
3. LocalDate를 toString()한 값의 0,4번째를 substring 하면 무슨 값이 나오나요?
4. admissionYear.compareTo("문자열")을 했을 때 `> 0`, `< 0`, `== 0` 각각이 의미하는 바가 무엇인가요?

다른 사람들이 이 코드를 읽었을 때 한번에 이해하고 건드릴 수 있을까요?
의도를 명확히 해보시길 바랍니다 :)

2024-04-03 04:45 UTC, Choi-JJunho commented on src/main/java/in/koreatech/koin/global/host/HostArgumentResolver.java
> +        return null;
### A
host라는 개념이 뭔가요?
클라이언트의 host는 얻지 않아도되는건가요?

2024-04-03 04:45 UTC, Choi-JJunho commented on src/main/java/in/koreatech/koin/global/host/HostInterceptor.java
> +}
### R
이 로직이 한번에 읽히나요? 결과물이 무엇이 나오는지 저는 잘 모르겠네요
조금은 더 간결하게 작성해볼 필요도 있을거에요
```suggestion
    @Override
    public boolean preHandle(HttpServletRequest request, HttpServletResponse response, Object handler) {
        String host = getHost(request);
        hostContext.setHost(host);
        return true;
    }
    
    public String getHost(HttpServletRequest request) {
        String scheme = request.getScheme();
        String serverName = request.getServerName();
        int serverPort = request.getServerPort();
    
        return (serverPort != 80 && serverPort != 443) ?
                String.format("%s://%s:%d", scheme, serverName, serverPort) :
                String.format("%s://%s", scheme, serverName);
    }
```

2024-04-03 04:45 UTC, Choi-JJunho commented on src/main/java/in/koreatech/koin/global/host/HostContext.java
> +}
### R

추가로 의문이 드는점은 host가 서버 호스트만 존재하나요?
그렇다면 `@Host`의 server 속성은 무엇을 의미하나요?

2024-04-03 04:55 UTC, kwoo28 commented on src/main/java/in/koreatech/koin/domain/user/dto/StudentRegisterRequest.java
> +        User user = User.builder()
붙여주겠습니다

2024-04-03 04:56 UTC, kwoo28 commented on src/main/java/in/koreatech/koin/domain/user/dto/StudentRegisterRequest.java
> +        LocalDateTime authExpiredAt = LocalDateTime.now().plusHours(1);
알겠습니다!

2024-04-03 05:05 UTC, kwoo28 commented on src/main/java/in/koreatech/koin/domain/user/dto/StudentRegisterRequest.java
> +            .authToken(passwordEncoder.encode(authExpiredAt))
만료일자를 계산하기보단 암호화하여 메일 인증할때 authToken으로 mysql상에 있는 회원의 authToken을 일치하는지 여부입니다. 근데 이미 mysql에 authToken 들어갈 수 있는 속성값이 있는데, Redis를 이용했을때의 장점이 있을까요? 아직 redis를 활용한적이 없어서 잘 감이안와서요..

2024-04-03 05:06 UTC, kwoo28 commented on src/main/java/in/koreatech/koin/domain/user/model/User.java
> +    }
유저 객체에 들어가기엔 적합하지 않고 재사용성이 높지가 않네요.. 수정하겠습니다.

2024-04-03 05:07 UTC, Choi-JJunho commented on src/main/java/in/koreatech/koin/domain/user/dto/StudentRegisterRequest.java
> +            .authToken(passwordEncoder.encode(authExpiredAt))
단순 비교라면 더욱 궁금증이 듭니다.
랜덤하게 생성되는 UUID가 아닌 `passwordEncoder.encode(authExpiredAt)` 가되어야만 하는 이유가 있나요?

2024-04-03 05:09 UTC, kwoo28 commented on src/main/java/in/koreatech/koin/domain/user/service/StudentService.java
> +        if (admissionYear.compareTo("1992") < 0
equals 사용한다는 방식을 잊고있었네요.. subString으로 학번의 년도를 추출하는 과정인데 아무래도 처음 보면 무엇을 의미하는지 직관적으로 알 수 없으니, 직관적으로 알 수 있는 메서드명을 이용하여 수정해보겠습니다!

2024-04-03 05:16 UTC, kwoo28 commented on src/main/java/in/koreatech/koin/domain/user/dto/StudentRegisterRequest.java
> +            .authToken(passwordEncoder.encode(authExpiredAt))
그냥 단순히 암호화 시키고자 encode메서드 사용했는데, 다른 사람이 보면 의문점이 드는 코드로 보일수 밖에 없겠군요... 수정해보겠습니다

2024-04-03 05:21 UTC, kwoo28 commented on src/main/java/in/koreatech/koin/domain/user/service/StudentService.java
> +            || admissionYear.compareTo((new LocalDate()).toString().substring(0, 4)) > 0) {
new LocalDate() 를하면 현재 년도 월 일로 출력되는걸로 생각했는데, 다시한번 체크해보겠습니다. 비교연산자는 이른 시간인지, 지난시간인지 체크하고자 적용했는데, 아무래도 다른 사람은 코드 보고 이해하는데 시간이 걸릴것같네요 ㅠ 수정해보겠습니다

2024-04-03 05:38 UTC, kwoo28 commented on src/main/java/in/koreatech/koin/global/host/HostArgumentResolver.java
> +        return null;
host는 프로토콜, 도메인, 포트등을 포함하는 네트워크 고유의 장치라고 이해했습니다. 클라이언트 host를 적지 않은 이유는 IpAddress도 있는데다가 굳이 클라이언트에서 host를 가져올일이 있을까싶어서 클라이언트에 해당하는건 따로 적지 않았습니다. 하지만 Host라는건 클라이언트, 서버의 개념에 다 들어가기때문에, Host는 Server를 대상으로 한다는걸 명확히 하고자 적어놨습니다.

2024-04-03 05:39 UTC, kwoo28 commented on src/main/java/in/koreatech/koin/global/host/HostArgumentResolver.java
> +        return null;
그런데 생각해보니 Host란 개념이 Ip 포함되기때문에 IPAddress어노테이션을 지우고 Host어노테이션에 포함시켜서, server일땐 프로토콜, 도메인이름, 포트를 String파라미터에 넣어주고, Client일땐 IpAddress값을 String 파라미터에 넣어주는게 어떨까 생각하긴했는데 이방법은 어떨까요??

2024-04-03 05:41 UTC, kwoo28 commented on src/main/java/in/koreatech/koin/global/host/HostInterceptor.java
> +}
오... 수정해주신 코드가 정말 간결해지고 직관적으로 무엇을 출력되는지도 알아보기가 정말 쉬워지네요...  써주신대로 수정해보겠습니다!

2024-04-03 05:46 UTC, kwoo28 commented on src/test/java/in/koreatech/koin/acceptance/UserApiTest.java
> +    @DisplayName("학생 회원가입을 후 학교 이메일요청 이벤트가 발생한다.")
이걸 캐치하시다니.. 수정해보겠습니다1

2024-04-03 05:47 UTC, kwoo28 commented on src/main/java/in/koreatech/koin/domain/user/service/StudentService.java
> +    public void StudentRegister(StudentRegisterRequest request, HttpServletRequest httpServletRequest) {
혹시 어디부분을 말씀하시는건지 알수 있을까요...?

2024-04-03 05:52 UTC, Choi-JJunho commented on src/main/java/in/koreatech/koin/domain/user/service/StudentService.java
> +    public void StudentRegister(StudentRegisterRequest request, HttpServletRequest httpServletRequest) {
메소드명이용~ `StudentRegister` PascalCase네요

2024-04-03 05:58 UTC, kwoo28 commented on src/main/java/in/koreatech/koin/domain/user/service/StudentService.java
> +    public void StudentRegister(StudentRegisterRequest request, HttpServletRequest httpServletRequest) {
헐 대문자로 되어있었네요..

2024-04-04 00:18 UTC, kwoo28 commented on src/main/java/in/koreatech/koin/domain/user/model/User.java
> +    }
기존 LocalTime필드를 "HH:mm"로 변환시켜주던 LocalTimeToStringConverter의 클래시이름을 LocalTimeToHHmmStringConverter로 변경했고, LocalTimeToYMDHMSStringConverter 객체 만들어서 expiredAt의 엔터티 타입을 LocalTime으로 변경하고 "yyyy-MM-dd HH:mm:ss"으로 DB에 변환되어 저장될 수 있게했습니다.

2024-04-05 05:02 UTC, seongjae6751 approved these changes

2024-04-08 07:27 UTC, Choi-JJunho requested changes
조금만 더..!! 코멘트 두개만 확인해주세요
고생하셨습니다

2024-04-08 07:27 UTC, Choi-JJunho commented on src/main/java/in/koreatech/koin/domain/user/model/AuthResult.java
> +        }).orElse(createErrorModelAndView("토큰에 해당하는 사용자를 찾을 수 없습니다."));
### C
orElseGet을 사용하는건 어떤가요
```suggestion
        }).orElseGet(createErrorModelAndView("토큰에 해당하는 사용자를 찾을 수 없습니다."));
```

2024-04-08 07:27 UTC, Choi-JJunho commented on src/main/java/in/koreatech/koin/domain/user/service/StudentService.java
> +            || new LocalDateTime().now().getYear() < studentNumberYear) {
### R
LocalDateTime의 정적 메소드를 활용할 수 있습니다.
추가로 clock도 주입해주세요
```suggestion
            || LocalDateTime.now(clock).getYear() < studentNumberYear) {
```

2024-04-08 07:36 UTC, kwoo28 commented on src/main/java/in/koreatech/koin/domain/user/service/StudentService.java
> +            || new LocalDateTime().now().getYear() < studentNumberYear) {
clock인자 넣어서 정적 메소드로 시도해봤는데 안되고,  현재 코드대로 해야만 되더라구요..

2024-04-08 07:43 UTC, kwoo28 commented on src/main/java/in/koreatech/koin/domain/user/model/AuthResult.java
> +        }).orElse(createErrorModelAndView("토큰에 해당하는 사용자를 찾을 수 없습니다."));
좋은것같습니다. 수정하겠습니다!

2024-04-08 08:17 UTC, Choi-JJunho approved these changes
Good 고생하셨습니다~

2024-04-08 08:19 UTC, merged