Fix: bearerToken 추출 오류 수정
BCSDLab/KOIN_API_V2 pull request #309
Opened 2024-04-04 08:44 UTC by kwoo28

# 🚀 작업 내용

1.인터셉터에서 Authorization의 token을 검증하고 추출하는 부분에서 문자열 시작 부분 체크를 "Bearer" -> "Bearer "로 수정했습니다.

# 💬 리뷰 중점사항

2024-04-04 08:47 UTC, Choi-JJunho requested changes
이거 설명하나만해주세용

2024-04-04 08:47 UTC, Choi-JJunho commented on src/main/java/in/koreatech/koin/domain/timetable/dto/LectureResponse.java
> +        List<String> numbers = List.of(classTime.split(", "));
### R
이게머죠

2024-04-04 10:54 UTC, seongjae6751 approved these changes
에러 찾느라 쉽지 않으셨을텐데 고생 많으셨습니다

2024-04-05 05:01 UTC, Choi-JJunho approved these changes

2024-04-05 05:01 UTC, merged