feat : 품절 알림 발송 구현
BCSDLab/KOIN_API_V2 pull request #372
Opened 2024-04-09 17:04 UTC by Choon0414

# 🔥 연관 이슈

- close #225 

# 🚀 작업 내용

1. `coop`에서 식단 상태를 품절로 변경 시, 품절 이벤트가 발생합니다.
2. `coopEventListener`에서 이벤트를 인지하면 알림을 구독한 사용자들에게 품절 알림 메시지를 발송합니다.

# 💬 리뷰 중점사항
- 멀티캐스트 방식이 동작을 하지 않아서 디바이스 토큰마다 반복해서 푸시하도록 수정했습니다.

2024-04-10 08:26 UTC, songsunkook requested changes
잘 짜주셨네요. 고생하셨습니다!
리뷰 확인해주세요~
알림 내용 변경은 머지 이후에 간단한 2줄짜리 PR로 다시 올려도 좋을 것 같아요

2024-04-10 08:26 UTC, songsunkook commented on src/test/java/in/koreatech/koin/acceptance/DiningApiTest.java
> +    private CoopEventListener coopEventListener;
### R
`@MockBean`이 필요한 필드는 AcceptanceTest 클래스에 선언해야 전체 테스트를 한 번에 돌렸을 때 정상적으로 동작하던데, 한 번 해보실래요?

2024-04-10 08:26 UTC, songsunkook commented on src/test/java/in/koreatech/koin/acceptance/DiningApiTest.java
> +            .body(new SoldOutRequest(1L, true))
### A
builder를 쓰면 쪼오오오금 더 직관적일 것 같아요! ~~수정안해도 무방합니다~~

2024-04-10 11:34 UTC, Choon0414 commented on src/main/java/in/koreatech/koin/global/domain/notification/service/NotificationService.java
> +    }
재사용성 고려를 안했네요. 수정했습니다!

2024-04-10 11:35 UTC, Choon0414 commented on src/main/java/in/koreatech/koin/global/domain/notification/service/NotificationService.java
> +            User user = userRepository.getById(type.getUser().getId());
`notification`과 `type` 대신 `soldOutSubscribes`와 `soldOutSubscribe`으로 수정했습니다!

2024-04-10 12:44 UTC, Choon0414 commented on src/test/java/in/koreatech/koin/acceptance/DiningApiTest.java
> +    private CoopEventListener coopEventListener;
AcceptanceTest로 옮기니까 통과하네요 감사합니다!

2024-04-10 12:44 UTC, Choon0414 commented on src/test/java/in/koreatech/koin/acceptance/DiningApiTest.java
> +            .body(new SoldOutRequest(1L, true))
수정했습니다

2024-04-11 01:25 UTC, songsunkook requested changes
쪼금만 더 수정해주시고 재리뷰 요청해주세요~

2024-04-11 01:25 UTC, songsunkook commented on src/main/java/in/koreatech/koin/domain/coop/dto/SoldOutRequest.java
> +    }
### R
Builder를 사용했다면 접근 제어자는 private으로 설정하는 게 좋을 것 같아요

2024-04-11 01:25 UTC, songsunkook commented on src/main/java/in/koreatech/koin/domain/coop/model/CoopEventListener.java
> +}
### A
트랜잭션 전파 👍

2024-04-11 01:25 UTC, songsunkook commented on src/main/java/in/koreatech/koin/global/domain/notification/service/NotificationService.java
> +    }
### R
이것도 재사용 가능하게 만들 수 있을 것 같아요
`DINING_SOLD_OUT`을 매개변수로 빼면 되지 않을까요??

2024-04-11 02:19 UTC, Choi-JJunho requested changes
알림기능의 첫 선구자!!
예제없이도 너무 잘 작성해주셨네요 👏👏
도메인의 역할에 대한 고민을 해보면 좋을 것 같네요

몇가지 코멘트 남겼으니 확인 부탁드려요~

2024-04-11 02:19 UTC, Choi-JJunho commented on src/main/java/in/koreatech/koin/global/domain/notification/service/NotificationService.java
> +    }
### R

DiningSoldOutEvent는 notificationService의 관심사가 아니에요~
Notification 객체로 조합하는것 까지 외부에서 수행하도록 고쳐주세요

2024-04-11 02:19 UTC, Choi-JJunho commented on src/main/java/in/koreatech/koin/global/domain/notification/service/NotificationService.java
> +    private void push(Notification notification) {
### R

NotificationService는 Notification 객체를 받아 저장하고, 알림을 발송하는 역할을 수행한다.

라는 역할에 대한 내용을 확인하시고 어떤 방식으로 리팩터링해야할지 고민해보세요 :)

```suggestion
    public void push(Notification notification) {
```

2024-04-11 02:19 UTC, Choi-JJunho commented on src/main/java/in/koreatech/koin/global/domain/notification/service/NotificationService.java
> +    }
### R 

overloading을 하면 이렇게도 표현할 수 있을것 같아요~
어떤가요?

```suggestion
    public void push(List<Notification notification> notifications) {
        for (Notification notification : notifications) {
            notificationRepository.save(notification);
            fcmClient.sendMessage(
                notification.getDeviceToken(),
                notification.getTitle(),
                notification.getMessage(),
                notification.getImageUrl(),
                notification.getMobileAppPath(),
                notification.getType()
            );
        }
    }
```

2024-04-12 06:26 UTC, Choon0414 commented on src/main/java/in/koreatech/koin/global/domain/notification/service/NotificationService.java
> +    private void push(Notification notification) {
역할의 분리에 대해 다시 한번 고민해보는 기회가 되었습니다 감사힙니다!

2024-04-13 05:18 UTC, Choon0414 commented on src/main/java/in/koreatech/koin/domain/coop/dto/SoldOutRequest.java
> +    }
궁금한게 있는데
다른 API 보니까 레코드 DTO에서는 `@Builder`를 거의 사용하지 않았던데 이유가 따로 있나요?

2024-04-13 05:48 UTC, Choon0414 commented on src/main/java/in/koreatech/koin/global/domain/notification/service/NotificationService.java
> +    }
각 리스너에서 notification을 만들도록 하고 push만 notificationService에서 쓰도록 빼주었습니다!

2024-04-14 07:55 UTC, songsunkook approved these changes
확실히 관심사에 따라 분리되니 훨씬 깔끔해진 것 같네요. 고생하셨습니다!

2024-04-14 07:55 UTC, songsunkook commented on src/main/java/in/koreatech/koin/domain/coop/dto/SoldOutRequest.java
> +    }
해당 부분은 저도 관례적으로 사용중입니다
이유를 유추해보자면 DTO는 내부 필드에 대해 비즈니스 로직에서 알아야 할 필요가 없고 오히려 비즈니스 로직이 DTO에 의존적으로 될 수 있다는 점이 있을 것 같아요.

2024-04-14 07:55 UTC, songsunkook commented on src/main/java/in/koreatech/koin/domain/coop/model/CoopEventListener.java
> +        notificationService.push(notifications);
👍

2024-04-15 02:21 UTC, Choon0414 commented on src/main/java/in/koreatech/koin/domain/coop/dto/SoldOutRequest.java
> +    }
답변 감사합니다!

2024-04-15 03:30 UTC, Choi-JJunho approved these changes
record 하나만 확인해주세요

2024-04-15 05:34 UTC, Choon0414 commented on src/main/java/in/koreatech/koin/domain/coop/dto/SoldOutRequest.java
> +    }
제거했습니다!

2024-04-15 05:35 UTC, Choi-JJunho approved these changes

2024-04-15 05:37 UTC, merged