Fix: 사장님 회원탈퇴 오류
BCSDLab/KOIN_API_V2 pull request #380
Opened 2024-04-10 12:12 UTC by kwoo28

# 🔥 연관 이슈

- close #379

# 🚀 작업 내용

1. 사장님 user_id과 연관되어있는 shop도 삭제했습니다.
2. shopRepository에서 delete구현
3. 사장님 회원탈퇴 테스트 구현
4. 회원탈퇴 로직 약간 수정

# 💬 리뷰 중점사항

2024-04-10 14:18 UTC, daheeParkk approved these changes
수고하셨습니다

2024-04-10 16:26 UTC, Choi-JJunho requested changes
연관되어있는 정보를 모두 지운다고하면 코멘트 한번 참고해서 반영 부탁드려요

2024-04-10 16:26 UTC, Choi-JJunho commented on src/main/java/in/koreatech/koin/domain/user/service/UserService.java
> +            ownerRepository.deleteByUserId(userId);
### R

회원 탈퇴 시 연관된 모든 정보를 지운다면 FK로 걸려있는 데이터 다 지워야할거같은데 한번 확인해보시겠어요?
user_id 를 FK로 가지고있는 컬럼 (혹은 Entity)들에 대해 확인해주세요

### 쿼리로 확인하는법
```sql
SELECT
    tc.CONSTRAINT_TYPE,
    tc.CONSTRAINT_NAME,
    tc.TABLE_NAME,
    kcu.COLUMN_NAME,
    kcu.REFERENCED_TABLE_NAME,
    kcu.REFERENCED_COLUMN_NAME
FROM
    information_schema.TABLE_CONSTRAINTS AS tc
JOIN
    information_schema.KEY_COLUMN_USAGE AS kcu
    ON tc.CONSTRAINT_NAME = kcu.CONSTRAINT_NAME
    AND tc.TABLE_SCHEMA = kcu.TABLE_SCHEMA
WHERE
    tc.TABLE_SCHEMA = 'koin' AND kcu.COLUMN_NAME LIKE '%user%';
```

2024-04-11 01:02 UTC, kwoo28 commented on src/main/java/in/koreatech/koin/domain/user/service/UserService.java
> +            ownerRepository.deleteByUserId(userId);
음..엄청많네요

2024-04-11 08:46 UTC, kwoo28 commented on src/main/java/in/koreatech/koin/domain/user/service/UserService.java
> +            ownerRepository.deleteByUserId(userId);
해당 이슈 오류를 다시 살펴보니 user_id를 참조하고 있는 데이터를 모두 지워주지 않아서 생긴 오류는 아닌것같아서 다시 수정해봤습니다.

2024-04-11 08:57 UTC, Choi-JJunho approved these changes
확인했습니다~

2024-04-11 09:12 UTC, merged