fix: POST/user/refresh 반환코드 수정
BCSDLab/KOIN_API_V2 pull request #399
Opened 2024-04-11 09:26 UTC by kwoo28

# 🔥 연관 이슈

- close #398

# 🚀 작업 내용

1. 상태코드 200에서 201로 변경했습니다.

# 💬 리뷰 중점사항

2024-04-11 09:31 UTC, daheeParkk requested changes
수고하셨습니다

2024-04-11 09:31 UTC, daheeParkk commented on src/main/java/in/koreatech/koin/domain/user/controller/UserController.java
> +            .body(tokenGroupResponse);
### R
테스트 코드도 201로 수정하면 될 것 같아요!

2024-04-11 17:07 UTC, kwoo28 commented on src/main/java/in/koreatech/koin/domain/user/controller/UserController.java
> +            .body(tokenGroupResponse);
넵!

2024-04-12 01:32 UTC, seongjae6751 approved these changes
고생하셨습니다~

2024-04-12 03:54 UTC, daheeParkk approved these changes

2024-04-12 03:55 UTC, merged