fix: 코인 인증 메일 폼 만료 시간 수정
BCSDLab/KOIN_API_V2 pull request #414
Opened 2024-04-14 11:16 UTC by seongjae6751

# 🔥 연관 이슈

- close #이슈번호

# 🚀 작업 내용

1. 인증 만료시간이 1시간으로 되어있던 것을 10시간으로 수정해줬습니다.

# 💬 리뷰 중점사항

2024-04-14 11:18 UTC, kwoo28 approved these changes

2024-04-14 11:18 UTC, kwoo28 commented
.

2024-04-14 13:49 UTC, duehee approved these changes

2024-04-14 20:46 UTC, Choi-JJunho requested changes
왜 10시간이 되었는지에 대한 설명이 필요해요~

2024-04-15 02:33 UTC, seongjae6751 commented
답글이 달리지가 않네요 😢 
@Choi-JJunho 
원래 레거시 코드에서 10시간으로 되어 있었습니다! 그래서 원경이가 전에 만료시간을 1시간에서 10시간으로 변경해주었고, 저는 이메일 폼(html코드)에 만료시간이 1시간으로 나와있던 것만 10시간으로 수정해줬습니다

2024-04-15 02:33 UTC, Choi-JJunho approved these changes
확인했습니다.

2024-04-15 02:51 UTC, daheeParkk approved these changes

2024-04-15 03:24 UTC, merged