feat: GET /admin/lands 기능 구현
BCSDLab/KOIN_API_V2 pull request #438
Opened 2024-04-17 09:58 UTC by YunYongWoon

# 🔥 연관 이슈

- close #10 

# 🚀 작업 내용

1. GET /admin/lands 마이그레이션 작업 진행하였습니다.
2. domain.community의 Criteria 클래스를 같이 사용하기 위해 global.model 패키지로 클래스 이동 후 일부 메서드 오버로딩하여 작업 진행하였습니다.

# 💬 리뷰 중점사항
첫 PR 올려봅니다. 테스트코드와 java17에 익숙하지 않아 실수나 놓치는 부분이 많을것이라 예상되는데, 잘 부탁드립니다!

2024-04-17 10:14 UTC, johnny19991006 reviewed
형님 첫 PR고생하셨습니다!!!
코드 리뷰하면서 많이 배운거 같습니다

2024-04-17 10:14 UTC, johnny19991006 commented on src/main/java/in/koreatech/koin/domain/admin/land/service/AdminLandService.java
> +        return AdminLandsResponse.of(result, criteria);
팩터리 패턴 Good~

2024-04-17 10:14 UTC, johnny19991006 commented on src/main/java/in/koreatech/koin/domain/admin/land/dto/AdminLandsResponse.java
> +        );
람다식 Good

2024-04-17 10:14 UTC, johnny19991006 commented on src/main/java/in/koreatech/koin/global/model/Criteria.java
> +        }
삼항 연산자를 위에서는 사용하고 아래서는 그냥 if문으로 처리한 이유가 있나요?

2024-04-17 10:18 UTC, YunYongWoon commented on src/main/java/in/koreatech/koin/global/model/Criteria.java
> +        }
큰 이유는 없습니다. 기존 validatePage 함수 복사 후 파라미터 추가해서 작업 진행하였고, 이 과정에서 큰 고민 없이 개발 진행한거같네요. 다음번엔 더 고민해서 개발해보도록 하겠습니다!

2024-04-17 12:01 UTC, Choi-JJunho requested changes
Good First PR!
코멘트 몇가지만 확인해주세요!

2024-04-17 13:20 UTC, 20HyeonsuLee requested changes
전체적으로 너무 잘 작성해주셨네요! 몇가지 걸리는 부분들에 대해서 리뷰 남겼습니다!

2024-04-17 13:20 UTC, 20HyeonsuLee commented on src/main/java/in/koreatech/koin/domain/admin/land/dto/AdminLandsResponse.java
> +    public static AdminLandsResponse of(Page<Land> result, Criteria criteria) {
# R
result라는 이름은 조금 모호한것같습니다!

2024-04-17 15:17 UTC, YunYongWoon commented on src/main/java/in/koreatech/koin/domain/admin/land/controller/AdminLandController.java
> +        @RequestParam(name = "is_deleted", defaultValue = "false") Boolean isDeleted
오프셋 기반 페이징으로 구현된 다른 코드를 찾아봤는데 `GET /articles` API가 `@RequestParam`으로 구현된것 보고 다 같이 약속된 무언가가 있나 해서 다음과 같이 구현하였습니다.

2024-04-17 15:18 UTC, YunYongWoon commented on src/main/java/in/koreatech/koin/domain/admin/land/dto/AdminLandResponse.java
> +@JsonNaming(value = PropertyNamingStrategies.SnakeCaseStrategy.class)
적용하겠습니다

2024-04-17 15:22 UTC, YunYongWoon commented on src/main/java/in/koreatech/koin/domain/admin/land/dto/AdminLandResponse.java
> +    @Schema(description = "이름", example = "금실타운", required = true)
수정하겠습니다

2024-04-17 15:23 UTC, YunYongWoon commented on src/main/java/in/koreatech/koin/domain/admin/land/service/AdminLandService.java
> +    @Transactional(readOnly = true)
평소 개발을 진행하는 경우 CRUD 작업 중 Read 관련 로직이 다른 로직들보다 상대적으로 적어서 항상 `@Transactional`을 전역으로 선언하고, Read 로직에 `@Trasactional(readOnly = true)`를 선언하는 방식으로 개발을 진행해왔었습니다. 팀 내부적으로 `@Trasactional(readOnly = true)`을 전역으로 선언하고 있다면, 제안해주신 방법으로 수정하도록 하겠습니다!

2024-04-17 15:27 UTC, YunYongWoon commented on src/main/java/in/koreatech/koin/global/model/Criteria.java
> +        long totalPage = total.equals(0L) ? 1L : (int) Math.ceil((double) total / limit);
체크 감사합니다. 수정하겠습니다!

2024-04-17 15:30 UTC, YunYongWoon commented on src/main/java/in/koreatech/koin/domain/admin/land/service/AdminLandService.java
> +        PageRequest pageRequest = PageRequest.of(criteria.getPage(), criteria.getLimit(), Sort.by(Sort.Direction.ASC, "id"));
저도 제안해주신 방법이 옳다고 생각합니다. `community` 도메인도 다음과 같이 page, limit 정보를 Long으로 받고 있는 상황이던데, 이 부분까지 같이 수정해도 될까요?

2024-04-17 16:06 UTC, YunYongWoon commented on src/main/java/in/koreatech/koin/global/model/Criteria.java
> +        long totalPage = total.equals(0L) ? 1L : (int) Math.ceil((double) total / limit);
`validateAndCalculate...`로 함수명 변경하였습니다.

2024-04-18 07:38 UTC, 20HyeonsuLee commented on src/main/java/in/koreatech/koin/domain/admin/land/service/AdminLandService.java
> +        PageRequest pageRequest = PageRequest.of(criteria.getPage(), criteria.getLimit(), Sort.by(Sort.Direction.ASC, "id"));
넵 그래도 좋을것같습니다!

2024-04-18 07:59 UTC, YunYongWoon commented on src/main/java/in/koreatech/koin/global/model/Criteria.java
> +        return new Criteria(validateAndCalculatePage(page, limit, total), validateAndCalculateLimit(limit));
JPA의 count()가 Long을 반환해서 Long으로 받았습니다. .intValue()로 Integer로 형변환해서 사용할까요?

2024-04-18 08:26 UTC, Choi-JJunho commented on src/main/java/in/koreatech/koin/domain/admin/land/service/AdminLandService.java
> +    @Transactional(readOnly = true)
이거 반영이 안된거같아용

2024-04-18 08:28 UTC, YunYongWoon commented on src/main/java/in/koreatech/koin/domain/admin/land/service/AdminLandService.java
> +    @Transactional(readOnly = true)
따로 코멘트 없고 따봉만 달려서 상관없는줄 알았는데....수정하겠습니다

2024-04-18 08:33 UTC, Choi-JJunho approved these changes
굿~ 고생하셨습니다

2024-04-18 08:39 UTC, merged