feat: 시간표 총 학점 조회
BCSDLab/KOIN_API_V2 pull request #440
Opened 2024-04-17 18:24 UTC by kwoo28

# 🔥 연관 이슈

- close #439

# 🚀 작업 내용

1. 해당 학기 총 학점 조회
2.  전체 학기 총 학점 조회

# 💬 리뷰 중점사항

2024-04-18 03:10 UTC, seongjae6751 requested changes
고생하셨습니다!

2024-04-18 03:10 UTC, seongjae6751 commented on src/main/java/in/koreatech/koin/domain/timetable/service/TimetableService.java
> +                .mapToInt(timeTable -> Integer.parseInt(timeTable.getGrades()))
R
이러면 사용자가 아직 아무런 시간표도 추가 하지 않은 경우 parseInt과정에서 에러가 날 수 있을 것 같은데 학점의 값이 있는지 없는지 검사를 하는 로직이 있어야 하지 않을까요?

2024-04-18 03:10 UTC, seongjae6751 commented on src/test/java/in/koreatech/koin/acceptance/TimetableApiTest.java
> +                        +Integer.parseInt(timeTable3.getGrades()));
C
전체 학점에 관한 테스트 코드나 아무런 시간표도 추가하지 않았을 때와 같은 테스트 코드도 있으면 더 좋을 것 같아요!

2024-04-18 05:06 UTC, kwoo28 commented on src/main/java/in/koreatech/koin/domain/timetable/dto/TimeTableResponse.java
> +    Integer totalGrades
좋은것같습니다! 용어변경하겠습니다

2024-04-18 05:12 UTC, kwoo28 commented on src/test/java/in/koreatech/koin/acceptance/TimetableApiTest.java
> +                        +Integer.parseInt(timeTable3.getGrades()));
넵 추가하겠습니다

2024-04-18 05:31 UTC, duehee approved these changes
고생하셨습니다~ 위 성재님께서 말씀해주신 부분 고려해보시면 좋을 거 같아요!

2024-04-18 05:31 UTC, duehee commented on src/main/java/in/koreatech/koin/domain/timetable/dto/TimeTableResponse.java
> +    Integer totalGrades
### A
학점 관련한 레거시 코드에서 사용하는 이름이 현재 grades로 알고 있습니다!
저번 레거시 코드 관련하여 리뷰하였을 때 이에 대한 의견을 말씀드렸는데, 현재는 Model이나 DB 내에서 사용하고 있는 이름인  grades를 사용하는 부분이 맞다고 저는 생각이 들었어요!

2024-04-18 05:35 UTC, kwoo28 commented on src/main/java/in/koreatech/koin/domain/timetable/dto/TimeTableResponse.java
> +    Integer totalGrades
어 그러네요. 코드 수정하면서 다시 보니 DB명과 일치시키고 레거시응답과 통일시키기 위해선 grade로 하는게 맞는것같아여

2024-04-18 05:40 UTC, seongjae6751 commented on src/main/java/in/koreatech/koin/domain/timetable/service/TimetableService.java
> +                .mapToInt(timeTable -> Integer.parseInt(timeTable.getGrades()))
아 stream이라 뒤에 체이닝 된 것들은 호출 되지 않겠네요!

2024-04-19 09:50 UTC, seongjae6751 approved these changes
고생하셨습니다!

2024-04-20 08:28 UTC, merged