feat: 도커파일 추가
BCSDLab/KOIN_API_V2 pull request #445
Opened 2024-04-18 07:03 UTC by johnny19991006

# 🔥 연관 이슈

- close #이슈번호

# 🚀 작업 내용

1.도커파일이 필요하여 추가합니다

# 💬 리뷰 중점사항

2024-04-18 07:04 UTC, Choi-JJunho requested changes
드디어 Dockerfile이..!!

2024-04-18 07:04 UTC, Choi-JJunho commented on Dockerfile
> +ENV JAVA_OPTS=""
이 ENV는 왜 넣었나요

2024-04-18 07:05 UTC, johnny19991006 commented on Dockerfile
> +ENV JAVA_OPTS=""
아 env는 혹시나 추후 디버깅할때 쓸까봐 넣었어요

2024-04-18 07:06 UTC, johnny19991006 commented on Dockerfile
> +FROM openjdk:17-slim
음... 이미지 크기 줄일려고 slim으로 설정

2024-04-18 07:13 UTC, Choi-JJunho commented on Dockerfile
> +FROM openjdk:17-slim
저는 갠적으로 amazoncorretto:17 좋아해요
aws 꺼라서 호환이슈에서 조금 안정적인 느낌

2024-04-18 07:14 UTC, johnny19991006 commented on Dockerfile
> +FROM openjdk:17-slim
네 반영하겠습니다~

2024-04-18 07:28 UTC, johnny19991006 commented
이거 깜빡하고 브랜치 업데이트 안하고 올렸는데 이거도 통과가 되는건가? 이상한데...

2024-04-18 15:20 UTC, 20HyeonsuLee requested changes
혹시 설명 부탁드려도 될까요?!?

2024-04-18 15:20 UTC, 20HyeonsuLee commented on Dockerfile
> +ENTRYPOINT ["java", "-jar", "/app/app.jar"]
# A
어떤 역할을 하는지 간단하게 설명해주실 수 있을까요?

2024-04-19 06:39 UTC, johnny19991006 commented on Dockerfile
> +ENTRYPOINT ["java", "-jar", "/app/app.jar"]
흠 From은 이미지를 자바17로 돌린다는 소리고요
WorkDIR은 /app에 jar파일을 배포하겠다는 소리
Volume은 /tmp에 임시로 공간을 만든단 소리
ADD는 추후에 ci/cd로 빌드한 jar파일을 생성된 이미지로 옮긴다는 소리
EntryPoint는 java의 jar파일 위치가 되었겠습니다

2024-04-19 07:05 UTC, 20HyeonsuLee commented on Dockerfile
> +ENTRYPOINT ["java", "-jar", "/app/app.jar"]
설명 감사합니다 ㅎㅎ

2024-04-19 07:06 UTC, 20HyeonsuLee approved these changes
수고하셨습니다!

2024-04-22 02:23 UTC, Choi-JJunho requested changes
코멘트 확인해주세요!

2024-04-22 02:23 UTC, Choi-JJunho commented on Dockerfile
> +VOLUME /tmp
### R

/tmp 경로 말고 적절한 위치 없을까요?

linux의 /tmp 경로는 말 그대로 `임시파일`이 위치하는 경로입니다.
없어져도 무관한 경로라서 가끔 몇몇 OS에서는 system cron으로 30일 뒤에 공간을 비운다는 등의 작업을 수행한다고도 하네요

/usr/local 어딘가에 좋은 위치는 없을까요?

참고자료: https://coding-panda.com/%EB%A6%AC%EB%88%85%EC%8A%A4-%EC%A3%BC%EC%9A%94-%EB%94%94%EB%A0%89%ED%86%A0%EB%A6%AC-%EB%B3%84-%EC%97%AD%ED%95%A0-%EB%B0%8F-%EC%84%A4%EB%AA%85/#tmp

2024-04-22 02:23 UTC, Choi-JJunho commented on Dockerfile
> +ENTRYPOINT ["java", "-jar", "/app/app.jar"]
### C
가독성을 위해 개행을 추가해주면 좋을 것 같아요

```suggestion
FROM amazoncorretto:17

WORKDIR /app

VOLUME /tmp

ADD ./build/libs/KOIN_API_V2.jar /app/app.jar

ENTRYPOINT ["java", "-jar", "/app/app.jar"]
```

2024-04-22 02:23 UTC, Choi-JJunho commented on Dockerfile
> +ADD ./build/libs/KOIN_API_V2.jar /app/app.jar
### C

COPY 말고 ADD를 사용한 이유가 있나요?

2024-04-23 02:12 UTC, johnny19991006 commented on Dockerfile
> +ENTRYPOINT ["java", "-jar", "/app/app.jar"]
넵 적용하겠습니다..!

2024-04-23 02:13 UTC, johnny19991006 commented on Dockerfile
> +VOLUME /tmp
음 이미지는 빌드후 삭제시켜도 무방한 이미지라 tmp에 넣어두었는데, 그렇다면
그냥 생략해도 무방할것 같습니다.

2024-04-23 02:16 UTC, johnny19991006 commented on Dockerfile
> +VOLUME /tmp
그리고 tmp라고 저장할경우 실제 저장되는 위치는 var/lib/jenkins/workspace에서의 tmp가 위치입니다.
![image](https://github.com/BCSDLab/KOIN_API_V2/assets/79901434/a59f6d08-85d6-4c09-94a3-a9e348817159)

2024-04-23 02:19 UTC, johnny19991006 commented on Dockerfile
> +ADD ./build/libs/KOIN_API_V2.jar /app/app.jar
맞는 말씀입니다 Copy가 조금더 적합할것 같습니다!

2024-04-23 02:35 UTC, johnny19991006 commented on Dockerfile
> +VOLUME /tmp
즉 따로 동기화할만한 데이터가 없으면 없애도 무방하다는 입장입니다

2024-04-23 05:35 UTC, Choi-JJunho approved these changes
확인했습니다 👍

2024-04-23 05:44 UTC, merged