feat : 버스 버저닝 V2 updated_at 추가
BCSDLab/KOIN_API_V2 pull request #446
Opened 2024-04-18 07:07 UTC by Choon0414

# 🔥 연관 이슈

- close #405 

# 🚀 작업 내용

1. 버스 시간표 조회 시 updated_at을 함께 반환하는 GET /timetable/v2를 추가했습니다.

# 💬 리뷰 중점사항

2024-04-20 13:49 UTC, dradnats1012 requested changes
고생하셨습니다!
로그만 지우면 될것 같아요

2024-04-20 13:49 UTC, dradnats1012 commented on src/test/java/in/koreatech/koin/acceptance/BusApiTest.java
> +            .log().all()
요거 지워야될것 같아요!

2024-04-20 13:49 UTC, dradnats1012 commented on src/test/java/in/koreatech/koin/acceptance/BusApiTest.java
> +            .log().all()
이친구도!!

2024-04-20 14:02 UTC, songsunkook approved these changes
고생하셨습니다!

2024-04-21 06:11 UTC, dradnats1012 approved these changes
고생하셨습니당

2024-04-21 06:15 UTC, merged