test: 테스트 리팩터링
BCSDLab/KOIN_API_V2 pull request #458
Opened 2024-04-23 05:22 UTC by Choi-JJunho

# 🔥 연관 이슈

- close #437 

# 🚀 작업 내용

1. 테스트 상에서의 시간을 고정시켰습니다.
  - 테스트 상에서의 모든 시간은 2024년 1월 15일 12:00분으로 고정됩니다.
  - 테스트 내에서 `LocalDate.now()` 를 사용할 경우 clock을 주입받아 사용하시면 됩니다.
2. TestFixture를 추가했습니다.
  - 테스트에서 동일한 값을 반복하여 사용하는것을 공통화시켜 Fixture를 구성했습니다.
  - 별도로 값을 조정하여 테스트해야하는 경우가 아니라면 fixture를 활용하여 사전에 구성된 값을 활용할 수 있습니다.
  - `repository.save()` 까지 수행하여 반환하므로 이점 참고해주시기바랍니다.
3. 가독성을 위한 Fixture 메소드에 한글 메소드 추가
  - 어떤 값을 의미하는지 명확히 하기위해 한글 메소드를 추가했습니다. ex) `userFixture.준호_학생()`
  - 인텔리제이 상에서 한글 변수명에 대한 경고를 띄웁니다. 이에 클래스 상단에 `@SuppressWarnings("NonAsciiCharacters")`를 추가하여 한글 변수명에 대한 경고를 생략할 수 있습니다.
4. JsonAssertions 활용하도록 수정
  - Get 요청에 대한 값 검증을 수행할 때 변수를 하나하나 지정하면서 assert를 수행하는것에 대한 가독성 및 유지보수성이 떨어진다고 판단했습니다.
  - 이에 별도의 JsonAssertions를 구성했습니다.
  - java의 multi-line String을 활용하여 Json 형태의 데이터를 isEqualTo 로직 내에 즉시 삽입하였습니다.
  - 해당 값은 내부적으로 ObjectMapper를 활용하여 Json 객체로 파싱되며 이에 대한 equals가 Map으로서 비교됩니다.
  - 때문에 Json 형태만 유지된다면 라인, 공백, 엔터 등의 공간을 신경쓸 필요가 없습니다.
  - 만약 검증 값을 조정하고싶다면 검증부에서 `String.format()` 메소드를 활용하여 값을 임의로 제어할 수도 있습니다.

5. 번외 내용으로 /bus/timetable/v2에 대한 반환 DTO 값 형태를 변경했습니다.
  - 기존에 updated_at 값이 `yyyy-MM-dd'T'HH:mm:ss` 로 반환되어 이에 대해 `yyyy-MM-dd HH:mm:ss` 형태로 수정했습니다.

# 💬 리뷰 중점사항

변경사항이 많습니다. 확인 잘부탁드립니다.

2024-04-24 04:04 UTC, dradnats1012 requested changes
확실히 깔끔하고 좋네요
진짜 고생하셨습니다!!!!!!! 💯 💯 💯 💯 💯 
중간에 로그 하나만 지우면 될 것 같아요!

2024-04-24 04:15 UTC, Choi-JJunho commented on src/test/java/in/koreatech/koin/acceptance/BusApiTest.java
> +            .log().all()
날카롭군요 👍

2024-04-24 04:37 UTC, dradnats1012 approved these changes
고생하셨습니다!

2024-04-25 08:17 UTC, 20HyeonsuLee approved these changes
와우 테스트코드가 이뻐졌어요 수고하셨습니다! 
혹시 RequestBody를 정적팩토리 메서드로 만드는것과 RestAssured모듈화하는것에 대해서는 어떻게생각하시나요??

2024-04-25 09:28 UTC, Choon0414 approved these changes
고생하셨습니다!
매 테스트마다 생성하던 객체들을 하나로 묶어버리니 코드가 짧아져서 눈에 더 잘 들어오네요!

2024-04-25 09:34 UTC, songsunkook approved these changes
엄청나네요.... 🤯🤯 고생하셨습니다!!
코멘트 몇 개만 확인 부탁드려요!

2024-04-25 09:34 UTC, songsunkook commented on src/test/java/in/koreatech/koin/fixture/ActivityFixture.java
> +    }
### A
롬복을 테스트에도 적용하는 건 어떤가요??

2024-04-25 09:34 UTC, songsunkook commented on src/test/java/in/koreatech/koin/fixture/ActivityFixture.java
> +    }
### C
테스트를 새로 작성할 때마다 각 엔티티의 빌더를 직접 작성하는 것은 번거로울 것 같습니다.
호출 시 바로 빌더를 사용하면서 save까지 자동으로 된다는 장점은 정말 좋지만, 위 단점이 크게 다가오는 것 같아요.
빌더를 포기하고 생성자로 호출한다면 아래처럼 코드가 굉장히 간단해질 것 같은데 어떻게 생각하시나요?
빌더를 사용하는 것이 훨씬 테스트를 보기 좋게 하지만 매번 빌더를 직접 작성해야 하는 점이 걱정됩니다.
취향차이라고 생각해서 어느 쪽이든 따라가겠습니다.

```suggestion
            public Activity save(String title, String description, String imageUrls, LocalDate date, boolean isDeleted) {
        return activityRepository.save(Activity.builder()
            .title(title)
            .description(description)
            .imageUrls(imageUrls)
            .date(date)
            .isDeleted(isDeleted)
            .build());
    }
```

2024-04-25 09:47 UTC, Choi-JJunho commented on src/test/java/in/koreatech/koin/fixture/ActivityFixture.java
> +    }
매번이라는게 어떤의미일까요..
제가 builder를 구현한 이유는 테스트상에서 세부값을 조정하기 위함입니다.
Entity가 생성되지 않는 한 이러한 builder 구현에 대한 소요는 없을 것 같아요

반대로 생각해봤을 때 null이여도 상관없는 값이거나, 생성자 파라미터의 필드 순서가 뒤바뀌거나 하는 등의 생성자를 사용했을 때의 단점이 떠오르네요

2024-04-25 09:49 UTC, Choi-JJunho commented on src/test/java/in/koreatech/koin/fixture/ActivityFixture.java
> +    }
고민중이긴합니다만.. 테스트 Fixture 외에는 사용을 안할것같기도하고 뭔가 필드주입이 난무하는 환경에서 굳이.. 필요할까 싶기도 한에ㅛ

2024-04-25 09:52 UTC, seongjae6751 approved these changes
중복되던 부분들을 묶어버리니까 코드의 양도 줄어들고 확실히 보기도 좋네요 정말 고생 많으셨습니다

2024-04-25 13:13 UTC, merged