feat : 회원 정보 수정에 비밀번호 수정 추가
BCSDLab/KOIN_API_V2 pull request #477
Opened 2024-04-27 11:56 UTC by duehee

# 🔥 연관 이슈

- close #421 

# 🚀 작업 내용

1. 회원 정보 수정에 비밀번호 수정 로직을 추가했습니다.

# 💬 리뷰 중점사항
시간을 많이 쓸 로직은 아니었는데, 이런저런 문제로 테스트 상으로 시간을 너무 많이 썼습니다😢
더 일찍 못 드려서 죄송합니당

2024-04-27 13:27 UTC, seongjae6751 requested changes
고생하셨습니다!

2024-04-27 13:27 UTC, seongjae6751 commented on src/main/java/in/koreatech/koin/domain/user/model/User.java
> +    public void updateStudentPassword(PasswordEncoder passwordEncoder, String password) {
C
여기에 검증 로직을 넣는 것보다 dto에서 @notblank로 검증하는 것이 더 좋지 않을까 생각하는데 어떻게 생각하시나요?

2024-04-27 13:29 UTC, seongjae6751 requested changes

2024-04-27 13:29 UTC, seongjae6751 commented on src/main/java/in/koreatech/koin/domain/user/model/User.java
> +    }
C
여기에 검증 로직을 넣는 것보다 dto에서 @notblank로 검증하는 것이 더 좋지 않을까 생각하는데 어떻게 생각하시나요?

2024-04-27 14:24 UTC, seongjae6751 approved these changes
샤워하다가 문득 말이 안되는 소리를 한 것을 깨달았습니다..ㅋㅋㅋㅜ 고생하셨습니다

2024-04-28 09:09 UTC, kwoo28 approved these changes
수고 많으셨습니다!

2024-04-28 12:07 UTC, merged