feat: 비밀번호 검증 api 작성
BCSDLab/KOIN_API_V2 pull request #478
Opened 2024-04-27 13:18 UTC by seongjae6751

# 🔥 연관 이슈

- close #442 

# 🚀 작업 내용

1. 비밀번호로 자신을 검증할 수 있는 로직을 작성하였습니다.

# 💬 리뷰 중점사항
우선 반환값을 boolean으로 했는데 적당 한 것인지 잘 모르겠네요.. 추가로 놓친 부분이 있으면 말씀해주시면 감사하겠습니다!

2024-04-28 08:49 UTC, kwoo28 approved these changes
수고 많으셨습니다!

2024-04-28 08:49 UTC, kwoo28 commented on src/main/java/in/koreatech/koin/domain/user/service/UserService.java
> +
반환타입을 void로 한다음에, 비밀번호가 다르다면 에러를 발생시키는 방법이 어떤가요?

2024-04-28 08:56 UTC, daheeParkk requested changes
수고하셨습니당

2024-04-28 08:56 UTC, daheeParkk commented on src/main/java/in/koreatech/koin/domain/user/controller/UserApi.java
> +    @Operation(summary = "비밀번호 검증")
### C
`@ApiResponses`와 `@Operation` 사이를 다른 곳처럼 붙이는 게 좋을 것 같아요

2024-04-28 08:56 UTC, daheeParkk commented on src/main/java/in/koreatech/koin/domain/user/service/UserService.java
> +
오,, 괜찮은 방법 같습니다

2024-04-28 08:57 UTC, daheeParkk commented on src/main/java/in/koreatech/koin/domain/user/service/UserService.java
> +
오,, 괜찮은 방법 같아요

2024-04-29 05:12 UTC, seongjae6751 commented on src/main/java/in/koreatech/koin/domain/user/service/UserService.java
> +
그게 좋을 것 같네요! 수정하겠습니다

2024-04-29 07:27 UTC, duehee approved these changes
고생하셨습니다~ :D

2024-04-29 14:38 UTC, daheeParkk requested changes
수고하셨습니당

2024-04-29 14:38 UTC, daheeParkk commented on src/main/java/in/koreatech/koin/domain/user/service/UserService.java
> +            throw new AuthenticationException("올바르지 않은 비밀정보입니다.");
### C
다른 예외들 처럼 `AuthenticationException`를 상속 받고 구체적인 예외 클래스를 만들어 withDetail로 log를 남기는게 좋지 않을까요?

2024-04-29 15:43 UTC, seongjae6751 commented on src/main/java/in/koreatech/koin/domain/user/service/UserService.java
> +            throw new AuthenticationException("올바르지 않은 비밀정보입니다.");
사실 예외 처리를 어디에서 어떻게 해야 할 것인지 고민이 계속 있었습니다.

이번에 예외처리 리팩터링 하면서, authorization과 authentication 예외는
상속 받는 자식 예외클래스가 없이 그대로 호출해서 쓰는 경우만 있는줄 알고, 
추상 클래스와 자식 클래스 들간의 관계로 리팩토링 하지 않았습니다. 

그런데 이런 경우가 계속 생길 것 같아서 authorization과 authentication도 추상 클래스와 자식 클래스 들로 정리를 해야 할 것 같네요.

여기서 나머지 예외클래스도 리팩토링 해버리면 이슈에 맞지 않는 것 같아서 approve 해주시면 새로 이슈 만들어서 해당 사항과 함께 나머지도 리팩토링 진행하겠습니다!

2024-04-29 16:01 UTC, daheeParkk commented on src/main/java/in/koreatech/koin/domain/user/service/UserService.java
> +            throw new AuthenticationException("올바르지 않은 비밀정보입니다.");
잘 이해가 가지 않습니다.. 현재 코드에서 구체적인 클래스를 상속받게 만들면 다른 코드에서 문제가 생긴다는 건가요?

2024-04-30 00:26 UTC, seongjae6751 commented on src/main/java/in/koreatech/koin/domain/user/service/UserService.java
> +            throw new AuthenticationException("올바르지 않은 비밀정보입니다.");
https://github.com/BCSDLab/KOIN_API_V2/pull/460

로그를 위한 예외 메시지와 사용자에게 보여줘야 하는 예외 메시지를 다르게 하기 위해서 얼마 전에 예외 리팩토링을 진행했습니다. 자식이 있는 부모 예외 클래스들을 추상 클래스로 만들고 자식 예외 클래스들은 부모 클래스를 상속 받아서 override하였습니다. 
그렇게 추상 부모 클래스 - 자식 클래스의 구조로 만든 예외들이 global 패키지에 있는 datanotfoundexception ~ externalserviceexception입니다.

authenticationexception과 authorizeexception은 상속 받는 클래스가 없는 줄 알았고 추상 부모클래스 - 자식 클래스간의 관계로 만들 필요성이 없다고 생각했었기에 리팩토링 하지 않았었습니다.
지금 보니까 authenticationexception을 상속 받는 예외가 하나 있었는데 제가 놓쳤던 것 같습니다. 추가로 현재 예외도 상속 받아서 구현을 해야 한다면 다른 예외들 처럼 부모 - 자식 관계로 다시 리팩토링을 해야 할 것 같습니다.

현재에 있는 예외를 그래도 상속 받아서 구현한다면 detail과 default message와 같은 동일한 속성이 부모와 자식 모두에 중복하여 존재하게 되는 일반적이지 않은 상속 관계가 될 것 입니다. 

그렇다고 현재 이 pr에서 authenticationexception과 authorizeexception의 나머지 리팩토링을 진행하면 변경해야 하는 파일이 너무 많아서 이 이슈에 맞지 않는, 본래의 목적에 주객이 전도된 상황이 될 것 같습니다..!

2024-04-30 00:27 UTC, Choi-JJunho requested changes
고생하셨습니다
코멘트 확인해주세요~

2024-04-30 00:27 UTC, Choi-JJunho commented on src/main/java/in/koreatech/koin/domain/user/dto/UserPasswordCheckRequest.java
> +    @Schema(description = "확인할 비밀번호 (SHA 256 해싱된 값)", example = "password", requiredMode = REQUIRED)
### A

```suggestion
public record UserPasswordCheckRequest(
    @Schema(description = "확인할 비밀번호 (SHA 256 해싱된 값)", example = "5e884898da28047151d0e56f8dc6292773603d0d6aabbdd62a11ef721d1542d8", requiredMode = REQUIRED)
```

example을 조금 더 친절하게 줄 수도 있을 것 같아요

2024-04-30 00:27 UTC, Choi-JJunho commented on src/main/java/in/koreatech/koin/domain/user/service/UserService.java
> +        }
### C

user에 isSamePassword 가 있습니다.


```suggestion
        if (!user.isSamePassword(passwordEncoder, password)) {
            throw new AuthenticationException("올바르지 않은 비밀번호입니다.");
        }
```

2024-04-30 00:27 UTC, Choi-JJunho commented on src/test/java/in/koreatech/koin/acceptance/UserApiTest.java
> +            .statusCode(HttpStatus.UNAUTHORIZED.value());
### C

테스트를 분리하는게 좋지 않을까 싶네요
"사용자가 비밀번호를 통해 자신이 맞는지 인증한다. - 비밀번호가 다르면 401 반환"

2024-04-30 00:28 UTC, Choi-JJunho commented on src/main/java/in/koreatech/koin/domain/user/service/UserService.java
> +            throw new AuthenticationException("올바르지 않은 비밀정보입니다.");
해당 내용 제가 다른 PR에서 리팩터링했습니다
- https://github.com/BCSDLab/KOIN_API_V2/pull/485
확인해주세요

2024-04-30 01:00 UTC, seongjae6751 commented on src/main/java/in/koreatech/koin/domain/user/service/UserService.java
> +        }
헉 그렇군요 반영했습니다!

2024-04-30 01:04 UTC, seongjae6751 commented on src/test/java/in/koreatech/koin/acceptance/UserApiTest.java
> +            .statusCode(HttpStatus.UNAUTHORIZED.value());
반영했습니다!

2024-04-30 01:52 UTC, Choi-JJunho approved these changes
고생하셨습니다~

2024-04-30 02:07 UTC, daheeParkk approved these changes

2024-04-30 02:09 UTC, merged