feat: 상점 운영중 기준으로 정렬 및 is_event 필드 추가
BCSDLab/KOIN_API_V2 pull request #479
Opened 2024-04-28 05:54 UTC by 20HyeonsuLee

# 🔥 연관 이슈

- close #471 

# 🚀 작업 내용

1. 응답에 `is_open`필드를 추가했습니다.
2. 상점이 운영중인지 판단하기 위해 각 상점마다 쿼리를 날려서 확인했습니다.
3. `is_open=true`인것들이 상단에 표시되게 정렬되어 응답되도록 변경하였습니다.
4. 응답 변경에 따른 테스트코드를 수정하였습니다.

# 💬 리뷰 중점사항
`GET /shops`api의 실행시간이 500ms에서 800ms정도로 느려졌는데 이 부분에 대해서 당장 성능 최적화를 해야할지 궁금합니다.
여담: 1초 이내 수행되면 사람이 빠르다고 느낀다고 합니다

2024-04-28 08:02 UTC, johnny19991006 reviewed
고생하셨습니다.~
성능 최적화의 이야기는 나중에 Redis를 활용해서 응답시간을 줄이면 어떨지 제안해봅니다~

2024-04-28 08:02 UTC, johnny19991006 commented on src/main/java/in/koreatech/koin/domain/shop/repository/ShopOpenRepository.java
> +
데이터를 다 받아와서 서비스 상에서 로직을 돌리는게 아닌 직접 db에서 쿼리문으로 로직을 돌린 이유는 무엇인가요?

2024-04-28 09:20 UTC, 20HyeonsuLee commented on src/main/java/in/koreatech/koin/domain/shop/repository/ShopOpenRepository.java
> +
로직으로 처리하는것도 고민해봤었는데 쿼리문으로 짜는편이 더 간결하게 작성되길래 쿼리문으로 작성했습니당
또 로직으로 처리하는것과 쿼리문으로 차리하는것에서 큰 성능차이가 없었던것도 이유중 하나입니다

2024-04-28 11:40 UTC, johnny19991006 approved these changes

2024-04-29 03:06 UTC, Choi-JJunho requested changes
코멘트 확인 한번 부탁드려요~

2024-04-29 03:06 UTC, Choi-JJunho commented on src/test/java/in/koreatech/koin/acceptance/ShopApiTest.java
> +        String dayOfWeek = LocalDate.now().getDayOfWeek().getDisplayName(TextStyle.FULL, Locale.US).toUpperCase();
### R

- https://github.com/BCSDLab/KOIN_API_V2/pull/482/files#r1582396098

> 리뷰: 테스트에서 now 사용할때 clock 주입해서 사용해주세요
> 2024-01-15 12:00:00 으로 시간 고정됩니다

> 질문: /shops api가 현재날짜 기준으로 운영중 여부를 반환하는데 clock을 사용해도 되는걸까요?

위 코멘트 이어서 리뷰 남깁니다.

현재 JpaAuditing 및 Clock에 대해서 테스트 전역적으로 시간이 고정되어있습니다.

시간을 고정하는 이유는 테스트가 시간에 따라 영향을 받지 않게하기 위함에 있습니다.
아래와 같이 날짜별로 테스트 결과가 달라지는 경우 if문으로 가능한 시간대를 모두 예외처리해줘야합니다.

- https://github.com/BCSDLab/KOIN_API_V2/pull/458

위 PR에서 설정했듯이 테스트의 세상에서는 2024-01-15 12:00 분으로 시간을 고정시켜서 다음과 같은 상황을 미연에 방지할 수 있습니다.

```
1월 15일 11:59:59.9999초에 엔티티 생성 -> 1월 16일 00:00:00.00001초에 API 실행 -> 예상하지 못한 시간대 변경으로 테스트 실패
```

저는 테스트는 시간, 공간에 제약을 받지 않고 항상 동일한 결과를 도출해야한다고 생각합니다.
이에 대해서 테스트를 올바르게 적용하려면 /shops API가 현재 시간을 구분할 때 LocalDateTime.now(clock) 을 활용하도록 수정이 필요해보이네요

2024-04-29 03:06 UTC, Choi-JJunho commented on src/main/java/in/koreatech/koin/domain/shop/repository/ShopOpenRepository.java
> +
현재 시간은 Java에서 관리하도록 하는것이 좋다고 생각합니다.

1. DB 혹은 OS 혹은 jvm에서 다루는 TimeZone이 다를 수 있음
    - jvm에서의 timeZone으로 통일시켜서 쿼리를 날리는게 조금 더 통일성있지 않을까 싶네요
2. 테스트하기 용이한 코드
    - 테스트쪽의 코멘트 확인해주세요

2024-04-29 03:09 UTC, 20HyeonsuLee commented on src/test/java/in/koreatech/koin/acceptance/ShopApiTest.java
> +        String dayOfWeek = LocalDate.now().getDayOfWeek().getDisplayName(TextStyle.FULL, Locale.US).toUpperCase();
테스트에서 보내는 요청은 Clock의 시간으로 처리된다는 말씀이 맞을까요?

2024-04-29 03:10 UTC, Choi-JJunho commented on src/test/java/in/koreatech/koin/acceptance/ShopApiTest.java
> +        String dayOfWeek = LocalDate.now().getDayOfWeek().getDisplayName(TextStyle.FULL, Locale.US).toUpperCase();
네네~!
LocalDateTime.now(clock) 으로 저희가 제어하는 시간대로 맞추고자 하는 의도가 있습니다

2024-04-29 05:22 UTC, 20HyeonsuLee commented on src/test/java/in/koreatech/koin/acceptance/ShopApiTest.java
> +        String dayOfWeek = LocalDate.now().getDayOfWeek().getDisplayName(TextStyle.FULL, Locale.US).toUpperCase();
꼼꼼한 설명 감사합니다 덕분에 이해했습니다!

2024-04-29 06:19 UTC, Choi-JJunho approved these changes
Good 고생하셨습니다

2024-04-29 06:21 UTC, merged