fix: 상점 수정시 배달금액 언더플로우 해결
BCSDLab/KOIN_API_V2 pull request #482
Opened 2024-04-28 15:32 UTC by 20HyeonsuLee

# 🔥 연관 이슈

- close #481

# 🚀 작업 내용

1. DB의 `delivery_price`가 `unsigned int`이기 때문에 음수를 입력할 시 발생한 에러였습니다.
2. 상점 수정 dto의 배달금액 필드에 `@Min`어노테이션을 이용해 0원이상 입력되도록 설정하였습니다.
3. 수정하는김에 메뉴 금액도 0원이상 입력하도록 수정하였습니다.

# 💬 리뷰 중점사항
리뷰 잘부탁드립니다!

2024-04-28 21:21 UTC, Choi-JJunho requested changes
굿굿! 사소한부분 몇개만 확인해주세요

2024-04-28 21:21 UTC, Choi-JJunho commented on src/main/java/in/koreatech/koin/domain/shop/dto/CreateMenuRequest.java
> +    @Min(value = 0, message = "가격은 0원 이상이어야 합니다.")
### C

PositiveOrZero라는 어노테이션도 있었던거같네요

2024-04-28 21:21 UTC, Choi-JJunho commented on src/main/java/in/koreatech/koin/domain/shop/repository/ShopOpenRepository.java
> +          )
### A
쿼리가 까리하네요..

2024-04-28 21:21 UTC, Choi-JJunho commented on src/main/java/in/koreatech/koin/domain/shop/service/ShopService.java
> +                boolean inOperation = shopOpenRepository.isOpen(shop.getId());
### C

메소드는 isOpen, 변수명은 isOperation 어떤게 맞는 정보일까요?

2024-04-28 21:21 UTC, Choi-JJunho commented on src/test/java/in/koreatech/koin/acceptance/ShopApiTest.java
> +        }else if (
### R
포맷팅해주세요

2024-04-28 21:21 UTC, Choi-JJunho commented on src/test/java/in/koreatech/koin/acceptance/ShopApiTest.java
> +        String dayOfWeek = LocalDate.now().getDayOfWeek().getDisplayName(TextStyle.FULL, Locale.US).toUpperCase();
### R

테스트에서 now 사용할때 clock 즈입해서 사용해주세요

2024-01-15 12:00:00 으로 시간 고정됩니다

2024-04-29 02:19 UTC, 20HyeonsuLee commented on src/test/java/in/koreatech/koin/acceptance/ShopApiTest.java
> +        String dayOfWeek = LocalDate.now().getDayOfWeek().getDisplayName(TextStyle.FULL, Locale.US).toUpperCase();
`/shops` api가 현재날짜 기준으로 운영중 여부를 반환하는데 clock을 사용해도 되는걸까요?

2024-04-29 02:21 UTC, 20HyeonsuLee commented on src/main/java/in/koreatech/koin/domain/shop/service/ShopService.java
> +                boolean inOperation = shopOpenRepository.isOpen(shop.getId());
이벤트가 메소드는 isEvent, 변수명은 `eventDuration`으로 되어있어서 비슷한 느낌으로 가져갔는데 하나로 통일하는게 좋을까요? 통일한다면 eventDuration도 isEvent롤 바꿔도 될까요?

2024-04-29 02:22 UTC, 20HyeonsuLee commented on src/main/java/in/koreatech/koin/domain/shop/repository/ShopOpenRepository.java
> +          )
요고는 이전pr에서 작업한 내용인데 아직 머지가 안돼서 여기에 딸려왔네요..

2024-04-29 02:54 UTC, Choi-JJunho commented on src/main/java/in/koreatech/koin/domain/shop/repository/ShopOpenRepository.java
> +          )
앗 핸드폰으로 리뷰해서 하나밖에 못봤었네요

2024-04-29 02:55 UTC, Choi-JJunho commented on src/test/java/in/koreatech/koin/acceptance/ShopApiTest.java
> +        String dayOfWeek = LocalDate.now().getDayOfWeek().getDisplayName(TextStyle.FULL, Locale.US).toUpperCase();
이전 PR에 이어서 달겠습니다 😓

2024-04-29 06:27 UTC, Choi-JJunho approved these changes
<img width="447" alt="image" src="https://github.com/BCSDLab/KOIN_API_V2/assets/49794401/b408633c-864c-4856-816d-3a1b3d860dd1">

Entity에도 @PositiveOrZero 걸어주는거 어떤가요
Persist 시점에 검증한답니다 :)

2024-04-29 06:45 UTC, johnny19991006 approved these changes

2024-04-29 06:45 UTC, merged