hotfix: 버스 API 응답시간 개선 및 응답 스키마 불일치 해결
BCSDLab/KOIN_API_V2 pull request #499
Opened 2024-05-02 09:03 UTC by songsunkook

# 🔥 연관 이슈

# 🚀 작업 내용

1. 시외버스/시내버스 OPEN API를 호출하는 주기 변경
    - 기존: 요청 시마다 캐시가 없으면 요청
    - 개선: 시내버스는 매 분마다, 시외버스는 매 시간마다 자동으로 호출하여 캐싱
    - 기대 효과: 코인 버스 API 호출 시간이 5초에서 0.1초 안쪽으로 개선됨
2. 응답 객체 불일치 문제 해결
    - bus timetable v2 API의 응답 객체가 어느순간 바뀌어있어서 안드로이드 프로덕션이 고장남
    - 원상복구
3. 어색하게 처리된 예외처리 수정

# 💬 리뷰 중점사항
### 이거 핫픽스로 올린거라 프로덕션으로 바로 머지됩니다.
머지 이후 production(main 브랜치)에 머지된 후 develop 브랜치에 다시 머지해야 합니다.
프로덕션에 바로 올라갈 내용이니 크리티컬한 이슈가 없는지 확인해주세요!

+) 머지된 이후 프로덕션 적용 배포는 오늘 자정에 해도 괜찮을까요?? @Choi-JJunho

2024-05-02 13:30 UTC, dradnats1012 requested changes
의논할만한 부분 코멘트 남겼습니다!

2024-05-02 13:30 UTC, dradnats1012 commented on src/main/java/in/koreatech/koin/domain/bus/util/CityBusOpenApiClient.java
> -    private List<CityBusRemainTime> getCityBusArrivalInfoByCache(String nodeId) {
아예 캐시 확인 로직을 빼도 괜찮을까요?
혹시나 외부 api 문제로 캐싱이 제대로 되지 않아 유효시간이 지나 캐시가 아예 없을 상황이 생길 수도 있을 것 같다는 생각이 드는데 어떻게 생각하시나요??

또 다른 의견은 기존의 시내버스 캐시 확인 로직은 버전 테이블을 참고했는데 시외버스처럼 레디스에 캐시아이디를 검색해서 확인하는 방법은 어떤가 의견이 궁금합니다!!

2024-05-02 13:30 UTC, dradnats1012 commented on src/main/java/in/koreatech/koin/domain/bus/util/ExpressBusOpenApiClient.java
시외버스 부분도 마찬가지로 캐시 확인 로직을 아예 없애는것에 대해서 불안합니다..!
의견이 궁금해용

2024-05-02 13:57 UTC, songsunkook commented on src/main/java/in/koreatech/koin/domain/bus/util/CityBusOpenApiClient.java
> -    private List<CityBusRemainTime> getCityBusArrivalInfoByCache(String nodeId) {
캐시 유효기간을 스케줄링의 2배 시간으로 늘리는 건 어떨까요?? 기존에 캐시가 있다면 덮어씌워지고 open api 문제가 있어도 한 번까지는 넘길 수 있는 장치가 된다고 생각합니다.

2024-05-02 14:04 UTC, dradnats1012 commented on src/main/java/in/koreatech/koin/domain/bus/util/CityBusOpenApiClient.java
> -    private List<CityBusRemainTime> getCityBusArrivalInfoByCache(String nodeId) {
캐시 유효시간을 늘리는것도 괜찮을 것 같네요!
그럼 다른 의견으로 isCacheExpired를 레디스에서 캐시 확인하는 방식으로 캐시가 없다면 에러를 던지는 방식은 어떤지 궁금해요!!!

2024-05-02 14:21 UTC, songsunkook commented on src/main/java/in/koreatech/koin/domain/bus/util/CityBusOpenApiClient.java
> -    private List<CityBusRemainTime> getCityBusArrivalInfoByCache(String nodeId) {
버스 정보가 없으면 openapi를 조회해도 캐시가 저장되지 않지 않나요?? 이 방식은 힘들 것 같습니당

2024-05-02 14:51 UTC, songsunkook commented on src/main/java/in/koreatech/koin/domain/bus/util/CityBusOpenApiClient.java
> -    private List<CityBusRemainTime> getCityBusArrivalInfoByCache(String nodeId) {
아 도착정보가 없어도 캐싱을 하는건가요..? 그럼 괜찮을 것 같네요! 유효기간을 늘려두고 그럼에도 캐시가 없다면 500번대 에러를 핸들링하도록(슬랙엔 안터지게) 하면 좋을 것 같아요

2024-05-02 16:13 UTC, Choi-JJunho commented on src/test/java/in/koreatech/koin/acceptance/BusApiTest.java
> +//TODO
### R

이게 뭐죠?

2024-05-04 06:33 UTC, songsunkook commented on src/test/java/in/koreatech/koin/acceptance/BusApiTest.java
> +//TODO
이런.. 수정했습니다 감사합니다

2024-05-04 06:47 UTC, johnny19991006 approved these changes
고생하셨습니다..! 핫픽스니 어푸르브를 조금더 모아보죠

2024-05-04 06:47 UTC, johnny19991006 commented on src/main/java/in/koreatech/koin/domain/bus/util/ExpressBusOpenApiClient.java
> +            }
코드 가독성이 조금 아쉽긴 한데 메서드로 따로 안뺀거는 매서드 재사용을 안해서 그러신거죠..?

2024-05-04 06:53 UTC, Choon0414 approved these changes
고생 많으셨습니다!

2024-05-04 07:42 UTC, dradnats1012 approved these changes
고생하셨습니다!!

2024-05-04 07:55 UTC, songsunkook commented on src/main/java/in/koreatech/koin/domain/bus/util/ExpressBusOpenApiClient.java
> +            }
분리하기 애매하기도 하고 hotfix라 빠르게 대응하느라 진행하지 못했습니다

2024-05-04 07:56 UTC, merged