fix : 품절 알림 발송 여부, 시간대 조건, 경로 추가
BCSDLab/KOIN_API_V2 pull request #501
Opened 2024-05-02 15:50 UTC by Choon0414

# 🔥 연관 이슈

- close #444 
- close #461 

# 🚀 작업 내용

1. 품절 취소 시에도 알림이 가는 버그를 수정했습니다.
2. 품절 요청 시, 해당 식사 시간 내에만 알림이 가도록 수정했습니다.
3. 품절 재요청 시, 기존에 알림이 발송된 식단의 경우 알림이 가지 않도록 수정했습니다.
4. 모바일에서 품절 알림 클릭 시, 앱 내 상세 식단 페이지 리다이렉트를 위한 `appPath`를 추가했습니다.
5. 알림 관련 테스트를 세분화 했습니다.

# 💬 리뷰 중점사항
- 품절 이벤트 발생 이후, 품절 알림이 발송 되는지에 대해서도 테스트를 하고 싶어서 `notificationService`를 모킹해서 진행했는데, 이런 식으로 테스트를 해도 되는지 확인 부탁드립니다.
- 품절 알림 발송 여부를 `Listener`에서 판단하다 보니 `DiningSoldOutEvent`를 전달하는 부분이 어색한 것 같습니다.
리뷰 부탁드립니다!

2024-05-02 16:09 UTC, Choi-JJunho requested changes
isSent 속성은 필요 없을거같아요 확인해주세요!

2024-05-02 16:09 UTC, Choi-JJunho commented on src/main/java/in/koreatech/koin/global/domain/notification/model/NotificationFactory.java
> +    }
### C

조사를... 판단하는 코드인가요?

2024-05-02 16:09 UTC, Choi-JJunho commented on src/main/java/in/koreatech/koin/global/domain/notification/model/NotificationFactory.java
> +            "%s 품절되었습니다.".formatted(getPostposition(place, "이", "가")),
### C

능수관`이` 를 제외한 나머지는 `가`가 들어가는거같은데.. 굳이 조사 구분해준 이유가 있나요?

A코너`가`, A[에이]`가` ...

2024-05-02 16:09 UTC, Choi-JJunho commented on src/main/java/in/koreatech/koin/domain/coop/model/CoopEventListener.java
> +        if (now.isBefore(diningTime.get("startTime")) || now.isAfter(diningTime.get("endTime"))) {
### R

enum 내부에 선언되어있는 Map의 구조를 알지 못하면 diningTime.get() 과정에서 휴먼에러가 발생할 수 밖에 없을것같아요
Map보다 명시적인 타입으로 구성할수는 없을까요?

2024-05-02 16:09 UTC, Choi-JJunho commented on src/main/java/in/koreatech/koin/domain/coop/model/CoopEventListener.java
> +        }
### R
이게 굳이 필요할까 싶네요
dining의 soldOut 속성으로 충분히 분간이 가능해보여요

if (dining.getsoldOut() != null && dining.updatedAt() != dining.getSoldOut()) {

}

2024-05-02 16:27 UTC, Choon0414 commented on src/main/java/in/koreatech/koin/domain/coop/model/CoopEventListener.java
> +        }
훨씬 간단하네요 수정하겠습니다!

2024-05-02 16:39 UTC, Choon0414 commented on src/main/java/in/koreatech/koin/global/domain/notification/model/NotificationFactory.java
> +            "%s 품절되었습니다.".formatted(getPostposition(place, "이", "가")),
지금은 능수관/코너 밖에 없지만 알림 종류가 늘어나면 조사 구분이 필요한 메시지도 더 생길 거라 생각했습니다.

2024-05-03 04:50 UTC, Choon0414 commented on src/main/java/in/koreatech/koin/domain/coop/model/CoopEventListener.java
> +        }
품절과 재품절 사이에 메뉴가 변경되면 updatedAt도 변경되어서 검증이 어려울 것 같은데 어떻게 생각하시나요?

2024-05-04 06:02 UTC, songsunkook requested changes
리뷰 늦게달아서 죄송합니다 ㅠㅠ 
코멘트 확인 부탁드려요!

2024-05-04 06:02 UTC, songsunkook commented on src/main/java/in/koreatech/koin/domain/dining/dto/DiningResponse.java
> +    boolean isSent
동시간대에 품절 알림을 2번 이상 보내지 않기 위해 DB에 전송 여부를 저장 한 것 같아요!
저도 계속 저장해야할 정보는 아니라고 생각해서, 식사시간 길이의 유효기간을 가지는 레디스 토큰을 만들어 검증하는 건 어떨까요?

2024-05-05 04:06 UTC, Choon0414 commented on src/main/java/in/koreatech/koin/domain/dining/model/DiningType.java
> +    private final LocalTime endTime;
좋은 것 같아요 수정하겠습니다!

2024-05-05 04:09 UTC, Choon0414 commented on src/main/java/in/koreatech/koin/domain/dining/dto/DiningResponse.java
> +    boolean isSent
알림을 보내려면 해당 식사시간에만 생성되는 레디스 토큰을 가져다 써야하고, 사용 후 없어지면 알림을 보내지 못하는 방식으로 이해했는데 맞나요?

2024-05-05 12:50 UTC, songsunkook commented on src/main/java/in/koreatech/koin/domain/dining/dto/DiningResponse.java
> +    boolean isSent
아닙니다! 제가 생각한 방향은 아래와 같아요

알림 전송 조건
- 식사시간이어야 한다. (LocalTime으로 측정)
- 이번 식사시간에 이미 알림을 보낸 이력이 없어야 한다. (Redis에 토큰이 없어야 함)

알림 이력 관리 (Redis)
- 알림을 전송함과 동시에 Redis에 식단 품절 알림을 전송했다는 의미의 토큰을 저장한다.
    - 이 토큰의 유효기간은 식사시간과 같아서 한 번 알림을 전송하면 그 식사시간에는 다시 알림을 전송하지 않게 됩니다.
    - ex) 09:20 품절 알림 -> 11:20까지는 다시 알림이 가지 않음

토큰 유효기간 조절
- 식사시간은 매번 다르지만(저녁_1시간, 아침_1시간반, 점심_2시간) 그 간격을 감안했을 때 2시간으로 적용하면 좋을 것 같습니다.
- 아니면 알림 발송 시각을 기준으로 해당 식사시간의 마감시간까지를 유효기간으로 두는 것도 좋아보입니다.

2024-05-05 13:37 UTC, Choon0414 commented on src/main/java/in/koreatech/koin/domain/dining/dto/DiningResponse.java
> +    boolean isSent
이해했습니다! '식사시간 내'라는 조건도 같이 있어서 유효 시간을 2시간으로 고정해도 괜찮을 것 같아요.
위 내용대로 수정하겠습니다.

2024-05-06 07:05 UTC, songsunkook approved these changes
라이브 코드리뷰 진행했습니다. 테스트 잘 짜주셨네요!
고생하셨습니다~

2024-05-06 09:42 UTC, Choi-JJunho requested changes

2024-05-06 10:51 UTC, Choon0414 commented on src/main/java/in/koreatech/koin/domain/coop/model/CoopEventListener.java
> +    public void onDiningSoldOutRequest(String place) {
아 public가 쏘는 다른 String들에 대해서도 반응할 수 있다는걸 생각 못했네요. 수정했습니다.

2024-05-06 20:54 UTC, Choi-JJunho approved these changes

2024-05-07 00:43 UTC, merged