Feat: 어드민 복덕방 생성 API
BCSDLab/KOIN_API_V2 pull request #505
Opened 2024-05-05 09:49 UTC by johnny19991006

# 🔥 연관 이슈

- close #11 

# 🚀 작업 내용

1.어드민API에서 복덕방 수정하는 API작성하였습니다.
![image](https://github.com/BCSDLab/KOIN_API_V2/assets/79901434/ea4401bf-8cff-4abe-ba22-af86e3005c9f)

# 💬 리뷰 중점사항
질문-> 현재 짜져있는 admin get land API에서는 domain(일반)의 Land를 참조하고 있던데,  혹시 어드민 짤때는 dao(model) 전략을 어떻게 가져갈지 궁금합니다.
1. 기존의 DAO참조
2. 기존의 DAO에서 상속받아 사용
3. 새로 DAO를 만들어 사용 (ex Land.java / AdminLand.java분리)

왜냐하면 이번에 코드를 짜면서 불편한 점이 있어 그랬습니다.
아래는 상황 설명입니다.
- 현재 Land의 imageUrl은 String형태 이다.(service단에서 image관련 로직 처리를 한다.)
- 하지만 AdminLandRequest에서는 List로 받아서 여러개의 image를 받을수 있게 해야 한다.
- 즉 build를 하는 과정에서 한번더 처리를 해줘야 하는 번거로움이 발생한다. 어드민용 dao가 있는것이 나을것 같다는 생각을 함.

2024-05-05 10:07 UTC, Choi-JJunho requested changes
고생하셨습니다
코멘트 확인해주세요~

2024-05-05 10:07 UTC, Choi-JJunho commented on src/main/java/in/koreatech/koin/admin/land/repository/AdminLandRepository.java
> +    Land findByName(String name);
### R

findBy의 네이밍은 Optional로 반환하는 것으로 컨벤션을 정했습니다.
[📚 코드 컨벤션 - 메서드 이름](https://github.com/BCSDLab/KOIN_API_V2/wiki/%F0%9F%93%9A-%EC%BD%94%EB%93%9C-%EC%BB%A8%EB%B2%A4%EC%85%98#%EB%A9%94%EC%84%9C%EB%93%9C-%EC%9D%B4%EB%A6%84) 확인 부탁드립니다.

```suggestion
    Optional<Land> findByName(String name);
    
    default Land getByName(String name) {
        return findByName(name).orElseThrow(() -> LandNotFoundException.withDetail("name: " + name));
    }
```

다른 Repository 확인해주세요

2024-05-05 10:07 UTC, Choi-JJunho commented on src/main/java/in/koreatech/koin/admin/land/dto/AdminLandsRequest.java
> +    // Continue adding other options following the same pattern
### R

불필요한 주석이네요~

2024-05-05 10:07 UTC, Choi-JJunho commented on src/main/java/in/koreatech/koin/admin/land/dto/AdminLandsRequest.java
> +@JsonNaming(PropertyNamingStrategies.SnakeCaseStrategy.class)
### R

static import 해주세요
```suggestion
@JsonNaming(SnakeCaseStrategy.class)
```

2024-05-05 10:07 UTC, Choi-JJunho commented on src/main/java/in/koreatech/koin/admin/land/dto/AdminLandsRequest.java
> +        }
### R

이건 어떤 역할을 하는 메소드죠?

2024-05-05 10:07 UTC, Choi-JJunho commented on src/main/java/in/koreatech/koin/admin/land/service/AdminLandService.java
> +        }
### R

Repository 내부에서 예외처리를 해주면 해당 예외처리는 필요 없을 것 같아요

2024-05-05 10:15 UTC, johnny19991006 commented on src/main/java/in/koreatech/koin/admin/land/dto/AdminLandsRequest.java
> +        }
DTO에서 list<Stinrg>으로 받아서 DB에 넣을때 ["image1","image2"]위와 같은 형식으로 List<String>으로 저장할수 있게 해주는 매서드 입니다

2024-05-05 10:15 UTC, johnny19991006 commented on src/main/java/in/koreatech/koin/admin/land/dto/AdminLandsRequest.java
> +@JsonNaming(PropertyNamingStrategies.SnakeCaseStrategy.class)
넵

2024-05-05 10:18 UTC, Choi-JJunho requested changes

2024-05-05 10:18 UTC, Choi-JJunho commented on src/main/java/in/koreatech/koin/domain/land/model/Land.java
>      }
### R
Entity에는 String이고 Get 해왔을때의 결과는 List<String>이여야하는 상황이라면 Land Entity에서 getImageUrls를 구현하면 될거같아요

Dining Entity의 getMenu() 메소드를 참고해보시면 될거같네요

ex)
```java
/**
 * DB에 "[메뉴, 메뉴, ...]" 형태로 저장되어 List로 파싱하여 반환
 */
public List<String> getMenu() {
    if (menu == null || menu.isBlank()) {
        throw new KoinIllegalStateException("메뉴가 잘못된 형태로 저장되어있습니다.", menu);
    }
    return Stream.of(menu.substring(1, menu.length() - 1).split(","))
        .map(str -> str.strip().replace("\"", ""))
        .toList();
}
```

2024-05-05 14:28 UTC, johnny19991006 commented on src/main/java/in/koreatech/koin/admin/land/service/AdminLandService.java
> +        }
감사합니다.
if (adminLandRepository.findByName(adminLandsRequest.name()).isPresent()) {
    throw LandNameDuplicationException.withDetail("email: " + adminLandsRequest.name());
}
와 (지금 마이그레이션 컨벤션)
Land existingLand = adminLandRepository.findByName(adminLandsRequest.name());
if (existingLand != null) {
    throw LandNameDuplicationException.withDetail("Land: " + existingLand.getName());
}
(레가시 컨벤션)
코드 모두 동작방식은 같지만 지적해 주신 코드가 Optional을 사용하여 혹시나 모를 null처리를 감싸주는 효과가 있네요.(물론 dto에서 notnull처리를 하여 null이 나올수는 없지만요.)

2024-05-05 17:00 UTC, 20HyeonsuLee requested changes
코드 안치신다고 하시더니 정말 잘 작성해주셨네요..! 몇가지 코멘트 남겼습니다!

2024-05-05 17:19 UTC, johnny19991006 commented on src/main/java/in/koreatech/koin/domain/land/model/Land.java
> +            .collect(Collectors.joining(", ")) + "]";
오우 dto에서 dao로 로직 바꿀때 실수를 했나봅니다.!!! 체킹 정말 감사합니다

2024-05-05 17:20 UTC, johnny19991006 commented on src/main/java/in/koreatech/koin/domain/land/model/Land.java
> +        this.imageUrls = convertImageUrlsToJson(imageUrls);
Jpa에서는 dao에서 list<string>형태로 받을수 없기에 괴랄한 구조가 되었습니다..

2024-05-05 17:20 UTC, johnny19991006 commented on src/main/java/in/koreatech/koin/domain/land/model/Land.java
> +        }
넵!!

2024-05-05 17:22 UTC, Choi-JJunho commented on src/main/java/in/koreatech/koin/domain/land/model/Land.java
> +            .collect(Collectors.joining(", ")) + "]";
추가로 다음과 같이 간결하게 나타낼 수도 있을 것같아요

return String.format("[%s]", imageUrls.collect(.collect(Collectors.joining(",")));

2024-05-05 17:23 UTC, johnny19991006 commented on src/main/java/in/koreatech/koin/domain/land/model/Land.java
> +            .collect(Collectors.joining(", ")) + "]";
오우 감사합니다..!!!

2024-05-05 17:27 UTC, johnny19991006 commented on src/main/java/in/koreatech/koin/domain/land/model/Land.java
> +            .collect(Collectors.joining(", ")) + "]";
그 List<String>타입에서는 .collect타입을 직접적으로 사용할수 없어서 
return String.format("[%s]", imageUrls.stream()
        .map(url -> "\"" + url + "\"")
        .collect(Collectors.joining(",")));
        이런식으로 사용해야 할것 같습니다!

2024-05-05 17:29 UTC, Choi-JJunho commented on src/main/java/in/koreatech/koin/domain/land/model/Land.java
> +            .collect(Collectors.joining(", ")) + "]";
String.format("[%s]", String.join(",", images).strip());
이런코드도 가능한거 알고계셨나요 ㅋㅋ

2024-05-05 17:31 UTC, johnny19991006 commented on src/main/java/in/koreatech/koin/domain/land/model/Land.java
> +            .collect(Collectors.joining(", ")) + "]";
OH.... 코드 장인들 점점 복잡하면서 간결해지는군요.. 작업 드가겠습니다.

2024-05-05 17:37 UTC, johnny19991006 commented on src/main/java/in/koreatech/koin/domain/land/model/Land.java
> +            .collect(Collectors.joining(", ")) + "]";
요방식은 [xxxx,xxxxx]이런식으로 저장이 됩니다.
["xxxx","xxxxx"]이런식으로 저장이 되어야 하기에
return String.format("[%s]", imageUrls.stream()
        .map(url -> "\"" + url + "\"")
        .collect(Collectors.joining(",")));
        이러한 형식으로 해결을 하는게 최선이지 않나 싶습니다..!

2024-05-05 17:43 UTC, Choi-JJunho commented on src/main/java/in/koreatech/koin/domain/land/model/Land.java
> +            .collect(Collectors.joining(", ")) + "]";
굿굿

2024-05-05 17:47 UTC, Choi-JJunho commented on src/main/java/in/koreatech/koin/admin/land/dto/AdminLandsRequest.java
> +    @Schema(description = "이름 - not null - 최대 255자", example = "금실타운", required = true)
###R
required 옵션은 Deprecated 되었습니다. requiredMode 로 수정해주세요
```suggestion
    @Schema(description = "이름 - not null - 최대 255자", example = "금실타운", requiredMode = Required)
```

2024-05-05 17:50 UTC, Choi-JJunho commented on src/main/java/in/koreatech/koin/admin/land/dto/AdminLandsRequest.java
> +    Boolean optRefrigerator,
### A

단순 궁금증인데 primitiveType으로하면 default value가 false로 담기나요?

```suggestion
    @Schema(description = "냉장고 보유 여부 - null일경우 false로 요청됨", example = "true")
    boolean optRefrigerator,
```

2024-05-05 17:53 UTC, johnny19991006 commented on src/main/java/in/koreatech/koin/admin/land/dto/AdminLandsRequest.java
> +    Boolean optRefrigerator,
그건 아니고 제가 아래서 따로 세팅을 해놓았습니다.
.optRefrigerator(optRefrigerator != null ? optRefrigerator : false)
더 좋은 방법은 boolean으로 정의하는거네요

2024-05-05 17:55 UTC, johnny19991006 commented on src/main/java/in/koreatech/koin/admin/land/dto/AdminLandsRequest.java
> +    Boolean optRefrigerator,
Boolean(Wrapper클래스)-디폴트값 null
boolean(Primitive타입)-디폴트값 false

2024-05-05 17:59 UTC, johnny19991006 commented on src/main/java/in/koreatech/koin/admin/land/dto/AdminLandsRequest.java
> +    Boolean optRefrigerator,
같은 의미이긴 하지만 컨벤션에 맞춘 대세에 따라가겠습니다.

2024-05-05 18:00 UTC, johnny19991006 commented on src/main/java/in/koreatech/koin/admin/land/dto/AdminLandsRequest.java
> +    @Schema(description = "이름 - not null - 최대 255자", example = "금실타운", required = true)
이것도 옛날 레가시를 따라가다보니 맞추지 못했네요..
계속 레가시 코드에 벗어나지 못해서 지적이 나오는군요

2024-05-05 18:03 UTC, Choi-JJunho commented on src/main/java/in/koreatech/koin/admin/land/controller/AdminLandController.java
> +    @Override
Override 생략해주세용

2024-05-05 18:04 UTC, Choi-JJunho commented on src/main/java/in/koreatech/koin/admin/land/service/AdminLandService.java
> +
###R
불필요한 공백이 있네요

2024-05-05 18:05 UTC, Choi-JJunho commented on src/main/java/in/koreatech/koin/domain/land/model/Land.java
> +    private String convertImageUrlsToJson(List<String> imageUrls) {
### C
함수명이 다소 직관적이지 못한거같아요 뭔가 objectMapper 쓸거같은 이름이네요
어짜피 인자로 List<String>을 받고있고 String을 반환하는 함수니까 convertToString 정도는 어떤가요?

2024-05-05 18:06 UTC, Choi-JJunho commented on src/test/java/in/koreatech/koin/admin/acceptance/AdminLandApiTest.java
> +            .when()
### R

body를 request 객체가 아닌 json 형태로 만들어서 넣어보는건 어떨까요?

```java
            .body("""
                {
                  "email": "test@koreatech.ac.kr",
                  "password": "1234"
                }
                """)
```

2024-05-05 18:08 UTC, Choi-JJunho commented on src/test/java/in/koreatech/koin/admin/acceptance/AdminLandApiTest.java
> +        softly.assertAll();
### R
다른 코드 참고해서 작성해주세요~~
```suggestion
        SoftAssertions.assertSoftly(softly -> {
          softly.assertThat(savedLand.getName()).as("복덕방명 확인").isEqualTo("금실타운");
          softly.assertThat(savedLand.getAddress()).as("주소확인").isEqualTo("충청남도 천안시 동남구 병천면");
          softly.assertThat(savedLand.getDescription()).as("계약사항 확인").isEqualTo("1년 계약시 20만원 할인");
          softly.assertThat(savedLand.getMonthlyFee()).as("월세확인").isEqualTo("200만원 (6개월)");
        });
```

2024-05-05 18:09 UTC, Choi-JJunho commented on src/test/java/in/koreatech/koin/admin/acceptance/AdminLandApiTest.java
> +        softly.assertAll();
### A
as()는 어떤 역할을 하는건가요? (진짜 몰라서 물어봄)

2024-05-05 18:10 UTC, johnny19991006 commented on src/test/java/in/koreatech/koin/admin/acceptance/AdminLandApiTest.java
> +        softly.assertAll();
그냥 DisplaName같은거라고 보심 됩니다..1

2024-05-05 18:12 UTC, johnny19991006 commented on src/test/java/in/koreatech/koin/admin/acceptance/AdminLandApiTest.java
> +            .when()
저는 Given When Then구조를 맞추려고 request형식으로 넣을려고 했는데, 참고하겠습니다!

2024-05-05 18:16 UTC, johnny19991006 commented on src/test/java/in/koreatech/koin/admin/acceptance/AdminLandApiTest.java
> +        softly.assertAll();
안좋아하시는것 같으니 제거하여 반영하겠습니다

2024-05-05 18:16 UTC, johnny19991006 commented on src/test/java/in/koreatech/koin/admin/acceptance/AdminLandApiTest.java
> +            .when()
생각해보니 그냥 request를 jsonBody로 바꾸면 되어서 크게 무리는 없을것 같습니다

2024-05-05 18:23 UTC, johnny19991006 commented on src/main/java/in/koreatech/koin/admin/land/controller/AdminLandController.java
> +    @Override
getLands까지 제거 완료했습니다

2024-05-05 18:38 UTC, Choi-JJunho commented on src/test/java/in/koreatech/koin/admin/acceptance/AdminLandApiTest.java
> +        "opt_microwave": true,
### A
혹시 값을 누락했을때도 잘 들어가는지 확인해볼수 있을까요?

2024-05-05 18:52 UTC, johnny19991006 commented on src/test/java/in/koreatech/koin/admin/acceptance/AdminLandApiTest.java
> +        "opt_microwave": true,
넵!

2024-05-06 07:36 UTC, YunYongWoon approved these changes
리뷰가 너무 늦어서 죄송합니다 ㅜㅜ.
딱히 코멘트 할건 없어서 코멘트 한두개 남기고 Approve 하겠습니다!

2024-05-06 07:36 UTC, YunYongWoon commented on src/main/java/in/koreatech/koin/admin/land/service/AdminLandService.java
> +            throw LandNameDuplicationException.withDetail("email: " + adminLandsRequest.name());
### A

`LandNameDuplicationException`에서 `name : 'xxx'`로 넣어주는데 여기서 `email: xxx`로 넣어줘야 되는지....에 대해 궁금증이 생겼습니다.

2024-05-06 07:36 UTC, YunYongWoon commented on src/main/java/in/koreatech/koin/domain/land/model/Land.java
> +        List<String> imageUrls,
### A

imageUrls가 DB에서 `["aaa", "bbb"]` 식으로 관리되고 있는게 충격이긴 하네요....

2024-05-06 08:24 UTC, johnny19991006 commented on src/main/java/in/koreatech/koin/admin/land/service/AdminLandService.java
> +            throw LandNameDuplicationException.withDetail("email: " + adminLandsRequest.name());
감사합니다! 바로 고치겠습니다!

2024-05-06 08:26 UTC, johnny19991006 commented on src/main/java/in/koreatech/koin/domain/land/model/Land.java
> +        List<String> imageUrls,
한번 db구조 변경이 필요할것 같긴 합니다..!!!

2024-05-07 09:38 UTC, 20HyeonsuLee approved these changes

2024-05-07 09:50 UTC, Choi-JJunho approved these changes

2024-05-07 09:51 UTC, merged