fear: admin으로 학생 정보 수정
BCSDLab/KOIN_API_V2 pull request #508
Opened 2024-05-07 07:54 UTC by seongjae6751

# 🔥 연관 이슈

- close #92 

# 🚀 작업 내용

1. 관리자 권한으로 특정 학생 정보를 수정할 수 있게 하였습니다.

# 💬 리뷰 중점사항
우선 관리자 계정이 맞는지 확인하기 위해 @Auth를 썼는데 가져온 관리자 id가 사용이 안되어서 이렇게 해도 되는가 고민이 많이 됩니다.. 관련해서 좋은 의견 있으면 말씀해주시면 감사하겠습니다

2024-05-08 06:48 UTC, kwoo28 requested changes
수고하셨습니다! 지금 로직으론 어드민계정에 접근 할 수 없어서 한번더 살펴봐야할것같습니다.

2024-05-08 06:48 UTC, kwoo28 commented on src/main/java/in/koreatech/koin/admin/user/controller/AdminUserController.java
> +        @Auth(permit = {ADMIN}) Integer adminId
## R

기존 코인로직은 DB에 있는 admin의 존재여부를 통해서 DB에 접근하는 방식입니다. 그래서 현재 구현한 코드처럼 단순히 @Auth(permit = {ADMIN})만 붙이면 현재 DB의 User에서 user_type을 ADMIN으로 전부 바꿔줘야하며, 추후에 유저회원에게 어드민 권한을 부여하는 서비스를 구현할때 User의 user_type을 admin으로 부여하게끔 구현해야합니다.

만약 DB에 있는 user_type을 변경하지 않고 기존코인 로직을 유지하게하려면, 현재 AuthArgumentResolver UserType을 통해서 검증하는 방식이 아닌, Authority객체를 구현한 후에 어드민이 존재하는지 확인하는 로직을 구현한 후에 @Auth(permit = {ADMIN})를 사용해야합니다.

그래서 요약하자면, DB에서 admin유저에 해당하는 userType을 수정하고 가독성을 높일건지, 기존 코인 로직을 유지할지 고민해봐야할것같은데 어덯게 하는게 좋을까요?

2024-05-08 09:08 UTC, kwoo28 approved these changes

2024-05-08 10:55 UTC, 20HyeonsuLee commented on src/main/java/in/koreatech/koin/admin/user/controller/AdminUserController.java
> +        @Auth(permit = {ADMIN}) Integer adminId
### admins테이블이 존재하는 이유
    - 어드민에 따라 권한을 다르게 줄 수 있다.
    - 굳이?? 어차피 지금 어드민 계정 하나로 돌려쓰고있는데 그럴 필요가 있나 싶다. 
    - 또 어드민 권한을 지금 시스템에서 그렇게 세분화할 필요가 있나 싶다.
    - 결국 지금 의미있는 기능을 하고있지 못하는 테이블이다.

### 내 생각
그냥 enum에 ADMIN권한 하나 추가해주고 아래의 관리자 권한을 STUDENT --> ADMIN으로 바꾸는게 낮지않나..
<img width="969" alt="image" src="https://github.com/BCSDLab/KOIN_API_V2/assets/127578418/31f0f84a-3c70-4ff8-9af5-b6a999700ddc">

2024-05-08 11:21 UTC, 20HyeonsuLee approved these changes
지나가다 리뷰남겨봐요.. ㅎㅎ

2024-05-08 11:21 UTC, 20HyeonsuLee commented on src/main/java/in/koreatech/koin/admin/user/service/AdminUserService.java
> +    public void checkNicknameDuplication(String nickname, Integer userId) {
# R
여기서만 쓰는거면 private이 좋아보여요

2024-05-08 11:21 UTC, 20HyeonsuLee commented on src/main/java/in/koreatech/koin/admin/user/service/AdminUserService.java
> +    public void checkDepartmentValid(String department) {
# R
여기서만 쓰는거면 private이 좋아보여요

2024-05-08 11:21 UTC, 20HyeonsuLee commented on src/main/java/in/koreatech/koin/admin/user/service/AdminUserService.java
> +        }
# C
요론식으로 jpa메소드로 사용 가능한 닉네임인지 확인해보는건 어떨까요?
또 void함수로 작성하기보단 boolean으로 중복여부를 반환하는건 어떨까요?
```suggestion
        if (nickname != null &&
            && adminUserRepository.existsByNicknameAndIdNot(nickname, userId)
        ) {
            throw DuplicationNicknameException.withDetail("nickname : " + nickname);
        }
```

2024-05-08 13:41 UTC, duehee approved these changes
고생하셨습니다~!

2024-05-08 13:41 UTC, duehee commented on src/main/java/in/koreatech/koin/admin/user/service/AdminUserService.java
> +        }
제가 작성한 메소드인데, JPA 메소드를 이용하는 방법도 있었군요👀
한 번 참고해봐야겠습니다

2024-05-08 13:46 UTC, kwoo28 commented on src/main/java/in/koreatech/koin/admin/user/service/AdminUserService.java
> +        }
저도 JPA메소드 이용하는 방법 첨알았네요. 좋은 지식 배워갑니다..

2024-05-09 00:13 UTC, Choi-JJunho commented on src/main/java/in/koreatech/koin/admin/user/controller/AdminUserController.java
> +    }
어드민가 일반 유저가 받는 Request, Response에 대한 요구사항이 항상 같을까? 를 고민해보면 좋을 것 같아요
저는 API별로 독립적인 요구사항을 가진다고 생각하여 dto를 재활용하는것은 가급적 지양하려는 편이에요

2024-05-09 01:13 UTC, johnny19991006 commented on src/main/java/in/koreatech/koin/admin/user/controller/AdminUserController.java
> +    }
dto는 분리해주세요~

2024-05-09 01:19 UTC, johnny19991006 commented on src/main/java/in/koreatech/koin/admin/user/controller/AdminUserController.java
> +        @Auth(permit = {ADMIN}) Integer adminId
STUDENT -> ADMIN 으로 바꾸면 기존 ADMIN이 동작을 못합니다.!! 유의해주세요

2024-05-09 01:26 UTC, seongjae6751 commented on src/main/java/in/koreatech/koin/admin/user/service/AdminUserService.java
> +    private final AdminUserRepository adminUserRepository;
위와 같은 이유로 별도로 만들었습니다..! 
단일 책임의 원칙은 어디까지가 단일 책임의 원칙인가..? 가 고민이 되는 것 같아요

2024-05-09 06:13 UTC, seongjae6751 commented on src/main/java/in/koreatech/koin/admin/user/service/AdminUserService.java
> +        }
와서 귀한 리뷰 남겨주셔서 감사합니다
앞으로도 와서 종종 남겨주세용ㅎㅎ

우선 말씀해주신대로 repository에서 named 쿼리를 사용해서 더 로직을 간단하게 변경했어요!

그런데 그 뒤에 말슴하씬 check 메서드들의 반환값이 boolean이면 좋겠다는 말씀에는 저는 현재처럼 void를 반환하는 것이 낫다고 생각합니다

메서드에서 boolean 값을 반환하도록 하면, 추가적인 조건 분기가 필요합니다. 만약 if와 저 check 메서드들로 로직을 감싸면 else문을 넣었을때 어떤 예외을 발생 혹은 반환시켜야 할까요? else문을 쓰지 않고 if문 다음에 바로 return 값으로 반환한다고 하면 굳이 boolean으로 반환해서 if문으로 감싸는 것에 크게 의미가 있을까요?

그래서 저는 void가 맞다고 생각하는데 제가 잘못 이해하고 있는 것이 있거나 추가적인 생각 있으시다면 말씀해주시면 감사하겠습니다!

2024-05-09 06:13 UTC, seongjae6751 commented on src/main/java/in/koreatech/koin/admin/user/service/AdminUserService.java
> +        adminStudentRepository.save(student);
지금 user entity에는 updateStudentPassword,
student entity에는 update문으로 모듈화가 되어 있다고 저는 생각을 했는데
혹시 어떤 부분을 말씀하시는 것인지 알 수 있을까요?

2024-05-09 06:32 UTC, 20HyeonsuLee commented on src/main/java/in/koreatech/koin/admin/user/service/AdminUserService.java
> +        }
저의 의견은 "함수에서는 boolean만 반환하고, 예외처리는 함수의 밖에서 해주는게 어떤가?"라는 의견이였습니다.
물론 모듈화라는것 자체가 추상화의 목적도 있겠지만 check~~~라는 void함수가 어떻게 처리되는지 알기 힘들다는 것 입니다.
(check라는 것에서 무엇을 체크해서 어떻게 처리하는지 알 수 없음.)
그래서 저는 보통 void함수는 최소한 줄이는편이긴 합니다.(반환값을 통해서 어떤 동작을 하는지 명확히 알 수 있기 때문)

2024-05-09 06:34 UTC, 20HyeonsuLee commented on src/main/java/in/koreatech/koin/admin/user/service/AdminUserService.java
> +        adminStudentRepository.save(student);
앗 그러네요 꼼꼼하게 못봤습니다 🙏

2024-05-09 06:35 UTC, Choi-JJunho commented on src/main/java/in/koreatech/koin/admin/user/service/AdminUserService.java
> +        }
함수 내부에서 검증하고 올바르면 pass, 그렇지 않다면 exception이 발생하는거죠?
그러면 check~ 보다는 validate~ 라는 네이밍은 어떨까요~

2024-05-09 06:35 UTC, 20HyeonsuLee commented on src/main/java/in/koreatech/koin/admin/user/service/AdminUserService.java
> +        }
물론 void함수로 처리해도 상관없을것같긴해요!

2024-05-09 06:47 UTC, seongjae6751 commented on src/main/java/in/koreatech/koin/admin/user/service/AdminUserService.java
> +        }
아 boolean으로 반환하고 예외를 밖에서 던지면 좋겠다는 말씀이셨군요..!
updateStudent 메서드 안에서 예외를 던지면 깔끔하지 않을 수 있겠다 라는 생각만 가지고 접근을 했었는데 그런 관점으로 볼 수도 있겠네요..! 
생각하지 못했던 부분을 짚어주셔서 감사합니다 ㅎㅎ

현수님 말씀도 일리가 있으나 저는 기존 방식이 보기에 더 깔끔한 것 같아서 저는 준호님 말씀대로 메서드 명을 validate로 변경하는 방식으로 접근하겠습니다! 

리뷰 달아줘서 고마워요! 🙇‍♂️

2024-05-09 07:08 UTC, 20HyeonsuLee approved these changes

2024-05-09 07:42 UTC, merged