fix : notification FK 회원 삭제 오류 수정
BCSDLab/KOIN_API_V2 pull request #514
Opened 2024-05-09 15:13 UTC by duehee

# 🔥 연관 이슈

- close #513 

# 🚀 작업 내용

1. notification / notification_subscribe에 대해 FK 오류 수정을 위해 DELETE CASCADE flyway sql문을 추가했습니다.

# 💬 리뷰 중점사항
FK에 관해서 CASCADE 처리를 현재 notification과 notification_subscribe에 적용시켰는데, 다른 부분에도 이를 적용해도 되는지, 그리고 추가적으로 CASCADE 처리를 다른 FK 값에 대해서 진행하는 것이 안전한가? 에 대해서 의논이 필요할 것 같습니다.(선권씨 입장)
확인하신다면 의견 부탁드립니당.

2024-05-09 15:26 UTC, kwoo28 approved these changes
현재 notificaton과 notification_subscribe의 데이터들은 유저가 삭제된다면 의미없는 데이터들이 되기때문에 cascade 사용하는 것은 옳다고 생각합니다.

하지만 예를들어 user_id를 참조하는 게시글이 사용자가 삭제돼도 남겨야할 가능성이 있는 데이터들과 같은 경우에 대해서는 cascade를 사용하는 것은 상황에 따라 적용해야할것같습니다.

2024-05-09 15:26 UTC, kwoo28 commented on src/main/resources/db/migration/V15__delete_notification_subscribe.sql
> +            ON UPDATE RESTRICT;
## A

혹시 이 부분은 왜쓴건지 알 수 있을까요..?

2024-05-09 15:26 UTC, kwoo28 commented on src/main/resources/db/migration/V15__delete_notification_subscribe.sql
> +            ON UPDATE RESTRICT;
on update restrict 부분만

2024-05-10 00:01 UTC, duehee commented on src/main/resources/db/migration/V15__delete_notification_subscribe.sql
> +            ON UPDATE RESTRICT;
MySQLworkbench에서 DELETE CASCADE 설정 시 나오는 코드를 가져와서 사용했는데, ON UPDATE 부분은 RESTRICT로 유지하는 부분에서 들어간 코드 같습니다

2024-05-10 01:42 UTC, Choi-JJunho commented on src/main/resources/db/migration/V15__delete_notification_subscribe.sql
> +            ON UPDATE RESTRICT;
저게 어떤 역할을 하는친구인지 궁금한데요

2024-05-10 01:51 UTC, duehee commented on src/main/resources/db/migration/V15__delete_notification_subscribe.sql
> +            ON UPDATE RESTRICT;
FK 내의 On Update가 RESTRICT로 설정된 경우에는 참조 테이블의 기본 키 값이 변경되려고 하는 경우에, 기본 키 값이 변경되는 경우에 이를 제한하는 역할을 합니다 (현재 notification과 notification_subscribe의 On Update 기본 설정 값이 RESTRICT)
현재 FK로 참고하는 user_id가 삭제되려고 할 때 RESTRICT로 설정되어 유저의 키 값이 삭제되려고 할 때 거부당하여 이를 CASCADE로 설정하여 이를 참고하는 테이블의 행을 삭제하도록 하여 문제를 해결했습니다.

2024-05-10 01:52 UTC, Choi-JJunho commented on src/main/resources/db/migration/V15__delete_notification_subscribe.sql
> +            ON UPDATE RESTRICT;
참조 무결성 제약에 대한 옵션이군요

1) On Delete
Cascade : 부모 데이터 삭제 시 자식 데이터도 삭제
Set null : 부모 데이터 삭제 시 자식 테이블의 참조 컬럼을 Null로 업데이트
Set default : 부모 데이터 삭제 시 자식 테이블의 참조 컬럼을 Default 값으로 업데이트 
Restrict : 자식 테이블이 참조하고 있을 경우, 데이터 삭제 불가 
No Action : Restrict와 동일, 옵션을 지정하지 않았을 경우 자동으로 선택된다.

2) On Update
Cascade : 부모 데이터 업데이트 시 자식 데이터도 업데이트
Set null : 부모 데이터 업데이트 시 자식 테이블의 참조 컬럼을 Null로 업데이트
Set default : 부모 데이터 업데이트 시 자식 테이블의 참조 컬럼을 Default 값으로 업데이트 
Restrict : 자식 테이블이 참조하고 있을 경우, 업데이트 불가 
No Action : Restrict와 동일, 옵션을 지정하지 않았을 경우 자동으로 선택된다.

이런 옵션들이 있다고 하네요
개념적으로 확인해보시면 좋을거같네요

참고: https://swingswing.tistory.com/5

2024-05-10 01:55 UTC, duehee commented on src/main/resources/db/migration/V15__delete_notification_subscribe.sql
> +            ON UPDATE RESTRICT;
어제는 간단하게 Cascade와 Restrict 정도만 확인해보았는데, 더 많은 옵션들이 있었네요!
오늘도 더 배워갑니다😄

2024-05-10 01:55 UTC, seongjae6751 approved these changes
고생 하셨습니다!

2024-05-10 01:59 UTC, Choi-JJunho requested changes

2024-05-10 01:59 UTC, Choi-JJunho commented on src/main/resources/db/migration/V15__delete_notification_subscribe.sql
> +ALTER TABLE `koin`.`notification_subscribe`
### C

DB 생략해주는거 어떤가요
Test 상에서 연결하는 데이터소스가 test db인 경우가 있어서 이 경우 flyway 오류가 나기도 하더라구요

```suggestion
ALTER TABLE `notification_subscribe`
DROP FOREIGN KEY `FK_NOTIFICATION_SUBSCRIBE_ON_USER`;
ALTER TABLE `notification_subscribe`
```

2024-05-10 02:02 UTC, duehee commented on src/main/resources/db/migration/V15__delete_notification_subscribe.sql
> +ALTER TABLE `koin`.`notification_subscribe`
반영하겠습니당

2024-05-10 02:12 UTC, Choi-JJunho approved these changes

2024-05-10 02:16 UTC, merged