feat: 사장님 비밀번호 변경 휴대폰 인증api 추가
BCSDLab/KOIN_API_V2 pull request #524
Opened 2024-05-12 06:21 UTC by 20HyeonsuLee

# 🔥 연관 이슈

- close #498 

# 🚀 작업 내용

1. 사장님 비밀번호 변경 휴대폰 인증 api를 추가했습니다.
2. 휴대폰인증 dto를 `01000000000`형식에서 `010-0000-0000`형식으로 통일하였습니다.
3. 기존 1분에 한번에서 하루 5회로 변경하였습니다.
    - 하루 최대 5번으로 바뀐것 + 문자인증 비용을 고려해서 테스트환경에서는 fast api를 이용하여 slack으로 인증번호를 받을 수 있도록 하였습니다.
    - fast api는 서버에 직접 올릴 예정이며 localhost:9999포트를 사용할 예정입니다.

# 💬 리뷰 중점사항
이메일인증 + 휴대폰인증 2개씩 api를 만들다 보니 헷갈리는 부분이 있었습니다. 꼼꼼하게 리뷰해주시면 감사하겠습니다!

2024-05-12 09:22 UTC, Choi-JJunho requested changes
굿굿 변수, 클래스명이 명시적으로 개선되면서 가독성이 훨씬 좋아졌네요~!
중간에 값 증가에 대한 ++ 연산자에서 최근 일어났던 동시성이슈가 생각났네요 😅
이 부분에서라도 한번 고려해보고 감을 잡아보는건 어떨까요?

2024-05-12 09:22 UTC, Choi-JJunho commented on src/main/java/in/koreatech/koin/domain/owner/controller/OwnerApi.java
> +    @PostMapping("/owners/verification/code/phone")
### A

갑자기 보면서 드는 생각인데 SMS? Phone? 뭐가 맞으려나..

2024-05-12 09:22 UTC, Choi-JJunho commented on src/main/java/in/koreatech/koin/domain/owner/controller/OwnerController.java
> +        ownerService.sendResetPasswordByEmail(request);
### A
메소드명 구분이 좋네요 👍

2024-05-12 09:22 UTC, Choi-JJunho commented on src/main/java/in/koreatech/koin/domain/owner/controller/OwnerController.java
> +        @Valid @RequestBody OwnerPasswordResetVerifyPhoneRequest request
### A
dto 분리 굿

2024-05-12 09:22 UTC, Choi-JJunho commented on src/main/java/in/koreatech/koin/domain/owner/dto/OwnerEmailVerifyRequest.java
> +    @Digits(integer = 6, fraction = 0, message = "인증 코드는 6자리 정수여야 합니다. ${validatedValue}")
### A
꼼꼼하네요

2024-05-12 09:22 UTC, Choi-JJunho commented on src/main/java/in/koreatech/koin/domain/owner/exception/DuplicationPhoneException.java
> +public class DuplicationPhoneException extends DuplicationException {
### C
`DuplicationPhoneNumberException` 어떤가요

2024-05-12 09:22 UTC, Choi-JJunho commented on src/main/java/in/koreatech/koin/domain/owner/exception/RequestVerificationLimitException.java
> +public class RequestVerificationLimitException extends KoinException {
### A
VerificationLimitExceededException는 어때요

2024-05-12 09:22 UTC, Choi-JJunho commented on src/main/java/in/koreatech/koin/domain/owner/model/redis/DailyVerificationLimit.java
> +        ++requestCount;
### R
흠흠.. brace.. 
```suggestion
        if (requestCount >= 5) {
            throw RequestVerificationLimitException.withDetail("limit: 5");
        }
        ++requestCount;
```

2024-05-12 09:22 UTC, Choi-JJunho commented on src/main/java/in/koreatech/koin/domain/owner/model/redis/OwnerVerificationStatus.java
> +public class OwnerVerificationStatus {
### A
더 직관적이고 좋네요  👍

2024-05-12 09:22 UTC, Choi-JJunho commented on src/main/java/in/koreatech/koin/domain/owner/model/redis/DailyVerificationLimit.java
> +        ++requestCount;
### C
이거 동시성 고려해서 AtomicInteger로 선언하는건 어때요?
```suggestion
        requestCount.incrementAndGet();
```

2024-05-13 02:53 UTC, 20HyeonsuLee commented on src/main/java/in/koreatech/koin/domain/owner/model/redis/DailyVerificationLimit.java
> +        ++requestCount;
AtomicInteger가 spring의 api동작에서도 원자성을 보장할 수 있는지는 잘 모르겠습니다(뭔가 안될거같음) redis단에서 트랜잭션 제어를 해주는 방향이 좋을 것 같은데 어떻게생각하시나요?

2024-05-13 03:06 UTC, 20HyeonsuLee commented on src/main/java/in/koreatech/koin/domain/owner/exception/RequestVerificationLimitException.java
> +public class RequestVerificationLimitException extends KoinException {
말씀해주신 내용 참고해서 VerificationDailyLimitExceededException로 변경하였습니다!

2024-05-13 03:06 UTC, 20HyeonsuLee commented on src/main/java/in/koreatech/koin/domain/owner/exception/DuplicationPhoneException.java
> +public class DuplicationPhoneException extends DuplicationException {
반영했습니다!

2024-05-13 03:06 UTC, 20HyeonsuLee commented on src/main/java/in/koreatech/koin/domain/owner/controller/OwnerApi.java
> +    @PostMapping("/owners/verification/code/phone")
Sms가 조금 더 적합해보여서 변경했습니다!

2024-05-13 03:35 UTC, Choi-JJunho commented on src/main/java/in/koreatech/koin/domain/owner/model/redis/DailyVerificationLimit.java
> +        ++requestCount;
뒤적이다보니 RedisAtomicInteger라는 친구도 있네요 👀
탐구가 필요한 부분인것같아요
https://docs.spring.io/spring-data/redis/docs/2.1.x/api/index.html?org/springframework/data/redis/support/atomic/RedisAtomicInteger.html

2024-05-13 05:17 UTC, Choi-JJunho commented on src/main/java/in/koreatech/koin/domain/owner/dto/OwnerPasswordUpdateSmsRequest.java
> +    @NotNull(message = "비밀번호는 비워둘 수 없습니다.")
### A
얘는 NotBlank가 아닌 이유가..?

2024-05-13 05:27 UTC, Choi-JJunho commented on src/main/java/in/koreatech/koin/domain/owner/service/OwnerService.java
> +    }
### A

저는 개인적으로 private 메소드는 가장 아래쪽에 위치하곤 하는데 어떻게생각하시나요?

참고자료: [클린코드 - 형식맞추기](https://velog.io/@junho5336/%ED%81%B4%EB%A6%B0%EC%BD%94%EB%93%9C-%ED%98%95%EC%8B%9D%EB%A7%9E%EC%B6%94%EA%B8%B0#%EC%88%98%EC%A7%81%EA%B1%B0%EB%A6%AC)

2024-05-13 05:27 UTC, Choi-JJunho approved these changes
굿굿~!
고생하셨습니다
아주 깔끔해졌네요

2024-05-13 06:37 UTC, 20HyeonsuLee commented on src/main/java/in/koreatech/koin/domain/owner/dto/OwnerPasswordUpdateSmsRequest.java
> +    @NotNull(message = "비밀번호는 비워둘 수 없습니다.")
매의눈 ㄷㄷ

2024-05-13 06:38 UTC, 20HyeonsuLee commented on src/main/java/in/koreatech/koin/domain/owner/service/OwnerService.java
> +    }
오호 좋습니다 수정했습니당

2024-05-13 11:20 UTC, merged