feature: 어드민 계정으로 특정 학생 조회
BCSDLab/KOIN_API_V2 pull request #528
Opened 2024-05-12 15:17 UTC by seongjae6751

# 🔥 연관 이슈

- close #91

# 🚀 작업 내용

1. 어드민 계정으로 특정 학생 조회 api를 구현 했습니다.
2. 전에 구현된 어드민 api들도 @auth를 붙여서 권한 필터링 되게 해줬습니다.

# 💬 리뷰 중점사항

2024-05-13 12:04 UTC, kwoo28 requested changes
수고 많으셨습니다!

2024-05-13 12:04 UTC, kwoo28 commented on src/main/java/in/koreatech/koin/admin/user/dto/AdminStudentResponse.java
> +            user.getGender().ordinal(),
## R

user의 gender가 null값이라면 NPE 발생하지 않을까요?

2024-05-13 15:08 UTC, seongjae6751 commented on src/main/java/in/koreatech/koin/admin/user/dto/AdminStudentResponse.java
> +            user.getGender().ordinal(),
꼼꼼하게 봐주셔서 감사합니당 수정했어요!

2024-05-13 16:35 UTC, kwoo28 approved these changes

2024-05-14 02:41 UTC, Choi-JJunho requested changes
코멘트 확인 부탁드려요~

2024-05-14 02:41 UTC, Choi-JJunho commented on src/main/java/in/koreatech/koin/admin/user/controller/AdminUserApi.java
> +
### A
공백이 두개~!

2024-05-14 02:41 UTC, Choi-JJunho commented on src/main/java/in/koreatech/koin/admin/user/dto/AdminStudentResponse.java
> +    Integer gender,
### R
아래에서 보면 nullable한거같은데 `requiredMode = REQUIRED`가 맞나요?

2024-05-14 02:41 UTC, Choi-JJunho commented on src/main/java/in/koreatech/koin/admin/user/dto/AdminStudentResponse.java
> +            userGender,
### C
굳이 변수로 뺄만큼 중요한 로직인가 싶긴하네요
```suggestion
            user.getGender() == null ? null : user.getGender().ordinal(),
```

2024-05-14 02:41 UTC, Choi-JJunho commented on src/main/java/in/koreatech/koin/admin/user/dto/AdminStudentUpdateResponse.java
> +    @Schema(description = "성별(남:0, 여:1)", example = "1", requiredMode = REQUIRED)
### R
이 값들도 다 nullable 한 값들일텐데 REQUIRED로 바뀐 이유가 있나요?
모든 값이 null이 아닌가요?

2024-05-15 05:00 UTC, Choi-JJunho approved these changes

2024-05-15 05:00 UTC, merged