feat: 특정 사장님 조회(어드민 계정)
BCSDLab/KOIN_API_V2 pull request #533
Opened 2024-05-13 11:58 UTC by kwoo28

# 🔥 연관 이슈

- close #88

# 🚀 작업 내용

1. /admin/users/owner/{id} API 작성

# 💬 리뷰 중점사항
기존 코인에서는 mysql에 shopId가 있다면 가져오고, 없다면 redis의 OwnerShop에서 shopId가져오는 방식으로 되어있습니다.(왜 mysql먼저 접근하게 설계한건지 모르겠음...)

하지만 현재 코마 로직상 OwnerShop은 생존시간이 2시간뿐이며, mysql에 shopId가 없다면 redis도 없다고 판단하여 mysql의 접근을 통해서만 shopId를 가져오도록 했습니다.

이 부분에 대해 중점적으로 봐주셨으면 좋겠습니다.

2024-05-13 14:46 UTC, seongjae6751 requested changes
고생하셨습니다!
고민하시는 사항은 저도 잘 모르는 것이라 owner 관련 이해관계자한테 검토 받는 것이 좀 더 좋지 않을까 싶네요..ㅎㅎ

2024-05-13 14:46 UTC, seongjae6751 commented on src/main/java/in/koreatech/koin/admin/user/repository/AdminShopRepository.java
> +    List<Shop> findAll();
A
지금 adminshopRepository는 findfindAllByOwnerId말고는 안 쓰이는 것 같은데
나중에 쓸 것 같은 것들을 다 추가 해 놓으신 걸까요?
명시적으로 선언한 메소드만 사용하겠다는 의미로 JpaReposiroty가 아닌 Repository를 사용하는 것으로 알고 있는데 필요한 것만 선언해서 사용하는 것이 좋지 않을까 하는 생각이 듭니당..

2024-05-13 14:57 UTC, kwoo28 commented on src/main/java/in/koreatech/koin/admin/user/repository/AdminShopRepository.java
> +    List<Shop> findAll();
기존 nomal repository 복붙했는데 필요한 것만 선언해두겠습니다!

2024-05-13 16:38 UTC, kwoo28 commented on src/main/java/in/koreatech/koin/admin/user/repository/AdminShopRepository.java
> +    List<Shop> findAll();
수정했습니다!

2024-05-14 01:09 UTC, seongjae6751 approved these changes

2024-05-14 07:54 UTC, seongjae6751 commented on src/main/java/in/koreatech/koin/admin/user/dto/AdminOwnerResponse.java
> +            userGender,
C
제가 받은 피드백 다시 말씀드리러 왔습니다..ㅎㅎ

2024-05-14 08:00 UTC, seongjae6751 requested changes

2024-05-14 13:27 UTC, kwoo28 commented on src/main/java/in/koreatech/koin/admin/user/dto/AdminOwnerResponse.java
> +    @Schema(description = "닉네임", example = "bbo", requiredMode = REQUIRED)
넵 수정했습니다!

2024-05-14 13:27 UTC, kwoo28 commented on src/main/java/in/koreatech/koin/admin/user/dto/AdminOwnerResponse.java
> +            userGender,
수정했습니다! 감사합니다

2024-05-15 07:11 UTC, seongjae6751 approved these changes
고생하셨습니다 merge conflict 났네요ㅠ 마지막으로 충돌만 해결해주세요

2024-05-15 14:48 UTC, duehee approved these changes
수고 많으셨습니다!
정신이 없어서 너무 늦게 리뷰 확인했네요😢
앞 성재님께서 잘 캐치해주신 부분이 많네요 :D

2024-05-15 14:54 UTC, merged