feat: 커스텀 시간표 API
BCSDLab/KOIN_API_V2 pull request #543
Opened 2024-05-15 08:25 UTC by kwoo28

# 🔥 연관 이슈

- close #542

# 🚀 작업 내용

기존 강의 시간표 생성하는 API를 이용하였습니다.
커스텀 시간표 추가할때 (학기, 이름, 시간)에 대한 요청값만 필요하기 때문에 기존 시간표 생성API를 커스텀 시간표를 고려하여 변경했습니다.

1. DTO 스키마 이름 변경
`@Schema(description = "강의(커스텀) 이름", example = "운영체제", requiredMode = REQUIRED)`
`@Schema(description = "강의(커스텀) 시간", example = "[210, 211]", requiredMode = REQUIRED)`

2. requiredMode 변경
커스텀 시간표를 고려하여 기존에 필수값이였던 학년하고 분반에 대한 요청과 응답 requiredMode를 REQUIRED에서 NOT_REQUIRED로 변경했습니다.

# 💬 리뷰 중점사항

2024-05-15 09:23 UTC, daheeParkk requested changes
수고하셨습니다!

2024-05-15 09:23 UTC, daheeParkk commented on src/main/java/in/koreatech/koin/domain/timetable/dto/TimeTableCreateRequest.java
>          String grades,
timetables 테이블에는 grades가 필수로 되어 있어서 db도 바꿔야 할 것 같아요

 +스웨거에는 왜 grades가 필수로 표시되어 있을까요

![image](https://github.com/BCSDLab/KOIN_API_V2/assets/106418303/89269a9a-9202-4855-8ef4-25670604ef38)

2024-05-15 10:23 UTC, kwoo28 commented on src/main/java/in/koreatech/koin/domain/timetable/dto/TimeTableCreateRequest.java
>          String grades,
다시보니 grade가 학년이 아니라 학점이였네요. 시간표 조회할때 총학점도 계산해서 넘겨주는데 null값을 허용하면 db와 로직을 변경해야돼서 grade 요청 기본값을 0으로 설정했습니다.

2024-05-16 07:02 UTC, seongjae6751 approved these changes
고생하셨습니다

2024-05-16 12:25 UTC, duehee approved these changes
고생하셨습니다~!

2024-05-16 12:25 UTC, duehee commented on src/main/java/in/koreatech/koin/domain/timetable/dto/TimeTableCreateRequest.java
> +        @Schema(description = "학점", example = "3", requiredMode = NOT_REQUIRED)
### A
앗.. 이런 중요한 걸 모르고 있었다니😵

2024-05-17 05:15 UTC, daheeParkk approved these changes
수고하셨습니다!

2024-05-17 05:20 UTC, merged