refactor: GET /shops api 성능최적화
BCSDLab/KOIN_API_V2 pull request #549
Opened 2024-05-16 14:10 UTC by 20HyeonsuLee

# 🔥 연관 이슈

- close #546 

# 🚀 작업 내용

1. GET /shops api응답속도 최적화를 위해 캐싱을 진행하였습니다.
- Spring의 `@Scheduled`를 이용해서 30초마다 redis의 /shops api의 응답캐시를 refresh해줬습니다.
     - 30초마다 캐시를 새로고치는 이유
          - is_open이 분단위로 현재시간을 기준으로 판단하기 때문에 1분마다 redis를 동기화 해줘야 한다.
          - 하지만 1분마다 하게 되면 실제 시간이 6시인데 사용자는 5:59분의 데이터를 받을 수도 있다. 때문에 30초단위로 redis동기화를 진행하였습니다.

# 💬 리뷰 중점사항
앤티티그래프를 이용해서 이른로딩을 하려고 했는데 여러개를 이른로딩할수 없다고 하네요..

2024-05-17 05:35 UTC, Choi-JJunho requested changes
코멘트 몇개만 확인해주세요~

2024-05-17 05:35 UTC, Choi-JJunho commented on src/main/java/in/koreatech/koin/domain/shop/repository/redis/ShopsRedisRepository.java
> +    @Autowired
### C

Autowired 선언해준 이유가 있을까요

2024-05-17 05:35 UTC, Choi-JJunho commented on src/main/java/in/koreatech/koin/domain/shop/repository/redis/ShopsRedisRepository.java
> +    private final RedisTemplate<String, Object> redisTemplate;
### A

RedisTemplate을 사용한 이유가 있나요?

2024-05-17 05:35 UTC, Choi-JJunho commented on src/main/java/in/koreatech/koin/domain/shop/service/ShopService.java
> +
### C

불필요한 공백 👀

2024-05-17 05:35 UTC, Choi-JJunho commented on src/main/java/in/koreatech/koin/global/config/AppConfig.java
> +}
### R

AppConfig 라는 클래스명을 지은 이유가있을까요?
ObjectMapper에 JavaTimeModule을 추가하겨 Bean으로 등록해준 이유도 궁금합니다.

2024-05-17 05:35 UTC, Choi-JJunho commented on src/main/java/in/koreatech/koin/global/config/RedisConfig.java
> +        template.setKeySerializer(new StringRedisSerializer());
### A
각각의 설정이 어떤 이유로 선언되었는지 궁금해요~

2024-05-18 10:42 UTC, 20HyeonsuLee commented on src/main/java/in/koreatech/koin/domain/shop/repository/redis/ShopsRedisRepository.java
> +    @Autowired
작성하다보니 코드가 꼬인것같아요 수정했습니다!

2024-05-18 10:43 UTC, 20HyeonsuLee commented on src/main/java/in/koreatech/koin/domain/shop/repository/redis/ShopsRedisRepository.java
> +    private final RedisTemplate<String, Object> redisTemplate;
redis에 객체를 저장하기 위해서는 여러가지 설정들이 필요해서 사용했습니다

2024-05-18 10:45 UTC, 20HyeonsuLee commented on src/main/java/in/koreatech/koin/global/config/AppConfig.java
> +}
이름이 좀 부적절하긴하네요! MapperConfig로 바꿔줬습니다!
이게 필요한 이유는 redis에 객체를 넣을 때 적절히 필드들을 문자열로 바꿔줘야하는데 그 과정에서 LocalTime을 변환 할 때 사용되기 때문입니다

2024-05-18 10:56 UTC, 20HyeonsuLee commented on src/main/java/in/koreatech/koin/global/config/AppConfig.java
> +}
다시보니 중복된 설정이였네요.. ㅎ 제거했습니다!

2024-05-18 15:03 UTC, johnny19991006 reviewed
고생하셨습니다~ 성능에 대한 고민으로 Redis를 사용하신게 인상이 깊습니다!!! 
코멘트 한번만 확인해주세요

2024-05-18 15:03 UTC, johnny19991006 commented on src/main/java/in/koreatech/koin/domain/shop/service/ShopService.java
> +            .sorted(Comparator.comparing(InnerShopResponse::isOpen, Collections.reverseOrder())).toList();
위에서는 Comparator를 사용하고, 아래서는 Collections를 사용한 이유가 궁금합니다.
아래서 Comparator.reversOrder를 활용하면 좀더 일관성 있게 코드를 작성할 수 있을거 같아요

2024-05-18 15:45 UTC, 20HyeonsuLee commented on src/main/java/in/koreatech/koin/domain/shop/service/ShopService.java
> +        return shopsRedisRepository.getShopsResponseByRedis();
좋습니당~

2024-05-18 15:48 UTC, 20HyeonsuLee commented on src/main/java/in/koreatech/koin/domain/shop/service/ShopService.java
> +            .sorted(Comparator.comparing(InnerShopResponse::isOpen, Collections.reverseOrder())).toList();
동의합니다

2024-05-19 07:25 UTC, johnny19991006 approved these changes

2024-05-20 02:04 UTC, Choi-JJunho approved these changes
고생하셨습니다

2024-05-20 02:04 UTC, Choi-JJunho commented on src/main/java/in/koreatech/koin/global/scheduler/CacheShopsScheduler.java
> +        shopService.refreshShopsCache();
### A
여담이지만 Scheduled와 Transactional을 함께 사용하면 안된다고하네요

> 참고자료: https://jo5ham.tistory.com/45
> 참고자료: https://stackoverflow.com/questions/45355601/why-scheduled-annotation-doesnt-work-with-transaction-annotation-spring-boot

2024-05-20 02:15 UTC, 20HyeonsuLee commented on src/main/java/in/koreatech/koin/domain/shop/service/ShopService.java
> +            refreshShopsCache();
redis에서는 @Transactional이 동작하지 않는다고 하더라구요(보통 관계형DB만 포함)
이전에 오너 회원가입 관련 동시성 이슈도 이것때문이라고 생각하고 있습니다.(트랜잭션 어노테이션을 붙였지만 동장하지 않았음)
때문에 따로 붙여주지 않았습니다. 만약 redis에도 트랜적션관리를 하고싶다면 별도의 설정이 필요하다고 하더라구요 이것 관련해서 공부해서 적용해보도록 하겠습니다!

2024-05-20 02:16 UTC, merged

2024-05-20 02:16 UTC, Choi-JJunho commented on src/main/java/in/koreatech/koin/domain/shop/service/ShopService.java
> +            refreshShopsCache();
오 하나 배워갑니다 👍