fix: 사장님 탈퇴 이슈 예외 처리
BCSDLab/KOIN_API_V2 pull request #559
Opened 2024-05-17 18:24 UTC by seongjae6751

# 🔥 연관 이슈

# 🚀 작업 내용
```
Exception: DataIntegrityViolationException
Location: HibernateJpaDialect.java Line 269
could not execute statement [Column 'owner_id' cannot be null] [update owner_attachments set owner_id=null where owner_id=? and ((is_deleted=0) )];
```
위와 같은 에러를 수정했습니다. 

* 동시성으로 이유를 파악했었는데 동시성이 문제가 아니였습니다.

해당 문제는 (orphanremoval = true)와 (cascade = remove)와 같은 자식 개체를 같이 삭제하게 해놓은 설정의 문제였습니다.
위와 같은 설정을 하게 되면 
부모 객체를 삭제할 때 해당 설정의 자식 엔티티는 자신이 참조하고 있던 부모 키(fk)를 null로 만들어서 고아 상태로 만드는 update 쿼리 문을 날립니다. 

위처럼 자식 객체도 같이 삭제되게 하는 설정을 하면 회원 탈퇴를 할 때 날라가는 쿼리문은 다음의 순서와 같습니다.

1. owner attachment의 owner_id(fk)를 null로 만드는 update 쿼리문 
2. owner attachment delete 쿼리문
3. owner delete 쿼리문
4. user delete 쿼리문

이때 외래키 설정이 NOT NULL로 되어있으면 부모 외래키를 null로 만들려고 하는 위 설정들과 충돌이 일어나게 됩니다.
따라서 fk값을 null로 만들 수 없게 many인 쪽에 (updatable = false)라는 설정을 추가 해줬습니다.
해당 설정을 적용하면 fk를 null로 만드는 1번을 실행하지 않고 2,3,4번을 수행하게 됩니다.

참고글: https://www.inflearn.com/questions/990032/onetomany%EC%97%90%EC%84%9C-joincolumn-nullable-false-updatable-false-%EC%97%90-%EB%8C%80%ED%95%98%EC%97%AC 

위와 같은 문제를 해결하기 위해 다음의 것들을 하였습니다.
1. owner attachment 테이블과 엔티티의 제약 조건을 맞추기 위해 nullable = false를 추가했습니다.
2. fk를 null로 만들지 않게 updatable = false를 추가했습니다
3. owner_attachment의 owner_id를 not null로 설정하면서 문제가 생긴 fixture들을 다 리팩토링 해줬습니다.
(owner와 attachment가 단방향 관계로 설계 되어있던 것을 양방향 관계로 다시 만들어줬습니다)

# 💬 리뷰 중점사항
삽질도 많이 했지만 삽질을 함으로 인해 jpa의 영속성과 동시성 처리에 대해 생각해볼 수 있는 좋은 기회를 가진 것 같습니다.

2024-05-17 18:39 UTC, kwoo28 requested changes
수고많으셨습니다!

2024-05-17 18:39 UTC, kwoo28 commented on src/main/java/in/koreatech/koin/domain/user/service/UserService.java
>          }
## R

동시성 이슈 문제라면 사장님말고도 학생도 동시성 이슈 문제에 포함되기때문에 try문에 학생 삭제하는 로직도 추가시켜야할것같습니다!

2024-05-18 06:03 UTC, seongjae6751 commented on src/main/java/in/koreatech/koin/domain/user/service/UserService.java
>          }
현재 학생 쪽은 탈퇴 시에 cascade나 orphan의 영향을 받는 곳이 없어서 우선 고려를 하지 않았습니다!

2024-05-18 13:07 UTC, kwoo28 commented on src/main/java/in/koreatech/koin/domain/user/service/UserService.java
>          }
음.. cascade나 orphan의 영향이 없어도 동시성 이슈가 발생할 수 있을것같아서 동시성 환경에서 테스트 해봐야할것같습니다.

2024-05-18 13:30 UTC, kwoo28 approved these changes

2024-05-19 15:23 UTC, duehee requested changes
수고하셨습니다~
코멘트 한 번만 확인 부탁드릴게요

2024-05-19 15:23 UTC, duehee commented on src/main/java/in/koreatech/koin/domain/user/service/UserService.java
>          }
### C
포맷팅 한 번 부탁드려요!!
```suggestion
            try {
                ownerRepository.deleteByUserId(userId);
            } catch (DataIntegrityViolationException e){
                throw OwnerNotFoundException.withDetail("owner userId: " + userId);
            }
        }
```

2024-05-26 03:47 UTC, duehee approved these changes
추가된 점으로 새로운 것 알고 가게 되네요👀
ㅎㅎㅎ.. 늦게 리뷰 남겨 죄송합니다

2024-05-26 16:14 UTC, merged