fix: 회원가입 동시성 이슈 처리
BCSDLab/KOIN_API_V2 pull request #562
Opened 2024-05-18 13:01 UTC by kwoo28

# 🔥 연관 이슈

- close #557

# 🚀 작업 내용

1. 해당 로직 과정에서 동시성 제어 방식에는 비관적인 방식이 있으나, 현재 리소스가 많은 곳에서 쓰이는 공유자원인 학생인만큼 전체적인 서비스 성능 저하가 유발될것이며, 단순 데이터 중복에 대한 에러를 반환하는것이기에 try-catch문으로 처리했습니다.

2. 동시성 환경에서 발생할 수 있는 로그를 검증하는 테스트를 작성했습니다.

# 💬 리뷰 중점사항

2024-05-19 10:15 UTC, seongjae6751 approved these changes
고생하셨습니다

2024-05-20 02:43 UTC, Choi-JJunho requested changes
동시성 테스트 작성하면서 ThreadPool을 생성해보셨군요 👍
몇가지 코멘트 남겼으니 확인 부탁드려요

2024-05-20 02:43 UTC, Choi-JJunho commented on src/test/java/in/koreatech/koin/acceptance/UserApiTest.java
> +    void concurrencyStudentRegister(CapturedOutput capturedOutput) throws InterruptedException{
### C
라인포맷팅 👀
```suggestion
    void concurrencyStudentRegister(CapturedOutput capturedOutput) throws InterruptedException {
```

2024-05-20 02:43 UTC, Choi-JJunho commented on src/test/java/in/koreatech/koin/acceptance/UserApiTest.java
> +    void concurrencyStudentRegister(CapturedOutput capturedOutput) throws InterruptedException{
### A
SpringBoot에서 CaturedOutput이란 친구를 제공하는군요
test에서 System 출력에대해 assert에 활용할 수 있도록 도와주는 친구라니
하나 배워갑니다 👍

참고자료: https://docs.spring.io/spring-boot/docs/current/api/org/springframework/boot/test/system/CapturedOutput.html

2024-05-20 02:43 UTC, Choi-JJunho commented on src/test/java/in/koreatech/koin/acceptance/UserApiTest.java
> +        ExecutorService executorService = Executors.newFixedThreadPool(threads);
### C

Thread 개수를 2개로 제한한 이유가 있나요?
10개 이상 해보는것도 괜찮아보이는데요

2024-05-20 02:43 UTC, Choi-JJunho commented on src/test/java/in/koreatech/koin/acceptance/UserApiTest.java
> +
### R
불필요한 공백 👀

2024-05-20 02:43 UTC, Choi-JJunho commented on src/main/java/in/koreatech/koin/domain/user/service/StudentService.java
> +            throw KoinIllegalArgumentException.withDetail("회원 가입 데이터 중복 동시성 발생");
### R

클라이언트에게 "회원 가입 데이터 중복 동시성 발생"이라는 메시지가 반환될텐데 서비스를 사용하면서 위와같은 문구를 보신적이 있나요?

동시성(Concurrency) 이라는 단어는 개발자들의 용어이지 클라이언트가 알 필요가 없는 문구라고 생각해요.
"요청이 너무 빠릅니다. 잠시후 다시 시도해주세요"
라고 메시지를 반환하되 개발자가 동시성 처리 코드임을 알 수 있도록 주석으로 표현해보는건 어떨까요?
차후에 try - catch 말고 다른 방법으로 개선해볼 수도 있을것 같아서요

```suggestion
            // 동시성 문제를 처리하기 위한 코드
            throw KoinIllegalArgumentException.withDetail("요청이 너무 빠릅니다.");
```

2024-05-20 07:02 UTC, kwoo28 commented on src/main/java/in/koreatech/koin/domain/user/service/StudentService.java
> +            throw KoinIllegalArgumentException.withDetail("회원 가입 데이터 중복 동시성 발생");
엇 그렇네요..! 제안해주신대로 수정했습니다!

2024-05-20 07:03 UTC, kwoo28 commented on src/test/java/in/koreatech/koin/acceptance/UserApiTest.java
> +                """)
수정했습니다!

2024-05-20 07:09 UTC, kwoo28 commented on src/test/java/in/koreatech/koin/acceptance/UserApiTest.java
> +        ExecutorService executorService = Executors.newFixedThreadPool(threads);
쓰레드를 2개로 해서 테스트를 여러번했는데 전부다 두 쓰레드에서 중복검사하는 쿼리조회부분이 동시에 발생했습니다.

그래서 괜히 여러개 생성해서 테스트시간 지연되는것보단 회원가입 동시성오류 체크하는데 필요한 최소한의 조건만 충족하면 충분하다고 생각해서 2개만 했습니다. 또한 try-catch문으로 동시성에러를 잡았기때문에 성능지연이 발생하지 않아서 굳이 여러개 생성할 필요가 없다생각했습니다.

혹시 10개 이상으로 하는게 좋을 이유가 있을까요?

2024-05-20 07:24 UTC, daheeParkk approved these changes
수고하셨습니다!

2024-05-20 07:24 UTC, daheeParkk commented on src/test/java/in/koreatech/koin/acceptance/UserApiTest.java
> +    void concurrencyStudentRegister(CapturedOutput capturedOutput) throws InterruptedException {
### A

동시성 발생에 대한 테스트를 이렇게 할 수 있군요 👍🏻

2024-05-20 07:36 UTC, duehee approved these changes
수고 많으셨습니다~
이번 동시성 문제를 해결하시면서 많이 고민하신 모습을 보았기에..😢
저도 열심히 공부해야겠습니당

2024-05-20 07:36 UTC, duehee commented on src/test/java/in/koreatech/koin/acceptance/UserApiTest.java
> +        ExecutorService executorService = Executors.newFixedThreadPool(threads);
### A
Threadpool을 이용하여 동시성 문제를 발생시킬 수 있군요👀

2024-05-26 03:25 UTC, Choi-JJunho approved these changes

2024-05-26 03:31 UTC, merged