feat : 학생, 사장님, 영양사 로그인 분기처리
BCSDLab/KOIN_API_V2 pull request #563
Opened 2024-05-18 14:38 UTC by duehee

# 🔥 연관 이슈

- close #537

# 🚀 작업 내용

1. UserType을 이용하여 로그인 API를 분기처리했습니다.
-> UserType에 맞추어 기존 사용하던 `/user/login`은 STUDENT,
     새롭게 추가한 `/user/coop/login`은 COOP, `/user/owner/login`은 OWNER로 나누어 처리했습니다.

# 💬 리뷰 중점사항
기존에 사용하던 Login API에 UserType을 추가하여 처리해보았습니다.
로그인을 진행할 때 UserType이 다르다면 403번 오류를 반환하도록 했습니다.
제가 접근한 방법으로 Login을 분기처리해도 되는지, 혹여나 다른 방법이 있다면 어떻게 하면 좋을지 의견 부탁드립니다 :D
추가적으로 트랙장님의 말씀대로, 모두가 인지가 필요한 내용이라고 해주셔서 백엔드분들 모두 태그했습니다. 감사합니다!

2024-05-18 16:30 UTC, 20HyeonsuLee requested changes
비지니스팀에서 진행중인 "상점 사장님 전화번호로 로그인"에 대해서 먼저 말씀드렸어야했는데 먼저 말씀드리지 못해 일을 두번 하게 만드는것같아서 죄송합니다... ㅠ 몇가지 코멘트 확인해주세요!

2024-05-18 16:30 UTC, 20HyeonsuLee commented on src/main/java/in/koreatech/koin/domain/user/service/UserService.java
>          User user = userRepository.getByEmail(request.email());
# C
아래와 같은 방식은 어떨까요?
```suggestion
        User user = userRepository.getByEmailAndUserType(request.email(), userType);
```

2024-05-18 16:30 UTC, 20HyeonsuLee commented on src/main/java/in/koreatech/koin/domain/user/service/UserService.java
> +            throw new AuthorizationException("잘못된 사용자 유형입니다. 확인해주세요.");
# R
사용자가 존재하면 존재하는거고 존재하지 않으면 존재하지 않은것이지
`잘못된 사용자 유형입니다. 확인해주세요.`라는 예외는 불필요해보여요

2024-05-18 16:30 UTC, 20HyeonsuLee commented on src/main/java/in/koreatech/koin/domain/user/service/UserService.java
> +    public UserLoginResponse login(UserLoginRequest request, UserType userType) {
# R
owner, coop, user모두 이 함수를 사용하고 있는데 3개의 로그인의 성격이 달라서 분리가 필요해보여요

2024-05-18 16:30 UTC, 20HyeonsuLee commented on src/main/java/in/koreatech/koin/domain/user/service/UserService.java
>              throw new AuthorizationException("미인증 상태입니다. 아우누리에서 인증메일을 확인해주세요");
# R
비밀번호가 틀린건데 아래의 예외는 적절치 못한것같아요
`throw new AuthorizationException("미인증 상태입니다. 아우누리에서 인증메일을 확인해주세요");`

2024-05-19 05:32 UTC, Invidam reviewed
프로젝트의 전범위에서 사용하는 핵심적인 수정사항이기 때문에 **백엔드끼리 논의**가 필요한 것보단 **클라이언트분들과 상의**가 필요해보이는데 (Web, iOS, Android 모두 반영해야 해서) 프로젝트 내에서 충분히 상의가 되었을까요??

+) 아직 상의가 안되었고 상의할 방법에 대해서 막막하다면 얘기해주세요 ㅋㅋㅋ

2024-05-19 05:58 UTC, 20HyeonsuLee commented on src/main/java/in/koreatech/koin/domain/user/service/UserService.java
>          User user = userRepository.getByEmail(request.email());
앗 맞네요 헷갈렸던 부분이 있었던것 같습니다!
추후에 owner로그인 시 휴대폰번호로 데이터를 찾아와야하는데 휴대폰번호가 유니크가 아니라서 휴대폰번호와 유저타입을 같이 검사해야할 경우가 생길것같습니다 그때 참고해주시면 감사할것같습니다!

2024-05-19 10:35 UTC, duehee commented on src/main/java/in/koreatech/koin/domain/user/controller/UserApi.java
> +    );
앗..! 회원가입 및 로그인까지 새로 기획 및 작업 중이실까요? 작성하시게 된다면 확인해보고 추가적으로 수정해보겠습니당 :D

2024-05-19 10:38 UTC, duehee commented on src/main/java/in/koreatech/koin/domain/user/service/UserService.java
>          User user = userRepository.getByEmail(request.email());
휴대폰 번호가 유니크가 아니어도 사장님이 유저타입을 다르게 하는 경우(학생 및 영양사)가 발생 할 수 있을까요?
혹여 이후 작성하게 된다면 일단 참고하여 작성하여 보겠습니다!

2024-05-19 10:43 UTC, duehee commented on src/main/java/in/koreatech/koin/domain/user/service/UserService.java
> +            throw new AuthorizationException("잘못된 사용자 유형입니다. 확인해주세요.");
해당 예외는 로그인 접근에 대해서 전자를 생각하고 작성한 것이 맞는데, 한 번 클라이언트님들과도 확인 해봐야 할 것 같아요!
감사합니당 :D

2024-05-19 10:47 UTC, duehee commented on src/main/java/in/koreatech/koin/domain/user/service/UserService.java
> +    public UserLoginResponse login(UserLoginRequest request, UserType userType) {
Owner은 비즈니스팀 측에서 작업이 끝나고 나서 한 번 확인을 해봐야 할 것 같습니당😅 
user(현재는 학생)측은 기존 사용, 영양사님은 현재 같은 이메일(coopexample1@koreatech.ac.kr)을 사용해서 그런지 기존 코인의 로그인이 가능해서 분리가 필요할 것 같아요.
UserType으로만 분리하여 접근하려고 했던 부분은 조금 생각이 짧았던 것 같네요😢

2024-05-19 11:04 UTC, duehee commented on src/main/java/in/koreatech/koin/domain/user/service/UserService.java
>              throw new AuthorizationException("미인증 상태입니다. 아우누리에서 인증메일을 확인해주세요");
위에 적어주신 예외는 인증을 진행하지 않은 경우에 발생하는 예외처리에요!

2024-05-19 11:29 UTC, duehee commented
클라이언트 측의 의견과 추가적으로 비즈니스 팀의 사장님 회원가입, 로그인 기능이 확인되면 추가적으로 작성하도록 하겠습니다!
의견 내주셔서 감사합니다! 슬랙에서 의견 다시 내도록 하겠습니다😄

2024-05-29 06:30 UTC, daheeParkk requested changes
수고하셨습니다!

2024-05-29 06:30 UTC, daheeParkk commented on src/main/java/in/koreatech/koin/domain/user/repository/UserRepository.java
> +    Optional<User> findByEmailAndUserType(String phoneNumber, UserType userType);
### R

`findByEmailAndUserType`인데 파라미터 값은 phoneNumber와 userType입니다!

2024-05-29 06:30 UTC, daheeParkk commented on src/main/java/in/koreatech/koin/domain/user/repository/UserRepository.java
> +    Optional<User> findByEmailAndUserType(String phoneNumber, UserType userType);
### C

유저타입과 이메일로 검색을 하고 있는데 영양사 계정은 아이디를 무조건 이메일로 하기로 한 건가요?

2024-05-29 06:34 UTC, duehee commented on src/main/java/in/koreatech/koin/domain/user/repository/UserRepository.java
> +    Optional<User> findByEmailAndUserType(String phoneNumber, UserType userType);
아이디를 저장할 곳이 email밖에 없어서, email에서 일반 아이디 형식으로 저장하여 사용하는 것을 생각하고 만들었습니다
아마 메소드 이름 때문에 혼동이 있을 거라고 생각이 들긴 했는데, 한 번 수정해봐야겠네요

2024-05-29 06:39 UTC, daheeParkk commented on src/main/java/in/koreatech/koin/domain/user/repository/UserRepository.java
> +    Optional<User> findByEmailAndUserType(String phoneNumber, UserType userType);
email에 아이디를 저장하는 거군요..!
그럼 이대로 하는 것도 괜찮아 보입니다

2024-05-30 05:31 UTC, kwoo28 approved these changes
다른팀과 논의하고 작업하느라 수고 많으셨습니다! 저는 고칠점이 딱히 보이진않는것같습니다..!

2024-05-30 05:31 UTC, kwoo28 commented on src/test/java/in/koreatech/koin/fixture/UserFixture.java
> +    public Owner 원경_사장님() {
ㅋㅋㅋ 왜 현수사장님 냅두고 원경사장님 추가한것인가요

2024-05-30 05:35 UTC, duehee commented on src/test/java/in/koreatech/koin/fixture/UserFixture.java
> +    public Owner 원경_사장님() {
다른 사장님들은 전화번호에 -가 다 있더라구요.. 새 사장님 추가~

2024-05-30 05:35 UTC, songsunkook commented on src/main/java/in/koreatech/koin/domain/user/repository/UserRepository.java
> +    Optional<User> findByEmailAndUserType(String phoneNumber, UserType userType);
email에 아이디를 저장하는 형태는 좋지 않아보이는데 컬럼명 수정이 필요해 보여요

2024-05-30 05:46 UTC, 20HyeonsuLee requested changes
빠르게 작업해주시느라 너무 고생하셨습니다~ 리뷰 남겼습니다!

2024-05-30 05:46 UTC, 20HyeonsuLee commented on src/main/java/in/koreatech/koin/domain/user/controller/UserApi.java
> +    @Operation(summary = "사장님 로그인")
# C
음.. 요고는 user쪽 말고 각각의 컨트롤러에서 (owner, student, coop) 처리해주는게 좋으려나요..? 의견이 궁금해요~

2024-05-30 05:46 UTC, 20HyeonsuLee commented on src/main/java/in/koreatech/koin/domain/user/controller/UserController.java
> +        return ResponseEntity.created(URI.create("/"))
# A
URI를 반환하고 있는데 이러한 방법을 선택하게된 이유가 궁금해요!

2024-05-30 05:46 UTC, 20HyeonsuLee commented on src/main/java/in/koreatech/koin/domain/user/dto/CoopLoginResponse.java
> +    String userType
# C
api를 분기한다면 user_type이 필요없어질것같은데 어떻게생각하시나오?

2024-05-30 05:46 UTC, 20HyeonsuLee commented on src/main/java/in/koreatech/koin/domain/user/dto/OwnerLoginRequest.java
> +    @Schema(description = "전화번호", example = "01024607469", requiredMode = REQUIRED)
# R
전화번호 가려야하지 않을까 싶어요!

2024-05-30 05:46 UTC, 20HyeonsuLee commented on src/main/java/in/koreatech/koin/domain/user/dto/StudentLoginRequest.java
> +    @Email(message = "이메일 형식을 지켜주세요. ${validatedValue}")
# R
아이디에는 이메일 형식을 검사할 필요는 없을것같아요!

2024-05-30 05:50 UTC, duehee commented on src/main/java/in/koreatech/koin/domain/user/controller/UserApi.java
> +    @Operation(summary = "사장님 로그인")
이 사항에 대해서는 조금 고민해보았는데, 생각해보면 사장님 회원가입도 owner에 따로 작성되어 있는 것 보면 나누어서 처리하는 게 맞는 거 같긴한데.. 현수님은 어떻게 생각하세요?

2024-05-30 05:52 UTC, duehee commented on src/main/java/in/koreatech/koin/domain/user/dto/CoopLoginResponse.java
> +    String userType
api를 나누게 된다면 필요 없을 것 같네요 ㅎㅎㅎ 감사합니다

2024-05-30 05:54 UTC, songsunkook commented on src/test/java/in/koreatech/koin/fixture/UserFixture.java
> +    public Owner 원경_사장님() {
잘 몰라서 그러는데 api별로 어떤 건 -가 있어야 하고 어떤 건 -가 없어야 하는 이슈가 생기는 건가요..? 만약 그렇다면 통일이 필요할 것 같습니다.

2024-05-30 06:12 UTC, duehee commented on src/main/java/in/koreatech/koin/domain/user/controller/UserController.java
> +        return ResponseEntity.created(URI.create("/"))
기존 유저 로그인 로직에 사용하던 방식을 그대로 가져와서 사용했는데, 로그인 로직에서 URI를 생성해서 201번 코드를 반환하는 게 옳은지 생각이 드네요. `ResponseEntity.ok(response)`를 사용하는 것이 좋을 거 같은데, 한 번 말 꺼내봐야겠어요!

2024-05-30 06:17 UTC, duehee commented on src/main/java/in/koreatech/koin/domain/user/dto/StudentLoginRequest.java
> +    @Email(message = "이메일 형식을 지켜주세요. ${validatedValue}")
앞으로는 필요 없을 거 같긴 하네요. 의견 감사합니당😄

2024-05-30 06:29 UTC, duehee commented on src/test/java/in/koreatech/koin/fixture/UserFixture.java
> +    public Owner 원경_사장님() {
현재는 -가 있고, 없고 뒤죽박죽인 상황인데, 앞으로는 사장님 회원가입 및 로그인 진행을 전화번호로 한다고 합니다!
이 과정에서 사장님 전화번호는 "-"가 없이 저장되도록 하고, 이를 이용해서 로그인을 진행한다고 해서 "-"를 제외한 방향으로 코드를 작성하였는데, 다른 api 작성 간에도 문제가 생길 수 있는 점을 미흡하게 생각한 거 같습니다.. 비즈니스팀과 한 번 더 이야기 나누어 보겠습니다!

2024-06-01 03:56 UTC, 20HyeonsuLee commented on src/main/java/in/koreatech/koin/domain/user/controller/UserApi.java
> +    @Operation(summary = "사장님 로그인")
저는 분리해주는게 좋을것같다는 의견입니다! 이제 owner, student, coop은 클라이언트도 레포를 3개로 분리하기도 했고요!

2024-06-04 01:56 UTC, duehee commented on src/test/java/in/koreatech/koin/fixture/UserFixture.java
> +    public Owner 원경_사장님() {
1차적으로 확인해본 점으로는 현재 최신으로 반영된 비즈니스 팀의 api에서는 "-" 없이 받도록 하였고, 예전에 작성된 코드들은 "-"를 받는 경우들이 있습니다(회원 정보 수정 등). 아마 이 점은 받는 형식만 수정하면 될 것 같은데, 괜찮지 않을까 싶습니다(현재는 전화번호를 직접적으로 사용하는 방식은 사장님 측의 api밖에 없음, 사장님 회원가입, 비밀번호 찾기, 비밀번호 변경 등)

2024-06-04 01:57 UTC, duehee commented on src/main/java/in/koreatech/koin/domain/user/controller/UserApi.java
> +    @Operation(summary = "사장님 로그인")
분리해서 작성해보겠습니다 :D

2024-06-08 04:28 UTC, 20HyeonsuLee requested changes
시험기간에 수고하십니다 ㅠ

2024-06-08 04:28 UTC, 20HyeonsuLee commented on src/main/resources/db/migration/V16__add_account_column_to_owners_table.sql
> +    ADD UNIQUE INDEX `account_UNIQUE` (`account`);
# C
새로 생성된 칼럼에 기존에 users테이블에 들어가 있던 phone_number를 넣어줘야할거같은데 어떻게생각하시나요

2024-06-11 08:14 UTC, daheeParkk approved these changes
수고하셨습니다! 👍🏻

2024-06-11 08:21 UTC, 20HyeonsuLee commented on src/main/resources/db/migration/V16__add_account_column_to_owners_table.sql
> +    ADD UNIQUE INDEX `account_UNIQUE` (`account`);
기존에 존재하는 사장님들의 데이터를 새로 생긴 테이블에 이관해야한다는 말이었습니다!

2024-06-11 08:28 UTC, duehee commented on src/main/resources/db/migration/V16__add_account_column_to_owners_table.sql
> +    ADD UNIQUE INDEX `account_UNIQUE` (`account`);
사장님들은 테이블이 새로 생긴 게 아니라, 필드만 account로 추가했습니다!
말씀하시는 내용은 전화번호 전부를 넣어야한다는 것 같은데, 그렇게 된다면 "-"이 포함된 전화번호가 저장되지 않을까요?
그래서 현재 코드에서는 새로 가입하게 되는 시점부터 "-"가 없는 번호들을 phoneNumber와 동일하게 account에 저장하도록 했습니다. (사장님 전화번호 회원가입 로직에 추가했습니다.)
이번 로그인에 대해 바꾸면서, 사장님의 email 칸에 기존에 전화번호가 들어가는 부분을 수정하면 좋을 것 같은데, 어떤 데이터를 넣어야 할 지 모르겠습니다 😵 좋은 생각이 있을까요..?

2024-06-11 08:35 UTC, 20HyeonsuLee commented on src/main/resources/db/migration/V16__add_account_column_to_owners_table.sql
> +    ADD UNIQUE INDEX `account_UNIQUE` (`account`);
flyway 쿼리문으로 넣어주거나 workbench에서 직접 넣어주거나 데이터를 넣어줄 필요는 있어보여요. -를 때는건 쿼리문으로 하면 되구요(아마 replace있음)
email은 어떻게 해야할지 고민이긴하네요~ 유니크, not null이라서!(사실 user, owner테이블 분리가 필요한부분인데..)
정 안된다면 id값을 email에 넣어주면 어떻까요?

2024-06-11 08:48 UTC, duehee commented on src/main/resources/db/migration/V16__add_account_column_to_owners_table.sql
> +    ADD UNIQUE INDEX `account_UNIQUE` (`account`);
ㅎㅎㅎㅎ.. 이미 있는 DB라.. 그건 아쉽네요..
사장님의 id는 사실상 account = 전화번호이다보니, 그냥 전화번호를 넣어도 괜찮지 않을까 싶네요..!
한 번 생각해봐야겠네요.. 영양사님도 coop_id를 새로 만들긴 했는데, email엔 어떤 값을 넣어야 할 지 모르겠어요.....ㅜㅜㅜ
email = id라고 생각하고 저장하는 방향이 지금으로서는 베스트이지 않을까 싶네요

2024-06-11 08:54 UTC, Choi-JJunho commented on src/main/resources/db/migration/V16__add_account_column_to_owners_table.sql
> +    ADD UNIQUE INDEX `account_UNIQUE` (`account`);
그때 owner 테이블 분리하기로 하지 않았나요?

2024-06-11 09:43 UTC, 20HyeonsuLee commented on src/main/resources/db/migration/V16__add_account_column_to_owners_table.sql
> +    ADD UNIQUE INDEX `account_UNIQUE` (`account`);
제가 말한 id는 key값이긴 합니다..(ex 1, 2, 3, 4)

2024-06-11 13:40 UTC, duehee commented on src/main/resources/db/migration/V16__add_account_column_to_owners_table.sql
> +    ADD UNIQUE INDEX `account_UNIQUE` (`account`);
기존 user_id 값을 말씀하셨던거군요 ㅎㅋㅋㅋㅋ 한 번 다른 분들한테도 여쭤봐야겠어요..!

2024-06-14 10:26 UTC, 20HyeonsuLee requested changes
현재 스테이지데이터 기준으로 로컬에서 돌려봤는데 owner.account에 기존 owner의 값을 채워넣던 중 duplicate account에러가 떠서 flyway쿼리가 실행이 안되네요 ㅠ
확인해보니 stage환경에 같은 전화번호의 owner계정이 여러개 있는 것이 있었습니다!(테스트계정이였음)
테스트 계정을 삭제하는 과정이 필요할거같아요!(flyway말고 직접 쿼리 날려도 될거같음)
prod은 중복된 전화번호를 가진 계정이 없는것을 확인했습니다!
결론
1. stage에 같은 전화번호를 사용하는 owner계정이 있다.
    - 이 계정들은 테스트계정인것을 확인
2. prod에는 같은 전화번호를 사용하는 owner없다.
3. stage환경의 테스트계정을 삭제해야한다.

시험기간에 공부하시느라 고생하셨을텐데 파이팅입니다..!

참고.
같은 전화번호의 owner가 있다면 몇명 있는지 확인하는 쿼리문.
 ```sql
    SELECT 
    REPLACE(phone_number, '-', '') AS normalized_phone_number,
    COUNT(*) AS occurrences
FROM 
    users
WHERE
	user_type = 'OWNER'
GROUP BY 
    normalized_phone_number
HAVING 
    occurrences > 1;
    ```

2024-06-14 10:26 UTC, 20HyeonsuLee commented on src/main/resources/db/migration/V17__create_coop_table_and_insert_data.sql
> +    `coop_id` VARCHAR(255) COMMENT '영양사 id, 일반 로그인 형식',
# C
coop_id대신 account어떨까요?
id --> 뭔가 1, 2, 3, 4, 5일거같은느낌?

2024-06-14 10:26 UTC, 20HyeonsuLee commented on src/test/java/in/koreatech/koin/fixture/UserFixture.java
> +            .account("010-9876-5432")
# R
하이픈 제거하면 터지는 테스트가 있을거같긴한데..
하이픈 제거해야할거같아요!

2024-06-14 10:27 UTC, 20HyeonsuLee approved these changes

2024-06-14 13:13 UTC, duehee commented on src/main/resources/db/migration/V17__create_coop_table_and_insert_data.sql
> +    `coop_id` VARCHAR(255) COMMENT '영양사 id, 일반 로그인 형식',
일반 아이디로 사용할 개념으로 coop_id를 사용했는데 그런 느낌이려나요..?

2024-06-14 13:13 UTC, duehee commented on src/test/java/in/koreatech/koin/fixture/UserFixture.java
> +            .account("010-9876-5432")
테스트 수정해보겠습니당

2024-06-14 15:16 UTC, merged