feat : 학생 시간표 보유 학기 확인 API
BCSDLab/KOIN_API_V2 pull request #570
Opened 2024-05-23 06:02 UTC by duehee

# 🔥 연관 이슈

- close #569 

# 🚀 작업 내용

1. 학생이 가지고 있는 시간표 정보를 통해 학기 정보를 가져오도록 했습니다.
-> user_id 기준으로 보유하고 있는 시간표의 학기를 모두 출력합니다. (커스텀 시간표에서 사용 예정)

# 💬 리뷰 중점사항
코드 리뷰해주셔서 감사합니당

2024-05-23 06:34 UTC, seongjae6751 requested changes
고생하셨습니다!
우리 팀 말고 다른 팀이 봤을 때도 더 잘 이해할 수 있게
이 api가 왜 추가되었는지 배경에 대해 좀 더 자세하게 설명을 적어야 할 것 같아요

2024-05-23 06:34 UTC, seongjae6751 commented on src/main/java/in/koreatech/koin/domain/timetable/service/SemesterService.java
> +        return SemesterCheckResponse.of(userId, timeTables);
C
시간표가 비어있는 학생이 많을텐데
timetable이 없을 때 error를 뱉는게 맞는 설계인걸까요?

막상 뭘 반환해야 하는지는 저도 잘 떠오르지는 않지만 에러를 반환하는 것이 맞는지는 잘 모르겠습니당..

2024-05-23 06:42 UTC, seongjae6751 commented on src/main/java/in/koreatech/koin/domain/timetable/service/SemesterService.java
> +        return SemesterCheckResponse.of(userId, timeTables);
시간표가 비어 있을 때는 빈 리스트가 반환 되도록 설계하는 것이 맞지 않을까요?

2024-05-23 07:10 UTC, daheeParkk requested changes
수고하셨습니다!

2024-05-23 07:10 UTC, daheeParkk commented on src/main/java/in/koreatech/koin/domain/timetable/dto/SemesterCheckResponse.java
> +            .toList();
### C

timeTables를 그대로 받는 것보다 service에서 처리한 값을 dto에 넘겨주는게 어떨까요?

2024-05-23 07:10 UTC, daheeParkk commented on src/main/java/in/koreatech/koin/domain/timetable/dto/SemesterCheckResponse.java
> +    public static SemesterCheckResponse of(Integer userId, List<TimeTable> timeTables) {
### C

timeTables보다 timetables가 괜찮지 않을까요?

2024-05-23 07:11 UTC, kwoo28 commented on src/main/java/in/koreatech/koin/domain/timetable/service/SemesterService.java
> +        return SemesterCheckResponse.of(userId, timeTables);
저도 비슷한 입장이라고 봅니다..!

2024-05-23 08:12 UTC, kwoo28 requested changes
수고 많으셨습니다!!

2024-05-23 08:12 UTC, kwoo28 commented on src/main/java/in/koreatech/koin/domain/timetable/repository/TimeTableRepository.java
> +    List<TimeTable> findAllByUserId(Integer id);
## C

그냥 여기서 semester를 리스트값으로 넘겨주는게 낫지 않을까요?
```suggestion
    List<String> findSemesterByUserId(Integer id);
```

2024-05-23 08:14 UTC, duehee commented on src/main/java/in/koreatech/koin/domain/timetable/service/SemesterService.java
> +        return SemesterCheckResponse.of(userId, timeTables);
앗 빈 리스트로 수정해서 올리겠습니당

2024-05-23 08:35 UTC, duehee commented on src/main/java/in/koreatech/koin/domain/timetable/repository/TimeTableRepository.java
> +    List<TimeTable> findAllByUserId(Integer id);
Repository내에서 List<String>을 그냥 사용할 수 있나요?
userId를 이용해서 TimeTable에서 Semester를 중복 제외해서 출력하는 방법을 사용했는데 비효율적일까요?

2024-05-23 08:37 UTC, duehee commented on src/main/java/in/koreatech/koin/domain/timetable/dto/SemesterCheckResponse.java
> +            .toList();
한 번 수정해보겠습니당

2024-05-24 06:12 UTC, kwoo28 commented on src/main/java/in/koreatech/koin/domain/timetable/repository/TimeTableRepository.java
> +    List<TimeTable> findAllByUserId(Integer id);
아 제가 순간 잘못생각했네요 ㅋㅋ 정빈님이 하신방법이 맞는것같습니다

2024-05-24 08:29 UTC, seongjae6751 requested changes

2024-05-24 08:29 UTC, seongjae6751 commented on src/main/java/in/koreatech/koin/domain/timetable/controller/TimetableApi.java
> +            @ApiResponse(responseCode = "404", content = @Content(schema = @Schema(hidden = true)))
C
에러를 반환하지 않는 것으로 수정했는데 403, 404가 뜰 경우가 여전히 존재 하나요?
클라이언트 분들이 스웨거를 생각보다 많이 신뢰하고 사용해서 더 신경써주면 좋을 것 같아요

2024-05-25 01:26 UTC, duehee commented on src/main/java/in/koreatech/koin/domain/timetable/controller/TimetableApi.java
> +            @ApiResponse(responseCode = "404", content = @Content(schema = @Schema(hidden = true)))
좀 더 신경써보겠습니다😂

2024-05-26 03:21 UTC, kwoo28 approved these changes

2024-05-26 03:38 UTC, seongjae6751 approved these changes

2024-05-26 05:12 UTC, songsunkook approved these changes
👍

2024-05-26 05:12 UTC, songsunkook commented on src/main/java/in/koreatech/koin/domain/timetable/dto/SemesterCheckResponse.java
> +        @Schema(description = "유저 학기", example = "[20191, 20192]", requiredMode = REQUIRED)
### A
사소한 내용인데, List<String>으로 반환하면 [20191, 20192]가 아니라 ["20191", "20192"]로 반환되지 않을까요?

2024-05-26 05:12 UTC, songsunkook commented on src/main/java/in/koreatech/koin/domain/timetable/service/SemesterService.java
> +            .map(timeTable -> timeTable.getSemester().getSemester())
### A
이것도 사소한 건데.. `.getSemester().getSemester()`는 좀 아찔한 것 같아요. 추후에 semester 테이블의 semester 속성명을 code 등으로 바꾸는 것도 좋아보이네요.

2024-05-26 10:43 UTC, duehee commented on src/main/java/in/koreatech/koin/domain/timetable/service/SemesterService.java
> +            .map(timeTable -> timeTable.getSemester().getSemester())
저도 초반에 작성할 때 조금 의아했었는데, 추후에 한 번 수정하면 좋겠네요 :D

2024-05-26 10:44 UTC, duehee commented on src/main/java/in/koreatech/koin/domain/timetable/dto/SemesterCheckResponse.java
> +        @Schema(description = "유저 학기", example = "[20191, 20192]", requiredMode = REQUIRED)
앗 그렇네요..! 사소한 부분이라도 잘 알려주셔서 감사합니당

2024-05-27 05:20 UTC, daheeParkk requested changes

2024-05-27 05:20 UTC, daheeParkk commented on src/main/java/in/koreatech/koin/domain/timetable/dto/SemesterCheckResponse.java
> +    ) {
### A

괄호 위치가 다른 record와 같으면 좋을 것 같아요!

2024-05-27 05:20 UTC, daheeParkk commented on src/main/java/in/koreatech/koin/domain/timetable/service/SemesterService.java
> +    private final TimeTableRepository timeTableRepository;
### C

repository와 DTO도 "Timetable~"로 바뀌어야 할 것 같아요!

2024-05-27 05:23 UTC, duehee commented on src/main/java/in/koreatech/koin/domain/timetable/dto/SemesterCheckResponse.java
> +    ) {
상당히 예리하시네요👀 포맷팅 다 했다고 생각했었는데 감사합니다

2024-05-27 05:44 UTC, daheeParkk approved these changes

2024-05-27 08:04 UTC, merged