feat : 티머니 시외버스 API 구현
BCSDLab/KOIN_API_V2 pull request #572
Opened 2024-05-24 11:26 UTC by Choon0414

# 🔥 연관 이슈

- close #526

# 🚀 작업 내용

1. 티머니 API를 구현하였습니다.
   - 티머니 API는 현재시간 이전의 배차정보는 제공하지 않습니다.
   - 그래서 스케줄링을 하루에 한 번(자정) 하도록, 캐시 만료시간은 48시간으로 수정하였습니다.
2. 시외버스 API를 추상화하였습니다. 
3. 우선 티머니로 시외버스 스케줄러를 활성화하였습니다.
    - 이후 호출 제어, 서킷브레이커가 모두 구현되면 공공데이터포털과 티머니를 함께 사용하도록 수정될 예정입니다.

# 💬 리뷰 중점사항

2024-05-24 11:33 UTC, songsunkook requested changes
인터페이스 분리까지 진행하고 다시 리뷰요청 부탁드립니다!

2024-05-25 03:10 UTC, dradnats1012 approved these changes
이제 시외버스쪽은 공공API 안쓰고 T머니로 바꾼건지 궁금해요

2024-05-25 03:10 UTC, dradnats1012 commented on src/main/java/in/koreatech/koin/domain/bus/util/TmoneyExpressBusOpenApiClient.java
> +                if (depart == arrival || depart.equals(BusStation.STATION) || arrival.equals(BusStation.STATION)) {
### A
공공데이터포털 쪽에는 없는데 T머니에서는 시외관련만 받아와서 그런건가요?
그게 아니라면 PublicOpenApiExpressBusOpenApiClient 쪽에도 추가하면 좋을것 같아요

2024-05-25 09:37 UTC, Choon0414 commented on src/main/java/in/koreatech/koin/domain/bus/model/express/ExpressBusCache.java
> +    private static final long CACHE_EXPIRE_HOUR = 48L;
티머니 api는 공공데이터포털과 다르게 현재 시간 이전의 배차 정보는 제공하지 않아서
하루 한 번 자정에 스케줄링을 하도록 바꿨어요.
그래서 24시간으로 했다가 조금 여유를 두고자 48시간으로 설정했습니다!

서킷브레이커, 호출제어랑 브랜치를 분리하려고 먼저 올린거라 이후에 다중화를 적용하면 공공데이터랑 티머니 모두 사용하도록 수정될 예정입니다.

2024-05-25 09:37 UTC, Choon0414 commented on src/main/java/in/koreatech/koin/domain/bus/util/TmoneyExpressBusOpenApiClient.java
> +                if (depart == arrival || depart.equals(BusStation.STATION) || arrival.equals(BusStation.STATION)) {
공공데이터포털쪽에도 있습니다!

2024-05-25 13:32 UTC, songsunkook approved these changes
고생하셨습니다!

2024-05-25 14:19 UTC, Choon0414 commented on src/main/java/in/koreatech/koin/domain/bus/util/BusScheduler.java
> +    @Scheduled(cron = "0 * * * * *")
`*/1`은 1분마다, `*`은 매분마다 로 변경사항은 없습니다.

2024-05-25 14:19 UTC, Choon0414 commented on src/main/java/in/koreatech/koin/domain/bus/util/BusScheduler.java
> +    @Scheduled(cron = "0 0 0 * * *")
좋습니다 바로 수정할게요!

2024-05-25 14:32 UTC, merged