feat : 서킷브레이커 구현
BCSDLab/KOIN_API_V2 pull request #579
Opened 2024-05-26 11:16 UTC by Choon0414

# 🔥 연관 이슈

- close #578 

# 🚀 작업 내용

1. 서킷브레이커를 구현하였습니다.
    - 외부 API의 장애 발생 시, 특정 조건을 만족하면(호출 실패 횟수) 내부 시스템으로부터 격리합니다.
2. 서킷브레이커를 공공데이터포털API와 티머니API에 적용하였습니다.
버스API 서킷브레이커 설정:
    - Closed(정상 상태)
        - API 호출을 연속 2번 실패하면 `Open`상태로 전환합니다.
    - Open(격리 상태)
        - API가 정상화 되기 전까지 대기하는 단계입니다.
        - 1시간 동안 API 호출 요청에 대해 `CallNotPermmitedException()`을 반환합니다. 
        - 이후 `Half Open`상태로 전환합니다.
    - Half Open(점검 상태)
        - API를 2회 호출하고, 한 번 이상 성공하면 `Closed`상태로 전환합니다. 

# 💬 리뷰 중점사항

2024-05-28 01:20 UTC, Choi-JJunho requested changes
사소한 몇가지만 확인해주세용~!

2024-05-28 01:20 UTC, Choi-JJunho commented on src/test/java/in/koreatech/koin/config/TestResilience4jConfig.java
> +@Configuration
### R
TestConfiguration으로 하는건 어때요?

2024-05-28 01:20 UTC, Choi-JJunho commented on src/test/java/in/koreatech/koin/service/CircuitBreakerServiceTest.java
> +@Service
### C
이 Service는 무엇을 의미하나요

2024-05-28 01:20 UTC, Choi-JJunho commented on src/test/java/in/koreatech/koin/AcceptanceTest.java
> +import in.koreatech.koin.service.CircuitBreakerServiceTest;
### R
만약 TestConfiguartion으로 하게된다면 `@Import`로 해당 클래스를 추가해줘야합니다.

2024-05-28 01:20 UTC, Choi-JJunho commented on src/test/java/in/koreatech/koin/AcceptanceTest.java
> +    protected CircuitBreakerServiceTest circuitBreakerServiceTest;
### C
네이밍을 맞춘다면 Test000 으로 맞추는건 어떤가요?
ex) `TestCircuitBreakerService`

2024-05-29 08:04 UTC, dradnats1012 approved these changes
서킷브레이커라는 개념에 대해 새롭게 알아갑니다!
그럼 처음에는 티머니와 공공api 중에 어떤거 먼저 호출하는건가요??

2024-06-05 12:08 UTC, Choon0414 commented on src/test/java/in/koreatech/koin/AcceptanceTest.java
> +    protected CircuitBreakerServiceTest circuitBreakerServiceTest;
수정했습니다!

2024-06-05 14:48 UTC, Choon0414 commented on src/test/java/in/koreatech/koin/service/CircuitBreakerServiceTest.java
> +@Service
임의로 작성했었는데 service일 이유는 없네요. 수정하겠습니다!

2024-06-05 16:03 UTC, Choon0414 commented on src/test/java/in/koreatech/koin/service/CircuitBreakerServiceTest.java
> +@Service
임시로 서킷브레이커 테스트용 메서드 사용을 위해 적었는데 service일 이유는 없는 것 같네요. 수정했습니다.

2024-06-07 01:15 UTC, Choi-JJunho approved these changes

2024-06-08 04:21 UTC, merged