Feature/75 put admin tech stacks
BCSDLab/KOIN_API_V2 pull request #585
Opened 2024-06-01 11:28 UTC by BaeJinho4028

# 🔥 연관 이슈

- close #75 

# 🚀 작업 내용

1. feat: Admin으로 BCSDLab 기술스택 수정 기능 구현

# 💬 리뷰 중점사항
TechStackNotFoundException이 필요해서 만들긴했는데, TrackNotFoundException랑 다를게 없어서 차라리 메세지만 변경 가능한 예외 만들지 고민중입니다.

post때도 그랬지만 레거시에서 body에 id가 들어가지만 이것이 실제로 반영되지는 않는데 제가 모르는 기능이 있는것인지 궁금합니다.
(커밋 기록 실수한것이라 신경 안쓰셔도됩니다.)

2024-06-04 00:36 UTC, Choi-JJunho requested changes
깔끔하군요 굿
하나만 확인해주세요~

2024-06-04 00:36 UTC, Choi-JJunho commented on src/main/java/in/koreatech/koin/domain/member/model/TechStack.java
>      }
### R

파라미터로 Dto를 받게 되면서 엔티티가 변경이 쉬운 DTO를 의존하게 되네요~
의존관계를 분리해보죠

2024-06-04 00:40 UTC, 20HyeonsuLee approved these changes
Good 수고하셨습니다~

2024-06-06 06:00 UTC, BaeJinho4028 commented on src/main/java/in/koreatech/koin/domain/member/model/TechStack.java
>      }
피드백 반영하였습니다.

dto를 넘기면 서비스단이 더욱 깔끔할것같아서 저리 작성하였는데, dto가 하나의 엔티티에 국한x, 불필요한 정보 노출, 변경 가능성, 재사용성 떨어짐 등의 이유로 의존을 조심해야하는군요. 감사합니다.

2024-06-06 06:09 UTC, Choi-JJunho approved these changes
굿 고생하셨습니다.

2024-06-06 06:39 UTC, merged