feat: 버스 필터링
BCSDLab/KOIN_API_V2 pull request #586
Opened 2024-06-03 00:27 UTC by ImTotem

# 🔥 연관 이슈

- close #527 

# 🚀 작업 내용

- 정류소별 경유노선 목록을 기준으로 버스를 필터링 합니다.
1. 정류소별 경유노선 목록을 조회하여 Redis에 캐싱
2. 출발 정류소 경유노선 목록과 도착 정류소 경유노선 목록을 조회
    - 캐싱된 정보가 없을경우 `[400, 402, 405]`를 반환
3. 두 경유노선 목록의 교집합을 구하여 필터링 목록 생성
4. 사용자가 요청을 보낼때마다 필터링하여 응답

- 필터링 위치를 변경하였습니다.
    - 기존: `OpenApiClient`에서 open api를 호출할 때 필터링
    - 변경 후: 사용자가 요청을 보낼때마다 Service에서 필터링

# 💬 리뷰 중점사항

2024-06-04 12:27 UTC, dradnats1012 requested changes
고생하셨습니다~!
몇가지 궁금한점 써놨어용

2024-06-04 12:27 UTC, dradnats1012 commented on src/main/java/in/koreatech/koin/domain/bus/service/BusService.java
> +            departAvailableBusNumbers.retainAll(arrivalAvailableBusNumbers);
### A
이건 교집합을 어디에 쓰는건지 궁금해요

2024-06-04 12:27 UTC, dradnats1012 commented on src/main/java/in/koreatech/koin/domain/bus/util/CityBusOpenApiClient.java
> -    private static final List<Long> AVAILABLE_CITY_BUS = List.of(400L, 402L, 405L);
### A
이쪽을 따로 클래스로 뺀 이유가 있나요???

2024-06-04 13:14 UTC, ImTotem commented on src/main/java/in/koreatech/koin/domain/bus/model/city/CityBusRoute.java
> +    String startnodenm // 기점, 종합터미널
jsonResponse 매핑용 레코드입니다
gson을 그냥 활용할 경우 class의 멤버 이름을 그대로 json의 key로 mapping 시키기 때문에 json의 key와 동일하게 맞춰줘야 합니다.
아래처럼 써도 되지만 다른 레코드들도 그냥 썼길래 맞춰서 그냥 썼습니다
```suggestion
    @SerializedName("endnodenm")
    String endNodeName, // 종점, 병천3리
    
    @SerializedName("routeid")
    String routeId, // 노선 ID, CAB285000142
    
    @SerializedName("routeno")
    Long routeNumber, // 노선 번호, 400
    
    @SerializedName("routetp")
    String routeType, // 노선 유형, 일반버스
    
    @SerializedName("startnodenm")
    String startNodeName // 기점, 종합터미널
```

2024-06-04 13:14 UTC, ImTotem commented on src/main/java/in/koreatech/koin/domain/bus/service/BusService.java
> +    private final CityBusRouteOpenApiClient cityBusRouteOpenApiClient;
수정했습니다 👍

2024-06-05 00:10 UTC, songsunkook commented on src/main/java/in/koreatech/koin/domain/bus/repository/CityBusRouteCacheRepository.java
> +    Optional<CityBusRouteCache> findById(String nodeId);
### A

> 레디스에 정상적으로 노선 정보가 저장되고,
repository.findAll()을 했을때는 정상적으로 결과가 나오는데
repository.findById(nodeId)를 했을때는 항상 empty가 뜨는데 아시는분 있나요 ㅠ

이건 어떻게 해결했는지 알려주실 수 있나요?

2024-06-05 00:36 UTC, songsunkook commented on src/main/java/in/koreatech/koin/domain/bus/util/CityBusRouteClient.java
> +        String url = "https://apis.data.go.kr/1613000/BusSttnInfoInqireService/getSttnThrghRouteList";
### C
기존 코드에서는 사용처가 없던 API인가요??
https://www.data.go.kr/tcs/dss/selectApiDataDetailView.do?publicDataPk=15098534 를 사용하신 것 같은데, 이 페이지 링크와 함께 "정류소별경유노선 목록조회"라는 부가설명까지 클래스 주석으로 달아주면 좋을 것 같아요

2024-06-05 00:56 UTC, songsunkook commented on src/main/java/in/koreatech/koin/domain/bus/util/CityBusRouteClient.java
> +    }
### C
save보다 saveAll이 더 성능 상 이점이 있다고 하더라구요
stream을 잘 써보면 바꿔볼 수 있지 않을까요??

2024-06-05 07:45 UTC, ImTotem commented on src/main/java/in/koreatech/koin/domain/bus/util/CityBusRouteClient.java
> +        String url = "https://apis.data.go.kr/1613000/BusSttnInfoInqireService/getSttnThrghRouteList";
추가했습니다! 👍

2024-06-05 07:45 UTC, ImTotem commented on src/main/java/in/koreatech/koin/domain/bus/util/CityBusRouteClient.java
> +    }
saveAll 반영했습니다! 👍 
saveAll의 존재를 까먹고 있었네요 😅

2024-06-05 08:54 UTC, songsunkook commented on src/main/java/in/koreatech/koin/domain/bus/util/CityBusRouteClient.java
> +        }
외부 api에 대한 의존성을 낮추기 위한 코드라는 거네요. 좋은 아이디어인 것 같습니다. 일단은 이대로 유지하는 게 좋을 것 같아요!


+) 마침 다른 분께서 서킷브레이커 작업을 해주고 계셔서 이 api도 서킷브레이커에 등록하고 고장나면 임의로 해당 번호를 캐시로 기입하는 정도로 수정할 수 있을 것 같아요. @Choon0414 확인 부탁드립니다!
다만 이렇게 되면 버스 번호에 의존적이게 되어버려서 이번 천안 버스 개편같은 상황이 또 생기면 코드를 직접 고쳐야 하는 점은 우려되네요.

2024-06-05 08:57 UTC, songsunkook approved these changes
고생하셨습니다! 👍

2024-06-14 01:48 UTC, dradnats1012 approved these changes
👍

2024-06-14 08:07 UTC, merged