feat: timetable frame api 중 post, get, delete 구현
BCSDLab/KOIN_API_V2 pull request #592
Opened 2024-06-06 14:51 UTC by seongjae6751

# 🔥 연관 이슈

# 🚀 작업 내용

![스크린샷(208)](https://github.com/BCSDLab/KOIN_API_V2/assets/103095432/d6b90414-53c6-466d-a5ad-683ffb35a7b0)

기존 timetable은 강의 정보를 lecture와 동일한 정보(강의 이름, 교수명, 이름, 장소 등)를 중복 저장하는 문제가 있었습니다. 이를 개선하여 timetable이 이제 lecture_id를 FK로 받아 저장하는 구조로 변경했습니다. 또한, 커스텀 시간표 기능에서 학기별로 여러 시간표를 저장할 수 있도록 timetable을 timetable_lecture와 timetable_frame으로 정규화했습니다.

![스크린샷(209)](https://github.com/BCSDLab/KOIN_API_V2/assets/103095432/eaafacb5-978a-450c-873e-cb4ca4d06c67)
`커스텀 시간표 ui`

timetable_frame은 위 사진에서 학기 별 시간표 이름과 메인 시간표 여부 등의 정보를 가지며,
timetable_lecture는 기존의 timetable들이 갖고 있던 정보들과 새롭게 lecture_id등을 가집니다.
자세한 내용은 아래 문서를 참고해주시면 감사하겠습니다.

[커스텀 시간표 회의록](https://docs.google.com/document/d/1gUD2gjiYdlOBv8xADNopl0N0Ikpj4HaOp7Zm91OcdwE/edit)
[커스텀 시간표 작업 문서](https://docs.google.com/document/d/1y66EwEENjK62KabSVPDIbb7fqOiGrFWoRxFTgAhTXYA/edit)

위와 같은 작업에서 저는 timetable_frame의 crd 기능들을 구현했습니다.
각 api 별로 갖는 기능은 다음과 같습니다.

* post/timetables/frame: 시간표 frame을 생성해줍니다. `"시간표" + 학기 시간표 개수 + 1`의 형식으로 생성됩니다.
* get/timetables/frame: 그 학기에 사용자가 갖고 있는 모든 시간표frame을 반환합니다.
* delete/timetables/frame: 사용자가 삭제하려는 시간표 frame이 해당 사용자의 것인지 확인 후 삭제 합니다. 메인 시간표를 삭제 할 시에 자동으로 다른 시간표가 메인으로 설정됩니다. 또한 timetable_frame의 id를 fk로 갖고 있는 timetable_lecture들은 자동으로 삭제됩니다.

회원 탈퇴 시 관련 timetable 정보들이 모두 수동으로 삭제되도록 처리했습니다. user에 timetable 정보를 넣을 수 없어서 orphan removal 설정을 할 수 없었습니다.

+ 나중에 develop에 flyway를 돌리고 공동 pr로 한번에 날릴 계획이라 우선은 develop이 아닌 다른 브랜치에 pr을 올립니다

# 💬 리뷰 중점사항

2024-06-14 07:27 UTC, daheeParkk approved these changes
수고하셨습니다! 👍🏻👍🏻

2024-06-14 07:29 UTC, daheeParkk requested changes

2024-06-14 07:29 UTC, daheeParkk commented on src/main/java/in/koreatech/koin/domain/timetable/controller/TimetableController.java
> +    @PostMapping("/timetables/frame")
### R
새로운 api는 앞에 V2 붙이기로 한 거 아니었나요??

2024-06-14 13:57 UTC, kwoo28 requested changes
테스트까지 작성하느라 수고 많으셨습니다!
코드도 깔끔하게 잘 작성하신것같습니다.

2024-06-14 13:57 UTC, kwoo28 commented on src/main/java/in/koreatech/koin/domain/timetable/dto/TimeTableFrameRequest.java
> +public record TimeTableFrameRequest(
## R

createDTO임을 명시할 수 있게 변경하는게 좋을것같습니다!

2024-06-14 13:57 UTC, kwoo28 commented on src/main/java/in/koreatech/koin/domain/timetable/service/TimetableService.java
> +                timetableFrameRepository.save(nextMainFrame);
## C
 
 트랜잭션이 커밋될때 변경사항이 자동으로 데이터베이스에 반영돼서 save는 안해도 되지 않을까요??

2024-06-15 14:09 UTC, duehee requested changes
고생하셨어요~ 코멘트 확인해주세요!!
추가적으로 테스트와 픽스처 작성해주셔서 먼저 머지될 것 같은데,
다희님께서 작성한 Frame의 is_deleted도 flyway에 추가해야 할 것 같네요(모델 때 빼먹은 제 실수.. ㅎㅎ..)

2024-06-15 14:09 UTC, duehee commented on src/main/java/in/koreatech/koin/domain/timetable/model/TimeTableLecture.java
> +public class TimeTableLecture extends BaseEntity {
### C
DTO랑 Mode 쪽 이름을 "Timetable~~~"로 수정해야 할 거 같아요!

2024-06-15 14:09 UTC, duehee commented on src/main/java/in/koreatech/koin/domain/user/service/UserService.java
> +            timeTableFrameRepository.deleteAllByUser(user);
### C
메소드명을 timetableFrameRepository를 사용하는게 좋을 거 같아요

2024-06-15 14:09 UTC, duehee commented on src/test/java/in/koreatech/koin/fixture/TimeTableV2Fixture.java
> +public class TimeTableV2Fixture {
### A
픽스처까지..!! 굳입니당

2024-06-15 15:55 UTC, seongjae6751 commented on src/main/java/in/koreatech/koin/domain/timetable/controller/TimetableController.java
> +    @PostMapping("/timetables/frame")
회의록 보면 지금 제가 한 방식대로 써져 있긴 합니다..!
[회의록](https://docs.google.com/document/d/1y66EwEENjK62KabSVPDIbb7fqOiGrFWoRxFTgAhTXYA/edit)

POST /v2/timetables만 두 개가 공존하는 상태가 되어서 V2를 붙인 걸로 이해했는데 V2를 붙여야 할까요?

2024-06-15 16:09 UTC, seongjae6751 commented on src/main/java/in/koreatech/koin/domain/timetable/service/TimetableService.java
> +                timetableFrameRepository.save(nextMainFrame);
저는 코드의 명확성을 위해 남겨놔도 좋지 않을까 생각하는데 어떻게 생각하시나요?

2024-06-15 16:14 UTC, seongjae6751 commented on src/test/java/in/koreatech/koin/fixture/TimeTableV2Fixture.java
> +public class TimeTableV2Fixture {
is_deleted는 다른 분들이 반영해주셔서 나중에 최종적으로 다 합쳐지면 괜찮을 것 같습니다ㅎㅎ

2024-06-17 01:08 UTC, daheeParkk approved these changes

2024-06-17 01:08 UTC, daheeParkk commented on src/main/java/in/koreatech/koin/domain/timetable/controller/TimetableController.java
> +    @PostMapping("/timetables/frame")
새로운 api 모두 v2 붙이면 통일성 있고, 클라이언트에서 보기 편할 것 같은데
스웨거에서 구분해 놓으면 꼭 필요해 보이지는 않네요..!

2024-06-17 13:52 UTC, kwoo28 commented on src/main/java/in/koreatech/koin/domain/timetable/service/TimetableService.java
> +                timetableFrameRepository.save(nextMainFrame);
그렇군요!

2024-06-17 13:53 UTC, duehee approved these changes
고생하셨어요👍

2024-06-17 13:55 UTC, kwoo28 approved these changes
수고 많으셨습니다!

2024-06-17 14:01 UTC, merged