feat: timetableFrame put, timetableLecture delete 구현 & reafactor: 기존 timetable delete, get 수정
BCSDLab/KOIN_API_V2 pull request #594
Opened 2024-06-07 09:53 UTC by daheeParkk

# 🔥 연관 이슈

# 🚀 작업 내용

timetables 테이블을 timetable_frame, timetable_lecture로 구분하였습니다.
기존 api도 사용해야 하므로 기존 api를 변경된 테이블에 맞게 로직을 수정하였고,
추가적인 api도 구현하였습니다.

## 테이블을 변경한 이유
![image](https://github.com/BCSDLab/KOIN_API_V2/assets/106418303/0275dabc-e5cd-4530-8329-5837cd2139b6)
- 상황 & 명칭 설명
  - 커스텀 시간표를 기획하면서 한 학기에 예비 수강 신청 시간표나 커스텀 시간표를 따로 넣을 수 있으면 좋을 것 같았습니다.
  - 위의 이미지에서 변경된 시간표 이미지의 왼쪽에 1안, 2안이라 써있는 부분 하나하나를 timetable_frame으로 뒀습니다.
  - 한 개의 timetable_frame 안에 생기는 강의는 timetable_lecture입니다.
- 기존
  - 한 학기에 한 개의 시간표
- 새로운 기획
  - 한 학기에 여러 개의 시간표 
 

## 변경된 테이블 구조
![image](https://github.com/BCSDLab/KOIN_API_V2/assets/106418303/f6dfb220-776e-4e50-b816-cfc4e57e7194)
- 변경 전 테이블
  - timetables 테이블에 강의 정보(lecture 테이블과 동일한 내용)가 모두 있습니다.
- 변경 후 테이블
  - timetable_lecture 
    - lecture와 동일한 내용을 가지는 대신 해당하는 lecture의 id를 가지고 있음 
  - timetable_frame
    - 한 학기에서 여러 개의 시간표를 갖기 위한 테이블
  
## 작업한 api
### 기존 api
- DELETE /timetable
  - timetable_lecture 테이블에서 삭제하도록 수정
- GET /timetables
  - timetable_lecture 테이블에 담긴 정보와 lecture 테이블에 담긴 정보를 합쳐서 기존 반환 값 유지하도록 수정

### 추가 api
- DELETE V2/timetables/lecture/{id}
  - DELETE /timetable api에서 수정한 로직과 똑같지만 추가로 만들었습니다. 
    - 이유: timetable frame과 lecture가 구분된 상황에서 기존 api를 사용하면 무엇을 삭제하는지 헷갈릴 것 같음  
- PUT V2/timetables/frame
  - 학기와 시간표 이름, 메인 시간표 여부를 수정하는 api입니다. 
  - 한 학기에 여러 시간표가 들어갈 수 있지만 그중 한 개는 메인 시간표이어야 합니다.
    - 메인 시간표 여부가 true로 들어오면 다른 메인 시간표를 찾아서 메인 여부를 false로 바꾸도록 했습니다.

# 💬 리뷰 중점사항
- PUT V2/timetables/frame
  - true인 메인 여부를 false로 직접 바꾸지 못하게 하고, 다른 시간표를 메인으로 바꿀 수만 있게 하였습니다.  
- 클라이언트에서 헷갈리지 않게 스웨거에 새로운 시간표를 표시했습니다.
  - ![image](https://github.com/BCSDLab/KOIN_API_V2/assets/106418303/16ad7349-2189-4b96-b5f4-6a763a898a99)
- 테스트 코드는 new-timetable 브랜치에 합친 후 작성하겠습니다.

2024-06-14 11:10 UTC, seongjae6751 requested changes
pr 설명 엄청 깔끔하게 적으셨네요..
어떻게 적는 것이 좋을지 또 배워갑니다
고생 많으셨습니다! 리뷰 드립니다

2024-06-14 11:10 UTC, seongjae6751 commented on src/main/java/in/koreatech/koin/domain/timetable/service/TimetableService.java
> +    }
```suggestion
private void cancelMainTimetable(Integer userId, Integer semesterId) {
    TimetableFrame mainTimetableFrame = timetableFrameRepository.findAllByUserIdAndSemesterId(userId, semesterId)
        .stream()
        .filter(TimetableFrame::isMain)
        .findFirst()
        .orElseThrow(() -> new TimetableLectureNotFoundException("못 찾음 userId: " + userId + ", semesterId: " + semesterId));
    mainTimetableFrame.cancelMain();
}
```

A
얘네가 재 사용 될 로직이 아니라면 하나로 합치는 것이 더 좋을 수도 있을 것 같습니당

2024-06-14 11:10 UTC, seongjae6751 commented on src/main/java/in/koreatech/koin/domain/timetable/service/TimetableService.java
> +            .orElseThrow(() -> TimetableLectureNotFoundException.withDetail("못 찾음 userId: "+ userId + ", semesterId: " + semesterId));
C
이것을 함수로 만들지 않고 repository에서 쿼리로 한번에 해결할 수 있을 것 같아요
ex) findFirstByUserIdAndSemesterIdAndIsMainTrue(userId, frame.getSemester().getId());

2024-06-14 13:37 UTC, kwoo28 requested changes
PR에 상세한 내용 올려주셔서 감사합니다.
기존 코드에서 사소한것까지 다 수정하느라 고생많으셨습니다..!

2024-06-14 13:37 UTC, kwoo28 commented on src/main/resources/db/migration/V16__add_timetable_frame.sql
> +    is_deleted TINYINT(1) NOT NULL DEFAULT 0 comment '시간표 삭제 여부',
## A

👍

2024-06-14 13:37 UTC, kwoo28 commented on src/test/java/in/koreatech/koin/acceptance/TimetableApiTest.java
> +    private TimetableFixture timetableFixture;
## A

이것까지 고쳤네요... 대단합니다

2024-06-14 13:37 UTC, kwoo28 commented on src/main/java/in/koreatech/koin/domain/timetable/service/TimetableService.java
> +    }
음..근데 단순 id로도 삭제해도 되지않나요?? 이미 위에 삭제하기전에 getById를 통해서 검증하는것같아서..

2024-06-14 13:37 UTC, kwoo28 commented on src/main/java/in/koreatech/koin/domain/timetable/model/TimetableFrame.java
> +    }
## C

이거 TimetableFrame.getIsMain()이랑 똑같은 기능같은데 안넣어도 되지않을까요?

2024-06-15 14:52 UTC, duehee requested changes
고생하셨습니다~ 저도 얼른.. 올릴게요😢

2024-06-15 14:52 UTC, duehee commented on src/main/java/in/koreatech/koin/domain/timetable/controller/TimetableController.java
> +        TimetableResponse timeTableResponse = timetableService.getTimetables(userId, semester);
### C
통일성 있게 timetableResponse가 좋지 않을까요?
한다면 아래도..!

2024-06-15 14:52 UTC, duehee commented on src/main/java/in/koreatech/koin/domain/timetable/model/TimetableFrame.java
> +    private boolean isDeleted = false;
### A 
제가 까먹어서 ㅎㅎ.. 제송합니다

2024-06-15 14:52 UTC, duehee commented on src/main/java/in/koreatech/koin/domain/timetable/repository/TimetableRepository.java
> +    Timetable save(Timetable timeTable);
### C
```suggestion
    Timetable save(Timetable timetable);
```

2024-06-17 02:52 UTC, daheeParkk commented on src/main/java/in/koreatech/koin/domain/timetable/service/TimetableService.java
> +        timetableLectureRepository.getById(id);
존재하는 timetableLecure인지 검증했습니다!

2024-06-17 02:53 UTC, daheeParkk commented on src/main/java/in/koreatech/koin/domain/timetable/service/TimetableService.java
> +    }
유저 본인의 시간표를 삭제하는 건지 확인해 봐야겠네요
user id도 추가하겠습니다

2024-06-17 02:54 UTC, daheeParkk commented on src/main/java/in/koreatech/koin/domain/timetable/service/TimetableService.java
> +        TimetableFrame mainTimetableFrame = findMainTimetable(userId, semester.getId());
기존에 사용하는 GET api라서 main table에만 값이 있습니다!

2024-06-17 03:04 UTC, daheeParkk commented on src/main/java/in/koreatech/koin/domain/timetable/service/TimetableService.java
> +        return getTimetableResponse(userId, semester);
기존 api를 사용한다면 한 학기에 여러 시간표가 있을 수 없어서  main timetable에만 값이 있습니다.

**[작업 문서](https://docs.google.com/document/d/1y66EwEENjK62KabSVPDIbb7fqOiGrFWoRxFTgAhTXYA/edit)** 보니 새로운 GET api에 대한 작업을 안 정한 것 같네요..

2024-06-17 03:09 UTC, daheeParkk commented on src/main/java/in/koreatech/koin/domain/timetable/dto/TimetableFrameUpdateRequest.java
> +    @Size(max = 255, message = "시간표 이름의 최대 길이는 255자입니다.")
바꾼다면 flyway도 바꿔야겠네요
나중에 합치면서 다른 분들과 얘기해보면 좋을 것 같아요

2024-06-17 03:11 UTC, daheeParkk commented on src/main/java/in/koreatech/koin/domain/timetable/service/TimetableService.java
> +            .orElseThrow(() -> TimetableLectureNotFoundException.withDetail("못 찾음 userId: "+ userId + ", semesterId: " + semesterId));
헉.. 에러 원인 찾으려고 빨리 적었다가 까먹고 못 바꿨습니다..ㅠㅠ

2024-06-17 03:13 UTC, daheeParkk commented on src/main/java/in/koreatech/koin/domain/timetable/service/TimetableService.java
> +    }
getTimetableResponse()에서도 findMainTimetable()를 사용하고 있습니다!
 \+ 하나의 메서드에 역할 한 개만 가지고 있는 게 좋다 생각해서 나눠봤습니다

2024-06-17 03:16 UTC, daheeParkk commented on src/main/java/in/koreatech/koin/domain/timetable/service/TimetableService.java
> +            .orElseThrow(() -> TimetableLectureNotFoundException.withDetail("못 찾음 userId: "+ userId + ", semesterId: " + semesterId));
생각 못 했네요...! repository로 바꾸겠습니다

2024-06-17 03:17 UTC, daheeParkk commented on src/main/java/in/koreatech/koin/domain/timetable/dto/TimetableFrameUpdateResponse.java
> +    @Schema(description = "메인 시간표 여부", example = "false", requiredMode = REQUIRED)
앗 복붙.. 죄송합니다

2024-06-17 03:19 UTC, daheeParkk commented on src/main/java/in/koreatech/koin/domain/timetable/dto/TimetableFrameUpdateResponse.java
> +    String semester,
오,, 그렇네요  frame_id로 바꾸겠습니다

2024-06-17 03:30 UTC, daheeParkk commented on src/main/java/in/koreatech/koin/domain/timetable/dto/TimetableFrameUpdateRequest.java
> +    String semester,
그러네요!

2024-06-17 03:30 UTC, daheeParkk commented on src/main/java/in/koreatech/koin/domain/timetable/model/TimetableFrame.java
> +    }
빼겠습니다!

2024-06-17 03:30 UTC, daheeParkk commented on src/main/java/in/koreatech/koin/domain/timetable/service/TimetableService.java
>      }
총 학점을 신경 못 썼네요..
합치면서 학점 계산 구현하신 분 코드로 하면 될 것 같아요

2024-06-17 13:55 UTC, duehee approved these changes
제 의견은 다 반영되었군요👀 고생하셨습니다~

2024-06-17 14:04 UTC, kwoo28 requested changes
마지막 한가지만...부탁드립니다

2024-06-17 14:04 UTC, kwoo28 commented on src/main/java/in/koreatech/koin/domain/timetable/dto/TimetableFrameUpdateRequest.java
> +    String semester,
semester를 변경하게되면 해당 시간표에 있는 강의들의 학기와 일치하지 않게돼서 semester는 변경하게 하면 안될것같아요.

2024-06-17 14:30 UTC, daheeParkk commented on src/main/java/in/koreatech/koin/domain/timetable/repository/TimetableFrameRepository.java
> +    }
> 현재 기존에 작성된 코드들을 보면, repository에서 get이라는 네이밍을 붙인 메서드들은 find 메서드에 예외 처리를 추가한 것들입니다. 보통 메서드의 이름을 find에서 get으로 변경하는 방식으로 통일성을 유지하고 있습니다. 이런 네이밍 컨벤션을 유지하는 것이 좋지 않을까 저는 생각하는데 어떻게 생각하시나요?

service에서는 파라미터로 알 수 있는 부분을 메서드명에 넣을 필요가 없다 생각했습니다.
service에서 모두 get~형식만 사용하는 건 아니니 통일성을 위해 기존처럼 하는게 좋을 것 같네요!

2024-06-17 17:01 UTC, kwoo28 approved these changes

2024-06-17 17:02 UTC, merged