feat: GET/semester/check수정 & POST/timetables수정 & POST/v2/timetables/lecture 추가
BCSDLab/KOIN_API_V2 pull request #596
Opened 2024-06-08 05:26 UTC by kwoo28

# 🔥 연관 이슈

해당 논의에 대한 자세한 설명은 아래 PR에 올라와있습니다.
https://github.com/BCSDLab/KOIN_API_V2/pull/594

# 🚀 작업 내용

1. 기존 API 수정
1-1.  GET/semester/check
기존 timetable테이블에서 새로 추가한 timetable_lecture에서 조회할수있게 서비스로직 변경했습니다.<br>
1-2. POST/timetables
사용자가 기존 API로 시간표 생성할때, 새로 추가한 timetable_lecture 컬럼에 맞는 데이터가 들어갈 수 있게 서비스로직 수정했습니다.

2. 버저닝 API 추가
2-1 POST/v2/timetables/lecture
새로 추가한 timetable_lecture 테이블의 컬럼에 맞는 시간표 생성 버저닝API를 추가했습니다.

# 💬 리뷰 중점사항
버저닝 시간표 생성 API를 추가한 이유는 아래 사진과 같이 로직 단순화를 통해 응답시간 단축하기 위함입니다.
<img width="512" alt="image" src="https://github.com/BCSDLab/KOIN_API_V2/assets/148550522/25fbfeaa-2930-4d1a-bf05-de0d4ff74e6d">

테스트코드는 new-timetable 브랜치가 합쳐지고 나면 작성할 예정입니다.

2024-06-14 08:00 UTC, daheeParkk requested changes
수고하셨습니다! 👍🏻👍🏻

2024-06-14 12:01 UTC, kwoo28 commented on src/main/java/in/koreatech/koin/domain/timetable/controller/TimetableController.java
>  public class TimetableController implements TimetableApi {
넵 기존 POST수정하게되면 다른 api 코드들까지 전부 바꿔줘야하는 상황이 벌어져서, 일단 다른 api는 삭제하고 작업해야할 api만 작성했습니다.

2024-06-14 12:04 UTC, kwoo28 commented on src/main/java/in/koreatech/koin/domain/timetable/service/TimetableService.java
>  public class TimetableService {
그게 더 좋은것같네요!

2024-06-14 12:07 UTC, kwoo28 commented on src/main/java/in/koreatech/koin/domain/timetable/service/TimetableService.java
> +        TimetableFrame TimetableFrame = timetableFrameRepository.getByUserIdAndSemester(userId, request.semester());
헉 그렇네요..! 수정하겠습니다

2024-06-14 13:59 UTC, seongjae6751 requested changes
고생 많으셨습니다! 리뷰 드립니당

2024-06-14 13:59 UTC, seongjae6751 commented on src/main/java/in/koreatech/koin/domain/timetable/dto/TimetableResponse.java
>      }
A
불필요한 공백이 존재하네요

2024-06-14 13:59 UTC, seongjae6751 commented on src/main/java/in/koreatech/koin/domain/timetable/repository/TimetableFrameRepository.java
> +    List<TimetableFrame> findAllByUserId(Integer userId);
A
사소한 것이고 어차피 합쳐지겠지만 통일성 있게 repository에서 첫 메서드 넣을때 개행 하나씩 넣는게 깔끔할 것 같네요

2024-06-14 13:59 UTC, seongjae6751 commented on src/main/java/in/koreatech/koin/domain/timetable/service/TimetableService.java
> +        TimetableFrame TimetableFrame = timetableFrameRepository.getByUserIdAndSemester(userId, request.semester());
R
한 유저 당 한 학기에 여러 timetableFrame을 갖고 있을텐데 단순히 userId와 semester만으로 갖고오면 안되지 않을까요?

2024-06-14 13:59 UTC, seongjae6751 commented on src/main/java/in/koreatech/koin/domain/timetable/dto/TimetableResponse.java
> +    Semester semester,
C
얘는 타입을 Semester로 바꾼 이유가 있나요? 객체를 반환하면 json 반환 값도 기존이랑 달라져서 문제가 생기지 않을까요?

2024-06-14 14:01 UTC, kwoo28 commented on src/main/java/in/koreatech/koin/domain/timetable/controller/TimetableController.java
>  public class TimetableController implements TimetableApi {
넵!

2024-06-14 14:01 UTC, kwoo28 commented on src/main/java/in/koreatech/koin/domain/timetable/dto/TimetableLectureCreateRequest.java
> +    @Schema(description = "강의 시간표 정보", requiredMode = REQUIRED)
헉 그렇네요.. 수정하겠씁니다

2024-06-14 14:03 UTC, kwoo28 commented on src/main/java/in/koreatech/koin/domain/timetable/dto/TimetableLectureResponse.java
> +        String regularNumber,
근데 현재 클라이언트는 regularNumber라는 필드명의 응답값을 이용하고있어서 고치게되면 큰 참사가 일어날거같습니다..

2024-06-14 14:11 UTC, kwoo28 commented on src/main/java/in/koreatech/koin/domain/timetable/dto/TimetableLectureResponse.java
> +        String regularNumber,
저도 직관적이지 않긴한데, DB와 model컬럼명도 regularNumber이며 지금껏 계속 써온상태에서 갑자기 바꾼다면 클라이언트하고 추후 유지보수하게 될사람이 헷갈리지 않을까요..?

2024-06-14 14:11 UTC, kwoo28 commented on src/main/java/in/koreatech/koin/domain/timetable/dto/TimetableLectureCreateRequest.java
> +public record TimetableLectureCreateRequest(
그게 좋겠네요!

2024-06-14 14:12 UTC, kwoo28 commented on src/main/java/in/koreatech/koin/domain/timetable/repository/TimetableFrameRepository.java
> +    List<TimetableFrame> findAllByUserId(Integer userId);
그 부분을 놓쳤네요..ㅎ

2024-06-14 14:13 UTC, kwoo28 commented on src/main/java/in/koreatech/koin/domain/timetable/dto/TimetableResponse.java
> +    Semester semester,
헉 그렇네요. 변경하겠습니다

2024-06-14 14:16 UTC, kwoo28 commented on src/main/java/in/koreatech/koin/domain/timetable/service/TimetableService.java
> +        TimetableFrame TimetableFrame = timetableFrameRepository.getByUserIdAndSemester(userId, request.semester());
현재 DB에 1:1로 존재하여 문제없을테고, 클라이언트가 Frame을 추가하여 1:N이 나올 상황은 버저닝 API를 사용하기때문에 굳이 레거시로직에서 고칠필요가 없다생각했습니다.

2024-06-14 14:22 UTC, kwoo28 commented on src/main/java/in/koreatech/koin/domain/timetable/service/TimetableService.java
> +        TimetableFrame TimetableFrame = timetableFrameRepository.getByUserIdAndSemester(userId, request.semester());
만약 A클라이언트는 버저닝을사용하고, B클라이언트는 기존API를 사용한다면 불일치가 생기겠네요.. isMain을 기준으로 갖고오게끔 변경하겠습니다!

2024-06-15 16:21 UTC, duehee requested changes
고생하셨씁니다!!

2024-06-15 16:21 UTC, duehee commented on src/main/java/in/koreatech/koin/domain/timetable/service/SemesterService.java
> +        List<TimetableFrame> timeTableFrames = timetableFrameRepository.findAllByUserId(userId);
### C
```suggestion
        List<TimetableFrame> timetableFrames = timetableFrameRepository.findAllByUserId(userId);
```

2024-06-15 16:21 UTC, duehee commented on src/main/java/in/koreatech/koin/domain/timetable/service/TimetableService.java
> +    public TimetableResponse createTimeTables(Integer userId, TimeTableCreateRequest request) {
### C
👀 
```suggestion
    public TimetableResponse createTimetables(Integer userId, TimeTableCreateRequest request) {
```

2024-06-17 02:10 UTC, daheeParkk commented on src/main/java/in/koreatech/koin/domain/timetable/controller/TimetableController.java
>  public class TimetableController implements TimetableApi {
바꿔줘야 하는 부분이 어떤 게 있나요??

2024-06-17 02:10 UTC, daheeParkk approved these changes

2024-06-17 02:43 UTC, seongjae6751 approved these changes
리뷰 조금만 더 확인해주세요! 고생하셨습니다

2024-06-17 02:43 UTC, seongjae6751 commented on src/main/java/in/koreatech/koin/domain/timetable/dto/TimetableLectureResponse.java
> +    Integer timetableFrameId,
A
밑에도 id가 있는데 description을 그냥 id가 아니라 OOid와 같이 조금 더 자세하게 적어주면 좋을 것 같아요

2024-06-17 02:43 UTC, seongjae6751 commented on src/main/java/in/koreatech/koin/domain/timetable/repository/TimetableFrameRepository.java
> +}
C
상위 메서드 이름도 밑과 같이 ismain을 메서드 명에 포함시켜줘야 하지 않을까요?
getByUserIdAndSemesterIdAndIsMain

2024-06-17 14:36 UTC, kwoo28 commented on src/main/java/in/koreatech/koin/domain/timetable/controller/TimetableApi.java
> +    @PostMapping("/v2/timetables/lecture")
대문자로 바꾸겠습니다!

2024-06-17 14:36 UTC, kwoo28 commented on src/main/java/in/koreatech/koin/domain/timetable/repository/TimetableFrameRepository.java
> +}
그게 좋겠네요!

2024-06-17 14:36 UTC, kwoo28 commented on src/main/java/in/koreatech/koin/domain/timetable/dto/TimetableLectureResponse.java
> +    Integer timetableFrameId,
넵!

2024-06-19 10:34 UTC, duehee approved these changes
전체적으로 수정하시느라 고생 많으셨습니다..~!!!
수정사항 한 가지 적어놨으니 하나만 확인해주세요!

2024-06-19 10:34 UTC, duehee commented on src/main/java/in/koreatech/koin/domain/timetable/controller/TimetableApiV2.java
> +    @PutMapping("/v2/timetables/lecture")
### A
v2로 통일했군용👀 추가적으로 lecture를 붙이는 게 맞는 거 같네요!!

2024-06-19 10:34 UTC, duehee commented on src/main/java/in/koreatech/koin/domain/timetable/dto/TimetableLectureUpdateRequest.java
>      @Schema(description = "시간표 프레임 고유 번호", example = "1", requiredMode = REQUIRED)
### C 
수정한다면 여기 부분도 "시간표 프레임 고유 id"로 일관성 있게 저장하는 게 좋을 거 같아요!

2024-06-19 10:34 UTC, duehee commented on src/main/resources/db/migration/V21__add_timetable_lecture.sql
> -    class_name VARCHAR(255) NULL comment '수업 이름',
### A
flyway도 변경되었네요! 확인하겠습니다

2024-06-19 10:39 UTC, seongjae6751 commented on src/main/java/in/koreatech/koin/domain/timetable/controller/TimetableApiV2.java
> +    @PutMapping("/v2/timetables/lecture")
저희 안 붙이기로 얘기되었던 것 아닌가요?https://docs.google.com/document/d/1y66EwEENjK62KabSVPDIbb7fqOiGrFWoRxFTgAhTXYA/edit

2024-06-19 10:49 UTC, merged