feat : GET /lectures id 반환 값 추가, PUT /timetables 수정, PUT /v2/timetables 추가
BCSDLab/KOIN_API_V2 pull request #608
Opened 2024-06-16 13:26 UTC by duehee

# 🔥 연관 이슈

- 연관 이슈는 #594를 참고해주세요.
- 기존 API 반환 값 추가, 기존 API의 수정, 새로운 API의 구현을 진행했습니다.

# 🚀 작업 내용

1. GET /lectures의 id 반환값을 추가했습니다.
- 반환하는 값에 없어서.. 추가했습니다.

2. PUT /timetables를 새로운 timetable_lecture 테이블에 맞도록 수정했습니다.
- 입력하는 값은 동일, 값 저장이 timetable이 아닌 timetable_lecture에 저장되도록 했습니다.
- 가능한 것은 현재 isMain이 true인, 존재하는 시간표에만 적용 가능합니다.

3. PUT /v2/timetables를 구현했습니다.
- 입력하는 값이 timetable_lecture에 맞추어 간소화된 Request를 가집니다.
- timetable_frame의 id를 이용하여 맞는 시간표에 저장하도록 했습니다.

아래는 각 2번과 3번을 이용하여 저장한 DB의 모습입니다. 사용한 테이블은 timetable_lecture입니다.
<img width="910" alt="Pasted Graphic 15" src="https://github.com/BCSDLab/KOIN_API_V2/assets/149302959/bd102e1f-4e95-4fc0-9e73-983086c70996">
<img width="907" alt="Pasted Graphic 16" src="https://github.com/BCSDLab/KOIN_API_V2/assets/149302959/f711dd44-eaa5-418c-8794-f6167ea3f751">

# 💬 리뷰 중점사항
작업하면서 기존 사용하던 GET / POST의 Response 값이 일치하지 않아 오류 발생, 코드드 주석처리 해놨습니다.
원경님 코드랑 합쳐지면 아마 문제 없을 것 같아서, 저는 주석처리 해놨습니다..
추가적으로 원래는 예정에 없던 버저닝을 구현했는데, 하다보니 Request 값도 달라져서 작성하는 게 맞다고 생각했습니다.

2024-06-16 19:56 UTC, seongjae6751 requested changes
깔끔하게 잘 구현하셨네요! 고생 많으셨습니다

2024-06-16 19:56 UTC, seongjae6751 commented on src/main/java/in/koreatech/koin/domain/timetable/model/TimetableLecture.java
> +}
A
entity메소드 에서 파라미터로 dto를 받는 것이 바람직한 가에 대해 생각해보면 좋을 것 같네요

+ 참고자료: https://www.inflearn.com/questions/584467/entity-%EB%A9%94%EC%86%8C%EB%93%9C-%ED%8C%8C%EB%9D%BC%EB%AF%B8%ED%84%B0%EB%A1%9C-dto%EB%A5%BC-%EB%B0%9B%EB%8A%94-%EA%B2%83-%EA%B4%9C%EC%B0%AE%EC%9D%84%EA%B9%8C%EC%9A%94

2024-06-16 19:56 UTC, seongjae6751 commented on src/main/java/in/koreatech/koin/domain/timetable/service/TimetableService.java
> +            timetableLectureRepository.save(timetableLecture);
R
커스텀 시간표가 아닌 강의 id와 timetableFrame id만 참조하고 있는 timeteble은 update를 지원하면 안 되지 않나요?

2024-06-16 19:56 UTC, seongjae6751 commented on src/main/java/in/koreatech/koin/domain/timetable/model/TimetableLecture.java
> +        this.classTime = request.classTime().toString();
R
classtime이 not requried이던데 검사 없이 toString을 하면 npe가 발생할 수도 있지 않을까요

2024-06-17 02:51 UTC, daheeParkk approved these changes
수고하셨습니다! 👍🏻👍🏻

2024-06-17 02:51 UTC, daheeParkk commented on src/main/java/in/koreatech/koin/domain/timetable/controller/TimetableApi.java
> +    */
### C

`TimetableResponse`에서 `regularNumber`의 
Schema name이 `과목코드 -> 수강정원`으로 바뀌어서 두 api를 주석 처리한 건가요?

2024-06-17 02:51 UTC, daheeParkk commented on src/main/java/in/koreatech/koin/domain/timetable/service/TimetableService.java
> +        return TimetableResponse.of(timetableLectures, timetableFrame, grades, totalGrades);
### A
getTimetableResponse()는 겹쳐서 나중에 통일해야겠네요

2024-06-17 06:52 UTC, kwoo28 requested changes
수고 많으셨습니다!

2024-06-17 06:52 UTC, kwoo28 commented on src/main/java/in/koreatech/koin/domain/timetable/dto/TimetableLectureUpdateRequest.java
> +        List<Integer> classTime,
```suggestion
        @Schema(description = "강의 이름", example = "운영체제", requiredMode = REQUIRED)
        String classTitle,

        @Schema(description = "강의 시간", example = "[210, 211]", requiredMode = REQUIRED)
        List<Integer> classTime,
```
로 해야할것같습니다!

2024-06-17 06:52 UTC, kwoo28 commented on src/main/java/in/koreatech/koin/domain/timetable/exception/TimetableFrameNotFoundException.java
> +    private static final String DEFAULT_MESSAGE = "존재하지 않는 시간표 프레임입니다.";
```suggestion
public class TimetableFrameNotFoundException extends DataNotFoundException {

    private static final String DEFAULT_MESSAGE = "존재하지 않는 시간표 프레임입니다.";
```

2024-06-17 12:25 UTC, duehee commented on src/main/java/in/koreatech/koin/domain/timetable/model/TimetableLecture.java
> +        this.classTime = request.classTime().toString();
앗 이건 아래서 나온 내용이라 REQUIRED로 바꿔야겠네요

2024-06-17 12:26 UTC, duehee commented on src/main/java/in/koreatech/koin/domain/timetable/controller/TimetableApi.java
> +    */
기존에 사용하던 Response가 오류나서 다 주석처리했습니다
원경님이 API 지우신거랑 동일한 내용입니당 ㅎ..

2024-06-17 12:49 UTC, duehee commented on src/main/java/in/koreatech/koin/domain/timetable/service/TimetableService.java
> +            timetableLectureRepository.save(timetableLecture);
지우는 게 맞을 것 같네요!

2024-06-17 15:48 UTC, seongjae6751 requested changes

2024-06-17 15:48 UTC, seongjae6751 commented on src/main/java/in/koreatech/koin/domain/timetable/dto/TimetableLectureUpdateRequest.java
> +        List<Integer> classTime,
C
여기를 required로 바꾸는게 맞나요?
커스텀 시간표가 아닌 그냥 강의에서 가져오는 시간표들은 title과 time을 안 갖고 요청 하지 않나요

2024-06-17 15:52 UTC, seongjae6751 commented on src/main/java/in/koreatech/koin/domain/timetable/dto/TimetableLectureUpdateRequest.java
> +        List<Integer> classTime,
아 기존꺼는 update를 지원안하게 되면 상관 없겠네요

2024-06-19 10:36 UTC, closed without merging

2024-06-19 10:37 UTC, duehee commented
원경님 PR이랑 합쳐서 작업 완료, PR 닫았습니다