feat: new timetable api 구현
BCSDLab/KOIN_API_V2 pull request #615
Opened 2024-06-20 08:24 UTC by daheeParkk

# 🔥 연관 이슈

# 🚀 작업 내용

timetables 테이블을 timetable_frame, timetable_lecture로 구분하였습니다.
기존 api도 사용해야 하므로 기존 api를 변경된 테이블에 맞게 로직을 수정하였고,
추가적인 api도 구현하였습니다.

## 테이블을 변경한 이유
![image](https://github.com/BCSDLab/KOIN_API_V2/assets/106418303/0275dabc-e5cd-4530-8329-5837cd2139b6)
- 상황 & 명칭 설명
  - 커스텀 시간표를 기획하면서 한 학기에 예비 수강 신청 시간표나 커스텀 시간표를 따로 넣을 수 있으면 좋을 것 같았습니다.
  - 위의 이미지에서 변경된 시간표 이미지의 왼쪽에 1안, 2안이라 써있는 부분 하나하나를 timetable_frame으로 뒀습니다.
  - 한 개의 timetable_frame 안에 생기는 강의는 timetable_lecture입니다.
- 기존
  - 한 학기에 한 개의 시간표
- 새로운 기획
  - 한 학기에 여러 개의 시간표 
 

## 변경된 테이블 구조
![image](https://github.com/BCSDLab/KOIN_API_V2/assets/106418303/66489030-6c51-45b0-9963-5d341517ed1e)
- 변경 전 테이블
  - timetables 테이블에 강의 정보(lecture 테이블과 동일한 내용)가 모두 있습니다.
- 변경 후 테이블
  - timetable_lecture 
    - lecture와 동일한 내용을 가지는 대신 해당하는 lecture의 id를 가지고 있음 
  - timetable_frame
    - 한 학기에서 여러 개의 시간표를 갖기 위한 테이블
  
## 작업한 api
### 기존 api
바뀐 테이블에 맞게 로직 수정
- GET timetables
- POST timetables
- PUT timetables
- DELETE timetables
- GET lectures
- GET semesters/check

### 추가 api
- POST v2/timetables/frame
  - 시간표 프레임 추가

- GET v2/timetables/frame
  - 시간표 프레임 조회

- PUT v2/timetables/frame
  - 시간표 프레임 수정

- DELETE v2/timetables/frame
  - 시간표 프레임 삭제

- POST v2/timetables/lectures
  - 시간표 강의 정보 추가

- GET v2/timetables/lectures
  - 시간표 강의 정보 조회

- PUT v2/timetables/lectures
  - 시간표 강의 정보 수정

- DELETE v2/timetables/lectures/{id}
  - 시간표 강의 정보 삭제

# 💬 리뷰 중점사항
- timetableV2 패키지를 새로 팠습니다. 
- 기존 timetable api는 삭제하지 않고 남겨뒀습니다.
  - 아직 기존 api를 사용하는 사용자들이 있음
- pr 코드가 많이 길어졌습니다ㅠㅠ  양해 부탁드립니다..

2024-06-28 02:25 UTC, 20HyeonsuLee requested changes
리뷰 남겼습니다! 눈 빠지는줄알았어요... 리뷰 확인해주세요~

2024-06-28 02:25 UTC, 20HyeonsuLee commented on src/main/java/in/koreatech/koin/domain/timetableV2/service/TimetableServiceV2.java
> +                timetableLectureRepositoryV2.save(timetableLecture);
# C
이런 코드는 어떨까요?
```suggestion
Lecture lecture = timetableLectureRequest.lectureId() == null? null lectureRepositoryV2.getLectureById(timetableLectureRequest.lectureId());
            TimetableLecture timetableLecture = timetableLectureRequest.toTimetableLecture(timetableFrame, lecture);
            timetableLectureRepositoryV2.save(timetableLecture);
```

2024-06-28 02:25 UTC, 20HyeonsuLee commented on src/main/java/in/koreatech/koin/domain/timetableV2/service/TimetableServiceV2.java
> +                timetableLecture.update(timetableRequest);
# R
dto가 eneity를 침범하고 있어요~ 필드를 하나씩 넘겨주는게 좋아보입니다

2024-06-28 02:25 UTC, 20HyeonsuLee commented on src/main/java/in/koreatech/koin/domain/timetableV2/service/TimetableServiceV2.java
> +                timetableLectureRepositoryV2.save(timetableLecture);
# C
save를 해주는 이유가 무엇일까요?

2024-06-28 02:25 UTC, 20HyeonsuLee commented on src/main/java/in/koreatech/koin/domain/timetableV2/service/TimetableServiceV2.java
> +            timetableFrame.getId());
# C
위에서 get한 TimetableFrame을 통해 알 수 있는데 다시 조회한 이유가 있을까요?

2024-06-28 02:25 UTC, 20HyeonsuLee commented on src/main/java/in/koreatech/koin/domain/timetableV2/service/TimetableServiceV2.java
> +        TimetableFrame frame = timetableFrameRepositoryV2.getById(timetableFrameId);
# C
TimetableFrame만 조회하면 List<TimetableLecture>도 같이 알 수 있을것같아요!
```suggestion
        TimetableFrame frame = timetableFrameRepositoryV2.getById(timetableFrameId);
```

2024-06-28 02:25 UTC, 20HyeonsuLee commented on src/main/java/in/koreatech/koin/domain/timetableV2/service/TimetableServiceV2.java
> +        TimetableFrame frame = timetableFrameRepositoryV2.getById(timetableLecture.getTimetableFrame().getId());
# C
TImetableFrame을 다시 조회한 이유가 있을까요?

2024-06-28 02:25 UTC, 20HyeonsuLee commented on src/main/java/in/koreatech/koin/domain/timetableV2/controller/TimetableControllerV2.java
> +        return ResponseEntity.ok().build();
# C
NO_CONTENT를 반환해야하지 않을까 싶습니다!

2024-06-28 02:25 UTC, 20HyeonsuLee commented on src/main/java/in/koreatech/koin/domain/timetableV2/service/TimetableServiceV2.java
> +    private TimetableLectureResponse getTimetableLectureResponse(Integer userId, TimetableFrame timetableFrame,
# R
라인 정리 해주세요~

2024-06-28 05:14 UTC, seongjae6751 commented on src/main/java/in/koreatech/koin/domain/timetableV2/model/TimetableFrame.java
> +    private Semester semester;
귀한 시간 내서 리뷰 남겨주셔서 정말 감사합니다!
우선 semester는 koin_batch로 현재 학교 강의 목록 추가할때(시간표 업데이트 할때)
추가되게 되어있어요 따로 로직상 추가하는 기능을 제공하지는 않고 있습니다.

semester entity에 string semester는 유니크 제약 조건이 현재 걸려 있는데 유니크 속성이 빠져있다는 것이 어떤 말씀이신지는 조금 더 자세히 설명해주실 수 있을까요??

2024-06-28 05:15 UTC, seongjae6751 commented on src/main/java/in/koreatech/koin/domain/timetableV2/model/TimetableFrame.java
> +    private boolean isDeleted = false;
헉 그러네요 수정 하도록 하겠습니다

2024-06-28 05:18 UTC, seongjae6751 commented on src/main/java/in/koreatech/koin/domain/timetableV2/model/TimetableFrame.java
> +        boolean isDeleted
와우 꼼꼼하시네요 Boolean isMain말씀하는 것 맞으실까요?
수정하도록 하겠습니다!

2024-06-28 05:24 UTC, seongjae6751 commented on src/main/java/in/koreatech/koin/domain/timetableV2/repository/SemesterRepositoryV2.java
> +    List<Semester> findAllByOrderBySemesterDesc();
꼼꼼함 아주 좋습니다 👍

2024-06-28 05:26 UTC, seongjae6751 commented on src/main/java/in/koreatech/koin/domain/timetableV2/service/TimetableServiceV2.java
> +        TimetableFrame timeTableFrame = request.toTimetablesFrame(user, semester, "시간표" + currentFrameCount, isMain);
맞습니당

2024-06-28 05:29 UTC, seongjae6751 commented on src/main/java/in/koreatech/koin/domain/timetableV2/model/TimetableFrame.java
> +@Where(clause = "is_deleted=0")
db에 isdeleted=false인 데이터가 많아서 우선 넣었는데 
확실히 어떻게 할지 더 논의의 필요성이 있을 수도 있을 것 같네요

2024-06-28 05:45 UTC, duehee commented on src/main/java/in/koreatech/koin/domain/timetableV2/service/TimetableServiceV2.java
> +        TimetableFrameUpdateRequest timetableFrameUpdateRequest, Integer userId) {
잘 되어 있는 것 같은데, 어떤 부분을 분리하면 좋을지 말씀해주시면 감사하겠습니다!!

2024-06-28 05:47 UTC, duehee commented on src/main/java/in/koreatech/koin/domain/timetableV2/service/TimetableServiceV2.java
> +        boolean isMain = (currentFrameCount == 1);
저희가 시간표는 1부터 시작해서, +1을 하는 부분이 더 직관적인 것 같습니다!

2024-06-28 05:48 UTC, duehee commented on src/main/java/in/koreatech/koin/domain/timetableV2/service/TimetableServiceV2.java
> +        timeTableFrame.updateTimetableFrame(semester, timetableFrameUpdateRequest.name(), isMain);
메인으로 사용하는 시간표 지정이 필요해서, 기존에 사용하는 코드를 그대로 사용하는 것이 좋다고 생각했습니다!
어떻게 생각하시나요?

2024-06-28 06:02 UTC, duehee commented on src/main/java/in/koreatech/koin/domain/timetableV2/service/TimetableServiceV2.java
> +                    findFirstByUserIdAndSemesterIdAndIsMainFalseOrderByCreatedAtAsc(userId,
변경 완

2024-06-28 06:15 UTC, duehee commented on src/main/java/in/koreatech/koin/domain/timetableV2/service/TimetableServiceV2.java
> +                timetableLectureRepositoryV2.save(timetableLecture);
삭제했어요!

2024-06-28 06:18 UTC, duehee commented on src/main/java/in/koreatech/koin/domain/timetableV2/service/TimetableServiceV2.java
> +            timetableFrame.getId());
TimetableFrame을 가져온다고 해서, 강의 내용을 가져올 수 없어서 추가적으로 id를 통해 TimetableLecture를 모두 가져올 수 있도록 했습니다

2024-06-28 06:22 UTC, duehee commented on src/main/java/in/koreatech/koin/domain/timetableV2/service/TimetableServiceV2.java
> +            timetableFrame.getId());
헐 그렇네요😵

2024-06-28 06:23 UTC, duehee commented on src/main/java/in/koreatech/koin/domain/timetableV2/service/TimetableServiceV2.java
> +        TimetableFrame frame = timetableFrameRepositoryV2.getById(timetableLecture.getTimetableFrame().getId());
수정했습니다!!

2024-06-28 08:05 UTC, 20HyeonsuLee commented on src/main/java/in/koreatech/koin/domain/timetableV2/model/TimetableFrame.java
> +    private Semester semester;
앗 잘못봤네요 확인했습니다~!

2024-06-28 08:06 UTC, 20HyeonsuLee commented on src/main/java/in/koreatech/koin/domain/timetableV2/model/TimetableFrame.java
> +@Where(clause = "is_deleted=0")
isDelete가 꼭 필요한 상황이 아니라면 없는게 좋다고 생각합니다~!

2024-06-28 08:12 UTC, 20HyeonsuLee commented on src/main/java/in/koreatech/koin/domain/timetableV2/dto/TimetableFrameCreateRequest.java
> +    }
추가로 Entity가 DTO의 영역을 침범하고있다는 생각이 듭니다

2024-06-28 08:16 UTC, 20HyeonsuLee commented on src/main/java/in/koreatech/koin/domain/timetableV2/service/TimetableServiceV2.java
> +        boolean isMain = (currentFrameCount == 1);
특정 유저의 시간표가 없으면, 지금 만드는 시간표가 그 유저의 메인시간표이다. 라는 흐름이 조금 더 자연스럽지 않나요..?
다른 도메인의 사람이 처음 코드를 봤을 때 시간표가 1부터 시작하는걸 알 수 있을지, `+1`의 의미가 무엇일지 파악하기는 쉽지 않을것이라고 생각합니다(저 역시도 그랬고요)

2024-06-28 08:20 UTC, 20HyeonsuLee commented on src/main/java/in/koreatech/koin/domain/timetableV2/service/TimetableServiceV2.java
> +        timeTableFrame.updateTimetableFrame(semester, timetableFrameUpdateRequest.name(), isMain);
DTO의 isMain이 NotNull이고 기존의 코드는 `updateTimetableFrame`에서 하는 일을 한번 더하고 있지 않나요?

2024-06-28 08:23 UTC, 20HyeonsuLee commented on src/main/java/in/koreatech/koin/domain/timetableV2/service/TimetableServiceV2.java
> +        timeTableFrame.updateTimetableFrame(semester, timetableFrameUpdateRequest.name(), isMain);
그리고, semester를 인자로 넘겨줄 필요가 있나요?

2024-06-28 08:25 UTC, 20HyeonsuLee commented on src/main/java/in/koreatech/koin/domain/timetableV2/service/TimetableServiceV2.java
> +        boolean isMain = (currentFrameCount == 1);
그리고 괄호는 필요없을것같습니다!
```suggestion
        boolean isMain = currentFrameCount == 1;
```

2024-06-29 03:06 UTC, 20HyeonsuLee approved these changes

2024-06-29 03:10 UTC, seongjae6751 approved these changes
모두 고생 많았습니다~

2024-06-29 03:55 UTC, merged