feat : coop_id 관련 flyway 추가
BCSDLab/KOIN_API_V2 pull request #618
Opened 2024-06-21 03:38 UTC by duehee

# 🔥 연관 이슈

- close #617 

# 🚀 작업 내용

1. coop 테이블의 coop_id 값에 NOT NULL 처리 및 user_id 기준 email 값이 들어가도록 했습니다.

# 💬 리뷰 중점사항
앞 timetable flyway 추가 때문에 어떻게 할까 헀는데, 빠르게 선행 가능 할 작업 같아서 번호를 땡겼습니다.

2024-06-21 04:34 UTC, songsunkook requested changes
빠른 적용 감사합니다. 코멘트 하나만 확인해주세요

2024-06-21 04:34 UTC, songsunkook commented on src/main/resources/db/migration/V19__update_coop_id_and_change_not_null.sql
### R

정말 사소한 건데, 하나는 DDL, 하나는 DML이다 보니 하나의 파일에 함께 넣기는 조금 애매한 것 같아요.
두 쿼리를 별도의 파일로 분리하면 좋을 것 같습니다!

2024-06-21 07:26 UTC, duehee commented on src/main/resources/db/migration/V19__update_coop_id_and_change_not_null.sql
의견 반영하겠습니다 :D

2024-06-22 04:16 UTC, songsunkook approved these changes
👍 고생하셨습니다

2024-06-22 04:21 UTC, seongjae6751 approved these changes
고생하셨습니다!

2024-06-22 04:36 UTC, merged