feat: 어드민 사장님 권한 허용
BCSDLab/KOIN_API_V2 pull request #621
Opened 2024-06-22 08:16 UTC by kwoo28

# 🔥 연관 이슈

- close #82

# 🚀 작업 내용

1. 사장님 인증권한을 허용하는 과정에서 아래와 같이 권한을 변경했습니다. 
IsAuthed=true
GrantShop=true

# 💬 리뷰 중점사항
레거시 코인 로직에서 불필요한 조건문과 ownershop 삭제하는 과정을 생략했습니다.

2024-06-23 07:05 UTC, 20HyeonsuLee requested changes
수고하셨습니디! 코멘트 하나만 확인해주세요~!

2024-06-23 07:05 UTC, 20HyeonsuLee commented on src/main/java/in/koreatech/koin/admin/user/service/AdminUserService.java
> +    }
# R
사장님 권한 승인 관련 코드가 맞을까요?
사장님 권한을 승인할 때 상점 할당도 해줘야 할 것 같아요!

사장님 회원가입, 승인 플로우

1. 사장님이 회원가입 을 진행한다.
    - 이 때 본인의 상점을 선택할 수 있다(본인의 상점이 있다면 그 상점에 계정을 연결)
    - `/owner/register`, `/owner/register/phone`API를 보면 `shop_id`필드가 있는데 이 필드가 null이면 상점 연결을 안하고, null이 아닌 유효한 shop_id가 있다면 그 상점에 해당 오너를 연결해줌
    - `/owner/register`, `/owner/register/phone`이 두 api는 redis에 owner_id, shop_id필드를 임시로 저장함
2. 어드민이 오너 회원가입을 승인한다.
     - `/owner/register`, `/owner/register/phone`api를 통해 저장된 redis의 owner_id, shop_id필드를 통해 승인을 진행함
     - 승인은 `grant_shop = true`로 승인한다.
     - 이때 redis의 shop_id를 확인해서 상점도 연결해줘야 한다.(shops테이블의 owner_id를 할당해주면 됨)

2024-06-23 09:56 UTC, kwoo28 commented on src/main/java/in/koreatech/koin/admin/user/service/AdminUserService.java
> +    }
사장님 회원가입 및 승인 플로우가 이런 형식이였군요..! 제가 착각했네요. 수정하겠습니다!

2024-06-23 10:59 UTC, kwoo28 commented on src/main/java/in/koreatech/koin/admin/user/service/AdminUserService.java
> +    }
근데 현재 OwnerShop의 TimeToLive가 2시간으로 되어있는데, 그러면 2시간 지나면 사라져서 연결할 방법이 없지 않나요??

2024-06-25 16:55 UTC, 20HyeonsuLee commented on src/main/java/in/koreatech/koin/admin/user/service/AdminUserService.java
> +    }
흠 그러게요 이 코드에 대해 아는사람한테 물어봐야겠네요

2024-06-25 16:57 UTC, 20HyeonsuLee requested changes
추가로 이슈95번은 구현하지 않으셨는데 클라이언트가 이 api를 물고있을거라서 회원 소프트딜리트를 안하기로 바뀌었어도 api는 작성해주셔야 할 것 같습니다!
(비즈니스로직이 없더라도 api자체는 있어야할거같음)

2024-06-26 06:55 UTC, duehee requested changes
고생하셨어요~ 
지금 보니 API가 엄청 많네요 ㄷㄷ 한 번 확인해주세요!

2024-06-26 06:55 UTC, duehee commented on src/main/java/in/koreatech/koin/admin/user/controller/AdminUserController.java
> +    @PostMapping("/admin/user/login")
### C
```suggestion
    @PostMapping("/admin/login")
```
다른 로그인 API들처럼 통일하는 게 좋을 거 같아요

2024-06-26 06:55 UTC, duehee commented on src/main/java/in/koreatech/koin/admin/user/dto/AdminStudentsResponse.java
> +    public static AdminStudentsResponse of(Page<Student> studentsPage) {
### C
`of`보단 `from`이 맞을 거 같은데 어떻게 생각하세요?

2024-06-26 06:55 UTC, duehee commented on src/main/java/in/koreatech/koin/admin/user/repository/AdminStudentRepository.java
> +    @Query(
### A
텍스트 블럭 짱 깔끔하네요😄

2024-06-26 06:55 UTC, duehee commented on src/main/java/in/koreatech/koin/admin/user/service/AdminUserService.java
> +        /* 어드민 권한이 없으면 없는 회원으로 간주 */
### C
권한이 없는 것으로 간주하고 예외를 처리 하는 것은 어떤가요?

2024-06-26 07:00 UTC, kwoo28 commented on src/main/java/in/koreatech/koin/admin/user/controller/AdminUserController.java
> +    @PostMapping("/admin/user/login")
현재 어드민 로그인 API는 "/admin/user/login"을 이용하고 있고, 어드민 API에선 대부분 /admin/user를 이용하고 있어서 위와같이 코드를 작성했습니다!

2024-06-26 07:00 UTC, kwoo28 commented on src/main/java/in/koreatech/koin/admin/user/dto/AdminStudentsResponse.java
> +    public static AdminStudentsResponse of(Page<Student> studentsPage) {
그게 좋겠네요 ㅎ

2024-06-26 07:04 UTC, kwoo28 commented on src/main/java/in/koreatech/koin/admin/user/service/AdminUserService.java
> +        /* 어드민 권한이 없으면 없는 회원으로 간주 */
제가 한건 아니고 성재형이 한거긴한데 어드민은 기존 레거시 API를 유지하는 방향인것같아서 저도 기존과 똑같은 로직으로 구성하는게 나을것같다는 생각이 듭니다..!

2024-06-26 07:21 UTC, 20HyeonsuLee requested changes

2024-06-26 07:21 UTC, 20HyeonsuLee commented on src/main/java/in/koreatech/koin/admin/user/service/AdminUserService.java
> +            Shop shop = adminShopRepository.getById(shopId);
# R
shopId에 null이 들어올 수도 있는데 null일 경우 로직이 필요해보입니다!

2024-06-26 07:30 UTC, duehee commented on src/main/java/in/koreatech/koin/admin/user/controller/AdminUserController.java
> +    @PostMapping("/admin/user/login")
레거시가 그렇다면 따르는 게 맞는 것 같습니당🙆‍♂️

2024-06-26 07:32 UTC, kwoo28 commented on src/main/java/in/koreatech/koin/admin/user/service/AdminUserService.java
> +            Shop shop = adminShopRepository.getById(shopId);
<img width="541" alt="image" src="https://github.com/BCSDLab/KOIN_API_V2/assets/148550522/a9725e77-83e1-44d8-baa7-9184ff0c5358">

사장님 회원가입 로직에서 이미 shopId가 null값인지 확인후 redis에 저장하는데, 인증과정에서 shopId에 null 체크는 불필요하지않을까요?

2024-06-26 07:34 UTC, kwoo28 commented on src/main/java/in/koreatech/koin/admin/user/service/AdminUserService.java
> +            Shop shop = adminShopRepository.getById(shopId);
아 상점이 없는경우도 있었군요..수정하겠습니다

2024-06-26 07:34 UTC, duehee commented on src/main/java/in/koreatech/koin/admin/user/service/AdminUserService.java
> +        /* 어드민 권한이 없으면 없는 회원으로 간주 */
그렇게 하고 있었군요..! 확인했습니다

2024-06-26 07:36 UTC, 20HyeonsuLee requested changes

2024-06-26 07:36 UTC, 20HyeonsuLee commented on src/main/java/in/koreatech/koin/admin/user/service/AdminUserService.java
> +        owner.setGrantShop(true);
# R
`Optional<OwnerShop> ownerShop = adminOwnerShopRedisRepository.findById(id);`
Reids에 값이 없을 경우도 생각해줘야할것같아요!

2024-06-26 07:36 UTC, 20HyeonsuLee commented on src/main/java/in/koreatech/koin/admin/user/service/AdminUserService.java
> +        adminUserRepository.save(user);
# C
save호출 안해도 변경감지로 DB반영이 될것같습니다!

2024-06-26 07:37 UTC, kwoo28 commented on src/main/java/in/koreatech/koin/admin/user/service/AdminUserService.java
> +        owner.setGrantShop(true);
아 없는경우는 GrantShop을 true로 해주면 안되겠군요.!

2024-06-26 07:41 UTC, kwoo28 commented on src/main/java/in/koreatech/koin/admin/user/service/AdminUserService.java
> +        adminUserRepository.save(user);
넵1

2024-06-26 07:49 UTC, duehee approved these changes
의견 반영해주셔서 감사합니당 :D
고생하셨어요~

2024-06-26 07:56 UTC, 20HyeonsuLee requested changes

2024-06-26 07:56 UTC, 20HyeonsuLee commented on src/main/java/in/koreatech/koin/admin/user/service/AdminUserService.java
> +        String accessToken = jwtProvider.createToken(user);
# C
Redis에 있는 admin의 토큰은 업데이트해주지 않아도 될까요?

2024-06-26 07:56 UTC, 20HyeonsuLee commented on src/main/java/in/koreatech/koin/admin/user/dto/AdminOwnerUpdateRequest.java
> +}
# R
스웨거 보니 들어가야할 필드가 더 있던데 확인 부탁드려요!
<img width="883" alt="image" src="https://github.com/BCSDLab/KOIN_API_V2/assets/127578418/4af4bc2e-8067-4638-99c4-562337030d34">

2024-06-26 08:29 UTC, kwoo28 commented on src/main/java/in/koreatech/koin/admin/user/service/AdminUserService.java
> +        String accessToken = jwtProvider.createToken(user);
혹시 어떤 token을 말씀하시는건가요?? 현재 있는 메서드는 accessToken을 발행해주는 역할이고, redis에 있는 refreshToken같은 경우는 로그인할때만 갱신되고 고정적이지 않나요??

2024-06-26 08:29 UTC, kwoo28 commented on src/main/java/in/koreatech/koin/admin/user/dto/AdminOwnerUpdateRequest.java
> +}
넵 수정했습니다!

2024-06-26 08:42 UTC, 20HyeonsuLee commented on src/main/java/in/koreatech/koin/admin/user/service/AdminUserService.java
> +        String accessToken = jwtProvider.createToken(user);
redis에 있는 토큰 만료일이 14일이라서 업데이트 해줘야하나? 싶었습니다

2024-06-26 08:45 UTC, kwoo28 commented on src/main/java/in/koreatech/koin/admin/user/service/AdminUserService.java
> +        String accessToken = jwtProvider.createToken(user);
그러면 로그인 하지않아도 무한적으로 갱신되어 보안에 취약하게 될것같은데 괜찮을까요?

2024-06-26 09:31 UTC, 20HyeonsuLee commented on src/main/java/in/koreatech/koin/admin/user/service/AdminUserService.java
> +        String accessToken = jwtProvider.createToken(user);
그렇네요 확인했습니다~

2024-06-26 11:00 UTC, 20HyeonsuLee approved these changes

2024-06-26 11:00 UTC, merged