feat: 어드민권한 상점, 카테고리 api작성
BCSDLab/KOIN_API_V2 pull request #627
Opened 2024-06-25 01:37 UTC by BaeJinho4028

# 🔥 연관 이슈

- close #51
- close #52 
- close #53 
- close #54 
- close #55 
- close #56 
- close #57 
- close #58 
- close #59 
- close #60 
- close #61 

# 🚀 작업 내용

1. 어드민권한 상점, 카테고리 api작성했습니다.
2. 레거시, 비슷한 코드 참고하여 작성하였습니다.

# 💬 리뷰 중점사항
1. 페이지네이션 처음 써봐서 잘 쓴건지 걱정되네요
2. 어드민은 softDelete 된것도 조회 가능해야해서 @Where(clause = "is_deleted=0") 를 제거했고, 유저들이 getAll 할때 softDelete된 것들은 불러와지지 않도록 작성했습니다.

2024-06-25 16:52 UTC, 20HyeonsuLee requested changes
10개나 만들시다니..  수고하셨습니다! 코멘트 남겼습니다!

2024-06-25 16:52 UTC, 20HyeonsuLee commented on src/main/java/in/koreatech/koin/admin/shop/controller/AdminShopController.java
> +        @RequestBody AdminCreateShopRequest adminCreateShopRequest,
# R
`@Valid`어노테이션이 필요합니다! 이 함수 말고도 @RequestBody가 있는 함수들 `@Valid`붙여주세요!

2024-06-25 16:52 UTC, 20HyeonsuLee commented on src/main/java/in/koreatech/koin/admin/shop/dto/AdminCreateShopRequest.java
> +    @UniqueId(message = "카테고리 ID는 중복될 수 없습니다.")
# A
내가 만든 어노테이션 잘 쓰고있군 ㅎㅎㅎㅎ

2024-06-25 16:52 UTC, 20HyeonsuLee commented on src/main/java/in/koreatech/koin/admin/shop/dto/AdminCreateShopRequest.java
> +    List<InnerShopOpen> open,
# A
생각해보니 이 필드는 항상 7개의 요일을 모두 입력 받아야합니다. 그래서 `Size=7`와 같은 어노테이션이 필요한데 기존 코드는 제한을 안걸어 뒀을거라.. 나중에 상점 관련해서 한번 수정해야겠군요. 일단 지금은 이대로 합시다!

2024-06-25 16:52 UTC, 20HyeonsuLee commented on src/main/java/in/koreatech/koin/admin/shop/dto/AdminCreateShopRequest.java
> +    @Schema(description = "요일별 휴무 여부 및 장사 시간", requiredMode = NOT_REQUIRED)
# R
여기도 `@Valid`를 달아줘야해요~
request dto에 존재하는 inner record에는 필드에도 `@Valid`어노테이션을 달아줘야한답니다~ 그래야 내부 record에도 적용이 됩니다!

2024-06-25 16:52 UTC, 20HyeonsuLee commented on src/main/java/in/koreatech/koin/admin/shop/dto/AdminCreateShopCategoryRequest.java
> +    @Schema(description = "이미지 URL", example = "https://static.koreatech.in/test.png", requiredMode = RequiredMode.REQUIRED)
# R
`@NotNull`또는 `@NotBlank`붙여줘야 할 것 같습니다!
(Put API도 동일)

참고
<img width="259" alt="image" src="https://github.com/BCSDLab/KOIN_API_V2/assets/127578418/2e48435e-5aa6-48e2-ade3-b7a5525f8720">

2024-06-25 16:52 UTC, 20HyeonsuLee commented on src/main/java/in/koreatech/koin/admin/shop/dto/AdminModifyShopRequest.java
> +        boolean closed,
# C
여기서는 원시타입 `boolean`을 사용한 이유가 있을까요?

2024-06-25 16:52 UTC, 20HyeonsuLee commented on src/main/java/in/koreatech/koin/domain/shop/model/Shop.java
> -@Where(clause = "is_deleted=0")
# R
`Shop`, `ShopCategory`에서 `@Where`절을 삭제하면 `ShopRepository`, `ShopCategoryRepository`에 있는 get, find관련된 메서드에 `isDeleted = false`관련 옵션을 추가해야합니다!
<img width="734" alt="image" src="https://github.com/BCSDLab/KOIN_API_V2/assets/127578418/7f1882e3-0a8f-4686-b89d-6df3c25bd7e0">
<img width="875" alt="image" src="https://github.com/BCSDLab/KOIN_API_V2/assets/127578418/742f2215-b772-4343-b000-8550b995093f">

2024-06-25 17:03 UTC, 20HyeonsuLee requested changes
ㅎㅎ 새로운거 발견

2024-06-25 17:03 UTC, 20HyeonsuLee commented on src/main/java/in/koreatech/koin/admin/shop/service/AdminShopService.java
> +        List<ShopCategory> Categories = adminShopCategoryRepository.findAllByIdIn(adminCreateShopRequest.categoryIds());
# R
변수명 소문자시작!
```suggestion
        List<ShopCategory> categories = adminShopCategoryRepository.findAllByIdIn(adminCreateShopRequest.categoryIds());
```

2024-06-26 08:22 UTC, BaeJinho4028 reviewed
피드백 반영하였고, where 관련해서는 충돌 해결하면서 반영하겠습니다.

2024-06-26 09:33 UTC, Choi-JJunho approved these changes

2024-06-26 09:57 UTC, johnny19991006 reviewed
아직 충동해결이 안되어 있어요~
해결되면 어푸르브 할게요!
(다들 왜 10개씩 만들어서 내눈을 혹사시키는가...)

2024-06-26 11:14 UTC, BaeJinho4028 commented
@20HyeonsuLee @johnny19991006 충돌 해결 완료했습니다~

2024-06-26 11:15 UTC, 20HyeonsuLee approved these changes

2024-06-26 11:16 UTC, merged