refactor :
BCSDLab/KOIN_API_V2 pull request #641
Opened 2024-06-26 15:27 UTC by Choon0414

# 🔥 연관 이슈

- close #

# 🚀 작업 내용

1. 버스 API Url 연결을 `httpUrlConnection`에서 `restTemplate`으로 수정했습니다.
   - 다른 API들은 모두 `restTemplate`을 사용해 통일성을 위해 수정했습니다.
2. Url 생성을 `StringBuilder`에서 `UriComponents`로 수정했습니다.
3. api 응답 받는 것을 `jsonObject`에서 `response`객로 수정했습니다.

# 💬 리뷰 중점사항

2024-07-02 00:49 UTC, ImTotem requested changes
`CityBusClient`, `CityBusRouteClient`에도 적용해주세요 🙏

2024-07-02 17:36 UTC, Choon0414 commented on src/test/java/in/koreatech/koin/acceptance/CircuitBreakerApiTest.java
> -                System.out.println("엥엥");
급하게 테스트 해본다는게 같이 올라갔네요ㅎㅎ..
시내버스 올리고 다시 요청할게요!

2024-07-22 15:39 UTC, dradnats1012 approved these changes
보기만 해도 예전의 악몽이 떠오르네요
고생하셨습니다!

2024-07-22 15:39 UTC, dradnats1012 commented on src/test/java/in/koreatech/koin/acceptance/CircuitBreakerApiTest.java
>              System.out.println(circuitBreaker.getState());
이것도 테스트용 같아요!

2024-07-22 15:42 UTC, songsunkook approved these changes
고생하셨습니다!

2024-07-22 19:39 UTC, Choon0414 commented on src/main/java/in/koreatech/koin/domain/bus/dto/CityBusApiResponse.java
`~BusApiResponse`는 클라이언트에게 반환되지 않고 Api 호출 -> 캐시 저장 사이에 전달용으로 만들어서 `@Schema`는 적용하지 않았습니다.
또 `restTemplate`이 필드명만 동일하면 자동으로 dto에 매핑해줘서 팩토리 메서드가 필요없었습니다.

2024-07-22 19:45 UTC, Choon0414 commented on src/test/java/in/koreatech/koin/acceptance/CircuitBreakerApiTest.java
>              System.out.println(circuitBreaker.getState());
수정했습니다!

2024-07-23 06:57 UTC, ImTotem approved these changes
늦어서 죄송합니다ㅠ

2024-07-23 06:57 UTC, merged