feat : 생협 운영시간 API 구현
BCSDLab/KOIN_API_V2 pull request #643
Opened 2024-06-26 15:46 UTC by Choon0414

# 🔥 연관 이슈

- close #

# 🚀 작업 내용

1. 생협 운영시간 API를 구현했습니다.
    - 생협의 각 매장별 정보를 조회합니다.
2. Admin 생협 운영시간 API를 구현했습니다.
    - 생협의 각 매장별 정보를 관리합니다.

# 💬 리뷰 중점사항

2024-07-02 04:37 UTC, dradnats1012 requested changes
몇가지 확인 부탁드립니당

2024-07-02 04:37 UTC, dradnats1012 commented on src/main/java/in/koreatech/koin/admin/coopShop/dto/AdminCoopShopResponse.java
> +    String remarks
### C
`remarks` 라는 변수명이 뭔가 알기 어려운것 같아요
보통 비고란에 휴무일만 나오면 아예 `restDay` 로 바꿔도 될것 같아요

2024-07-02 04:37 UTC, dradnats1012 commented on src/main/java/in/koreatech/koin/domain/coopshop/controller/CoopShopApi.java
> +    @GetMapping("/coop")
### A
`@RequestMapping("/coop")` 빼도 될것 같아요

2024-07-02 04:37 UTC, dradnats1012 commented on src/main/java/in/koreatech/koin/domain/coopshop/controller/CoopShopController.java
> +    @GetMapping("/coop")
### A
`@RequestMapping("/coop")` 빼도 될것 같아요

그런데 `CoopController`도 이렇게 빼놔서 두 컨트롤러를 분리하는게 맞나 궁금해요
`CoopController`는 식단쪽이긴한데 다른 분들 의견이 궁금해요

2024-07-02 04:37 UTC, dradnats1012 commented on src/main/resources/db/migration/V21__add_coop_shop_table.sql
이거 지금 플라이웨이에 파일 많이 생겨서 올리기전에 버전 확인하고 올려야할것 같아요

2024-07-02 05:24 UTC, ImTotem requested changes
수고하셨습니다!

2024-07-02 05:24 UTC, ImTotem commented on src/main/java/in/koreatech/koin/admin/coopShop/dto/AdminCoopShopResponse.java
> +    String remarks
휴무 뿐만 아니라 다른 특이사항들도 올 수 있어서 remakrs가 맞는거 같아요.

2024-07-02 05:24 UTC, ImTotem commented on src/main/java/in/koreatech/koin/domain/coopshop/service/CoopShopService.java
> +        return coopShopRepository.findAll().stream()
### C
이렇게 반환하면 isDeleted가 true인 값들도 반환되는거 아닌가요?

2024-07-02 07:25 UTC, songsunkook requested changes
늦었지만 리뷰 남겼습니다! 확인 부탁드려요~

2024-07-02 07:25 UTC, songsunkook commented on src/main/java/in/koreatech/koin/admin/coopShop/controller/AdminCoopShopController.java
> +    }
### A
페이징은 컨트롤러 파라미터단에서부터 쉽게 받을 수 있도록 제공했던 것 같은데 파라미터 네이밍같은게 어긋나나요? 사용하지 않은 이유가 있는지 궁금합니다.

2024-07-02 07:25 UTC, songsunkook commented on src/main/java/in/koreatech/koin/admin/coopShop/controller/AdminCoopShopController.java
> +public class AdminCoopShopController implements AdminCoopShopApi {
### C
admin api의 수요가 있었나요? 별도로 만든 이유가 궁금합니다.

2024-07-02 07:25 UTC, songsunkook commented on src/main/java/in/koreatech/koin/domain/coopshop/controller/CoopShopController.java
> +    @GetMapping("/coop")
사용처를 생각해보면 일반 사용자들이 학식당 정보를 조회하는 경우잖아요?
저는 `DiningContoller`로 넘기는 것이 적절해 보입니다.
`CoopController`는 영양사님께서 사용하시는 기능이 들어가는 게 좋아 보여요


+) 혹시 `CoopApi`에서 아래 부분 수정해주실 수 있나요?
<img width="545" alt="image" src="https://github.com/BCSDLab/KOIN_API_V2/assets/21010656/34eefead-b955-4b52-b782-0cadfd374833">

2024-07-02 07:25 UTC, songsunkook commented on src/main/java/in/koreatech/koin/domain/coopshop/model/CoopOpen.java
> +    public CoopOpen(
### C
private으로 수정해주세요!

2024-07-02 07:25 UTC, songsunkook commented on src/main/java/in/koreatech/koin/domain/coopshop/model/CoopShop.java
> +    private List<CoopOpen> coopOpens = new ArrayList<>();
### A
cascade를 ALL로 두지 않은 이유가 있는 건가요??

2024-07-02 07:25 UTC, songsunkook commented on src/main/java/in/koreatech/koin/domain/coopshop/model/CoopShop.java
> +    public CoopShop(
### A
private으로 바꿔주세요~

2024-07-02 18:00 UTC, Choon0414 commented on src/main/java/in/koreatech/koin/domain/coopshop/controller/CoopShopController.java
> +    @GetMapping("/coop")
학식당 정보도 있지만 생협의 여러 매장 정보 조회에 대한 API라 `Coop`이나 `Dining`이랑은 분리하는게 맞다고 생각합니다!
`coop`이 원래는 생협을 뜻하는 단어인데 영양사님 페이지에 써버려서.. 혹시 `/coopshop` 로 바꿔서 따로 유지하는건 어떻게 생각하시나요?

오너 부분은 수정할게용

2024-07-02 18:00 UTC, Choon0414 commented on src/main/java/in/koreatech/koin/domain/coopshop/controller/CoopShopApi.java
> +    @GetMapping("/coop")
수정하겠습니다!

2024-07-02 18:07 UTC, Choon0414 commented on src/main/java/in/koreatech/koin/admin/coopShop/controller/AdminCoopShopController.java
> +public class AdminCoopShopController implements AdminCoopShopApi {
이전 회의때 운영시간 관리를 어드민으로 하자는 의견이 나와서 만들었습니다!

2024-07-03 07:08 UTC, Choon0414 commented on src/main/java/in/koreatech/koin/domain/coopshop/service/CoopShopService.java
> +        return coopShopRepository.findAll().stream()
수정하겠습니다!

2024-07-09 09:07 UTC, Choon0414 commented on src/main/java/in/koreatech/koin/domain/coopshop/model/CoopShop.java
> +    private List<CoopOpen> coopOpens = new ArrayList<>();
사용하는 type들만 명시적으로 하려고 따로 적었습니다!

2024-07-09 12:49 UTC, Choon0414 commented on src/main/java/in/koreatech/koin/admin/coopShop/controller/AdminCoopShopController.java
> +    }
찾아보니 admin도 `Pageable`을 이용해서 구현할 수는 있는데
기존의 admin에서 인자들을 따로 받아 사용하는 이유는 `Criteria` 라는 클래스를 이용해 페이지나 표시 크기의 범위를 검증하는 단계를 추가하기 위함인 것 같습니다!
```
Criteria criteria = Criteria.of(page, limit, total);
```

```
public static Criteria of(Integer page, Integer limit, Integer total) {
        return new Criteria(validateAndCalculatePage(page, limit, total), validateAndCalculateLimit(limit));
    }
```

2024-07-13 11:39 UTC, dradnats1012 approved these changes
늦어서 죄송합니다 ㅠㅠ 
고생하셨습니다!

2024-07-13 11:45 UTC, ImTotem approved these changes
수고하셨습니다!!

2024-07-14 08:54 UTC, songsunkook approved these changes
리뷰를 아주 잘 반영해주셨네요..!!
큰 작업이었을 텐데 고생하셨습니다!!

2024-07-14 12:10 UTC, merged