Fix: 이모지 검증 추가
BCSDLab/KOIN_API_V2 pull request #651
Opened 2024-07-01 10:09 UTC by kwoo28

# 🔥 연관 이슈

- close #649

# 🚀 작업 내용

1. 기존 로그인시에 이메일에 이모지를 넣어 발생한 에러는 기존에 있던 이메일 형식 검증 어노테이션을 추가했습니다.

2. 이모지 검증 어노테이션을 추가하여 닉네임이나 이름같은 필드에 이모지를 넣을시 발생할 에러를 방지했습니다.

# 💬 리뷰 중점사항

2024-07-01 14:03 UTC, duehee requested changes
황당한 이슈..!
새로운 어노테이션 만드느라 수고하셨습니다~ 코멘트 한 번 확인해주세요

2024-07-01 14:03 UTC, duehee commented on src/main/java/in/koreatech/koin/global/validation/EmojiValidator.java
> +public class EmojiValidator implements ConstraintValidator<NotEmoji, String> {
### A
이모지 검증 로직이라니.. 이렇게 이모지를 넣어서 로그인을 시도하려는 사람은 처음봤네요 👀

2024-07-01 14:37 UTC, daheeParkk approved these changes
수고하셨습니다!

2024-07-02 09:15 UTC, kwoo28 commented on src/main/java/in/koreatech/koin/domain/user/dto/UserLoginRequest.java
> +    @Email(message = "이메일 형식을 지켜주세요. ${validatedValue}")
아 알겠습니다!

2024-07-02 09:16 UTC, kwoo28 commented on src/main/java/in/koreatech/koin/global/validation/EmojiValidator.java
> +public class EmojiValidator implements ConstraintValidator<NotEmoji, String> {
생각치도 못한 오류..

2024-07-03 01:56 UTC, duehee approved these changes
체크 완! 수고하셨습니당

2024-07-03 01:56 UTC, duehee commented on src/main/java/in/koreatech/koin/domain/user/dto/UserLoginRequest.java
> +    @NotEmoji
### A
구우웃😄

2024-07-03 04:38 UTC, merged