fix: 어드민 사장님 페이지네이션 수정
BCSDLab/KOIN_API_V2 pull request #654
Opened 2024-07-03 05:20 UTC by kwoo28

# 🔥 연관 이슈

- close #653

현재 인증 요청 사장님 페이지에서 모든 사장님 페이지가 조회되고 있습니다.
또한 사장님 페이지네이션과 인증 요청 사장님 페이지네이션에서 DB에서 조회하는 로직이 잘못되어 두 API 로직 수정했습니다.

# 🚀 작업 내용

1. 기존 사장님 페이지네이션과 인증 요청 사장님 페이지네이션 로직 수정했습니다.

# 💬 리뷰 중점사항
**기존로직**
사장님, 인증요청 사장님 페이지 네이션 : Owner 테이블의 모든 행을 포함하고, Shop 테이블에서 일치하는 행이 있으면 그 데이터를 함께 가져오는 Left Join을 사용

**개선로직**
사장님 페이지 네이션 : Owner의 user_id와 User의 id가 같은 데이터를 조회하여 반환
인증 요청 사장님 페이지 네이션 : IsAuthed = false인 사장님 데이터를 가져온 후 Redis에서 상점을 조회하여 반환

2024-07-05 09:21 UTC, duehee requested changes
고생하셨습니다~
코멘트 한 번 확인해주세요!

2024-07-05 09:21 UTC, duehee commented on src/main/java/in/koreatech/koin/admin/user/repository/AdminOwnerRepository.java
> +    """)
### C
아래 있는 AdminUserRepository이랑 코드 블럭 형식이 안 맞춰져있어서, 어느 하나에 맞추면 좋겠어요!
개인적으로는 이 선이랑 맞추는 게 예쁜 듯 싶네요
```suggestion
    @Query("""
        SELECT o FROM Owner o
        JOIN o.user u
        WHERE u.isAuthed = true
        AND u.email LIKE CONCAT('%', :query, '%')
        """)
```

2024-07-05 09:21 UTC, duehee commented on src/main/java/in/koreatech/koin/admin/user/service/AdminUserService.java
> +        return AdminNewOwnersResponse.of(ownerIncludingShops, result, criteria);
### A
궁금한 점인데, 기존의 사장님 조회에는 원래 상점이 안 나오나요?
ADMIN이 지금 오류가 있는 상태라 해서 들어가서 보는데 헷갈리네용😵

2024-07-05 10:56 UTC, 20HyeonsuLee approved these changes
잘 작성해주셨네용 어프로브합니당

2024-07-05 17:31 UTC, kwoo28 commented on src/main/java/in/koreatech/koin/domain/user/dto/StudentLoginRequest.java
> +    @Email(message = "이메일 형식을 지켜주세요. ${validatedValue}")
엇..그렇네요 지우겠습니다!

2024-07-05 17:31 UTC, kwoo28 commented on src/main/java/in/koreatech/koin/admin/user/repository/AdminOwnerRepository.java
> +    """)
맞추겠습니다! 감사합니다

2024-07-05 17:34 UTC, kwoo28 commented on src/main/java/in/koreatech/koin/admin/user/service/AdminUserService.java
> +        return AdminNewOwnersResponse.of(ownerIncludingShops, result, criteria);
네 맞아요. 레거시에선 기존의 사장님 조회는 상점이 반환을 안하더라요!

2024-07-06 02:21 UTC, duehee approved these changes
굿~ 반영 감사합니다

2024-07-06 02:56 UTC, merged