feat: 학생 회원가입 인증 로직 변경
BCSDLab/KOIN_API_V2 pull request #669
Opened 2024-07-08 17:41 UTC by kwoo28

# 🔥 연관 이슈

- close #544

# 🚀 작업 내용

변경된 로직은 아래와 같이 이루어집니다.

1. 학생이 회원가입을 하면 Redis에 정보를 10시간동안 저장한다.
(회원가입할때  mysql, redis둘다 이메일, 닉네일 중복 검사)

2. 10시간안에 이메일 인증할 시 mysql저장 후 redis에서 데이터 삭제

또한 인증 토큰 관련 오류메시지중 "이미 만료된 토큰입니다.", "이미 인증된 사용자입니다.", "토큰에 해당하는 사용자를 찾을 수 없습니다." 라는 오류메시지 출력을 "유효하지 않는 토큰입니다." 로 간소화했습니다.

Redis관련 이해를 돕기위해 아래와같이 사진으로 과정 첨부합니다.

1. 회원가입시 Redis저장합니다.
![image](https://github.com/BCSDLab/KOIN_API_V2/assets/148550522/530cce62-e725-4708-a2ea-c8d5125f63a7)
![image](https://github.com/BCSDLab/KOIN_API_V2/assets/148550522/ef6fe928-21a2-4c40-ab6c-9f5a895516ac)

2. 중복된 이메일로 회원가입시 Redis에서 중복검증합니다.
![image](https://github.com/BCSDLab/KOIN_API_V2/assets/148550522/63ec3272-f4ae-4679-87d1-c6e15006ac1f)

3. 회원가입 인증시 Redis에 저장된 데이터를 삭제합니다.
![image](https://github.com/BCSDLab/KOIN_API_V2/assets/148550522/1204b443-27c0-401c-ba9d-82fd8690ae2f)
![image](https://github.com/BCSDLab/KOIN_API_V2/assets/148550522/5cf5c339-6f99-4265-ae1f-9d22f278d212)

# 💬 리뷰 중점사항
Redis관련작업은 아래와 같은 공식문서에서 참조해서 작업했습니다.
https://docs.spring.io/spring-data/redis/reference/redis/redis-repositories/indexes.html
https://redis.io/docs/latest/integrate/redisom-for-java/

2024-07-09 12:36 UTC, duehee requested changes
작성 수고 많으셨습니다~
코멘트 한 번 확인해주세요! 굿굿 :D

2024-07-09 12:36 UTC, duehee commented on src/main/java/in/koreatech/koin/domain/user/model/redis/StudentTemporaryStatus.java
> +    }
### C
라인의 상태가..!

2024-07-09 12:36 UTC, duehee commented on src/main/java/in/koreatech/koin/domain/user/repository/StudentRedisRepository.java
> +    Optional<StudentTemporaryStatus> findById(String email);
### C
findByEmail이 낫지 않을까요?
```suggestion
    Optional<StudentTemporaryStatus> findByEmail(String email);
```

2024-07-09 12:36 UTC, duehee commented on src/main/java/in/koreatech/koin/domain/user/service/StudentService.java
> +        userRepository.findByEmail(request.email())
### A
findBy를 사용한 이유가 있었군요👀

2024-07-09 12:36 UTC, duehee commented on src/main/java/in/koreatech/koin/domain/user/service/UserService.java
> +        Optional<StudentTemporaryStatus> studentTemporaryStatus = studentRedisRepository.findById(request.email());
### C
이 로직의 경우는 getByEmail을 사용해서 예외처리 해주는 건 어떨까요?

2024-07-09 12:36 UTC, duehee commented on src/test/java/in/koreatech/koin/AcceptanceTest.java
> +}
### C
여기도 👀

2024-07-09 12:36 UTC, duehee commented on src/test/resources/application.yml
> +OPEN_API_KEY_TMONEY: testck
### C
마지막!!

2024-07-09 12:37 UTC, duehee commented on src/main/java/in/koreatech/koin/domain/user/repository/StudentRedisRepository.java
> +}
여기에는 안 떠있네요 왜지???!

2024-07-10 05:29 UTC, kwoo28 commented on src/main/java/in/koreatech/koin/domain/user/model/redis/StudentTemporaryStatus.java
> +    private static final long CACHE_EXPIRE_SECOND = 60 * 60 * 10L;
그러게요... 근데 수정하게 된다면 팀 전체 논의사항으로 올려야 할것같네요..

2024-07-10 05:30 UTC, kwoo28 commented on src/main/java/in/koreatech/koin/domain/user/model/redis/StudentTemporaryStatus.java
> +    }
오.. 세밀한 캐치 감사합니다

2024-07-10 05:32 UTC, kwoo28 commented on src/main/java/in/koreatech/koin/domain/user/repository/StudentRedisRepository.java
> +    Optional<StudentTemporaryStatus> findById(String email);
저도 처음에 findByEmail로 했는데, 현재 key값인 email은 Id로 해야만 데이터를 찾을 수 있더라고요 ㅋㅋ

2024-07-10 05:32 UTC, kwoo28 commented on src/main/java/in/koreatech/koin/domain/user/repository/StudentRedisRepository.java
> +}
!

2024-07-10 05:39 UTC, kwoo28 commented on src/main/java/in/koreatech/koin/domain/user/service/UserService.java
> +        Optional<StudentTemporaryStatus> studentTemporaryStatus = studentRedisRepository.findById(request.email());
일반적으로 Repository에서 getBy를 통해 예외처리를 하는 상황은 "데이터를 찾을 수 없습니다."라는 일반적인 예외를 발생시킬때 사용하는것같습니다. 하지만 현재 "미인증 상태입니다. 아우누리에서 인증메일을 확인해주세요"라는 예외처리를 내야 하는 상황인데 이걸 Repository에 구현하는건 너무 사소한 부분까지 Repository계층에서 책임까지 맡게되는것같아 계층의 경계가 모호해지는것같아서 서비스계층에서 예외처리 했습니다. 이 부분에 대해 혹시 어덯게 생각하시나요!

2024-07-10 05:40 UTC, kwoo28 commented on src/test/java/in/koreatech/koin/AcceptanceTest.java
> +}
AcceptanceTest는 왜 커밋에 올라간거지....ㅋㅋ 일단 고치겠습니다 감사합니다!

2024-07-10 07:38 UTC, duehee approved these changes
굿! 의견 반영 감사합니당
말씀 주신 부분에서는 의견 달아봤으니 확인해주세요~

2024-07-10 07:38 UTC, duehee commented on src/main/java/in/koreatech/koin/domain/user/service/UserService.java
> +        Optional<StudentTemporaryStatus> studentTemporaryStatus = studentRedisRepository.findById(request.email());
Repository에서 이를 처리한다면, 혹시나 나중에 findById를 쓰게 되는 메소드가 생긴다면 문제가 생길 수도 있겠네요.
코드는 확장성을 고려해서 짜는 것이 중요하니까요..!
저는 혹시나 id를 못 찾는 경우를 생각해서 예외 관련해서 말씀드려봤답니다🤔

2024-07-10 09:51 UTC, seongjae6751 approved these changes
저는 크게 수정할 점이 보이지 않네요!
고생 많으셨습니다.
+ 전에는 왜 안 됐던 것인지 혹시 아셨나요?

2024-07-10 13:43 UTC, kwoo28 commented
> 저는 크게 수정할 점이 보이지 않네요! 고생 많으셨습니다.
> 
> * 전에는 왜 안 됐던 것인지 혹시 아셨나요?

인증시간이 지나도 보조인덱스인 @Indexed 필드는 자동삭제 안되는 문제였습니다., 근데 지금보니 그 부분 해결하는걸 깜빡했네요; 감사합니다..큰일날뻔했네요

2024-07-15 04:51 UTC, merged