feat: 리뷰관련 기능 작성
BCSDLab/KOIN_API_V2 pull request #675
Opened 2024-07-10 07:45 UTC by 20HyeonsuLee

# 🔥 연관 이슈

- close #662 
- close #663  
- close #664 
- close #665 
- close #673
- close #674

# 🚀 작업 내용

1. 리뷰 관련 API를 작성하였습니다.
2. 리뷰 신고하기 관련 API를 작성하였습니다.

# 💬 리뷰 중점사항
양이 조금 많긴 하지만... 리뷰 잘부탁드립니다!
코드가 조금 지저분한 느낌이 있습니다..
기획이 명확해지면 리팩토링을 할 예정입니다

2024-07-13 02:22 UTC, BaeJinho4028 approved these changes
LGTM 👍 
간단한 몇가지만 확인해주세요

2024-07-13 02:22 UTC, BaeJinho4028 commented on src/main/java/in/koreatech/koin/domain/shop/repository/ShopReviewRepository.java
> +               AND r.reportedBy.id = :userId)
`)`  줄넘김하는것이 좋을 것 같습니다!

2024-07-13 02:22 UTC, BaeJinho4028 commented on src/test/java/in/koreatech/koin/acceptance/ShopReviewApiTest.java
> +
공백이 있네요

2024-07-13 02:22 UTC, BaeJinho4028 commented on src/test/java/in/koreatech/koin/acceptance/ShopReviewApiTest.java
> +
이곳도 동일

2024-07-13 02:22 UTC, BaeJinho4028 commented on src/test/java/in/koreatech/koin/acceptance/ShopReviewApiTest.java
> +
이곳도 동일

2024-07-13 02:22 UTC, BaeJinho4028 commented on src/test/java/in/koreatech/koin/acceptance/ShopReviewApiTest.java
> +
이곳도 동일

2024-07-13 02:29 UTC, Choi-JJunho requested changes
늦어서 죄송해여~ 코멘트 확인 부탁합니다

2024-07-13 02:29 UTC, Choi-JJunho commented on src/main/java/in/koreatech/koin/domain/shop/dto/ShopReviewReportRequest.java
> +    @NotBlank(message = "신고 제목은 필수입니다.")
### R

신고 내용

2024-07-13 02:29 UTC, Choi-JJunho commented on src/main/java/in/koreatech/koin/domain/shop/dto/ShopReviewResponse.java
> +    Integer totalPage,
### C

어짜피 페이징 관련된 값인데 과도한 설명인듯
조건에 맞는.. 라는 문장은 생략해도될듯

2024-07-13 02:29 UTC, Choi-JJunho commented on src/main/java/in/koreatech/koin/domain/shop/dto/ShopReviewResponse.java
> +        boolean isMine,
### A

확실히 값을 익명으로 보여주려면 있어야겠네

2024-07-13 02:29 UTC, Choi-JJunho commented on src/main/java/in/koreatech/koin/domain/shop/dto/ShopReviewResponse.java
> +            reviews.stream().map(review -> InnerReviewResponse.from(review, userId)).toList()
### C

특정 유저의 값을 필터링하는게 DTO의 책임일까 고민이좀 되네

2024-07-13 02:29 UTC, Choi-JJunho commented on src/main/java/in/koreatech/koin/domain/shop/dto/ShopReviewResponse.java
> +            double averageRating = totalCount == 0? 0.0: totalSum / totalCount;
### C
 포맷팅이 안되어있는느낌

2024-07-13 02:29 UTC, Choi-JJunho commented on src/main/java/in/koreatech/koin/domain/shop/model/ShopReviewMenu.java
> +    private String menuName;
### A

나중에 메뉴 상세보기같은거 나오면 메뉴 아이디도 값에 넣어줘야겠네

2024-07-13 02:29 UTC, Choi-JJunho commented on src/main/java/in/koreatech/koin/domain/shop/model/ShopReviewReport.java
> +    private String reasonDetail;
### A
그냥 title, content로 하면 어떤지 ?

2024-07-13 02:29 UTC, Choi-JJunho commented on src/main/java/in/koreatech/koin/domain/shop/model/ShopReviewReport.java
> +    private Student reportedBy;
### A
Author
Writer
UserId ...

2024-07-13 02:29 UTC, Choi-JJunho commented on src/main/java/in/koreatech/koin/domain/shop/model/ShopReviewReportCategory.java
> +    private String detail;
### A
이건 어떤 속성인지?

2024-07-13 02:29 UTC, Choi-JJunho commented on src/main/java/in/koreatech/koin/domain/shop/service/ShopReviewService.java
> +    TODO:
### R
일부러 남겨둔건가?

2024-07-13 02:29 UTC, Choi-JJunho commented on src/main/java/in/koreatech/koin/domain/shop/service/ShopReviewService.java
> +        }
### R
이걸 왜 여기서 처리하고있는지..?

2024-07-13 02:29 UTC, Choi-JJunho commented on src/main/resources/db/migration/V29__add_shop_review.sql
> +    rating INT NOT NULL CHECK (rating BETWEEN 0 AND 5),
### A
CHECK 제약 꼼꼼하네 ㅋㅋㅋㅋ

2024-07-13 02:29 UTC, Choi-JJunho commented on src/main/resources/db/migration/V29__add_shop_review.sql
> +('기타', '');
### A
아 이걸 서버에서 관리하는구만

2024-07-13 02:29 UTC, Choi-JJunho commented on src/test/java/in/koreatech/koin/fixture/ShopReviewReportCategoryFixture.java
> +    public ShopReviewReportCategory 리뷰_신고_카테고리_1() {
### C

변수명을 명확하게 하는건 어떤지??
리뷰_신고_주제에_맞지않음

2024-07-13 05:15 UTC, 20HyeonsuLee commented on src/main/java/in/koreatech/koin/domain/shop/controller/ShopApi.java
> +    @GetMapping("/shops/reviews/categories")
엇 맞네요 reports어디갔지

2024-07-13 05:25 UTC, 20HyeonsuLee commented on src/main/java/in/koreatech/koin/domain/shop/service/ShopReviewService.java
> +    TODO:
이미 완료한 TODO는 삭제하도록 하겠습니다!

2024-07-13 05:35 UTC, 20HyeonsuLee commented on src/main/java/in/koreatech/koin/domain/shop/service/ShopReviewService.java
> +        }
하나의 API에 대해서 회원일 경우, 비회원일 경우 각각 로직이 달라서 토큰으로 회원인지 비회원인지 구분하려고 했는데 좋은 방법이 있을까요!?

2024-07-13 06:49 UTC, 20HyeonsuLee commented on src/main/java/in/koreatech/koin/domain/shop/dto/ShopReviewResponse.java
> +            reviews.stream().map(review -> InnerReviewResponse.from(review, userId)).toList()
조금 애매한 부분인 것 같긴 한데 고민이 되긴 하네요..!

2024-07-14 21:23 UTC, Choi-JJunho commented on src/main/java/in/koreatech/koin/domain/shop/service/ShopReviewService.java
> +        }
회원용, 비회원용 API를 나누는게 좋아보이는데..

2024-07-15 01:54 UTC, 20HyeonsuLee commented on src/main/java/in/koreatech/koin/domain/shop/model/ShopReviewReportCategory.java
> +    private String detail;
신고 사유 카테고리의 세부 신고사유입니다!

2024-07-15 02:03 UTC, Choi-JJunho commented on src/main/java/in/koreatech/koin/domain/shop/service/ShopReviewService.java
> +        }
정정) UserId를 추출해오는 `@UserId` 어노테이션 활용하도록 해보죠

2024-07-15 02:15 UTC, 20HyeonsuLee commented on src/main/java/in/koreatech/koin/domain/shop/service/ShopReviewService.java
> +        }
깔끔하게 해결되네요👍

2024-07-15 03:17 UTC, Choi-JJunho approved these changes
고생하셨습니다 👍

2024-07-15 03:59 UTC, merged