fix: User 인코딩 설정
BCSDLab/KOIN_API_V2 pull request #703
Opened 2024-07-15 15:55 UTC by kwoo28

# 🔥 연관 이슈

- close #702

# 🚀 작업 내용

현재 Users 테이블은 인코딩이 'utf8_unicode_ci'로 설정되어있어 일부 특수문자 및 이모지가 허용되지 않습니다.

그래서 몇몇 API에서 특수문자 요청이 들어오게될시 DB에서 서버에러가 발생하고있습니다.

그렇다고 API를 만들때마다 필드에 하나씩 이모지 및 일부 특수문자 검증어노테이션을 붙이기엔 너무 비효율적이며 까먹고 실수할 수 있습니다. 그렇기때문에 Users테이블에 이모지 및 모든 특수문자를 허용하는 'utf8mb4_unicode_ci'로 변경했으며, Users테이블 필드에 이모지나 특수문자가 들어가지 않게하기 위해 쓰기작업이 되는 회원가입 및 회원수정에만 정규화패턴으로 한글,영문,숫자만 허용할 수 있게 검증했습니다.

이렇게 하여 users 테이블 필드에 이모지나 특수문자가 들어갈 일 없이 각 API 필드마다 어노테이션을 추가하지 않고도 서버에러가 발생하지 않을 수 있게됩니다.

# 💬 리뷰 중점사항

2024-07-15 16:28 UTC, duehee requested changes
고생하셨습니다!
코멘트 한 번만 확인해주세요!

2024-07-15 16:28 UTC, duehee commented on src/main/java/in/koreatech/koin/domain/user/dto/StudentRegisterRequest.java
> +    @Pattern(regexp = "^[ㄱ-ㅎ가-힣a-zA-Z0-9]+$", message = "한글, 영문 및 숫자만 사용할 수 있습니다.")
### A
`utf8mb4_unicode_ci`를 이용해서 Request에서 모든 문자를 받는 접근 방식이라니 좋은 것 같아요! 이모지를 제외하더라도, 혹여나 이상한 문자가 더 들어오는 상황을 방지 할 수 있을 것 같네요

2024-07-15 16:28 UTC, duehee commented on src/main/java/in/koreatech/koin/domain/user/dto/StudentUpdateRequest.java
> +        @Pattern(regexp = "^[ㄱ-ㅎ가-힣a-zA-Z0-9]+$", message = "한글, 영문 및 숫자만 사용할 수 있습니다.")
### C
이름에서 숫자를 허용해도 괜찮을까요??
```suggestion
        @Pattern(regexp = "^[ㄱ-ㅎ가-힣a-zA-Z]+$", message = "이름은 한글, 영문만 사용할 수 있습니다.")
```
는 어떻게 생각하세요?

2024-07-15 16:34 UTC, kwoo28 commented on src/main/java/in/koreatech/koin/domain/user/dto/StudentUpdateRequest.java
> +        @Pattern(regexp = "^[ㄱ-ㅎ가-힣a-zA-Z0-9]+$", message = "한글, 영문 및 숫자만 사용할 수 있습니다.")
그렇네요! 이름엔 숫자가 들어갈 필요가 없겠군요. 수정하겠습니다

2024-07-15 17:12 UTC, duehee commented
굿뜨👍

2024-07-15 17:14 UTC, duehee approved these changes
커밋 이름이 이상해요..~
의견 반영 감사합니당

2024-07-16 08:31 UTC, seongjae6751 requested changes
고생하셨습니다~

2024-07-16 08:31 UTC, seongjae6751 commented on src/main/resources/db/migration/V31__alter_users_collation.sql
> +ALTER TABLE users CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
C
테이블은 이모지가 허용되게 확장하고
dto에서는 막는 이유가 있을까요?

2024-07-17 03:57 UTC, kwoo28 commented on src/main/resources/db/migration/V31__alter_users_collation.sql
> +ALTER TABLE users CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
현재 테이블에선 이모지와 몇몇 특수문자가 읽히지 않아서 해당 문자열을 쿼리문으로 날릴시 에러가 발생합니다. 그렇기때문에 테이블에서 인코딩을 확장하지 않으면 API 문자열 필드마다 하나하나 전부 어노테이션을 넣어서 방지해줘야하는데 까먹고 실수할수도있고, 비효율적이라고 생각해서 테이블에서 인코딩 확장했습니다.

2024-07-18 06:00 UTC, seongjae6751 approved these changes
고생하셨습니다!

2024-07-18 06:27 UTC, merged