feat: 모든 상점 조회시 필터 유효성 검사 추가
BCSDLab/KOIN_API_V2 pull request #751
Opened 2024-08-04 16:45 UTC by 20HyeonsuLee

# 🔥 연관 이슈

- close #742
- close #749 
- close #750

# 🚀 작업 내용

1. 모든 상점 조회시 필터값에 유효성 검사를 추가했습니다.
2. 리뷰 작성시 내용이 null이 될 수 있게 변경했습니다.(기획에 맞도록 변경)
3. 리뷰 신고 내역을 여러개 선택할 수 있도록 변경했습니다.

# 💬 리뷰 중점사항

2024-08-04 23:42 UTC, Choi-JJunho requested changes
굿굿 하나만 확인해줘요

2024-08-04 23:42 UTC, Choi-JJunho commented on src/main/java/in/koreatech/koin/domain/shop/model/ShopReview.java
>      private String content;
### C

이 값은 Column으로 다루지 않겠다는건가요?
그렇다면 Transient같은거라도 붙여주는게 좋아보이네요

2024-08-05 07:39 UTC, duehee requested changes
상점 쪽도 재밌는 것 같네요👀 리뷰 기능은 확실히 도움이 많이 될 거 같아요! 
고생하셨습니다~ 코멘트 한 번 확인해주세요!

2024-08-05 07:39 UTC, duehee commented on src/main/java/in/koreatech/koin/domain/shop/dto/CreateReviewRequest.java
> +        @JsonProperty("content") String content,
### A
기획측에서도 내용 리뷰가 없어도 작성할 수 있도록 했군용
배달의 민족도 별점만 작성하는 리뷰를 사용하는 것 같더라구요

2024-08-05 07:39 UTC, duehee commented on src/test/java/in/koreatech/koin/acceptance/ShopReviewApiTest.java
> +    void 리뷰_내용을_작성하지_않고_리뷰를_등록할_수_있다() {
### C
`@displayName`을 사용하지 않고 그대로 메소드 명으로 사용하신 이유가 있나요?
ex) `createReviewWithoutContent`

2024-08-05 08:12 UTC, Choi-JJunho approved these changes

2024-08-05 08:15 UTC, 20HyeonsuLee commented on src/test/java/in/koreatech/koin/acceptance/ShopReviewApiTest.java
> +    void 리뷰_내용을_작성하지_않고_리뷰를_등록할_수_있다() {
함수명을 영어로 작성하는게 보기 힘들어서 한글이름으로 해봤는데 너무 좋아서 계속 사용하고있어요

2024-08-05 08:16 UTC, Choi-JJunho commented on src/test/java/in/koreatech/koin/acceptance/ShopReviewApiTest.java
> +    void 리뷰_내용을_작성하지_않고_리뷰를_등록할_수_있다() {
어디는 DisplayName을 쓰고 어디는 한글로 쓰고 왔다갔다하면 복잡할것 같은데 컨벤션을 정의해보는건 어떨까요?
ex) 테스트코드 작성 시 000 으로 작성한다. 

https://github.com/BCSDLab/KOIN_API_V2/wiki/%F0%9F%93%9A-%EC%BD%94%EB%93%9C-%EC%BB%A8%EB%B2%A4%EC%85%98

2024-08-05 08:17 UTC, duehee commented on src/test/java/in/koreatech/koin/acceptance/ShopReviewApiTest.java
> +    void 리뷰_내용을_작성하지_않고_리뷰를_등록할_수_있다() {
앗 그런 의도였군요!
한 번 나중에 테스트 작성할 때 영어 이름 생각 안 나면 이렇게 작성해봐야겠어요😄

2024-08-05 08:19 UTC, 20HyeonsuLee commented on src/test/java/in/koreatech/koin/acceptance/ShopReviewApiTest.java
> +    void 리뷰_내용을_작성하지_않고_리뷰를_등록할_수_있다() {
오호 좋습니다 컨벤션으로 한번 추진해봐야겠어요

2024-08-05 08:29 UTC, duehee approved these changes

2024-08-05 10:25 UTC, merged