Feature/757 shop review admin
BCSDLab/KOIN_API_V2 pull request #805
Opened 2024-08-16 12:06 UTC by Backend-Changyeon

# 🔥 연관 이슈

- close #757 

# 🚀 작업 내용
1. 상점 리뷰 및 신고 조회
2. 리뷰 상태 변경 (신고 처리)

# 💬 리뷰 중점사항

2024-08-16 17:26 UTC, BaeJinho4028 reviewed
역시 저보다 훨씬 잘하시네요.. 👍 
몇가지 간단하게 리뷰 남깁니다

2024-08-16 17:26 UTC, BaeJinho4028 commented on src/main/java/in/koreatech/koin/admin/shop/controller/AdminShopController.java
> +        return ResponseEntity.status(HttpStatus.OK).body(adminShopService.getReviews(page, limit, isReported, isHaveUnhandledReport, shopId));
`) {` 부분을 줄넘김 해주시면 더욱 깔끔할것 같습니다!

2024-08-16 17:26 UTC, BaeJinho4028 commented on src/main/java/in/koreatech/koin/admin/shop/controller/AdminShopController.java
> +        return ResponseEntity.status(HttpStatus.OK).body(adminShopService.getReviews(page, limit, isReported, isHaveUnhandledReport, shopId));
여기도 줄너비가 초과되었네요 😢 

이미 하셨을 것같지만 밑은 BCSD 코드포맷팅 파일 적용 방법입니다. 
https://github.com/BCSDLab/KOIN_API_V2/wiki/%F0%9F%92%A1-%EC%BD%94%EB%93%9C%EC%BB%A8%EB%B2%A4%EC%85%98-%EC%A0%81%EC%9A%A9%ED%95%98%EA%B8%B0

2024-08-16 17:26 UTC, BaeJinho4028 commented on src/main/java/in/koreatech/koin/admin/shop/dto/AdminModifyShopReviewReportStatusRequest.java
> +}
클래스 바디부분은 줄넘김 하나 해주시면 좋을 것 같습니다!

그리고 POSIX 구문 경고가 떠있네요. 주노님 블로그 참고하시면 좋을 것 같습니다
https://velog.io/@junho5336/No-newline-at-end-of-file

2024-08-16 17:26 UTC, BaeJinho4028 commented on src/main/java/in/koreatech/koin/admin/shop/dto/AdminShopsReviewsResponse.java
> +            }
따로 변수 지정하지말고, 삼항연산자를 쓰는것은 어떤것같으신가요? (코드 취향 질문)

2024-08-16 17:26 UTC, BaeJinho4028 commented on src/main/java/in/koreatech/koin/admin/shop/dto/AdminShopsReviewsResponse.java
> +}
여기도 POSIX 경고

2024-08-16 17:26 UTC, BaeJinho4028 commented on src/main/java/in/koreatech/koin/admin/shop/repository/AdminShopReviewCustomRepository.java
> +}
public interface AdminShopReviewCustomRepository {

    Page<ShopReview> findShopReview(Integer shopId, Boolean isReported, Boolean isHaveUnhandledReport, Pageable pageable);

    Long countShopReview(Integer shopId, Boolean isReported, Boolean isHaveUnhandledReport);
}

이렇게 줄넘김하면 더욱 좋을 것 같습니다!

2024-08-16 17:26 UTC, BaeJinho4028 commented on src/main/java/in/koreatech/koin/admin/shop/repository/AdminShopReviewCustomRepositoryImpl.java
> +public class AdminShopReviewCustomRepositoryImpl implements AdminShopReviewCustomRepository {
지금보니 역할과 구현을 분리하셨군요. 이유가 따로 있을까요?

2024-08-16 17:26 UTC, BaeJinho4028 commented on src/main/java/in/koreatech/koin/admin/shop/repository/AdminShopReviewRepository.java
> +}
이 함수를 사용하는 서비스단에서 에러가 발생하네요. id에 해당하는 것이 없어서 null일 경우 예외처리를 해주시면 좋을 것 같습니다!

그리고 여기도 body시작에 줄넘김 하나만 해주시면 좋을것 같습니다!

2024-08-16 17:26 UTC, BaeJinho4028 commented on src/main/java/in/koreatech/koin/admin/shop/service/AdminShopService.java
> +        unhandledReports.forEach(report -> report.modifyReportStatus(adminModifyShopReviewReportStatusRequest.reportStatus()));
가로 길이가 넘어가네요 😢 

Line : 307, 308, 313, 320

2024-08-17 01:11 UTC, 20HyeonsuLee requested changes
첫 PR..! 역시 현직자라서 그런지 잘하시네요👍

리뷰 남겼습니다 확인해주세요~

2024-08-17 01:11 UTC, 20HyeonsuLee commented on src/main/java/in/koreatech/koin/admin/shop/repository/AdminShopReviewCustomRepositoryImpl.java
> +        }
# C
공통된 로직을 모듈화 해보는건 어떨까요?

2024-08-17 01:11 UTC, 20HyeonsuLee commented on src/main/java/in/koreatech/koin/admin/shop/service/AdminShopService.java
> +                .filter(report -> report.getReportStatus() == ReportStatus.UNHANDLED)
# C
`static import`한번 해주시면 좋을 것 같습니다!
맥 기준 `option + enter`누른 다음 `static import`할 수 있습니다!

2024-08-17 01:11 UTC, 20HyeonsuLee commented on src/main/java/in/koreatech/koin/global/config/QueryDslConfig.java
> +public class QueryDslConfig {
# A
리뷰 관련 기능을 만들 때 queryDSL로 작성해주신 이유가 궁금합니다!

2024-08-17 02:24 UTC, Backend-Changyeon commented on src/main/java/in/koreatech/koin/admin/shop/dto/AdminShopsReviewsResponse.java
> +            }
@BaeJinho4028 
제가 개인적으로 삼항연잔사를 별로 안좋아하기는 하는데 java에는 optional이라는 좋은 친구가 있다는것을 이제 알았네요
수정했습니다
```suggestion
String nickName = Optional.ofNullable(review.getReviewer().getUser().getNickname())
                                      .orElse(review.getReviewer().getAnonymousNickname());
```

2024-08-17 02:27 UTC, Backend-Changyeon commented on src/main/java/in/koreatech/koin/admin/shop/repository/AdminShopReviewCustomRepositoryImpl.java
> +public class AdminShopReviewCustomRepositoryImpl implements AdminShopReviewCustomRepository {
@BaeJinho4028 
비즈니스 로직을 담당하는 서비스 레이어는 레포지토리가 어떻게 구현되어있는지 구체적으로 알 필요 없다고 생각했습니다 ㅎㅎ
서비스 레이어는 레포지토리 레이어가 **어떤 인자를 필요로 하는지**, **그리고 무엇을 반환해주는지**가 중요하고 그 안에서 어떤 일이 일어나는지는 몰라야 한다고 생각합니다.

2024-08-17 02:43 UTC, Backend-Changyeon commented on src/main/java/in/koreatech/koin/admin/shop/service/AdminShopService.java
> +                .filter(report -> report.getReportStatus() == ReportStatus.UNHANDLED)
@20HyeonsuLee static import를 사용하는 이유가 뭘까요?

2024-08-17 02:45 UTC, Backend-Changyeon commented on src/main/java/in/koreatech/koin/global/config/QueryDslConfig.java
> +public class QueryDslConfig {
nullable한 값들을 서비스 로직에서 다루고 싶지 않고, 레포지토리 레이어에서 다루고 싶었습니다.
서비스 입장에서는 isReported, isHaveUnhandledReport이 null이던, 아니던 알 필요 없으니까요.
동적 쿼리가 만들어지는 것이기 때문에 querydsl로 좀 자바틱(?)한 동적 쿼리를 만들고 싶었습니다.

2024-08-17 03:51 UTC, 20HyeonsuLee commented on src/main/java/in/koreatech/koin/global/config/QueryDslConfig.java
> +public class QueryDslConfig {
nullable한 것들을 동적 쿼리로 만들기 좋을 것 같습니다

2024-08-17 04:03 UTC, 20HyeonsuLee commented on src/main/java/in/koreatech/koin/admin/shop/service/AdminShopService.java
> +                .filter(report -> report.getReportStatus() == ReportStatus.UNHANDLED)
저는 주로 코드가 간결해져서 사용하는 것 같습니다.
`static import`를 하지 않으면 명시적인 측면에서 장점이 있습니다.
저희 프로젝트 규모에서는 간결해지는 것이 저한테는 조금 더 크게 다가오는 것 같아요 창연님 생각은 어떠실까요?

2024-08-17 11:28 UTC, BaeJinho4028 approved these changes

2024-08-17 13:40 UTC, 20HyeonsuLee approved these changes

2024-08-17 13:44 UTC, merged