feat: 내가 추가한 키워드 api작성, 키워드 추천 api 작성, 많이 검색한 인기 키워드 api 작성
BCSDLab/KOIN_API_V2 pull request #824
Opened 2024-08-23 15:38 UTC by seongjae6751

# 🔥 연관 이슈

- close #790 
- close #809
- close #816
# 🚀 작업 내용

1. 파일 구조를 아래와 같이 정리했습니다.
domain
  └── community
      ├── articles
      │   ├── controller
      │   └── ...
      └── keyword
          ├── controller
          └── ...

2. 내가 추가한 키워드 api작성 했습니다.  -> GET /articles/keyword/me
3. 키워드 추천 api 작성 했습니다. -> GET /articles/keyword/suggestions
4. 많이 검색한 인기 키워드 api 작성 했습니다. -> GET /articles/hot/keyword

# 💬 리뷰 중점사항
1. 연관관계 편의 메서드 적용:

* Post articles/keyword의 서비스 로직에서 [#789 PR](https://github.com/BCSDLab/KOIN_API_V2/pull/789)에서 언급된 연관관계 편의 메서드를 적용하려 했으나, 현재 구조에서 어떻게 적용할지 확신이 서지 않습니다. 조언해주시면 감사하겠습니다.

2. 빈 리스트 반환 처리:
* 사용자가 추가한 키워드가 없는 경우, GET /articles/keyword/me API는 빈 리스트를 반환하도록 구현했습니다.

3. 키워드 추천 로직:
* 추천 기준: 일주일 동안 가장 많이 사용된 키워드를 바탕으로 추천합니다.
* 캐싱 활용: Redis 캐시를 활용하여 키워드 추천을 제공합니다. 사용자가 이미 추가한 키워드는 추천 목록에서 제외됩니다.
* 로직:
Redis에서 사용자가 추가하지 않은 키워드 5개를 가져옵니다. (Redis에는 총 15개의 키워드가 저장되어 있어야 합니다)
Redis 로직: 일주일 동안 사용된 키워드 중 가장 많이 사용된 15개의 키워드를 유지하여, 사용자가 인기 키워드 10개를 모두 추가하더라도 5개는 추천할 수 있도록 설정했습니다.

4. 인기 키워드 로직:
* 검색된 키워드를 공백 기준으로 분리하여 DB에 주기적으로 저장합니다.
* 비로그인 API에서 공격을 방지하기 위해 무분별한 데이터 저장을 어떻게 처리할지 고민 중입니다.
* 동일 IP의 다중 검색과 여러 IP에서의 검색 가중치를 다르게 설정했습니다.
* 해당 날짜에 검색된 키워드가 없을 경우, 최신 검색어로 대체합니다.

2024-08-25 05:22 UTC, songsunkook requested changes
길고 복잡한 로직이었던 것 같은데 고생하셨습니다. 👍 👍 
혹시 여러 이슈를 하나의 PR로 묶어 올린 이유가 있을까요?? 인지해야 할 배경이나 파일체인지 등 리뷰어에게 압박이 심해서 다음부터는 이슈별로 분리하면 좋을 것 같습니다.
~~한 시간넘게 리뷰하느라 쓰러질 뻔...~~
키워드 관리 특성 상 지금 당장은 아니더라도 mysql 말고 다른 데이터 관리 방법을 고민해보는 것도 좋을 것 같아요.

2024-08-25 05:22 UTC, songsunkook commented on src/main/java/in/koreatech/koin/domain/community/keywords/service/KeywordService.java
> +            } else {
### C
`if-else` 대신 `continue`나 `break`을 사용하는 건 어떨까요?

2024-08-25 05:22 UTC, songsunkook commented on src/main/java/in/koreatech/koin/domain/community/keywords/service/KeywordService.java
> +
### C
형변환이 많이 이루어지고 있고 배열의 각 요소가 어떤 의미인지 직관적이지 못해서 약간 불안정해보이는데 Repository에서 반환할 때 별도 클래스로 매핑해서 반환하거나 하는 방향은 어떨까요?

2024-08-25 05:22 UTC, songsunkook commented on src/main/java/in/koreatech/koin/domain/community/repository/ArticleKeywordRepository.java
> 연관관계 편의 메서드 적용:
Post articles/keyword의 서비스 로직에서 언급된 연관관계 편의 메서드를 적용하면 좋겠다는 선권 님의 말씀대로 적용해보려 했으나, 현재 구조에서 어떻게 적용할지 잘 모르겠습니다.ㅜ 조언해주시면 감사하겠습니다.

저도 될지 안될지 잘 모르겠습니다. 편의 메서드로 분리할 수 있다면 더 예쁜 코드가 되지 않을까 해서 꺼내본 말이었는데 만약 안된다면 그대로 둬도 좋습니다!

> 많이 검색한 인기 키워드 조회 로직:
현재 requestparam으로 몇개를 반환할지를 받고 있어 레디스에 캐시 형태로는 올리지 못했습니다. 엄청나게 데이터가 많아 질 것과 최적화를 생각하면 캐시 형태로 만드는 것이 좋을 것 같은데 어떻게 최적화 하면 좋겠는지 조언 해주시면 감사하겠습니다.

엄청나게 데이터가 많아진다면 인메모리 DB인 redis에서 다루기는 위험해보여요. mySql말고 대용량 데이터를 다루는 별도 도구를 찾아봐야 할 것 같습니다.

> 비로그인 API에서 공격을 방지하기 위해 무분별한 데이터 저장을 어떻게 처리할지 고민 중입니다.

문장에서 유의미한 키워드만 추출하여 저장하는 로직을 만들어보는 건 어떨까요? 위에서 코멘트 남긴 내용중에 있었던 것 같아요. 

> 동일 IP의 다중 검색과 여러 IP에서의 검색 가중치를 다르게 설정했습니다.

코드의 어느 부분인지 명확히 짚어주시면 좋을 것 같아요.

> 해당 날짜에 검색된 키워드가 없을 경우, 최신 검색어로 대체합니다.

어떤 부분에 대한 설명인지 모르겠어요. 추천 키워드인가요? 만약 그렇다면 인기있는 키워드가 아니라 최신 키워드가 추천되는 것인가요..??

> (1) 키워드가 몇십만개가 된다고 하면 findall로 한번에 다 가져올 경우 컴퓨터가 터져버릴 것이라 생각했습니다. 따라서 100개씩 가져오도록 설정했습니다.

(위에서 언급한 내용과 비슷합니다.)
엄청나게 데이터가 많아지는데 다른 데이터와 관계는 거의 맺지 않는다면 mySql말고 대용량 데이터를 다루는 별도 도구를 찾아봐야 할 것 같습니다.

> (2) article은 한번에 많아야 2개~3개가 올라올 것이고 보통은 동시에 공지사항이 올라올 경우가 없어 한 개의 article만 있을 것이기 때문에 해당 로직이 돌아가는 대부분의 시간복잡도는 O(n^3)이 아닙니다.

👍 

> koin_batch만 저 api를 사용하게 할 수 있을지 고민 중에 있습니다.
(방안1) 특정 ip만 해당 api를 쓸 수 있게 한다.
(방안2) yml에 비밀키를 설정해서 api를 호출할때 키를 같이 넘겨주고, 비밀 키가 맞을때만 해당 api를 호출 할 수 있게 한다.

헤더에 인증정보를 부가하면 어떨까요? 지난 번에 나왔던 이슈와 함께 진행하는 것도 좋아 보여요.
[참고 슬랙](https://bcsdlab.slack.com/archives/CGQK77GCB/p1723429432312019)

2024-08-28 10:36 UTC, seongjae6751 commented on src/main/java/in/koreatech/koin/domain/community/keywords/scheduler/KeywordScheduler.java
> +            log.warn("추천 키워드 업데이트 중에 오류가 발생했습니다.");
어떻게 할지 한번 생각을 해봐야겠네요..🥲

2024-08-29 16:16 UTC, dradnats1012 commented on src/main/java/in/koreatech/koin/domain/community/article/dto/ArticleHotKeywordResponse.java
> +    public static ArticleHotKeywordResponse from(List<String> results) {
여기서 results 에는 5개만 오는건가요?
만약 5개가 초과나 미만이 오면 어떻게 되나요??

2024-08-29 16:20 UTC, dradnats1012 commented on src/main/java/in/koreatech/koin/domain/community/article/model/ArticleSearchKeywordIpMap.java
> +
개행 2개 발견!

2024-08-29 16:20 UTC, dradnats1012 commented on src/main/java/in/koreatech/koin/domain/community/article/repository/ArticleRepository.java
> +
여기도 개행 2개요

2024-08-29 16:21 UTC, dradnats1012 commented on src/main/java/in/koreatech/koin/domain/community/article/repository/ArticleSearchKeywordIpMapRepository.java
> +    void save(ArticleSearchKeywordIpMap map);
보통 클래스 시작하고 개행 해주는걸로 아는데 어떠신가요?

2024-08-29 16:21 UTC, dradnats1012 commented on src/main/java/in/koreatech/koin/domain/community/article/repository/ArticleSearchKeywordRepository.java
> +    void save(ArticleSearchKeyword keyword);
여기도 개행이요!

2024-08-29 16:38 UTC, dradnats1012 commented on src/main/java/in/koreatech/koin/domain/community/keyword/repository/ArticleKeywordSuggestRepository.java
> +    List<ArticleKeywordSuggestCache> findTop15ByOrderByCountDesc();
요구사항이 바뀔 경우를 생각해서 키워드 개수를 인자로 받는건 어떻게 생각하시나요?

2024-08-29 16:42 UTC, dradnats1012 commented on src/main/java/in/koreatech/koin/domain/community/keyword/service/KeywordService.java
> +            .limit(5)
이건 상수로 등록하지 않은 이유가 있나요?

2024-08-29 16:43 UTC, dradnats1012 commented on src/main/java/in/koreatech/koin/domain/community/keyword/service/KeywordService.java
> +        if (keyword.contains(" ")) {
줄바꿈이 들어가면 어떻게 되나요?

2024-08-30 02:15 UTC, seongjae6751 commented on src/main/java/in/koreatech/koin/domain/community/article/dto/ArticleHotKeywordResponse.java
> +    public static ArticleHotKeywordResponse from(List<String> results) {
항상 5개가 아니라 count라는 requestparam으로 탄력적으로 받을 수 있습니다..!

2024-08-30 02:15 UTC, seongjae6751 commented on src/main/java/in/koreatech/koin/domain/community/keyword/repository/ArticleKeywordSuggestRepository.java
> +    List<ArticleKeywordSuggestCache> findTop15ByOrderByCountDesc();
키워드가 엄청나게 많아지면(금방 몇 만개까지 가지 않을까 예상합니다..)  추천 하는 api가 응답이 너무 오래 걸릴 것 같아서 현재 레디스에 캐시로 올린 상황입니다..! 이런 응답속도 개선 및 최적화를 위해서 현재 고정으로만 만들었는데 어떻게 생각하실까요..??

2024-08-30 02:15 UTC, seongjae6751 commented on src/main/java/in/koreatech/koin/domain/community/keyword/service/KeywordService.java
> +            .limit(5)
상수 등록하겠습니다 감사합니다!

2024-08-30 02:15 UTC, seongjae6751 commented on src/main/java/in/koreatech/koin/domain/community/keyword/service/KeywordService.java
> +        if (keyword.contains(" ")) {
헉 줄바꿈은 생각을 못해봤네요 처리하는 로직 추가하겠습니다!

2024-09-01 01:18 UTC, dradnats1012 approved these changes
고생하셨습니다!

2024-09-01 01:42 UTC, songsunkook approved these changes
고생하셨습니다~

2024-09-01 01:42 UTC, songsunkook commented on src/main/java/in/koreatech/koin/domain/community/article/repository/ArticleSearchKeywordRepository.java
> +    List<String> findTopKeywordsByLatest(Pageable pageable);
### A
이 쿼리는 쿼리메서드를 사용할 수 없었는지 궁금해요!

2024-09-01 01:42 UTC, songsunkook commented on src/main/java/in/koreatech/koin/domain/community/article/service/CommunityService.java
> +    }
### C
최근에 성빈이가 사용하지 않는다고 지운 부분인데 다시 살린 이유가 있을까요??
([PR 링크](https://github.com/BCSDLab/KOIN_API_V2/pull/830/files#diff-36d902c24bc93f94b2fcc1850401f62e483f660ad60ec15f814eeaf6e268eab3))

2024-09-01 01:42 UTC, songsunkook commented on src/main/java/in/koreatech/koin/domain/community/article/service/CommunityService.java
> +            : 1.0 / Math.pow(2, 4);
### C
이런 부분은 코드만으로는 이해하기 힘든데 주석으로 설명을 부가해주면 어떨까요?

2024-09-01 01:42 UTC, songsunkook commented on src/main/java/in/koreatech/koin/domain/community/article/service/CommunityService.java
> +        LocalDateTime sixHoursThirtyMinutesAgo = now.minusHours(6).minusMinutes(30);
### A
변수명에 수치를 표현해야하는 이유가 있었는지 궁금해요. 대신 용도를 표현할 수는 없는 건가요?

2024-09-01 01:42 UTC, songsunkook commented on src/main/java/in/koreatech/koin/domain/timetable/service/SemesterService.java
코드 끼워팔기..? ㄷㄷ

2024-09-01 03:55 UTC, seongjae6751 commented on src/main/java/in/koreatech/koin/domain/community/article/repository/ArticleSearchKeywordRepository.java
> +    List<String> findTopKeywordsByLatest(Pageable pageable);
성능 측면에서 articleSearchKeyword를 가져와서 가공 하는것보다 쿼리메서드를 사용해서 바로 keyword를 쓰는 것이 나을 것이라고 생각했습니다!

2024-09-01 03:55 UTC, seongjae6751 commented on src/main/java/in/koreatech/koin/domain/community/article/service/CommunityService.java
> +    }
충돌..ㅠ 이네요

2024-09-01 03:55 UTC, seongjae6751 commented on src/main/java/in/koreatech/koin/domain/community/article/service/CommunityService.java
> +        LocalDateTime sixHoursThirtyMinutesAgo = now.minusHours(6).minusMinutes(30);
타당하신 말씀입니다!

2024-09-01 03:55 UTC, seongjae6751 commented on src/main/java/in/koreatech/koin/domain/timetable/service/SemesterService.java
제가 추가 한게 아닌데 이상하게 이렇게 되었네요ㅠ

2024-09-01 04:01 UTC, merged