테스트 최적화 코드 예시
BCSDLab/KOIN_API_V2 pull request #867
Opened 2024-09-03 07:42 UTC by 20HyeonsuLee

# 🔥 연관 이슈

- close #이슈번호

# 🚀 작업 내용

1.

# 💬 리뷰 중점사항

2024-09-09 01:17 UTC, duehee approved these changes
양이 완전 많네요.. 트랙장님 대박😮  
고생 많으셨습니다! 간단한 코멘트 남겼으니 확인해주세요~

2024-09-09 01:17 UTC, duehee commented on src/test/java/in/koreatech/koin/acceptance/AuthApiTest.java
> +    void 용자가_로그인_이후_refreshToken을_재발급한다() throws Exception {
### C
👀 
```suggestion
    void 사용자가_로그인_이후_refreshToken을_재발급한다() throws Exception {
```

2024-09-09 01:17 UTC, duehee commented on src/test/java/in/koreatech/koin/acceptance/MemberApiTest.java
> +    void BCSDLab_회원의_정보를_조회한다() throws Exception {
### C
사소하긴 한데, 상단의 ActivityApiTest에서는 `BCSD_Lab`으로 되어있어서, 통일하는 것도 좋을 거 같아요!

2024-09-09 01:17 UTC, duehee commented on src/test/java/in/koreatech/koin/acceptance/TrackApiTest.java
>      @DisplayName("BCSDLab 트랙 정보 단건 조회 - 삭제된 멤버는 조회하지 않는다.")
### C
`@DisplayName`은 삭제해도 될 것 같아요

2024-09-09 02:36 UTC, Choi-JJunho requested changes
이렇게 많은양을.. 진짜 고생하셨습니다
몇가지 코멘트 남겼으니 확인 부탁드릴게요~

+) 추가로 PR에 속도가 얼마나 개선되었는지 결과를 알려주면 좋을 것 같아요!
- PC 사양, 이전 속도, 개선 후 속도

2024-09-09 02:36 UTC, Choi-JJunho commented on src/test/java/in/koreatech/koin/acceptance/DiningApiTest.java
> +                get("/dinings/search?keyword=육개장&page=1&limit=10&filter=B코너")
### A
이거 파라미터 구분하는건 어떤가요?

2024-09-09 02:36 UTC, Choi-JJunho commented on src/test/java/in/koreatech/koin/acceptance/KeywordApiTest.java
> +    @Transactional
### R
> class level에 `@Transactional`이 선언되어있는데 메소드 레벨에 불필요한 중복 선언이 있는거같아요

ditto

2024-09-09 02:36 UTC, Choi-JJunho commented on src/test/java/in/koreatech/koin/admin/acceptance/AdminShopApiTest.java
> +import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*;
### A

갑자기 헷갈리는 부분인데 wildcard import에 대한 컨벤션이 없었나요

2024-09-09 02:36 UTC, Choi-JJunho commented on src/test/java/in/koreatech/koin/admin/acceptance/AdminTrackApiTest.java
> +
### R

두줄공백 포착! 👀

2024-09-09 03:16 UTC, 20HyeonsuLee commented on src/test/java/in/koreatech/koin/admin/acceptance/AdminShopApiTest.java
> +import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*;
3개 이상부터 가능하다고 되어있었네요
그런데 import정리를하면(option + command + i) `wildcard import`가 풀리고 각각의 임포트로 분리되어버리네요..

2024-09-09 03:39 UTC, 20HyeonsuLee commented on src/test/java/in/koreatech/koin/acceptance/BusApiTest.java
> +    void 시내버스_시간표를_조회한다_지원하지_않음() throws Exception {
시내버스 관계자(박성빈)에게 물어보니 없어도 되는 테스트라고 하길래 삭제했습니다

2024-09-09 03:44 UTC, 20HyeonsuLee commented on src/test/java/in/koreatech/koin/AcceptanceTest.java
>  }
protected로 변경했습니다

2024-09-11 07:45 UTC, daheeParkk approved these changes
코드 양이 많네요.. 고생하셨습니다..!

2024-09-11 08:21 UTC, songsunkook approved these changes
엄청나네요.. ㄷㄷ
고생하셨습니다!

2024-09-11 08:25 UTC, Choi-JJunho approved these changes

2024-09-11 08:34 UTC, dradnats1012 approved these changes
왕많네요
고생하셨습니당

2024-09-12 02:16 UTC, Choon0414 approved these changes
이 많은 양을 다 하셨다니.. 고생하셨습니다.

2024-09-12 14:18 UTC, merged