feat : 강제 업데이트 api 구현
BCSDLab/KOIN_API_V2 pull request #900
Opened 2024-09-18 15:40 UTC by Choon0414

# 🔥 연관 이슈

- close #878 

# 🚀 작업 내용

1. 강제 업데이트 API를 구현하였습니다.
    - 일반 api는 클라이언트의 최소 업데이트 버전과 업데이트 문구를 반환합니다.
    - admin api는 클라이언트의 최소 업데이트 버전과 업데이트 문구를 조회, 수정할 수 있습니다.
    - admin api는 과거 클라이언트의 업데이트 버전 이력을 조회할 수 있습니다.
 
2. 기존의 bus, timetable과 같은 api 버전과 클라이언트 버전을 관리하는 테이블을 분리하였습니다.
    - API의 버전 관리와 클라이언트의 버전 관리는 성격이 다르다고 생각해서 별도로 분리하였습니다.
    - Version API : API의 버전을 관리(bus, timetable과 같은 데이터 갱신일 수정) 
    - UpdateVersion API : 클라이언트의 버전을 관리(모바일 버전 및 업데이트 문구 수정)

# 💬 리뷰 중점사항

2024-09-19 01:35 UTC, songsunkook requested changes
1200줄.. 연휴동안 코드만 치셨나요 ㄷㄷ
고생하셨습니다! 👍  코멘트 확인 부탁드립니당

2024-09-19 01:35 UTC, songsunkook commented on src/main/java/in/koreatech/koin/admin/updateversion/controller/AdminUpdateVersionController.java
> +@RequestMapping("/admin/update")
### C
`/admin/version`도 괜찮아보이는데 `/admin/update/version`를 사용한 이유가 있을까요? 대체재가 없지 않다면 동사는 지양하는 편이 좋지 않을까 하는 의견입니당

2024-09-19 01:35 UTC, songsunkook commented on src/main/java/in/koreatech/koin/admin/updateversion/dto/AdminUpdateHistoryResponse.java
> +    List<UpdateHistory> versions
### R
엔티티를 직접 DTO에서 참조하는 것보다는 내부 클래스로 분리하는 방향이 적절해 보입니다

2024-09-19 01:35 UTC, songsunkook commented on src/main/java/in/koreatech/koin/admin/updateversion/dto/AdminUpdateVersionsResponse.java
> +    @Schema(description = "조건에 해당하는 총 버전 타입의 수", example = "2", requiredMode = REQUIRED)
### A
DTO 중 여기만 클래스명과 첫 몸체 라인 사이에 개행이 되어있어요

2024-09-19 01:35 UTC, songsunkook commented on src/main/java/in/koreatech/koin/admin/updateversion/dto/AdminUpdateVersionsResponse.java
> +    List<AdminUpdateVersionResponse> versions
### C
DTO가 타 DTO에 의존하는 형태로 보이는데 괜찮을까요? 단건 응답 명세가 바뀌면 다건 응답 명세도 함께 바뀌게 될텐데 조금 우려되네요

2024-09-19 01:35 UTC, songsunkook commented on src/main/java/in/koreatech/koin/admin/updateversion/repository/AdminUpdateHistoryRepository.java
> +    Integer countByType(UpdateVersionType type);
### C
Spring Data JPA에서 `countBy...`는 Long을 반환한다고 알고있습니다!

2024-09-19 01:35 UTC, songsunkook commented on src/main/java/in/koreatech/koin/admin/updateversion/repository/AdminUpdateVersionRepository.java
> +    Integer count();
### C
여기도 count가 Integer를 반환하네요

2024-09-19 01:35 UTC, songsunkook commented on src/main/java/in/koreatech/koin/admin/updateversion/service/AdminUpdateVersionService.java
> +            .build();
### C
`public static UpdateHistory createByVersion(Version version)`같은 생성 메서드를 만드는 방향은 어떨까요?

2024-09-19 01:35 UTC, songsunkook commented on src/main/java/in/koreatech/koin/domain/updateversion/controller/UpdateVersionApi.java
> +    ResponseEntity<UpdateVersionResponse> getVersion(
### C
`/update/version/{type}`은 버전을 업데이트하는 요청처럼 보입니다. update를 꼭 명시해야하는 이유가 없다면 제거하는 것은 어떨까요? `/version/{type}`만으로는 충분하지 않다고 보시는지 궁금합니다.

2024-09-19 01:35 UTC, songsunkook commented on src/main/java/in/koreatech/koin/domain/updateversion/model/UpdateHistory.java
> +@Table(name = "update_history")
### C
update_history라면 어떤 대상을 update한 이력을 관리하는 건지 직관적으로 이해하기 힘들 것 같아요. version이라는 단어를 사용하지 않는 이유가 있나요..?

2024-09-19 01:35 UTC, songsunkook commented on src/main/java/in/koreatech/koin/domain/updateversion/model/UpdateVersion.java
> +
### A
`update_versions`와 `update_history`는 무엇이 다른 건가요?
ERD나 동작 로직 설명을 간단하게라도 PR 설명에 부가해주시면 이해하기 훨씬 수월할 것 같아요!

2024-09-19 01:35 UTC, songsunkook commented on src/main/resources/db/migration/V60__add_version_history_table.sql
> +DELETE FROM `versions` WHERE `id` = 1;
### C
이 문장이 의미하는 바가 무엇인가요? 꼭 필요한 문장이라면 주석으로 의도를 명시해주시는 것도 좋을 것 같아요

2024-09-19 01:35 UTC, songsunkook commented on src/main/resources/db/migration/V60__add_version_history_table.sql
> +INSERT INTO `update_history` (`type`, `version`, `created_at`) VALUES ('IOS', '3.1.0', '2018-04-17 15:00:00');
### R
DDL과 DML은 별도 파일로 분리하는 방향이 더 적절해 보입니다!

2024-09-19 01:45 UTC, Choon0414 commented on src/main/java/in/koreatech/koin/admin/updateversion/controller/AdminUpdateVersionController.java
> +@RequestMapping("/admin/update")
version과는 별도로 update version api를 만들었는데, 이후에 version에 대한 어드민 페이지가 생기면 겹칠 것 같아 동일하게 `/update/version`으로 맞췄습니다. 
version이 생길 가능성이 없으면 `/admin/version`이 더 좋은 것 같습니다!

2024-09-19 02:00 UTC, duehee requested changes
연휴 기간에 고생 많으셨습니다🐱
앞에 선권님이 열정리뷰를 ㄷㄷ.. 간단한 코멘트 확인해주세요!

2024-09-19 02:01 UTC, Choon0414 commented on src/main/java/in/koreatech/koin/domain/updateversion/model/UpdateHistory.java
> +@Table(name = "update_history")
추가하는게 더 적절해보이네요👍

2024-09-19 02:13 UTC, Choon0414 commented on src/main/java/in/koreatech/koin/domain/updateversion/controller/UpdateVersionApi.java
> +    ResponseEntity<UpdateVersionResponse> getVersion(
기존의 version과 혼동이 있을 것 같아서 추가했습니다.
겹쳐도 괜찮을까요?

2024-09-19 02:13 UTC, Choon0414 commented on src/main/java/in/koreatech/koin/admin/updateversion/dto/AdminUpdateVersionsResponse.java
> +    List<AdminUpdateVersionResponse> versions
다건 조회용 Inner 클래스로 새로 추가하겠습니👍

2024-09-19 02:23 UTC, Choon0414 commented on src/test/java/in/koreatech/koin/fixture/UpdateVersionFixture.java
> +    public UpdateVersion Android() {
추가했습니다.

2024-09-19 02:40 UTC, Choon0414 commented on src/main/java/in/koreatech/koin/domain/updateversion/model/UpdateVersion.java
> +
처음에 versions에서 모바일의 과거 업데이트 이력을 따로 유지하기 위해 history를 만들었다가 update_versions로 분리하면서 update_history와 컬럼이 같아졌습니다.
update_versions는 현재의 업데이트 버전 하나만 유지하고, update_history는 과거의 버전 이력들을 모두 가지고 있습니다.

update_versions에 모두 합치고, 제일 최근 날짜의 버전을 조회하도록 하는 방향이 나을까요?

2024-09-19 02:56 UTC, Choon0414 commented on src/main/java/in/koreatech/koin/admin/updateversion/repository/AdminUpdateHistoryRepository.java
> +    Integer countByType(UpdateVersionType type);
업데이트가 빈번하지는 않아서 Integer로도 수용이 될 것 같은데 Integer로 사용해도 될까요?

Long으로 받으면, `Criteria.of()`가 받는 매개변수 자료형도 수정이 필요합니다.
```
public static Criteria of(Integer page, Integer limit, Integer total) {
    int validatedLimit = validateAndCalculateLimit(limit);
    return new Criteria(validateAndCalculatePage(page, validatedLimit, total), validatedLimit);
}
```

2024-09-19 03:23 UTC, songsunkook commented on src/main/java/in/koreatech/koin/admin/updateversion/repository/AdminUpdateHistoryRepository.java
> +    Integer countByType(UpdateVersionType type);
`Criteria.of`도 Long을 받도록 수정하려고 했었는데 사용처가 많고 당시 이슈가 급해서 미뤄두었습니다.
개인적으로는 Spring Data JPA에서 Long을 반환하기에 따라가는 게 적절하다고 생각합니다.

2024-09-19 03:26 UTC, songsunkook commented on src/main/java/in/koreatech/koin/domain/updateversion/controller/UpdateVersionApi.java
> +    ResponseEntity<UpdateVersionResponse> getVersion(
저는 오히려 기존 version과 분리되는 게 더 혼동을 일으킬 수 있다고 생각합니다

2024-09-19 03:30 UTC, songsunkook commented on src/main/java/in/koreatech/koin/domain/updateversion/model/UpdateVersion.java
> +
컬럼이 동일하다면 테이블을 통합하는 방향이 더 간결하지 않을까요?
`is_before`와 같은 컬럼을 부가하면 해소할 수 있어 보입니다. 과거 버전의 content를 유지하지 않을 이유도 없어보이구요

2024-09-19 03:31 UTC, songsunkook commented on src/main/resources/db/migration/V60__add_version_history_table.sql
> +DELETE FROM `versions` WHERE `id` = 1;
없애는 이유가 궁금합니다. 반드시 없애야만 했나요?

2024-09-19 06:13 UTC, Choon0414 commented on src/main/java/in/koreatech/koin/admin/updateversion/repository/AdminUpdateHistoryRepository.java
> +    Integer countByType(UpdateVersionType type);
그럼 우선 형변환으로 사용하고, 이후 작업 때 Criteria도 함께 수정하겠습니다!

2024-09-21 06:03 UTC, songsunkook approved these changes
고생하셨습니다!

2024-09-21 06:03 UTC, songsunkook commented on src/main/java/in/koreatech/koin/domain/version/controller/VersionController.java
>      }
### C
이건 어디서 사용중인가요?

2024-09-21 06:42 UTC, Choon0414 commented on src/main/java/in/koreatech/koin/domain/version/controller/VersionController.java
>      }
bus, timetable에서 사용중입니다!

2024-09-21 07:19 UTC, dradnats1012 approved these changes
고생하셨습니당

2024-09-21 07:19 UTC, dradnats1012 commented on src/main/java/in/koreatech/koin/admin/version/controller/AdminVersionController.java
> +    @GetMapping("/version")
`/version`까지 빼도 될 것 같아용

2024-09-21 09:07 UTC, kwoo28 approved these changes
고생 많으셨습니다! 문제될건 없어보이고 궁금한 부분 몇가지 코멘트 남겼습니다.

2024-09-21 12:42 UTC, duehee approved these changes
굿~! 제 리뷰도 반영해주셔서 감사합니다~ flyway 쪽 한 번만 확인해주세요!

2024-09-21 12:42 UTC, duehee commented on src/main/resources/db/migration/V61__alter_version_table.sql
> +    `is_previous`   tinyint(1)      NOT NULL    DEFAULT 0   COMMENT '지난 버전 여부'
### C
MySQL에서 어느 버전 이상부턴 int에 크기를 정하면 오류는 아니더라도 경고가 뜨더라구요.
직접 workbench에서 쿼리문 넣으실 때 경고문 안 뜨셨나요?
```suggestion
    `is_previous`   tinyint      NOT NULL    DEFAULT 0   COMMENT '지난 버전 여부'
```

2024-09-22 14:18 UTC, Choon0414 commented on src/main/resources/db/migration/V61__alter_version_table.sql
> +    `is_previous`   tinyint(1)      NOT NULL    DEFAULT 0   COMMENT '지난 버전 여부'
수정했습니다 감사합니다!

2024-09-22 14:18 UTC, Choon0414 commented on src/main/java/in/koreatech/koin/domain/version/model/VersionContent.java
> +    private String content;
길이를 안지웠네요 감사합니다

2024-09-22 14:46 UTC, merged