feat: 어드민 혜택 상점 및 자동완성 검색기능 추가
BCSDLab/KOIN_API_V2 pull request #906
Opened 2024-09-20 09:58 UTC by BaeJinho4028

# 🔥 연관 이슈

- close #885 

# 🚀 작업 내용

1. 어드민 권한 혜택 카테고리 및 혜택 상점 기능
2. 자동완성 검색기능

# 💬 리뷰 중점사항

Normal 버전에 on/off image_url이 없어서 추가하였고, json 필드를 snake_case로 통일했습니다.

2024-09-21 08:18 UTC, 20HyeonsuLee requested changes
수고하셨습니다~ 코멘트 몇개만 확인해주세요!

2024-09-21 08:18 UTC, 20HyeonsuLee commented on src/main/java/in/koreatech/koin/admin/benefit/service/AdminBenefitService.java
> +        return AdminCreateBenefitCategoryResponse.from(savedBenefitCategory);
# A
저장한 값을 반환해주는 이유가 있을까요?

2024-09-21 08:18 UTC, 20HyeonsuLee commented on src/main/java/in/koreatech/koin/admin/benefit/service/AdminBenefitService.java
> +        System.out.println("=============123");
# R
디버깅의 흔적이👀

2024-09-21 08:18 UTC, 20HyeonsuLee commented on src/main/java/in/koreatech/koin/admin/benefit/service/AdminBenefitService.java
> +        List<Shop> shops = adminShopRepository.searchByName(query);
# A
`query`라는 변수명은 어떤걸 의미하는 걸까요?

2024-09-21 08:18 UTC, 20HyeonsuLee commented on src/main/java/in/koreatech/koin/domain/benefit/model/BenefitCategory.java
> +    String offImageUrl;
# A
👍👍

2024-09-21 08:18 UTC, 20HyeonsuLee commented on src/main/java/in/koreatech/koin/admin/benefit/dto/AdminCreateBenefitShopsResponse.java
> +    @JsonNaming(SnakeCaseStrategy.class)
# R
여기는 `@JsonNaming(SnakeCaseStrategy.class)`가 필요 없을 것 같아요

2024-09-21 08:18 UTC, 20HyeonsuLee commented on src/main/java/in/koreatech/koin/admin/benefit/dto/AdminBenefitShopsResponse.java
> +    @JsonNaming(SnakeCaseStrategy.class)
# R
여기는 `@JsonNaming(SnakeCaseStrategy.class)`가 필요 없을 것 같아요

2024-09-21 15:37 UTC, BaeJinho4028 commented on src/main/java/in/koreatech/koin/admin/benefit/service/AdminBenefitService.java
> +        }
좋습니다 👍

2024-09-22 06:14 UTC, 20HyeonsuLee commented on src/main/java/in/koreatech/koin/admin/benefit/service/AdminBenefitService.java
> +        return AdminCreateBenefitCategoryResponse.from(savedBenefitCategory);
좋은 방식인 것 같습니다! 다만 클라이언트 분들과 한번 상의를 한번 해보면 좋을 것 같다는 생각입니다

2024-09-22 06:16 UTC, 20HyeonsuLee commented on src/main/java/in/koreatech/koin/admin/benefit/service/AdminBenefitService.java
> +        List<Shop> shops = adminShopRepository.searchByName(query);
`searchKeyword`와 같은 변수명은 어떻까요?

2024-09-22 06:25 UTC, 20HyeonsuLee commented on src/main/java/in/koreatech/koin/admin/benefit/dto/AdminBenefitShopsResponse.java
> +    @JsonNaming(SnakeCaseStrategy.class)
기존의 dto들에는 필요한 곳에만 적고있는거로 알고있긴 합니다

2024-09-22 10:07 UTC, BaeJinho4028 commented on src/main/java/in/koreatech/koin/admin/benefit/service/AdminBenefitService.java
> +        List<Shop> shops = adminShopRepository.searchByName(query);
좋습니다! 수정해놓겠습니다!

2024-09-22 10:08 UTC, 20HyeonsuLee approved these changes

2024-09-23 00:12 UTC, Choi-JJunho approved these changes
크리티컬하진 않은 문제들이라 Approve 드립니다.
코멘트 확인 부탁드릴게요

2024-09-23 00:12 UTC, Choi-JJunho commented on src/main/java/in/koreatech/koin/admin/benefit/dto/AdminBenefitCategoryResponse.java
> +        public static InnerBenefitResponse from(BenefitCategory benefitCategory) {
### C
외부에서 InnerBenefitResponse 를 만들어서 사용할 일이 있나요?
없다면 접근제어자를 private으로 설정하는건 어떨까요?

2024-09-23 00:12 UTC, Choi-JJunho commented on src/main/java/in/koreatech/koin/admin/benefit/dto/AdminBenefitShopsResponse.java
> +        public static InnerShopResponse from(Shop shop) {
### C

> 외부에서 InnerBenefitResponse 를 만들어서 사용할 일이 있나요?
없다면 접근제어자를 private으로 설정하는건 어떨까요?

ditto

2024-09-23 00:12 UTC, Choi-JJunho commented on src/main/java/in/koreatech/koin/admin/benefit/repository/AdminBenefitCategoryRepository.java
> +    int count();;
### R

세미콜론 두개👀

2024-09-23 00:41 UTC, BaeJinho4028 commented on src/main/java/in/koreatech/koin/admin/benefit/dto/AdminBenefitCategoryResponse.java
> +        public static InnerBenefitResponse from(BenefitCategory benefitCategory) {
잊고있었네요. 좋은 지적 감사합니다! 아래도 동일하게 수정하겠습니다!

2024-09-23 01:32 UTC, merged