feat: 비밀번호 변경 api 구현
BCSDLab/KOIN_API_V2 pull request #927
Opened 2024-09-26 11:22 UTC by seongjae6751

# 🔥 연관 이슈

- close #921

# 🚀 작업 내용

1. 비밀번호 변경 api를 구현했습니다.

# 💬 리뷰 중점사항

2024-09-27 03:56 UTC, duehee requested changes
고생하셨습니다~ 코멘트 확인 부탁드려요

2024-09-27 03:56 UTC, duehee commented on src/main/java/in/koreatech/koin/domain/user/dto/UserPasswordChangeSubmitRequest.java
> +@JsonNaming(SnakeCaseStrategy.class)
## C
위에는 지우고, 아래는 `@JsonNaming`을 넣으셨는데 지금보니까 password 단일 필드면 굳이 필요할까 싶네요👀

2024-09-27 03:56 UTC, duehee commented on src/test/java/in/koreatech/koin/acceptance/UserApiTest.java
> +                """));
## A
통일이 목적이라면 좀 더 밀어야 할 거 같아요~
```suggestion
                        {
                            "anonymous_nickname": "익명",
                            "email": "juno@koreatech.ac.kr",
                            "gender": 1,
                            "major": "기계공학부",
                            "name": "서정빈",
                            "nickname": "duehee",
                            "phone_number": "01023456789",
                            "student_number": "2019136136"
                        }
                    """));
```

2024-09-27 03:56 UTC, duehee commented on src/test/java/in/koreatech/koin/acceptance/UserApiTest.java
> +
## C
공백 한 줄👀 
```suggestion
```

2024-09-27 04:33 UTC, Soundbar91 approved these changes
고생하셨습니다 ! 

한 가지 궁금한 사항이 있어서 코멘트 남겼습니다 !

2024-09-27 04:33 UTC, Soundbar91 commented on src/main/java/in/koreatech/koin/domain/user/service/StudentService.java
> +        user.updateStudentPassword(passwordEncoder, request.password());
## A
changePasswordSubmit에는 `userRepository.save(authedUser);`로 저장을 하고, changePassword는 `save` 메소드 없이 변경감지를 이용하는 것 같은데 혹시 의도하신건지 아니면 다른 이유가 있으신건지 궁금합니다 !

2024-09-30 03:42 UTC, seongjae6751 commented on src/main/java/in/koreatech/koin/domain/user/dto/UserPasswordChangeSubmitRequest.java
> +@JsonNaming(SnakeCaseStrategy.class)
사실 changeRequest라는 이름을 제가 쓰고 싶어서, 원래 changeRequest를 changeSubmitRequest으로 만들고 changeRequest는 제가 새로 만든겁니다..! 그냥 기존꺼 이름을 바꾸니까 아예 새로 추가한 것 처럼 된 것 같네요..
제가 만든 코드는 아니지만 jsonnaming없애도록 하겠습니다

2024-09-30 03:43 UTC, seongjae6751 commented on src/test/java/in/koreatech/koin/acceptance/UserApiTest.java
> +                """));
이것도 목적이 있는게 아니라 그냥 라인 포맷팅.. ctrl alt l한겁니다..!

2024-09-30 03:44 UTC, seongjae6751 commented on src/main/java/in/koreatech/koin/domain/user/service/StudentService.java
> +        user.updateStudentPassword(passwordEncoder, request.password());
changePasswordSubmit은 제가 만든게 아니고 이름만 바꾼겁니다..! changePassword만 제가 만든건데 submit은 원래 제가 만든게 아니라 목적은 잘 모르겠네요..

2024-09-30 03:45 UTC, duehee commented on src/main/java/in/koreatech/koin/domain/user/dto/UserPasswordChangeSubmitRequest.java
> +@JsonNaming(SnakeCaseStrategy.class)
ㅎㅋㅋ 저도 코드 다시 보고 없어도 되겠다 싶어서.. 의견 수렴 감사합니당

2024-09-30 03:46 UTC, duehee commented on src/test/java/in/koreatech/koin/acceptance/UserApiTest.java
> +                """));
포맷팅이 애매하게 됐네요🤔 json이라 그런가

2024-09-30 06:37 UTC, seongjae6751 commented on src/main/java/in/koreatech/koin/domain/user/dto/UserPasswordChangeSubmitRequest.java
> +@JsonNaming(SnakeCaseStrategy.class)
다른 곳들도 필드 한개여도 jsonnaming을 다 넣어서 추가하는 방향으로 했습니다~

2024-09-30 07:34 UTC, duehee approved these changes
간단한 코멘트 하나 남겼어요! 
패키지 분리는 다른 유저팀 분들도 확인하시고 의견 남기시면 좋겠고, 추가적으로 진행한다고 하면 클라님들한테 알리고 작업하면 좋겠네요. 추후에 학생 측 기능을 더 추가한다고 하면 이 방향이 좋을 거 같기도 하네요!

2024-09-30 07:34 UTC, duehee commented on src/main/java/in/koreatech/koin/domain/user/controller/UserController.java
>          @ModelAttribute("nickname")
### C
닉네임은 학생측만 수정하는 것 같은데, 옮긴다면 중복도 옮기는 게 좋지 않을까요?

2024-09-30 07:38 UTC, seongjae6751 commented on src/main/java/in/koreatech/koin/domain/user/controller/UserController.java
>          @ModelAttribute("nickname")
패키지 분리 전에 회의 때 모두 동의 하셨었어요..!
하지만 추가적으로 모두가 코멘트 남기길 바라신다면 그때까지 머지 시키지 않겠습니다.
저는 분리하면 안될 이유가 없다고 생각합니다.
닉네임은 같이 옮기도록 하겠습니다!

2024-09-30 07:42 UTC, seongjae6751 commented on src/main/java/in/koreatech/koin/domain/user/controller/UserController.java
>          @ModelAttribute("nickname")
다시보니까 nickname은 student가 갖고 있는 필드가 아니라 user가 갖고 있는 필드라 확장성을 생각하면(나중에 어떤 user가 추가될지 모름) 그대로 남기는 것이 좋지 않을까 싶은데 어떻게 생각하시나요

2024-09-30 10:21 UTC, Soundbar91 commented on src/main/java/in/koreatech/koin/domain/user/controller/UserController.java
>          @ModelAttribute("nickname")
말씀해주신 확장성을 생각하면 남기는 것이 좋다고 생각합니다. 

잘은 모르지만, 영양사나 사장님의 경우 닉네임 수정의 경우 큰 관심사가 아니기 때문에 관련해서 기능이 없다고 생각을 했습니다. 

추후에 졸업생 같은 수정의 필요가 조금이라도 있는 user가 추가되면 남기는 것이 좋을 것 같습니다.

2024-09-30 10:38 UTC, Soundbar91 reviewed
고생 많으셨습니다!

전환된 이후에 코드를 보면서 user 패키지에 뭔가 이것저것 많다는 생각이 들었는데, 팀에 들어오자마자 패키지 분할이 됐네요. 

주간 공유 때 언급이 됐는지는 잘 모르지만, 언급이 됐었다면 한 번 더 같이 짚고 넘어가면 좋을 것 같습니다 !

2024-09-30 10:38 UTC, Soundbar91 commented on src/main/java/in/koreatech/koin/domain/user/controller/UserController.java
>      public ResponseEntity<CoopResponse> getCoop(
## A
이 친구도 coop 패키지로 보내고 싶다는 생각이 드네요. 

잘은 모르지만 owner의 경우 `GET /onwer`에서 비슷하게 처리하고 있는 것 같아서, 넘길 수 있지 않을까?라고 생각이 들었습니다.

2024-09-30 11:47 UTC, kwoo28 approved these changes
패키지를 분리하니까 훨씬 깔끔해지네요.. 수고 많으셨습니다!

2024-09-30 11:52 UTC, kwoo28 commented on src/main/java/in/koreatech/koin/domain/user/controller/UserController.java
>          @ModelAttribute("nickname")
저도 추후 다른 user타입에서 충분히 사용할 여지가 있기때문에, 확장성을 생각하면 남기는 것이 좋은것같다고 생각이 듭니다.

2024-10-01 14:11 UTC, merged