feat: 어드민 계정 분할 API 구현
BCSDLab/KOIN_API_V2 pull request #981
Opened 2024-10-29 07:26 UTC by Soundbar91

# 🔥 연관 이슈

- close #975 

# 🚀 작업 내용

- 어드민 계정 생성 API 구현했습니다. 
   - 어드민 계정 생성은 `어드민 계정 생성`권한을 가진 어드민 계정만 가능합니다. 
- 어드민 계정 조회 API 구현했습니다.
- 어드민 계정 권한 부여 API 구현했습니다. 
  - 어드민 계정 권한(ex. 어드민 계정 생성)은 `슈퍼 어드민`만 가능합니다.
- 어드민 계정 인증 API 구현했습니다. 
  - 어드민 계정 인증(isAuthed)은 `슈퍼 어드민`만 가능합니다. 
- 어드민 계정 정보업데이트 API 구현했습니다. 
  - 기본 정보 (이름, 트랙명, 팀명) 업데이트 API
  - 비밀번호 업데이트 API
- 어드민 로그인 API 내부에 인증 로직 하나를 추가했습니다. 
  - `UserType`가 `Admin`이지만, `Admins`테이블에 없는 경우 오류를 발생시킵니다.
- 기존 테스트 코드에 있는 어드민 수정 및 작업 내용 API 구현했습니다. 

# 💬 리뷰 중점사항
[API 명세서](https://www.notion.so/Admin-3bf1ea8cb3924ec0b1a057bab449c3e8?pvs=4) 및 [작업 내용 문서](https://www.notion.so/baefebf7b82d4c90b634925e4be065e6?pvs=4)입니다. 참고하시면 편하실 거 같습니다. 

오류 및 질문, 개인적으로 놓친 부분이 있다면 코멘트 남겨주세요 !

2024-10-31 08:46 UTC, duehee requested changes
제가.. Admin 회의록을 더 읽어봐야겠네요..
긴 코드 입력하시느라 고생 많으셨습니다! 질문 및 수정사항이 있어서 대답해주시면 감사하겠습니다🙇

2024-10-31 08:46 UTC, duehee commented on src/main/java/in/koreatech/koin/admin/user/service/AdminUserService.java
> +        validateAdminLogin(user,request);
### C
```suggestion
        validateAdminLogin(user, request);
```
👀

2024-10-31 08:46 UTC, duehee commented on src/main/java/in/koreatech/koin/admin/user/service/AdminUserService.java
> +        user.update(null, request.name(), null, null);
### C
어드민도 결국 학생의 기능을 사용할 수 있다면, 굳이 update를 user에서 사용해서 다른 정보를 null 값을 넣는 게 효율적인가 생각이 드네요. 어드민에서는 트랙과 팀정도만 바꿔도 괜찮지 않을까요?
-> 다시 확인해보니 어드민은 아이디를 따로 유지하다보니 이렇게 데이터를 넣어도 될 거 같네요 ㅎ.. 제가 잘못 생각했습니다.

2024-10-31 08:46 UTC, duehee commented on src/main/java/in/koreatech/koin/global/domain/email/model/EmailAddress.java
> +    private static final String ADMIN_EMAIL_PATTERN = "^koin\\d{5}$";
### C
위 공백 있어요
```suggestion
    private static final String ADMIN_EMAIL_PATTERN = "^koin\\d{5}$";
```

2024-10-31 08:46 UTC, duehee commented on src/main/resources/db/migration/V83__create_admins_table.sql
> +ORDER BY u.id ASC LIMIT 1;
### C
사소하긴한데, DML이랑 DLL flyway는 분리하는 게 좋을 것 같아요! 저번에 선권님께서 말씀해주시더라구요. drop과 create를 합쳐 82번 flyway를 작성하고, 아래 insert를 83번 flyway로 두면 좋을 것 같네용😃

2024-10-31 08:46 UTC, duehee commented on src/main/java/in/koreatech/koin/admin/user/model/Admin.java
> +    private boolean createAdmin = false;
### A
createAdmin이 True면 어드민 생성 권한을 부여받는건가요??? 어드민을 생성할 수 있는 권한은 SuperAdmin이 아니라도 가능한걸까용.. 이 설명에선 PL님만 가능한 거 같아서요.
<img width="589" alt="image" src="https://github.com/user-attachments/assets/e4847b13-4387-4c8a-9a6d-b1afdddfdb54">

2024-10-31 08:46 UTC, duehee commented on src/main/java/in/koreatech/koin/global/domain/email/model/EmailAddress.java
> +    private static final String ADMIN_EMAIL_PATTERN = "^koin\\d{5}$";
어드민 이메일 패턴.. 저는 기존에 있던 아이디에서 ADMIN 권한을 추가적으로 부여해서 사용하는 줄 알았는데 새로운 아이디의 사용이었나요!??

2024-10-31 08:48 UTC, duehee commented on src/main/java/in/koreatech/koin/admin/user/enums/TrackType.java
> +    DA("데이터 분석"),
ㅎㅎ 지금 보니까 설명서가 있었군요. 다음 리뷰때 제대로 이해하고 달겠습니다.. ㅠ

2024-10-31 13:22 UTC, Soundbar91 commented on src/main/java/in/koreatech/koin/global/domain/email/model/EmailAddress.java
> +    private static final String ADMIN_EMAIL_PATTERN = "^koin\\d{5}$";
넵 새로운 아이디 사용입니다 !

2024-10-31 13:23 UTC, Soundbar91 commented on src/main/resources/db/migration/V83__create_admins_table.sql
> +ORDER BY u.id ASC LIMIT 1;
좋은 의견 감사합니다. 반영하겠습니다 !

2024-11-01 10:39 UTC, Soundbar91 commented on src/main/java/in/koreatech/koin/admin/user/model/Admin.java
> +    private boolean createAdmin = false;
createAdmin이 True인 경우 `어드민 생성 권한`을 부여받습니다 !
SuperAdmin의 경우 생성된 어드민 계정의 `isAuthed`를 true으로 설정하는 권한, 어드민 계정에 createAdmin 권한을 True으로 변경할 수 있는 등 모든 행위를 할 수 있습니다.

2024-11-02 06:27 UTC, kwoo28 approved these changes
많은 작업하시느라 수고 많으셨습니다! 궁금한점 몇가지 코멘트 올렸습니다

2024-11-02 06:27 UTC, kwoo28 commented on src/main/java/in/koreatech/koin/admin/user/enums/TeamType.java
> +    USER("유저");
## C
궁금한점이 2가지 있습니다!

1. 현재 Enum에서 name을 영어로 둔 이유
현재 User.TeamType을 Enum의 value값으로 저장하고 클라이언트한테 반환할때도 Enum의 value값으로 반환하고 있는데, name을 영어로 두고 value를 한글로 코드 짜신 이유가 궁금합니다! 한글을 name값으로 두고 value필드를 없애도되지않나요?

2. 영어가 더 직관적이지않나요?
저는 현재 영어로만 코인 개발자분들이 더 직관적으로 알아볼 수 있을것같다는 생각이 듭니다, TrackType같은 경우에도 클라이언트분들이 "아이오에스", "데이터 분석"와 같이 작성해서 요청 보내고 받게될텐데 이것보단 "IOS", "DA"가 더 클라이언트분들에게도 직관적으로 와닿을 수 있지 않을까요??

그래서 전 value필드를 추가하지 않고 name을 영어로 둬서 해당 값을 DB에 저장하고 반환하는 방식이 좋을수도 있다 생각하는데 어덯게 생각하신가요?

2024-11-02 06:37 UTC, Soundbar91 commented on src/main/java/in/koreatech/koin/admin/user/service/AdminUserService.java
> +        user.update(null, request.name(), null, null);
이 부분에 대해서 동의합니다. 

저도 코드 작성하면서 `null`값만 넣을거면 별도의 메소드를 만드는 것이 좋지 않을까 라는 생각이 들었습니다. 
당시 내렸던 결론은 기존에 있는 코드 재사용하자였습니다. 

어드민에서 전화번호, 닉네임 등의 정보가 크게 필요하지 않은 느낌이여서 말씀해주신 방안을 반영해보겠습니다.

2024-11-02 06:49 UTC, Soundbar91 commented on src/main/java/in/koreatech/koin/admin/user/enums/TeamType.java
> +    USER("유저");
1. 응답을 할 때 한글로 넘겨주고 싶다는 생각으로 한글을 뒀는데,  다시 코드를 보니 전혀 사용하지 않고 있었네요,,
2. 동의합니다. `아이오에스` 이 친구에서 말씀해주신 생각이 쌔게 왔었는데, 영어가 확실히 나을 거 같습니다.

enum이 지금 코드 상에서 입력값 유효성 검증을 위해서만 사용하는 느낌이 들어서 관련해서 수정하겠습니다.
감사합니다!

2024-11-03 09:33 UTC, duehee approved these changes
고생하셨어요!! 코멘트 간단히 남겼으니 확인해주세요! 👍

2024-11-03 09:33 UTC, duehee commented on src/main/java/in/koreatech/koin/admin/user/dto/AdminResponse.java
> +    Boolean superAdmin
### A
좋은 변수명이 있을까 지피티한테 물어봤는데, canCreateAdmin를 추천해주네요 👀

2024-11-03 09:33 UTC, duehee commented on src/main/java/in/koreatech/koin/global/domain/email/model/EmailAddress.java
> +    private static final String ADMIN_EMAIL_PATTERN = "^koin\\d{5}$";
공백 전에 아니면.. 이메일 형식 관련해서는 13번째 줄 정도에 선언하면 깔끔할 거 같은데 어떨까요?

2024-11-03 10:52 UTC, merged