feat: VersionType에 AND_OWNER 추가 및 관련 코드 수정
BCSDLab/KOIN_API_V2 pull request #988
Opened 2024-10-31 13:57 UTC by krSeonghyeon

# 🔥 연관 이슈

- close #986 

# 🚀 작업 내용

- 안드로이드의 사장님 앱 강제 업데이트 기능을 위한 새 타입 추가입니다.
1. 버전 타입에 AND_OWNER("android_owner")를 추가했습니다.
2. swagger에 android_owner를 추가했습니다.
3. 타입 체크 로직에 android_owner를 추가했습니다.
4. 초기 버전 정보를 삽입하는 쿼리를 flyway에 추가했습니다.

# 💬 리뷰 중점사항

2024-10-31 14:05 UTC, BaeJinho4028 requested changes
잘해주셨네요 👍 👍 
네이밍 하나만 수정해주시면 좋을것같습니다.

2024-10-31 14:05 UTC, BaeJinho4028 commented on src/main/java/in/koreatech/koin/domain/version/model/VersionType.java
> +    AND_OWNER("android_owner"),
`AND`는 조금 오해의 소지가 있어보여요. 그냥 `ANDROID_OWNER`가 더 나을 것 같다는 의견 드립니다.

2024-10-31 14:14 UTC, krSeonghyeon commented on src/main/java/in/koreatech/koin/domain/version/model/VersionType.java
> +    AND_OWNER("android_owner"),
반영했습니다.

2024-10-31 15:13 UTC, BaeJinho4028 approved these changes

2024-10-31 15:33 UTC, krSeonghyeon commented on src/main/java/in/koreatech/koin/admin/version/service/AdminVersionService.java
> +    private static boolean checkType(VersionType versionType) {
반영했는데, 말하신 방향대로 반영한 건지 모르겠네요
확인 부탁드립니다!

2024-11-01 07:07 UTC, 20HyeonsuLee requested changes
리뷰 하나만 다시 확인해줘요~

2024-11-01 07:07 UTC, 20HyeonsuLee commented on src/main/java/in/koreatech/koin/admin/version/service/AdminVersionService.java
> +    }
# C
isPlatform이라는 메소드를 VersionType에넣으면 책임 분리가 확실하게 될 것 같아요~

2024-11-01 08:48 UTC, krSeonghyeon commented on src/main/java/in/koreatech/koin/admin/version/service/AdminVersionService.java
> +    }
당연한 부분인데 생각하지 않았었네요
반영했습니다!

2024-11-01 08:57 UTC, 20HyeonsuLee requested changes
하핫 아까 못봤던게 보여서.. 다시 리뷰남깁니다..

2024-11-01 08:57 UTC, 20HyeonsuLee commented on src/main/java/in/koreatech/koin/admin/version/service/AdminVersionService.java
>              throw new KoinIllegalArgumentException("unsupported type", "type: " + versionType);
# R
withDetail 메소드를 이용해서 예외를 생성하고 있어요~

2024-11-01 09:15 UTC, krSeonghyeon commented on src/main/java/in/koreatech/koin/admin/version/service/AdminVersionService.java
>              throw new KoinIllegalArgumentException("unsupported type", "type: " + versionType);
반영했습니다!

2024-11-01 12:21 UTC, 20HyeonsuLee approved these changes

2024-11-01 13:07 UTC, merged