feat: 전화하기 리뷰 유도 푸시알림 기능 구현
BCSDLab/KOIN_API_V2 pull request #992
Opened 2024-11-03 12:55 UTC by krSeonghyeon

# 🔥 연관 이슈

- close #976 

# 🚀 작업 내용
- 전화하기 버튼을 누른 사용자에게 누른 시점으로부터 1시간 이후, 리뷰 작성을 유도하는 푸시 알림을 발송하는 기능입니다.

### 테이블추가
1. 상점 / 콜밴 / 기타 구분을 위한 shop_main_categories 테이블을 추가하였습니다.
2. 동적인 푸시 알림 메세지를 관리하기 위한 shop_notifcation_messages 테이블을 추가하였습니다.
3. 알림 발송 대기를 관리하기 위한 shop_notification_queue 테이블을 추가하였습니다.
4. 기존 shop_categories에 main_catrogory_id 컬럼을 추가하고, 관련 데이터를 업데이트하였습니다.
5. 이 알림은 default가 구독이므로 현재 student의 모든 회원을 notifcation_subscribe에 추가하는 flyway또한 추가하였습니다.

### 로직
1. 회원가입(학생)이 완료될 시에도 notification_subscribe에 추가되도록 변경하였습니다.
2. 푸시 알림을 위한 REVIEW_PROMPT 타입을 추가하였습니다.
3. 기존 전화하기 api가 없어서 전화하기 리뷰 유도 푸시알림 요청 api를 추가하였습니다.
4. api가 호출되면 shopId와 studentId로 이벤트를 발행합니다.
5. 이벤트 리스너에서 구독 여부를 확인, 구독한 경우 shopId, userId, 현재시간+1시간을 ShopNotificationQueue 테이블에 저장합니다.
6. 스케줄러를 만들어서 1분마다 ShopNotificationQueue 테이블에서 현재시간보다 작은시간으로 저장된 데이터를 리스트로 가져옵니다.
7. 가져온 데이터로 알림을 만들어서 push합니다.

### 테스트
1. 1시간 뒤를 테스트하는 것이기때문에 mockClock을 추가하여 1시간 10분 뒤의 상황으로 만들었습니다.
2. 정상적인 요청진행 (이벤트 리스너의 메소드 실행) 확인
3. 1시간 10분 뒤의 상황으로 cron 메소드를 호출
4. 해당 메소드가 정상적으로 진행되어 notification의 push가 호출되었는지 확인
5. 알림 전송 후 정상적으로 shop_notification_queue에서 삭제되었는지 확인

# 💬 리뷰 중점사항
- FCM 자체는 테스트해보지 못해서 추가적인 확인이 필요할 것 같습니다.
- 새로 회원가입하는 회원에 대해서 정상적으로 추가되는지 확인이 필요할 것 같습니다.

2024-11-05 02:23 UTC, BaeJinho4028 requested changes
수고하셨습니다. 
제 생각보다 부피가 커지긴했는데, 확장성을 고려했으니 천천히 지켜봐도 될것같습니다.
몇가지만 체크 부탁드려요

2024-11-05 02:23 UTC, BaeJinho4028 commented on src/main/java/in/koreatech/koin/global/domain/notification/model/NotificationFactory.java
> +        MobileAppPath path,
다른곳에서 mobileAppPath로 쓰고있다면 변수명을 통일하는 것이 좋을 것 같습니다.

2024-11-05 02:23 UTC, BaeJinho4028 commented on src/main/java/in/koreatech/koin/global/domain/notification/model/NotificationFactory.java
> +        String content,
content? message? 통일 부탁드려요

2024-11-05 02:23 UTC, BaeJinho4028 commented on src/main/java/in/koreatech/koin/global/domain/notification/model/NotificationFactory.java
> +        return new Notification(
다른 곳에서는 builder쓰셨던거같은데 ,builder를 안쓰신 이유가 있을까요? (순수 궁금증)

2024-11-05 02:23 UTC, BaeJinho4028 commented on src/main/resources/db/migration/V87__add_shop_main_categories_table_and_insert_data.sql
> +    notification_message_id INT UNSIGNED NOT NULL COMMENT '알림 메시지 id',
해당 라인만 NOT NULL 간격이 안맞네요

2024-11-05 05:20 UTC, krSeonghyeon commented on src/main/java/in/koreatech/koin/domain/shop/model/shop/ShopNotificationQueue.java
> +public class ShopNotificationQueue {
수행해야 할 작업이 순차적으로 쌓인다고 생각해서 알림 큐라고 네이밍했습니다.
Schedule은 일정이라는 의미가 강해서
이 테이블의 목적은 작업에 필요한 데이터를 임시적으로 저장해두는 공간이라는 의미엔 큐라는 네이밍이 더 나은 것 같다고 생각합니다.
아니면 다른 적절한 네이밍이 있을까요?

2024-11-05 05:20 UTC, krSeonghyeon commented on src/main/resources/db/migration/V88__alter_shop_categories_add_main_category_id_column.sql
> +WHERE id = 12;
pr 검토하면서 확인했던 부분인데 추가한다고 하고 잊어버렸네요
바로 추가하도록 하겠습니다

2024-11-05 05:22 UTC, krSeonghyeon commented on src/main/java/in/koreatech/koin/domain/shop/repository/shop/ShopNotificationQueueRepository.java
> +    List<ShopNotificationQueue> findAll();
동의합니다. 추가하도록 하겠습니다.

2024-11-05 05:26 UTC, krSeonghyeon commented on src/main/java/in/koreatech/koin/domain/shop/repository/shop/ShopCategoryMapRepository.java
> +    ShopNotificationMessage findNotificationMessageByShopId(@Param("shopId") Integer shopId);
해당 부분은 특정 상점에 대한 카테고리 등록이 정상적으로 되지 않아
상점 노출이 누락된 부분이기 때문에 그 자체가 수정해야 할 오류라고 생각됩니다.

하지만, NPE가 발생할 위험성을 고려해서 Optional 처리 로직과 예외처리를 추가하도록 하겠습니다.
감사합니다!

2024-11-05 05:31 UTC, krSeonghyeon commented on src/main/java/in/koreatech/koin/global/domain/notification/model/NotificationFactory.java
> +        MobileAppPath path,
해당 부분은 NotificationFactory에 존재하는 다른 메소드와 변수명을 통일한 부분입니다.
감사합니다.

2024-11-05 05:33 UTC, krSeonghyeon commented on src/main/java/in/koreatech/koin/global/domain/notification/model/NotificationFactory.java
> +        return new Notification(
해당 클래스에 있는 다른 메소드와 통일성을 맞추기 위해서 사용하지 않았습니다.
Notification 엔티티 자체에도 builder가 없기도 하네요.

2024-11-05 05:35 UTC, krSeonghyeon commented on src/main/resources/db/migration/V87__add_shop_main_categories_table_and_insert_data.sql
> +    notification_message_id INT UNSIGNED NOT NULL COMMENT '알림 메시지 id',
인텔리제이 자체 라인포맷팅을 사용했는데, 어색하게 느껴지는 부분이네요
직접 수정하도록 하겠습니다.

2024-11-05 05:40 UTC, krSeonghyeon commented on src/main/java/in/koreatech/koin/global/domain/notification/model/NotificationFactory.java
> +        String content,
혼동을 줄만한 부분인 것 같네요.
수정해서 반영하겠습니다.

2024-11-05 07:33 UTC, krSeonghyeon commented on src/main/java/in/koreatech/koin/domain/shop/service/NotificationScheduleService.java
> +            .toList();
맞네요.
페치조인써서 한 번에 가져오도록 수정하도록 하겠습니다.

2024-11-05 11:44 UTC, krSeonghyeon commented on src/main/java/in/koreatech/koin/domain/shop/service/NotificationScheduleService.java
> +            .toList();
모두 수정했습니다.
fetch join으로 바꾸는 과정에서 일부 최적화 및 변경도 진행했습니다.

2024-11-05 13:22 UTC, krSeonghyeon commented on src/main/resources/db/migration/V88__alter_shop_categories_add_main_category_id_column.sql
> +WHERE id BETWEEN 2 AND 10;
현재 프로덕션이랑 스테이지의 카테고리 상태가 일치하지 않아서
이 부분은 스테이지에 맞춰져있습니다.
다른 방안이 필요할 것 같습니다

2024-11-05 13:25 UTC, krSeonghyeon commented on src/main/java/in/koreatech/koin/domain/shop/scheduler/NotificationScheduler.java
> +        }
다른 분들의 스케줄러와 형태 통일을 위해 로깅을 사용했습니다.

2024-11-05 13:26 UTC, krSeonghyeon commented on src/main/java/in/koreatech/koin/domain/shop/service/NotificationScheduleService.java
> +public class NotificationScheduleService {
여기서는 @Transactional만 사용하는 로직이어서 추가하지않았는데,
추가하도록 하겠습니다.

2024-11-05 13:28 UTC, krSeonghyeon commented on src/main/java/in/koreatech/koin/domain/shop/service/ShopService.java
> +    public void createCallNotification(Integer shopId, Integer studentId) {
그게 더 나은 것 같습니다. 수정하겠습니다

2024-11-05 13:29 UTC, krSeonghyeon commented on src/main/java/in/koreatech/koin/domain/shop/service/NotificationScheduleService.java
> +        LocalDateTime now = LocalDateTime.now();
처음 알았네요.
수정하겠습니다.

2024-11-05 13:34 UTC, krSeonghyeon commented on src/main/java/in/koreatech/koin/domain/shop/service/NotificationScheduleService.java
> +    }
수정했습니다.

2024-11-05 13:42 UTC, krSeonghyeon commented on src/main/java/in/koreatech/koin/domain/shop/model/event/listener/NotificationEventListener.java
> +    public void onNotificationEventCreate(NotificationCreateEvent event) {
사실 꼭 필요하지는 않긴 합니다.

추후 전화하기 외에 다른 로직이 추가되지 않는다면 이벤트 리스너를 사용하지 않고
ShopService에서 해당 내용을 구현해도 될 것 같습니다.

제가 이벤트 리스너를 사용했던 이유는 핵심 로직 외의 부가적인 이벤트라고 생각해서 분리하여
ShopService의 publishCallNotification의 트랜잭션을 잡지 않고 별도로 처리하도록 하기위해 사용하였습니다.

ShopService자체에서 구현해도 문제는 없을 것 같습니다.

2024-11-05 13:43 UTC, krSeonghyeon commented on src/main/java/in/koreatech/koin/domain/shop/repository/shop/ShopNotificationQueueRepository.java
> +            JOIN FETCH smc.notificationMessage m
사용해보지 않은 부분이어서 고려를 못했네요.
확인해보고 수정해보겠습니다.

2024-11-05 13:51 UTC, krSeonghyeon commented on src/main/java/in/koreatech/koin/domain/shop/model/shop/ShopNotificationQueue.java
> +public class ShopNotificationQueue {
처음에 redis 사용에 대해 많이 고민했었고, 처음 구현 시에는 적용을 했었습니다.

제가 redis를 제대로 학습하지 못한 점도 있고, key value 형태로 저장했다가 다시 복구하는 과정에서 null 검사를 철저히 진행해야 한다는 경고가 많이 나왔습니다.

그래서 DB를 사용하는 방법에 대해서 다시 고민해보게 되었는데,
메세지 자체를 프로그램이 아닌 DB에 저장하여 메세지를 매핑하기 위해 DB호출이 필요하다는 점과 1분마다 하나의 쿼리로 정보를 가져오는 것은 서버에 큰 부담이 되지 않으리라 판단하여 DB를 사용하는 것으로 수정하였습니다.

추후 리팩토링 기간에 redis를 제대로 학습해보고 다시 판단해본 뒤 수정해보도록 하겠습니다.

2024-11-05 14:05 UTC, 20HyeonsuLee commented on src/main/java/in/koreatech/koin/domain/shop/model/shop/ShopNotificationQueue.java
> +public class ShopNotificationQueue {
좋습니다~ RDB에 알림 대기큐를 유지하는건.. 뭔가 뭔가네요

2024-11-05 14:07 UTC, 20HyeonsuLee commented on src/main/java/in/koreatech/koin/domain/shop/model/event/listener/NotificationEventListener.java
> +    public void onNotificationEventCreate(NotificationCreateEvent event) {
어디까지를 이벤트로 정의할지 고민이네요 당장 알림이 날라가지 않으니, 이벤트라고 보기는 애매하지 않을까요?

2024-11-05 14:09 UTC, 20HyeonsuLee commented on src/main/java/in/koreatech/koin/domain/shop/scheduler/NotificationScheduler.java
> +        }
로깅은 어디서 이루어져야하는지 로깅의 책임을 고민해보면 좋을 것 같네요

2024-11-05 14:09 UTC, 20HyeonsuLee commented on src/main/java/in/koreatech/koin/domain/shop/service/NotificationScheduleService.java
> +public class NotificationScheduleService {
지금 컨벤션으로 Service로직에 readOnly를 붙여주고 있습니다 😃

2024-11-05 14:25 UTC, krSeonghyeon commented on src/main/java/in/koreatech/koin/domain/shop/scheduler/NotificationScheduler.java
> +        }
✓ 스케줄러 예외처리기 (리팩토링기간)

2024-11-05 14:48 UTC, 20HyeonsuLee commented on src/main/java/in/koreatech/koin/domain/shop/model/event/listener/NotificationEventListener.java
> +    public void onNotificationEventCreate(NotificationCreateEvent event) {
푸시알림을 발송할때 이벤트리스너를 사용하는 이유는 `보낸 알림은 롤백할 수 없다`의 이유가 가장 큰 것 같습니다.
때문에 `commit`까지 완료되어서 작업의 성공이 확정되었을 때 알림을 보내도록 이벤트리스너를 after_commit으로 지정하는 것 같습니다. 그러한 관점에서 봤을때 이벤트 리스너를 사용하지 않아도 될 것 같습니다.

추가적으로
>shopService자체에 shop과 무관한 여러 repository들과 의존성을 가지는 부분
이 부분을 해결하기 위해서 이벤트 리스너를 사용하는게 맞을지, 별도의 서비스 클래스로 로직을 분리하는게 맞을지 생각해보면 좋을 것 같네요

2024-11-06 01:35 UTC, krSeonghyeon commented on src/main/java/in/koreatech/koin/domain/shop/model/event/listener/NotificationEventListener.java
> +    public void onNotificationEventCreate(NotificationCreateEvent event) {
네 서비스 클래스로 옮기는 것이 낫겠네요.
수정하도록 하겠습니다.

2024-11-07 10:36 UTC, BaeJinho4028 approved these changes

2024-11-07 10:36 UTC, BaeJinho4028 commented on src/main/java/in/koreatech/koin/domain/shop/exception/NotificationMessageNotFoundException.java
> +    private static final String DEFAULT_MESSAGE = "해당 상점에 해당하는 메세지를 찾지 못했습니다.";
알림 메시지라고 표기하는게 더 명확하지 않나 싶기도하네요

2024-11-07 10:36 UTC, BaeJinho4028 commented on src/main/java/in/koreatech/koin/domain/shop/model/shop/ShopNotificationQueue.java
> +public class ShopNotificationQueue {
Queue인데 순차적으로 처리하는것같은 느낌이 들어서요. 임시로 저장하는거면 Buffer도 괜찮을 것 같기는한데 머지전에 한번만 고민해보시면 좋을것같습니다.

2024-11-07 11:54 UTC, merged